organicmaps/organicmaps

android/AndroidManifest.xml
android/res/values/donottranslate.xml

Fixes "This app can't be installed" error.
Closes https://github.com/omapsapp/omapsapp/issues/105

[android] Remove data sharing beetween Release/Beta/Debug versions

---

android/build.gradle

Fixes "Requested NDK version 21.3.6528147 did not match the version
21.4.7075529 requested by ndk.dir"

[android] Update Android NDK to the latest LTS

---

platform/platform_mac.mm

Странно, что пути были слишком длинными. Когда билд папка на уровне с omim репо, пути должны быть, как в этом PR. У большинства, видимо, работало, когда собиралось в самой папке репо.

Fixed paths to resources for desktop version

---

map/framework_light.hpp
routing/routes_builder/routes_builder.hpp
storage/country_info_reader_light.cpp
storage/country_info_reader_light.hpp
storage/storage_integration_tests/download_calc_size_test.cpp
storage/storage_integration_tests/storage_3levels_tests.cpp
storage/storage_integration_tests/storage_downloading_tests.cpp
storage/storage_integration_tests/storage_group_download_tests.cpp
storage/storage_integration_tests/storage_http_tests.cpp
storage/storage_integration_tests/storage_update_tests.cpp
storage/storage_integration_tests/test_defines.cpp

Судя по всему, storage_integration_tests в оригинальном репо не запускались очень давно.
- Обратите внимание на создание и удаление Framework в тестах;
- Добавил наш наш dev url для download тестов;
- Тесты, которые качают кучу данных, пока закоментил - они все равно проверяли супер очевидные use case;
https://github.com/omapsapp/omapsapp/issues/222

Restored storage_integration_tests

---

tools/unix/run_tests.sh

Теперь можно быстро и удобно запускать основные тесты.

Fixed run_tests.sh script on Mac

---

drape/support_manager.cpp
drape/vulkan/vulkan_pipeline.cpp
drape_frontend/frontend_renderer.cpp
drape_frontend/my_position_controller.cpp
drape_frontend/rule_drawer.cpp
drape_frontend/traffic_generator.cpp
routing/routing_quality/routing_quality_tool/utils.cpp

`std::vector` is not very well suited for static, constant arrays.
Since creating it from a `std::initializer_list` requires memory allocation,
modern C++ compilers miss out on many optimizations.
In particular, compilers are forced to insert a call to a global
atomic variable and a bunch of code for initialization at the place of
its use. Plus access to heap memory cause cache misses
For example for this function:
bool f(const int *arr, int x)
{
static std::vector<Foo> const values = {A, B, C};
for (auto v : values) {
if (arr[static_cast<size_t>(v)] == x)
return true;
}
return false;
}
compiler generates ~60 instructions (gcc 10.2 -O3 -march=native),
if replace `std::vector` with `std::array` the result code contains only 9 instructions.

std::vector -> std::array for constant

---

base/math.hpp

Usage of reinterpret_cast here break strict aliasing rules,
so this is undefined behaviour. gcc reports:
dereferencing type-punned pointer will break strict-aliasing rules
[-Wstrict-aliasing]
I checked generated assembly, and in clang case `AlmostEqualULPs`
generates the same code before and after my patch. So it should not be
any speed regression after this UB fix.
Signed-off-by: Evgeniy A. Dushistov <dushistov@mail.ru>

Fix reinterpret_cast UB for base::AlmostEqualULPs

---

iphone/Maps/Classes/MapViewController.mm

As per: https://github.com/mapsme/omim/pull/14102
History: #108 
Lots of apps seem to implement their own shortcuts which creates confusion for the end-user. Zooming on an Apple Mac or iOS app has always used CMD + and CMD -.
So to be more in line with Apples defaults from apps (like Apple Maps) which use CMD + and CMD - I have added these as defaults.
A dedicated re-center button it useful when the map was moved or zoomed to quickly get back to the current location and default zoom level.
`CMD +` for Zoom In (With an alternative of CMD = to also make it work on non numeric keyboards without much confusion.
`CMD -` for Zoom Out
`CMD 0` for recentering the map / switching to next position mode. (Will re-center if clicked enough)
The original zoom in and zoom out on the arrow keys are still …

[iOS] Add more keyboard shortcuts

---

android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
android/src/com/mapswithme/maps/MapFragment.java
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/MwmBroadcastReceiver.java
android/src/com/mapswithme/maps/MwmJobIntentService.java
android/src/com/mapswithme/maps/SplashActivity.java
android/src/com/mapswithme/maps/background/UpgradeReceiver.java
android/src/com/mapswithme/maps/location/LocationHelper.java
android/src/com/mapswithme/util/Counters.java
android/src/com/mapswithme/util/PermissionsUtils.java
android/src/com/mapswithme/util/SharedPropertiesUtils.java
android/src/com/mapswithme/util/StorageUtils.java

- Fix a crash if location permission is not granted.
- Use exceptions instead of boolean for I/O errors.
- Handle the first run properly.
- Fix UpgradeReceiver.
Closes #340

[android] Streamline SplashScreen

---

drape_frontend/selection_shape_generator.cpp

`segments.size()` has `size_t` type, `i` also has `size_t` type.
We inside cycle via `segments`, so `segments.size() > 0`.
I can not see any reason to cast size_t to int before comparing.

removing strange case size_t -> int to fix compiler warning

---

android/src/com/mapswithme/util/StorageUtils.java

Use internal storage for tempDir. Currently tempDir contains only one
file - vulkan_dump.bin. There is no need to create misleading external
/sdcard/Android/data/app.organicmaps directory just for one file.
Fixes #534

[android] Remove rudimental cache dir from /sdcard

---

android/src/com/mapswithme/util/HttpClient.java

Compression is handled automatically since API 10:
https://android-developers.googleblog.com/2011/09/androids-http-clients.html

[android] Fix gzip handlung in HttpClient

---

android/src/com/mapswithme/maps/settings/StoragePathManager.java

Environment.isExternalStorageEmulated() throws IllegalArgumentException
on some Androids.
Don't call isExternalStorageEmulated() and don't ignore emulated storage.
Fixes #538 

[android] Don't ignore /storage/emulated

---

iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMiPhoneRoutePreview.xib

The "Go" button has a hardcoded size, so in some languages, the title of the button is truncated. 
Before the fix:
After the fix:

Fix layout on route preview screen.

---

drape_frontend/apply_feature_functors.cpp
drape_frontend/visual_params.cpp
drape_frontend/visual_params.hpp

Goal is to increase number of POI's on the screen.
Now each rect of POI icon extends by specified attribute from style - `icon-min-distance` ~240 in the file `Icons.mapcss`
There are two ways to decrease that extending:
- change style
- implement global scale factor for these extendings
I did second one. It is easy to remove it later, when style will be redone. It is placed in `VisualParams` class.
This is screenshot after introducing this scale factor:

[drape] Add scale factor for POI extending

---

editor/osm_auth.cpp

The reason was that the format of the form values in response was changed by OSM developers.
TODO: Properly parse the web page response and extract proper permissions and form values
instead of hard-coding them.

Fixed failing OSM login

---

android/src/com/mapswithme/maps/downloader/ChunkTask.java
android/src/com/mapswithme/util/Constants.java
platform/background_downloader_ios.mm
platform/http_thread_apple.mm
storage/pinger.cpp

Timeouts were very long. It's better to fail earlier from a UX perspective.

Reduced HTTP connections timeouts

---

iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm

Instead of 0% now user sees 0.14%
Rationale: for very slow connections it helps to see that download is not stale.
Unfortunately, on Android, it's not that easy. The current implementation stores an integer.

[ios] Display fractional download progress

---

android/src/com/mapswithme/maps/bookmarks/BookmarkCategorySettingsFragment.java

fix for #308 
removed redundant validation dialog for case, when user renames bookmark list to the same name as before.

[android] fix for validation during bookmark list renaming

---

drape/drape_global.hpp
drape/hw_texture.cpp
iphone/Maps/Maps.xcodeproj/project.pbxproj
xcode/common.xcconfig
xcode/drape/drape.xcodeproj/project.pbxproj
xcode/shaders/shaders.xcodeproj/project.pbxproj

Metal is supported since MacOS El Captain.
This patch fixes Simulator on M1.
[1]: https://support.apple.com/en-us/HT205073
Please help to fix problem with `NSString * libPath = [[NSBundle mainBundle] pathForResource:@"shaders_metal" ofType:@"metallib"];` (missing resource file on Simulator)

[desktop][ios] Enable Metal for MacOS and iPhone Simulator

---

platform/background_downloader_ios.mm

TODO: Pinger tries different URLs after the resumable failure of the first one.
But resume saves and retries with the same URL which has failed before.
Please try to use it on a bad network and see if it works.
Note: It may be better to use a chunked downloader instead of the background system one here.

[ios] Resume failed downloads

---

iphone/Maps/UI/CarPlay/CarPlayMapViewController.swift

Changed MapView's leading constraint to be equal to safeArea's leading anchor instead of superview's leading anchor. Closes #804

[ios] MapView's leading constraint fixed for CarPlay

---

android/build.gradle

- removed unused flavors for Samsung and Amazon.
- removed obsolete mips related lines
- excluded vulcan validation layers from the build. For F-Droid build size will be reduced approximately by 15 Mb, for Google Play and Huawey App Gallery approximately by 7-8 MB.

[android] Build.gradle cleanup. Optimized build size.

---

tools/unix/generate_localizations.sh

We use tool called `twine` to generate strings. `twine` is basically just a ruby gem integrated as a git submodule.
This gem has two runtime dependencies `safe_yaml` and `rubyzip` (described in `twine.gemspec` file).
Unfortunately, this fact is not documented anywhere. Script `generate_localizations.sh` advises installing ruby only, which is not enough to run `twine` properly (#889).
This PR proposes the following changes to `generate_localizations.sh` file:
- `twine` is now built, packed and installed using built-in tool called `gem`.
- `twine` package will be rebuilt and reinstalled automatically if `tools/twine` HEAD commit changes.
- added check that `twine` submodule is fetched correctly.

[tools][twine] Build twine gem before usage

---

editor/osm_editor.cpp

The old "OMaps" wording was still present when a map was created with the app; I replaced it with "Organic Maps".

Fixed text when a new note is created within app

---

storage/map_files_downloader.cpp

Desktop application (DEBUG version) fails with the following error when trying to download maps.
```
LOG TID(1) INFO      7.20201 storage/storage.cpp:1178 DownloadNode() Downloading Russia_Pskov Oblast
LOG TID(6) DEBUG     7.24453 platform/http_client_curl.cpp:228 RunHttpRequest() Executing curl -s -w '%{http_code}' -X GET -D '/home/s/tmp/95fa83d1-6b89-4a17-bef9-085499e78a99' -m '10' -o /home/s/tmp/ff61f21c-0a31-4d23-91e2-a44a798395ec ''
LOG TID(6) ERROR       7.418 platform/http_client_curl.cpp:236 RunHttpRequest() Error 768 while calling curl -s -w '%{http_code}' -X GET -D '/home/s/tmp/95fa83d1-6b89-4a17-bef9-085499e78a99' -m '10' -o /home/s/tmp/ff61f21c-0a31-4d23-91e2-a44a798395ec ''
TID(6) ASSERT FAILED
base/logging.cpp:98
CHECK(level < g_LogAbortLevel) 3 3 Abort. Log level is too …
```

[storage] Don't perform http request if meta server is undefined

---

android/res/layout/fragment_editor.xml
android/res/layout/fragment_timetable.xml
android/res/layout/item_timetable.xml

With switched on big font size in the system layout was a bit broken in editor.
Before:
After:

[android] Fixed layout bugs with text cut in editor.

---

.github/workflows/android-release.yaml

- Remove unused flavors.
Follow up fe13f34 "remove unused flavors"
- Run "build" and "publish" in the single Gradle invocation.
Otherwise "publish" repacks packages t created by "build".
- Use separate tags for Android and iOS.

[android][ci] Refactor the release pipeline

---

android/jni/com/mapswithme/platform/Platform.cpp
android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/settings/StoragePathManager.java
android/src/com/mapswithme/util/Config.java

[android] Fix bugs in external storage scanning code
The app scans all available storages for the maps files on every start.
Initially, we prepare a list of available directories and scan them
for the write access and the free space. After that, we pick a first
directory which contains existing maps files. A first directory from
the list is used if no maps files were found.
The problem was that directory from settings.ini wasn't first in
the scan list. It could lead to weird behaviour if you add/remove
SD cards between app runs. App could switch to a newly added SD
card if this card had some old maps files. After switching the new
patch wasn't saved to settings.ini.
This patch sets the highest priority to a directory from settings.ini.
The configuration file is now updated in all cases. …

[android] Fix bugs in external storage scanning code 

---

android/src/com/mapswithme/util/Utils.java

Closes https://github.com/organicmaps/organicmaps/issues/1002

[android] Fix for cut text in snackbar when it's long.

---

iphone/Maps/UI/CarPlay/CarPlayMapViewController.swift

Revert "[ios] MapView's leading constraint fixed for CarPlay"
This reverts commit ce8f7367e60890caccffaf14fb3ca4562980a481.
Reopens #804

Revert/fix not centered CarPlay navigation mode

---

.github/workflows/ios-beta.yaml

iOS uses the number of commits in the current day as a build number.

[ios][ci] Add --depth to git clone

---

android/jni/com/mapswithme/maps/DownloaderAdapter.cpp
android/src/com/mapswithme/maps/downloader/MapDownloadManager.java
android/src/com/mapswithme/maps/downloader/MapDownloadProgressTracker.java
android/src/com/mapswithme/maps/downloader/MapManager.java

mTrackingIds (Java) and g_completionHandlers (C++) do the same job.

[android] Fix download progress

---

CONTRIBUTORS
map/routing_mark.cpp

Currently, the application only allows for 3 intermediate stops: A, B, C.
The minimal changes to code allow for up to 100 intermediate stops (or more?).
Currently, the **C stop icon** is used for testing purposes. This is supposed to be **replaced with a "+" icon later** in development for a more streamlined user experience.
While looking for a way to allow for more stops, I came across the following code:
`android/src/com/mapswithme/maps/routing/TransitStepView.java:112`
```
@DrawableRes
private static int getIntermediatePointDrawableId(int index)
{
switch (index)
{
case 0:
return R.drawable.ic_24px_route_point_a;
case 1:
return R.drawable.ic_24px_route_point_b;
case 2:
return R.drawable.ic_24px_route_point_c;
}
throw new AssertionError("Unknown intermediate point index: " + index);
} …
```

More intermediate stops

---

android/build.gradle

- [google] Publish to production without manual approval.
- [huawei] Update Gradle plugin to support Gradle 7.x.
- [huawei] Publish to production without manual approval.

[android] Tweak Huawei and Google Play publishing

---

data/categories.txt

"Abfalleimer" and "Mülleimer " are both widely used to search for wastebins.
See: https://de.wikipedia.org/wiki/Abfalleimer

[categories] add german trash bin synonym

---

android/AndroidManifest.xml

In our case it does not work anyway because of foreign domains.
Without this flag the app will be more private and do not issue requests to foreign sites
Only if the system finds a matching Digital Asset Links file for ALL hosts in the manifest does it then establish your app as the default handler for the specified URL patterns.
Fixes #1276
@rtsisyk please double-check that new behavior is the same as it is now after a fresh app install for omaps.app, ge0.me and map.google.com

[android] Disable non-working links verification

---

docs/INSTALL.md

Latest Qt version is 6.1.3 which doesn't work with building, adding @5 ensures that Qt 5 is installed instead of the latest version.
(This is my first ever pull-request! 🥳)

Adding version specifier for brew Qt in the docs

---

android/src/com/mapswithme/maps/settings/HelpFragment.java
android/src/com/mapswithme/util/Utils.java
iphone/Maps/UI/Settings/MWMHelpController.m

It helps to restore the context of email conversation by just looking at the topic.

Better wording in support emails

---

android/res/values/themes-base.xml
android/res/values/themes.xml

See issue [#769](https://github.com/organicmaps/organicmaps/issues/769) "Wrong styling for 'copy coordinates' popup in night mode"
Added explicit popup menu style for light and dark themes:

Wrong styling for 'copy coordinates' popup in night mode

---

3party/open-location-code/README.md
3party/open-location-code/codearea.cc
3party/open-location-code/codearea.h
3party/open-location-code/openlocationcode.cc
3party/open-location-code/openlocationcode.h
android/jni/com/mapswithme/maps/Framework.cpp
android/jni/com/mapswithme/maps/Framework.hpp
android/src/com/mapswithme/maps/Framework.java
android/src/com/mapswithme/maps/routing/RoutingController.java
android/src/com/mapswithme/maps/widget/placepage/CoordinatesFormat.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
map/place_page_info.cpp
platform/measurement_utils.cpp
platform/measurement_utils.hpp
platform/platform_tests/measurement_tests.cpp
qt/bookmark_dialog.cpp

Fix for issue [#457](https://github.com/organicmaps/organicmaps/issues/457) "Better support for OLC (Open Location Code)".
* Updated `3party/open-location-code` to latest version 1.0.4.
* Added full OLC code and OSM.org link to point coordinates formats.
Short OLC format is not supported because it requires reference coordinates (nearest city usually). It's hard to implement curently.
TODO: There's is a bug in search. If you enter short OLC code `WF8Q+WF` in search field then decoded coordinates depend on current position. So if user moves and GPS coordinates change then decoded coordinates change too. This is not how OLC should work.

#457 Better support for OLC

---

android/build.gradle

Now -Parm32 works only for debug builds. This PR fixes it for all build types.

[android] Split abi (arch) not only in debug, but also in beta and release builds

---

xcode/shaders/shaders.xcodeproj/project.pbxproj

With this fix, every iOS launch from XCode will be almost instant. Without it, the shaders library is always rebuilt.

[ios] Fixed always rebuilding shaders library

---

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

When an hotel POI has stars : all the end of hotel subtitles is colored yellow, only the stars should be colored yellow, the remaining characters shall be grey as the rest of the string.
(here `· Wifi `shall be grey color)
The coloration was set to be applied until the end of the text with `sb.length()` 
This PR propose a fix, unfortunatly I was not able to build the application to test my modification.
* OS: Android 12
* Organic Maps version: 2021.11.04-2-FDroid
* Data Version: 211022

[android] modified PlacePageView to fix hotel subtitles color

---

docs/INSTALL.md

As per discussion https://github.com/organicmaps/organicmaps/discussions/1538
I'm not sure if we need a special case for Win10 `bash ./configure.sh`?
Also please check my thoughts on using shallow clone for submodules - do you think it'll work like that? (I'm using shallow submodules right now and builds are working fine).

[docs] Dedup and improve Getting Sources section

---

android/src/fdroid/play/release-notes/en-US/default.txt

At the moment there are no release notes displayed in F-Droid app.
The symlink to Google Play relnotes was broken.

[fdroid] Fix release notes symlink

---

docs/COMMIT_MESSAGES.md

Much more useful now as it doesn't list all the misspellings and obscure one-off entries in front.

[docs] Sort historical list of [subsystems] by most used

---

android/res/layout/place_page_opening_hours.xml
android/res/layout/place_page_opening_hours_item.xml
android/res/values/styles-place_page.xml
android/src/com/mapswithme/maps/editor/data/TimeFormatUtils.java
android/src/com/mapswithme/maps/editor/data/Timespan.java
android/src/com/mapswithme/maps/widget/placepage/PlaceOpeningHoursAdapter.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

Another week, another PR!
Closes Issue #970. Made Android Opening hours UI simmilar to iOS. `opening_hours` value matches different cases:
E.g.
* `opening_hours = 24/7`
* `opening_hours` unparsable
🌍 https://osm.org/node/3882420485 → 🕗 `24/7`
🌍 https://osm.org/node/6070463188 → 🕗 Unparsed `Mo-Fr 09:00-19:00; Sa,Su,PH 09:00-20:00`
Show just label:
Unparsable sample:
E.g.
* `opening_hours = 10:00-22:00`
* `opening_hours = Mo-Su 17:00-00:00`
🌍 https://osm.org/node/4601505099 → 🕗`Mo-Su 17:00-00:00`
Open hours are right aligned:
E.g.
* `opening_hours = 10:00-16:00, 16:30-22:00`
* `opening_hours = Mo-Su 10:00-16:00, 16:30-22:00`
🌍 https://osm.org/node/6293418985 → 🕗`Mo-Su 9:30-14:00, 15:00-18:30`
Open hours are right aligned. Non-business hours text below hours.
E.g.
* `opening_hours = Mo-Fr …

[Android] Opening hours UI rework

---

android/res/layout/about.xml
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java

Issue: https://github.com/organicmaps/organicmaps/issues/1616
It works - e.g. the title is copyable via long click the same way as e.g. email is copyable.
What I don't like though is that before that change it was possible to "pull"/expand the bottom sheet by just clicking almost anywhere on it (including title/subtitle). After that change its not possible (though clicking on subtitle works).
It looks like that the title TextView is catching the on-click events which were toggling the bottom sheet though it should catch long clicks only...
I tried explicitly catching the clicks also and then passing them back to the parent and a lot of other trial-and-error...
I spent quite a lot of time on it without success and now I feel I need help from people more familiar with that stuff please!

[android] Make POI title, address, etc. copyable

---

android/src/com/mapswithme/maps/search/SearchFragment.java

Instead of opening the map view, pressing enter in the search view closes the keyboard and removes focus from the input field.
Fixes #1573

[android] Clear search input on enter

---

android/src/com/mapswithme/maps/editor/EditorHostFragment.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java

Adds a new function in SearchToolbarController to control the button visibility, overridden in EditorHostFragment to return false.
Fixes #1285
Signed-off-by: Arnaud Vergnet <arnaud.vergnet@mailo.com>

[android] Hide duplicate back button in cuisine editor

---

android/res/layout/fragment_editor_host.xml
android/src/com/mapswithme/maps/editor/EditorHostFragment.java

Resizes the toolbar layout to contain only the save button when the search controls are hidden, to leave room for the toolbar title.
| Main editor | Opening hours editor | Cuisine editor |
| - | - | - |
| ![Screenshot_20211208-092706](https://user-images.githubusercontent.com/80701113/145185421-17fed80f-328e-4381-9c3e-aae33b53563d.png) | ![Screenshot_20211208-092719](https://user-images.githubusercontent.com/80701113/145185427-34da0267-610f-4f4c-8110-2a3ec3dea477.png) | ![Screenshot_20211208-092732](https://user-images.githubusercontent.com/80701113/145185431-c14fea26-59b6-48f2-abbd-261bedabfab5.png) |
| Main editor | Opening hours editor | Cuisine editor |
| - | - | - |
| ![Screenshot_20211208-093404](https://user-images.githubusercontent.com/80701113/145185838-328cbc9e-f0f1-4a5e-acdd-a12 …

[android] Make editor toolbar title visible if search is hidden

---

search/query_params.cpp
search/ranker.cpp
search/ranking_info.cpp
search/ranking_utils.cpp
search/ranking_utils.hpp
search/search_integration_tests/processor_test.cpp
search/search_tests/ranking_tests.cpp

This PR fixes some bugs in search rankings, and should make search more usable, especially for partial matches and buildings whose numbers aren't yet in OSM. I think it'll help with some of the issues linked in #1560 
Here's a summary of changes:
Search can now recognize `rt`=route, `ct`=court, and a few other synonyms.
(Reverted this to prior behavior with better understanding of its role)
~~The current version of search pops the last word of a query and saves it to a variable called m_prefix. The prefix token was used differently than the rest of the query when ranking results, so a search for "S Valley Way" would be more-or-less truncated to "S Valley". As a result, the search was unable to differentiate between Way/St/Circle/etc.~~
~~Searching for an address as "1600 Pennsylvania Ave" …

[search] Improve search ranking behavior

---

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
android/src/com/mapswithme/maps/widget/placepage/PlacePhoneAdapter.java
android/src/com/mapswithme/util/Utils.java

If a PP info line like POI name or e-mail contain only one copy option then
don't show the copy pop-up menu - copy it to clipboard immediately.
PP info lines like coordinates and most social media links display a pop-up
menu still (e.g. to copy a full social media url or a username only).
Needed-for: #1616

[android] Don't show PP copy pop-up menu if there is one copy option only

---

CMakeLists.txt
android/build.gradle
docs/INSTALL.md
tools/unix/build_omim.sh

"-Pnjobs=<N>" option for gradle builds.
"-n <NUM>" option for build_omim.sh.
E.g. on my computer ninja defaults to launching 6 compile processes and the computer becomes unresponsive for some time. I have no lags when I set it to e.g. 3 processes.

[build] Add cli options to limit number of parallel processes

---

platform/measurement_utils.cpp
platform/platform_tests/measurement_tests.cpp

E.g. both 998m and 1004m are rounded to 1.0km now
(before the change 998m was rounded to 1000m).
```
True
dist	Before	After
-----	------	-----
0.3m	0m	0m
0.9m	0m	1m
998m	1000m	1.0km
1000m	1000m	1.0km
1004m	1.0km	1.0km
9992m	10.0km	10km
10000m	10.0km	10km
10005m	10km	10km
```

[platform] Make distance rounding more consistent

---

data/strings/strings.txt
data/strings/types_strings.txt
tools/python/clean_strings_txt.py
tools/python/find_untranslated_strings.py

Needed-for: #1703 
- introduced CLI
- added languages stats
- filter output by selected languages
- plurals support
- more thorough file format check
- added validation mode
- preliminary "ref=" support
- general refactoring
- beautified by autopep8
Also fixed language code typos and wrong plurals use in translation files - found them thanks to the script.
We can re-format translation files in next PR. We can use the script for validation in CI and in generate_localizations.sh runs - could be done in separate PRs.
Scope:
please consider it from a "better than before" perspective.
There is much more that could be done to improve the script functionality-wise and also the code could be better at places, more efficient, readable, more consistent variables naming, etc. So its far from being …

[tools] Update find_untranslated_strings.py

---

android/src/com/mapswithme/maps/editor/EditorFragment.java
android/src/com/mapswithme/maps/editor/data/TimeFormatUtils.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

Changed string representation of opening hours in long-click copy menu and in editor UI.
It how includes non-business hours:
| --- | --- |
| ![opening_hours_editor-daily-before](https://user-images.githubusercontent.com/720808/147562263-c5a4519a-ee61-4161-838c-e64769d11aed.png) | ![opening_hours_editor-daily-after](https://user-images.githubusercontent.com/720808/147562290-3ecf85a6-d30b-49d2-b1a3-025e915d90a4.png) |
| ![opening_hours_editor-week-before](https://user-images.githubusercontent.com/720808/147562317-25ef455d-3a21-4803-8728-8bfdfd39cc96.png) | ![opening_hours_editor-week-after](https://user-images.githubusercontent.com/720808/147562555-58882f2d-09f8-416f-9eb3-9e9b908abe1f.png) |
Also long-click menu with copy opening hours now also includes non-business …

Issues #1297 - Added non-business hours time to editor UI and copy text

---

3party/opening_hours/opening_hours.cpp
routing/index_router.cpp
routing/junction_visitor.cpp
routing/junction_visitor.hpp
routing/routing_integration_tests/pedestrian_route_test.cpp
routing/routing_integration_tests/route_test.cpp
routing/routing_integration_tests/turn_test.cpp

Closes https://github.com/organicmaps/organicmaps/issues/821
According to the comments, some unneeded loops may occur, but will debug them separately if any.
It should work fine because we have honest **Leaps Graph** that is generated 4 days now ..

Removed bad workaround with several start/end MWMs in optimal route.

---

configure.sh

Fixes repository configuration when there are spaces in the filepath, otherwise the error `line 132: cd: too many arguments` is thrown

Putting paths in quotation marks 

---

map/framework.cpp

Needed-for: #1847
Works well so far.
Buildings still have a priority, so its not possible to select indoor-mapped foot paths etc. inside a building. Which is fine to my mind.
Need to add translation for some types that were previously not likely to be selected like aeroway-runway (inside of airport area).

[core] Prioritize line features selection over area ones

---

android/res/values-sw360dp-v13/values-preference.xml

Override the the iconSpaceReserved property specified in [the Android sources](https://cs.android.com/android/platform/superproject/+/android-12.0.0_r4:prebuilts/sdk/current/support/v7/preference/res/values-sw360dp-v13/values-sw360dp-v13.xml) as none of the Settings items has an icon; hence the space is wasted and leads to the truncation of item names and descriptions. Inspired by https://stackoverflow.com/a/52960668.
Closes #1872

[android] Remove space for icons in Settings

---

generator/routing_index_generator.cpp
indexer/indexer_tests/categories_test.cpp
routing/index_graph_loader.cpp
routing/index_router.cpp
routing/road_access.cpp
routing/road_access.hpp
routing/single_vehicle_world_graph.hpp
routing_common/bicycle_model.cpp
routing_common/car_model.cpp
routing_common/pedestrian_model.cpp
routing_common/vehicle_model.cpp
routing_common/vehicle_model.hpp

Closes #1088
Closes #1739
Some issues from #1201 
Can make full test only after new data generation.
Sometimes current bicycle routing makes really strange routes, e.g. bicycle in Istanbul or Zurich via ferries is not working because of banned footways when entering/exit ferries. The idea behind that is to allow footways but with the small speed 2 km/h. So this approach will work for fast bicycle routes, but probably not good for cycling-only-based routes (who doesn't want to dismount).

[routing] Bicycle model enhancements.

---

data/styles/clear/include/Roads.mapcss
data/styles/clear/include/Roads_label.mapcss
data/styles/vehicle/include/Roads.mapcss

Promote unclassified from z12 to z11.
Demote residential from z11 to z12.
Promote highway links to start 3 zoom levels more
than respective highway (was 4-6 levels more).
Closes: #1766
Changes are not finished yet - need to apply to road labels, vehicle style, etc. I'll finish it if there is approval in principal for the change.

Adjust highways visibility

---

.gitmodules
base/CMakeLists.txt
base/string_utils.cpp

Faster double parsing with a fallback to our existing one, also closes #1659

Faster and locale-independent parser for double/float

---

iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
map/framework.cpp

The problem was that before were separate URL schemes for ge0 and for API, now our om:// scheme supports both.
Use https://omaps.app/test for testing.

Fixed non-working API on iOS and Android

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/routing/RoutingController.java

This PR changes the behavior of the Android back button while in navigation mode. Instead of stopping navigation without confirmation, it now brings the user back to the planning state and rebuilds the route with its new position. If any place detail bottom sheets are open, it first closes them. 
Here is a small demo showing this behavior (sorry for the black screen flashes):
https://user-images.githubusercontent.com/80701113/151960057-60d4e49c-c154-4083-a5bd-fabb9fce46cf.mp4
Fixes #836
Fixes #1946

[android] Go back to planning state from navigation on system back button press

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/search/FloatingSearchToolbarController.java

This PR makes `cancelSearchApiAndHide` in `FloatingSearchToolbarController.java` public to simplify stopping search. It is used in `MwmActivity.java` instead of the simple function `hide` to make sure the search is stopped.
Fixes #1732

[android] Properly stop search on click on "Add Place"

---

android/src/com/mapswithme/maps/location/AndroidNativeProvider.java

Previous version entirely ignored `fused` and `passive` location
providers.
This patch only affects non-GMS builds (i.e. F-Droid), because
all other versions use Google Play Location API.
See #1853

[android] Remove location provider whitelisting

---

android/res/values-be/strings.xml
android/res/values-pl/strings.xml
android/res/values-ru/strings.xml
android/res/values-uk/strings.xml
android/res/values/donottranslate.xml
android/res/values/strings.xml
android/res/xml/prefs_main.xml
android/src/com/mapswithme/maps/base/BaseActivityDelegate.java
android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
android/src/com/mapswithme/util/Config.java
android/src/com/mapswithme/util/Utils.java
data/strings/strings.txt

Allows to show app on lock screen, enabled in the settings.
Closes #558
For me it's useful while using a phone in navigation mode on a bicycle inside phone case/enclosure.
Description of steps in the video:
1. Settings shown -> `Show application on lock screen` disabled.
2. I click power button twice -> screen is turned off and then lock screen is shown.
3. I unlock the phone.
4. `Show application on lock screen` enabled.
5. I click power button twice -> screen blinks and instead of lock screen Organic Maps is shown.
6. I move the map a bit to show that it is possible to use the app.
7. I make a gesture to show home (equivalent to clicking middle onscreen button).
8. Lock screen now is shown (because I tried to switch to a different app than Organic Maps). …

Show application on lock screen

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/routing/RoutingController.java
android/src/com/mapswithme/maps/routing/SearchWheel.java
android/src/com/mapswithme/maps/search/FloatingSearchToolbarController.java

This PR tries to make showing and closing floating panels/toolbars easier. It encapsulates show and close functions in `MwmActivity` for easier management. It essentially adds functions to close all floating panels, called before showing a new one to ensure only one is shown at the same time.
I did not find any bugs from the simple testing I did, but it might require some more with different scenarios (especially on tablet).
Fixes #2005

[android] Simplify float toolbars and panels lifecycles

---

android/res/values-be/strings.xml
android/res/values-pl/strings.xml
android/res/values-ru/strings.xml
android/res/values-uk/strings.xml
android/res/values/strings.xml
android/res/xml/prefs_main.xml
android/src/com/mapswithme/util/Config.java
data/strings/strings.txt

Needed-for: #1928
Multiple lines for prefs titles tested on Android 5 & 9.
Before:
After:
Before:
After:

Enable Show on lock screen by default and improve prefs titles display

---

android/AndroidManifest.xml
android/res/values-v31/autoverify.xml
android/res/values/autoverify.xml

See also 6b3313e "Disable non-working links verification"
Use the following command to check:
```
adb shell pm get-app-links app.organicmaps.debug
```
Expected output:
```
app.organicmaps.debug:
ID: 42334759-b298-4b82-a9ce-4cae78320426
Signatures: [96:D6:28:81:78:B0:1B:86:9B:D3:FF:BF:95:B3:3B:EE:DE:23:01:68:DF:88:2A:1D:7A:4B:B2:8B:85:34:59:F4]
Domain verification state:
omaps.app: verified <!-- HERE
```

[android] Fix links verification on Android 12

---

android/jni/com/mapswithme/platform/Localization.cpp
android/src/com/mapswithme/util/Utils.java
data/strings/strings.txt
map/place_page_info.cpp
platform/localization.hpp
platform/localization.mm
platform/localization_dummy.cpp

See #1643
Current state:
However I realized it'll be confusing to the user to see a static time on the dynamic current location PP.
I think a better behavior will be to keep displaying "My Position" when the current location is selected and replace to "Me at ..." upon bookmark creation.
I need help in RD and codebase navigation though, otherwise it takes me tremendous time to find where things are...
Where bookmarks are created? So that I can inject datetime into bookmark's name if it was created from the current location.

Add datetime to My Position

---

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

There is no way to load "plain text" HTML into the WebView:
https://developer.android.com/reference/android/webkit/WebView#loadData(java.lang.String,%20java.lang.String,%20java.lang.String)
Fixes #2114, where HTML was not rendered because it contained non-percent escaped hash signs "#".

[android] Fixed not rendered HTML in bookmark descriptions

---

android/src/com/mapswithme/maps/location/LocationHelper.java
android/src/com/mapswithme/maps/routing/NavigationController.java
android/src/com/mapswithme/util/LocationUtils.java

`Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1` is always true,
because JELLY_BEAN_MR1 is API=17, but our minimal level is API=21.
No semantic changes intended.

[android] Remove dead location code

---

iphone/Maps/UI/Editor/OpeningHours/Cells/MWMOpeningHoursTimeSelectorTableViewCell.xib

Date pickers have started to appear in compact mode in one of the last
iOS releases. Explicitly setting them to "wheels" style restores the
intended appearance.
This fixes #2047.
Appearance verified on simulators:
- iPhone X, iOS 12.4
- iPhone 12 mini, iOS 15.2

Fix appearance of date pickers for editing opening hours (#2047)

---

android/res/drawable/ic_question_mark.xml
android/res/layout/map_navigation_buttons.xml
android/res/values-ar/strings.xml
data/strings/strings.txt
iphone/Maps/LocalizedStrings/ar.lproj/Localizable.strings

Fixes #1252 by forcing LTR layout for Layers, zoom in/out and position buttons.
Also updates translations after the user's feedback, and mirrors the question mark icon.

RTL fixes for Android

---

iphone/Maps/UI/PlacePage/PlacePage.storyboard

This appears to be fixing the problem on first sight by mimicking what has been done for `PlacePageHeaderView`. Looking very closely at the HeaderView and the Action Bar it becomes apparent that this isn't correct.
As it is now, the HeaderView has rounded corners applied independently of the main PlacePage view. That means the *bottom* corners of the HeaderView are rounded as well. That isn't a big visual issue since there's white on light gray background, however it shows that the rounding is done in a non-ideal way.
The same applies to the action bar: The top corners are rounded as well.
Instead, both views should be clipped by the main PlacePage view so that corner rounding only happens on the actual outer corners. Making the PlacePage clip its subviews however also breaks (rather: …

Fix corner rounding on the bottom of PlacePage

---

data/strings/sound.txt

Me and my friends noticed this while routing, in italian we use "poi" and not "quindi" in this case. If you say "Gira a destra, quindi gira a sinistra" it's like saying "turn right, so turn left", it doesn't make any sense XD 

Fix italian translation of "then"

---

tools/unix/generate_localizations.sh

Now no need to run the script with `sudo` to allow to install system-wide.

[strings] Install Twine in user's home, not system-wide

---

qt/res/app.organicmaps.desktop.metainfo.xml

Needed for #535 
I used https://www.freedesktop.org/software/appstream/metainfocreator/ to generate it.
For reference, it also provided some meson code to validate the file and generate translations:
```meson
metainfo_file = '/path/to/app.organicmaps.desktop.metainfo.xml'
ascli_exe = find_program('appstreamcli', required: false)
if ascli_exe.found()
test('validate metainfo file',
ascli_exe,
args: ['validate',
'--no-net',
'--pedantic',
metainfo_file]
)
endif
```
> AppStream MetaInfo files are recognized by xgettext, so you just need to add app.organicmaps.desktop to your POTFILES.in to generate templates for all translatable elements in the file. When building the software, you can then instruct your build system to merge in the translations into the new file before installing the …

Add appstream data

---

android/res/layout/layout_nav_top.xml

To finish off #2307.
So only the bottom bar is mirrored in RTL layouts.

[android] Don't mirror next turn sign in LTR layout

---

.github/workflows/android-monkey.yaml

```
Error: On [20](https://github.com/organicmaps/organicmaps/runs/5765697202?check_suite_focus=true#step:4:20)[22](https://github.com/organicmaps/organicmaps/runs/5765697202?check_suite_focus=true#step:4:22)-04-05, the default branch will be renamed from "master" to "main". Your action is currently pinned to "@master". Even though GitHub creates redirects for renamed branches, testing found that this rename breaks existing GitHub Actions workflows that are pinned to the old branch name.
We strongly advise updating your GitHub Action YAML from:
uses: 'google-github-actions/setup-gcloud@master'
to:
uses: 'google-github-actions/setup-gcloud@v0'
```

Fixed GitHub Action error

---

qt/CMakeLists.txt

This adds cmake rules for installing the program, paving the way for the flatpak (#535), and allowing me to remove all these installation commands from the nix package:
https://github.com/NixOS/nixpkgs/blob/710fed5a2483f945b14f4a58af2cd3676b42d8c8/pkgs/applications/misc/organicmaps/default.nix#L68
https://github.com/NixOS/nixpkgs/blob/710fed5a2483f945b14f4a58af2cd3676b42d8c8/pkgs/applications/misc/organicmaps/default.nix#L76-L79

[desktop] add cmake install rules

---

android/src/com/mapswithme/util/SharingUtils.java

When sharing a bookmarks list a system chooser appears and amongst other targets there is Organic Maps app, i.e. its possible to share back to the app.
1. It doesn't make sense.
2. It leads to "Bookmarks upload failed. The file may be corrupted or defective." error.
This patch excludes self from sharing targets list. Tested on Android 9.0.
Unfortunately this solution will work for Android 7.0+ only.
I didn't find a good solution for earlier Android versions.

[android] Prevent sharing bookmarks to self

---

docs/CONTRIBUTING.md
docs/JAVA_STYLE.md
docs/PR_GUIDE.md

This PR adds information about the Java style used in the Android app. This will make it easier for new contributors to use the right code style.

[docs] Add Java style guide

---

docs/TRANSLATIONS.md

There is no folder named `utils`, it’s the `tools` folder.

[docs] Fix folder name

---

android/src/com/mapswithme/maps/MwmActivity.java

Causes this:
```
04-08 19:29:09.226  6669  6669 W TrafficManager: There are no attached callbacks. Invoke the 'detachAll' method only when it's really needed!
04-08 19:29:09.226  6669  6669 W TrafficManager: java.lang.Throwable
04-08 19:29:09.226  6669  6669 W TrafficManager: 	at com.mapswithme.maps.maplayer.traffic.TrafficManager.detachAll(TrafficManager.java:102)
04-08 19:29:09.226  6669  6669 W TrafficManager: 	at com.mapswithme.maps.MwmActivity.onSafeDestroy(MwmActivity.java:1067)
04-08 19:29:09.226  6669  6669 W TrafficManager: 	at com.mapswithme.maps.base.BaseMwmFragmentActivity.onDestroy(BaseMwmFragmentActivity.java:169)
04-08 19:29:09.226  6669  6669 W TrafficManager: 	at android.app.Activity.performDestroy(Activity.java:8239)
04-08 19:29:09.226  6669  6669 W TrafficManager: 	at …
```

[android] Removed unnecessary call to TrafficManager

---

android/src/com/mapswithme/maps/search/FloatingSearchToolbarController.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java

Do not rely on the focus event to detect a tap on the search query when looking at results on the map. Instead this PR makes use of the onClick event as before patch #2081 but also disables focusing and long pressing the input.
Compared to the previous implementation of onClick event handling, only a single click is needed to detect a tap. Compared to the current implementation using onFocus event (introduced with #2081), it works the same across Android versions.
Tested on physical device with Android 7 and an Android 11 emulator.
I do not have the internet bandwidth or the disk space to test on all Android versions. So please test this on your device to make sure it correctly fixes the issue and does not introduce any new.
Fixes #2347

[android] Fix search floating toolbar focus on Android 8 and lower

---

drape_frontend/visual_params.cpp
generator/routing_index_generator.cpp
indexer/feature_decl.cpp
map/CMakeLists.txt
map/framework.cpp
map/framework.hpp
map/framework_visualize.cpp
qt/CMakeLists.txt
qt/draw_widget.cpp
qt/draw_widget.hpp
qt/main.cpp
qt/mainwindow.cpp
qt/mainwindow.hpp
qt/mwms_borders_selection.cpp
qt/mwms_borders_selection.hpp
qt/popup_menu_holder.cpp
qt/popup_menu_holder.hpp
qt/qt_common/map_widget.cpp
qt/selection.hpp
routing/cross_mwm_connector.hpp
routing/cross_mwm_connector_serialization.hpp
routing/cross_mwm_graph.cpp
routing/cross_mwm_graph.hpp
routing/cross_mwm_index_graph.hpp
routing/leaps_graph.cpp
routing/routing_tests/cross_mwm_connector_test.cpp
routing/single_vehicle_world_graph.cpp
routing/single_vehicle_world_graph.hpp
routing/world_graph.cpp
routing/world_graph.hpp

Removed dummy:
```
std::vector<Segment> m_enters;
std::vector<Segment> m_exits;
std::map<uint32_t, std::vector<uint32_t>> m_transitFeatureIdToSegmentId;
```
Replaced:
```
std::unordered_map<Key, Transition<CrossMwmId>, HashKey> with std::vector<std::pair<Key, Transition>>
```

[routing] CrossMwmConnector refactoring.

---

android/res/values/styles.xml

Enabled ElevationOverlays make components mix colors to produce a "3d elevated look" - that's how the grey color not defined in the palette came into existence.
Tested on a5.0 and a9.0.
No regressions found in different dialogs of the app, the dark mode also looks consistent.
Closes #2297

[android] Fix bg color of layers and main menus

---

coding/buffered_file_writer.cpp
coding/buffered_file_writer.hpp
coding/coding_tests/reader_test.cpp
coding/file_writer.cpp
coding/file_writer.hpp
coding/reader_streambuf.cpp
coding/reader_streambuf.hpp
coding/writer.hpp
generator/feature_emitter_iface.hpp
generator/intermediate_data.cpp
generator/intermediate_data.hpp
generator/world_map_generator.hpp

- C++11 Destructor has implicit non-throwing exception specification
- Throw from a function marked noexcept, std::terminate is called immediately
Now we have Flush() noexcept(false) call in ~FileWriter() and I don't know how to avoid it and don't break the code.
So mark ~FileWriter() as noexcept(false) too.
Closes https://github.com/organicmaps/organicmaps/issues/672

Explicitly set ~FileWriter() as noexcept(false).

---

routing/routing_tests/turns_generator_test.cpp
routing/turns_generator.cpp

Currently GetTurnDirection() is overcomplicated.
This is an attempt to make it more straightforward.
Also some bugs were found and fixed.
Full list nodes.candidates was used in many cases
but uturn had to be excluded.
The issue #2422 was expected to be handled even twice:
- Removing a slight turn if ingoing and outgoing edges
are not links and all other possible ways out are links.
- Usage of RightmostDirection() if
the route goes along the rightmost candidate.
But both failed because of mentioned nodes.candidates problem.

[Routing] Fixes: #2422 + GetTurnDirection() refactoring

---

iphone/Maps/UI/PlacePage/Components/PlacePageHeader/PlacePageHeaderViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard
iphone/Maps/UI/PlacePage/PlacePageViewController.swift

Hi, here's my second attempt at fixing place page corners. :)
Apart from the action bar (bottom) corners mentioned in #1675, this also fixes top corners on iPhone-size devices. It also fixes visual glitches within the place page that were caused by corners that actually should not be rounded.
One thing I couldn't conclude so far: I have added code sections that set `view.layer.maskedCorners` to configure which corners don't need rounding. I feel like this *may* be part of the theme (`PlacePageStyleSheet.swift`) to keep all styling configuration in one place. May also lead to even more, very specific styles though. Also that would need extension of the theming code of course.
What do you think?

Fix place page corner rounding

---

iphone/Maps/UI/Storyboard/Settings.storyboard

The settings table view has several cells that show the currently selected value on the right, next to the disclosure indicator. In comparison to Apple's apps, the content was too close to the indicator triangle. Refer to the iOS Settings app for example.
This change gives the selected value a bit more space by placing it where Interface Builder snaps automatically. The new position is (most likely) the same as used in Apple's apps.
Current state in OM:
iOS Settings app:
State in OM with this change:
(Also includes a minor typo fix while I was looking at this file...)

[ios] Settings: Fix spacing between disclosure indicator and selected option

---

data/countries-strings/fr.json/localize.json
data/countries-strings/pl.json/localize.json
data/countries_names.txt

Both "Östra Götaland" and "Västra Götaland" where translated as "Östra Götaland" in french and polish which made the swedish map download confusing.

[strings] Fix translation of "Västra Götaland" in fr and pl

---

android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
android/src/com/mapswithme/maps/location/BaseLocationProvider.java
android/src/com/mapswithme/maps/location/LocationHelper.java
android/src/com/mapswithme/util/LocationUtils.java

This device (stock system):
```
Android version: 31
Device: samsung SM-A525F
App version: app.organicmaps 2022.04.27-2-Google
Locale : ru_RU
Location providers: passive network fused gps 
```
prints in location logs:
"fused" locations from AndroidNative provider with network accuracy=500.
User confirmed that the build with these PR works better.

[android] Check if new fused location is better than old one, except Google provider.

---

android/res/values-be/strings.xml
android/res/values-ru/strings.xml
android/res/values-uk/strings.xml
android/res/values/strings.xml
android/src/com/mapswithme/maps/settings/StorageItem.java
android/src/com/mapswithme/maps/settings/StoragePathAdapter.java
android/src/com/mapswithme/maps/settings/StoragePathFragment.java
android/src/com/mapswithme/maps/settings/StoragePathManager.java
data/strings/strings.txt

Allow "emulated" in available storages list.
For new installs (and if the storage with maps was removed) default to storage with the most free space.
Omit internal storage if it backs emulated one (same physical device) unless a user had "internal" as the currently configured storage.
If the user changes to any other storage (e.g. emulated) then "internal" will disappear from a list of available storages.
And minor changes as per review comments in #2566.
Sample logs:
"Internal" is omitted because its the same physical device as "emulated". Also a storage with the most free space is selected as no map files found:
```
2022-05-18 15:37:45.034 I/com.mapswithme.maps.settings.StoragePathManager: Currently configured storage: N/A
2022-05-18 15:37:45.034 …
```

Allow emulated storage

---

android/build.gradle
android/gradle.properties
android/jni/com/mapswithme/maps/Framework.cpp
android/src/com/mapswithme/maps/Framework.java
android/src/com/mapswithme/maps/settings/StoragePathFragment.java
android/src/com/mapswithme/maps/settings/StoragePathManager.java
android/src/com/mapswithme/util/StorageUtils.java

Map files were "disappearing" because the app couldn't find them in internal storage (due to unreliable detection algo - if there were empty maps directories in certain order) and hence switched to emulated storage (and internal storage became hidden for the user as duplicating the same physical device).
- Improve reliability of map files detection (calc sizes of *.mwm files)
- Make internal storage always visible (so affected users can manually switch back to it and have their maps back)
- Catch possible exceptions in getDirSizeRecursively()
Users that lost their maps before and didn't download any new maps (incl. world maps) will be switched to internal storage automatically (and have their maps back).
Other users will have an internal storage option added (if it was hidden before), but …

Fix disappearing map files after allowing emulated storage

---

generator/generator_tests/CMakeLists.txt
generator/generator_tests/collector_building_parts_tests.cpp
generator/generator_tests/relation_tags_tests.cpp
generator/relation_tags.cpp

Closes #2052 
Added special case when `associatedStreet` relation has `wikipedia` tag then this tag should not be copied to relation members.

Issue 2052 wikipedia link from street relation

---

android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/help/FaqFragment.java
android/src/com/mapswithme/maps/help/HelpFragment.java
android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
android/src/com/mapswithme/util/Constants.java
android/src/com/mapswithme/util/StorageUtils.java
android/src/com/mapswithme/util/Utils.java
android/src/com/mapswithme/util/log/FileLoggerStrategy.java
android/src/com/mapswithme/util/log/LogCatStrategy.java
android/src/com/mapswithme/util/log/LoggerFactory.java
android/src/com/mapswithme/util/log/ZipLogsTask.java

- use internal storage as a logs folder fallback location (fixes https://github.com/organicmaps/organicmaps/issues/2567#issuecomment-1145751561)
- try to re-create / re-get a changed folder from the system if its gone
- the current logs location stays active until app restart or another "folder is gone" issue
- switch file logging off if nothing had helped
- show message to a user if he tries to enable the logging setting but a logs folder can't be created
- fix DEBUG core messages not logged after file logging is switched on and off
- better logging and error handling
- simplify and delete unused code
- make bugreport and general feedback features send to flavor-specific support email
upd:
- check logs folder for writability
(for cases it becomes readonly after it was initially created)

[android] Refactor logging and logs folder fallback to internal storage location

---

docs/STYLES.md

generate_drules (kothic) now now work with python3 (https://github.com/organicmaps/organicmaps/pull/2568)

[docs] Remove mention of python2

---

data/sound-strings/de.json/localize.json
data/strings/sound.txt

[strings] fix de translation for 'camera ahead'

---

platform/platform_linux.cpp

This eliminates the need for constantly passing `-data_path`  as a CLI argument,
when  $XDG_DATA_HOME is set to something app specific like:
`~/.var/app/app.organicmaps.desktop/data`
Fixes second part of https://github.com/organicmaps/organicmaps/issues/2387.

[platform][linux] Use $XDG_DATA_HOME if defined

---

android/build.gradle
data/copyright.html

[Glide](https://github.com/bumptech/glide) is used for loading images and videos but I did not see any usage of this lib. I was able to sync gradle and build on an emulator without issues. Maybe this was a leftover from the mapsme fork?

[android] Remove unused com.github.bumptech.glide dependency

---

CMakeLists.txt
platform/CMakeLists.txt

It should also initialize proper parameters used to compile ObjC(++) files

Initialize ObjC to skip m/mm files in Unity builds

---

data/categories.txt

I used Google Translate to add all missing sports translations for a couple of languages.
Cricket and Bowls translations are incomplete because 🦗 and 🥣.
Just to be sure, these are the languages I used:
ar:arabic
cs:czech
da:danish
de:german
el:greek
es:spanish
es-mx:spanish
eu:baskan
fa:persian
fi:finnish
fr:french
hu:hungarian
id:indonesian
it:italian
ja:japanese
ko:korean
mr:marathi
nb:norwegian
nl:dutch
pl:polish
pt:portuguese
pt-BR:portuguese
ro:romanian
ru:russian
sk:slovak
sv:swedish
sw:swahili
th:thai
tr:turkish
uk:ukrainian
vi:vietnamese
zh-Hans:simplified chinese
zh-Hant:traditional chinese
#2511

[search] Make all existing sports searchable

---

qt/draw_widget.cpp
routing/car_directions.cpp
routing/car_directions.hpp
routing/directions_engine.cpp
routing/directions_engine.hpp
routing/following_info.hpp
routing/index_router.cpp
routing/loaded_path_segment.hpp
routing/pedestrian_directions.cpp
routing/pedestrian_directions.hpp
routing/route.cpp
routing/route.hpp
routing/routing_helpers.cpp
routing/routing_helpers.hpp
routing/routing_session.cpp
routing/routing_tests/CMakeLists.txt
routing/routing_tests/route_tests.cpp
routing/routing_tests/routing_helpers_tests.cpp
routing/routing_tests/routing_session_test.cpp
routing/routing_tests/tools.cpp
routing/routing_tests/tools.hpp
routing/routing_tests/turns_generator_test.cpp
routing/turns.cpp
routing/turns.hpp

Now RouteSegments generation starts at DirectionsEngine::Generate().
But this is just preparation, when segments are not created,
but turns, street names, any new staff like speed limits are created
with indexes when it should be applied later.
Later in FillSegmentInfo all this info is unpacked to RouteSegments
and populated by segments and junctions.
This approach is overcomplicated and makes difficult adding new info,
like speed limits, by creating more and more data to pack and unpack.
Also extra memory allocations are done for intermediate steps.
Several todo were found mentioning desirability of changes.
For this reason it was decided to create RouteSegments
at DirectionsEngine::Generate() with all available info
with minimal post-processing at later stages.

Directions refactoring + Show speed limit

---

android/res/layout/bottom_sheet.xml
android/res/values/styles.xml
android/res/values/themes-base.xml
android/src/com/mapswithme/util/bottomsheet/MenuBottomSheetFragment.java

This PR comes to finish the work on refactoring the various bottom sheets. Here I focused making sure all bottom sheets follow the same styling.
Apart from internal code changes, there are also some visual changes:
- Bottom sheet dialogs (when the background is dimmed) have the same handle and same corner radius as the place page and navigation menu.
| Menu swiping | Menu opened | Place page collapsed | Navigation menu |
|-|-|-|-|
| ![Screenshot_20220628_084851](https://user-images.githubusercontent.com/80701113/176112259-9a6d9ad4-e2a6-49d2-8296-68df4cef1af3.png) | ![Screenshot_20220628_084924](https://user-images.githubusercontent.com/80701113/176112316-75f71f12-4070-4b14-a549-790086c81cec.png) | ![Screenshot_20220628_084942](https://user-images.githubusercontent.com/80701113/176112371-85 …

[android] unify styling for all bottom sheets

---

android/src/com/mapswithme/maps/bookmarks/BookmarksToolbarController.java

By using the same fix as in https://github.com/organicmaps/organicmaps/pull/1671, this PR removes the second back button in the header for the bookmark search.
| Portrait | Landscape |
|-|-|
| ![Screenshot_1656718849](https://user-images.githubusercontent.com/80701113/176978055-298b5628-9d95-4748-bf4b-60c5d5d4d4e4.png) | ![Screenshot_1656718853](https://user-images.githubusercontent.com/80701113/176978060-769e593e-3aa9-495f-a233-84e716b492c7.png) |
Closes #2173

[android] show only one back arrow in bookmark search

---

android/res/layout/bottom_sheet.xml

This will work on any bottom sheet menu, not only the bookmark list.
| Portrait | Landscape |
|-|-|
|![Screenshot_1656754738](https://user-images.githubusercontent.com/80701113/176995269-cde9a449-3972-48a4-8c2a-4ed6df93fd2d.png) | ![Screenshot_1656754745](https://user-images.githubusercontent.com/80701113/176995273-1580b9a4-5083-49ac-b8f5-fda03ad6b033.png) |
Closes #2635

[android] make bottom sheet menu title 3 lines max

---

indexer/editable_map_object.cpp

Instead of copying the whole feature types object before adding the cuisine selection, we copy only the types which are not cuisines.
This allows removing cuisines from the current feature.
Closes #1283, closes #2842

[editor] Allow removing cuisines from selection

---

tools/unix/version.sh

Git was using local dates instead of UTC ones, and that lead to wrong and inconsistent version numbers.

Version script should use UTC dates instead of local ones

---

routing/car_directions.cpp
routing/pedestrian_directions.cpp
routing/route.cpp
routing/route.hpp
routing/routing_session.cpp
routing/routing_tests/route_tests.cpp

Text info about next turn street/road will be displayed
at least during 60 seconds before turn.
Fix for #2640

Show text info about next turn street/road longer

---

map/framework.cpp
map/framework.hpp

When in transit navigation mode, instead of showing an empty place page on selecting a subway station, the subway POI place page is now shown.
More information such as transit lines could be shown while in this mode so I left the todo.
Closes #2214

[framework] Fill transit mark place page with feature info

---

android/jni/com/mapswithme/util/StringUtils.cpp

Added filtering not only by english but in translated label too.
Closes #285 and #2841.
| Rus | Ukr | Hebr |
| --- | --- | ---- |
| ![cuisine-filter](https://user-images.githubusercontent.com/720808/177290290-80139adc-f3f2-4261-bd7a-fcf819e970be.png) | ![cuisine-filter-ukr](https://user-images.githubusercontent.com/720808/177290706-3355c733-643d-4eee-87ee-1e436abc6429.png) | ![cuisine-filter-hebr](https://user-images.githubusercontent.com/720808/177290754-8ddfd689-c0c6-4f70-a806-a4d65e85bc28.png) |

Cuisine editor filter fix

---

indexer/feature_data.cpp

Easy (but not perfect) fix for of #2511.

Give priority to tag sport over leisure=pitch

---

routing_common/vehicle_model.cpp

Fixed issue from user.
Worth to update other cases from here https://github.com/organicmaps/organicmaps/issues/1201

[routing] Select max speed in VehicleModel::GetAdditionalRoadSpeed.

---

data/strings/strings.txt

This is the opposite to [load_kmz_successful] and is used at loading bookmarks from the file system into the app:
https://github.com/organicmaps/organicmaps/blob/2b1e4d54f9ae334cec73a851e56375a978ebe251/android/src/com/mapswithme/maps/MwmActivity.java#L1849-L1853
So it's about _loading_, not *up*loading.
Fixed the English text and the German translation. Russian and Ukrainian translations are correct, but some of the other translations probably need to be fixed.

[string] Fix text for [load_kmz_failed]

---

feature_list/feature_list.cpp
generator/feature_segments_checker/feature_segments_checker.cpp
generator/generator_tool/generator_tool.cpp
generator/statistics.cpp
generator/statistics.hpp
indexer/data_header.hpp
indexer/feature.cpp
indexer/feature.hpp

1. Fixed some wrong stats, e.g. inner geometry sizes were double-calculated and only the best outer geometry was taken into account. Improved labelling and output formatting.
2. Added detailed outer geometry stats.
Sample run cmd:
```
../omim-build-release/generator_tool --stats_general=true --stats_geometry=true --stats_geometry_dup_factor=2.0 --stats_types=true --output="Russia_Mari El"
```
Sample stats:
```
File section sizes
addr :     101929
altitudes :     341744
centers :    1150880
city_roads :      20416
cross_mwm :     641444
descriptions :    1429959
features :    7129219
geom0 :      14355
geom1 :      78810
geom2 :    1068665
geom3 :    5885068
header :         32
idx :    1077635
isolines_info :          7
maxspeeds :       4257
meta :     215981
metalines :       9796
offs …
```

[tools] Fix map file stats and add outer geometry stats

---

data/strings/types_strings.txt

In my opinion the german translations for wilderness_hut (line ~21696) and alpine_hut (line ~20841) have a wrong translations with different meaning:
- 'unbewirtschaftete schutzhütte' means 'unmanaged shelter'
- 'bewirtschaftete schutzhütte' means 'managed shelter'
While wilderness and alpine indicate more the locationtype. Wilderness a hut in the forest and alpine in the mountains. Looking at the other translations it seams that there is the same consens. 'Cabană în pădure' means 'Cabin in the forest' ([deepl](https://www.deepl.com/translator#ro/en/Caban%C4%83%20%C3%AEn%20p%C4%83dure)) 
Signed-off-by: Christos Sidiropoulos csidirop@runbox.com

Change german translations for wilderness_hut and alpine_hut

---

3party/opening_hours/CMakeLists.txt
3party/opening_hours/rules_evaluation.cpp
generator/generator_tests/collector_building_parts_tests.cpp
generator/generator_tests/relation_tags_tests.cpp
geometry/clipping.cpp
routing/cross_mwm_graph.cpp
routing/fake_vertex.hpp

Distributions like openSUSE compile packages with the "-Werror=return-type".
Signed-off-by: Jaime Marquínez Ferrándiz <jaime.marquinez.ferrandiz@fastmail.net>

Add missing returns in non-void functions

---

.github/workflows/linux-check.yaml
tools/python/ResponseProvider.py
tools/python/testserver.py

Errors were ignored in `ResponseProvider.py`. Added more logging.
Replaced float division with int division.
Fixed some API mismatch in `http.server` implementation between Python 2 and Python 3.
Is there any way we can run all unit tests with this branch version of scripts?

Fix testserver behaviour after migration to Python 3

---

android/res/layout/item_bookmark_category.xml

Closes issue #2964 
| Before | Checkbox padding | Checkbox and `⋮` button padding |
| --------------- | --------------- | --------------- |
| ![2022-07-19 19 49 18](https://user-images.githubusercontent.com/720808/179913680-4e55deba-d102-4b47-956e-4fa1d4bba722.png) | ![2022-07-19 18 41 13](https://user-images.githubusercontent.com/720808/179913866-2d0ec94c-3592-47f4-a69b-99b1d5ec1266.png) | ![2022-07-19 18 54 55](https://user-images.githubusercontent.com/720808/179913903-a7a1c9db-8eec-4938-8add-bad200575352.png) |
Reduced padding for checkbox and `⋮` button.

[Android] Changed padding of bookmark category item

---

tools/python/transit/gtfs/download_gtfs.py

While using the download_gtfs.py script seems that feed["spec"] values is GTFS not gtfs.
Signed-off-by: Yellowhat <yellowhat46@gmail.com>

download_gtfs.py: `feed["spec"]` is not "GTFS"

---

data/categories.txt

Removed "pitná voda" as this conflicts with "drinking water" category.
Removed "voda" as this conflicts with "Water" category.
These terms are not included in bar category in other languages (except Czech and Slovak).
After this change, user will be able to search "drinking water" ("pitná voda"). Before this, bars were displayed as a result.
Signed-off-by: Vladan Kudlac <vladankudlac@gmail.com>

[search] Remove water from cs+sk bar category

---

search/latlon_match.cpp

Fix coordinates processing if query contains '\n'

---

.github/workflows/linux-check.yaml

OSM dev server https://master.apis.dev.openstreetmap.org is down.
Enable tests back when it works.

Temporarily disable OSM auth tests

---

android/res/layout/fragment_timetable.xml
android/src/com/mapswithme/maps/editor/TimetableContainerFragment.java

Fixing issue #3077 
The problem is caused by white bar at the bottom. It's bound to "Simple mode" button. And when the button is hidden the bar height becomes too big.
Fix: If opening_hours format is invalid, then hide both button and it's background.
| Normal layout | Wrong OH format |
| -------------- | --------- |
| <img width="437" alt="Normal layout" src="https://user-images.githubusercontent.com/720808/184106845-7e319427-6d50-4775-8062-2f9775ecb082.png"> | <img width="436" alt="Wrong OH format" src="https://user-images.githubusercontent.com/720808/184106901-5db42360-c2c8-4d9e-bf85-a469e54b276f.png"> |

[Android] Fixed advanced timetable editor layout

---

iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.mm
iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.xib

Now label max lines are 2 for portrait and 1 for landscape (was unlimited).
Font increased from 18 to 24 (like many other fonts on this screen). Scaled till 0.5.
Horizontal. Unscaled.
Horizontal. Scaled font:
Vertical. Scaled and Unscaled.

[iPhone] Increased visibility of next street

---

docs/EXPERIMENTAL_PUBLIC_TRANSPORT_SUPPORT.md

Updated docs as Open Mobility Data doesn't need API key whereas Transitland does.
Signed-off-by: Maciej Sikorski <maciejosikorski@gmail.com>

[docs]Update EXPERIMENTAL_PUBLIC_TRANSPORT_SUPPORT.md

---

android/res/values-sw720dp/font_sizes.xml
android/res/values/font_sizes.xml

fixes #2198
Increased the font size for the roundabout exit number in navigation mode.
Signed-off-by: pratyaksh1610 <pratyakshkhuranaofficial@gmail.com>

[android] Increased the font size of exit number

---

data/categories.txt
data/strings/types_strings.txt

This small change allows many people in Italy not to confuse search results related to tram and bus stops (and train stations): now all of them have a different description.
This bug was originally reported by @amreo during an OpenStreetMap mapping party in the lovely La Pigna, Sanremo (Italy):
https://scambi.org/2022/lab/18/
Added the `Signed-off-by` as expected but I've not executed the `ruby` stuff, sorry.
Please note (since in some projects it's a problem in compilation): There is an apostrophe character in my translation: `'`
This change also adds the ability to search "pullman" (widely used in Torino) plus a couple of autocomplete limitation (3 characters).
Thank you for this amazing Free/Libre and Open Source Project.

[string] Fix Italian generic "Stop": set "Bus stop" + "Bus tram"

---

generator/osm2meta.cpp

This tag is frequenty misused and a full url is provided.
It's incorrect but happens so often that we should protect against it.

[generator] Update checks for wikimedia_commons tag

---

data/categories.txt
data/strings/strings.txt
data/strings/types_strings.txt
tools/python/strings_utils.py

Added all missing Dutch translations in `strings.txt` and `types_strings.txt`.
Encountered some errors in `string_utils.py` on Windows.
- Incorrect paths
- Writing the sorted file crashes at non-Latin characters
```py
File "./organicmaps\tools\python\strings_utils.py", line 642, in <module>
strings.write_formatted(target_file=args.output, langs=args.langs, keep_resolved=args.keep_resolved)
File "./organicmaps\tools\python\strings_utils.py", line 359, in write_formatted
self._write_translations_for_langs(outfile, sorted_langs, tran, ref_tran)
File "./organicmaps\tools\python\strings_utils.py", line 365, in _write_translations_for_langs
outfile.write("    {0} = {1}\n".format(
File "./cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0] …
```

 [strings] Add nl-Dutch translations

---

android/res/layout-land/layout_nav.xml
android/res/layout/activity_map.xml
android/res/layout/layout_nav.xml
android/res/layout/layout_nav_top.xml
android/res/layout/menu.xml
android/res/values/themes.xml
android/src/com/mapswithme/maps/MapFragment.java
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/routing/NavigationController.java
android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java

Makes the navigation bar semi transparent to make the map more visible. This is only true for the map activity, other activities/screens are untouched.
This was not a trivial change as the navigation bar is now drawn on top of the app and we need to make UI elements manually avoid it. On the splash screen, the navigation bar is now the same color as the background.
I handled map UI elements such as the buttons, navigation UI, ... and also the ruler/copyright and the compass. Please help me test this PR to make sure it does not introduce new issues.
Helps towards https://github.com/organicmaps/organicmaps/issues/3029.
Closes https://github.com/organicmaps/organicmaps/issues/2943.
https://user-images.githubusercontent.com/80701113/188902190-d3936d1d-9576-46cd-acca-2f0f59dac1aa.mp4 …

[android] Make navigation bar semi-transparent 

---

android/res/layout-h400dp/map_buttons_layout_regular.xml
android/res/layout-land/map_buttons_bottom.xml
android/res/layout/map_buttons_bottom.xml
android/res/layout/map_buttons_layout_regular.xml
android/res/values/dimens.xml
android/res/values/styles.xml

When the screen is larger than 450dp, bottom map buttons will align to the left as requested in https://github.com/organicmaps/organicmaps/pull/2905#issuecomment-1236192812. This threshold can be edited in the `map_buttons_bottom_max_width` value.
To make code easier to maintain, bottom menu buttons have been extracted into their own layout file.
| Portrait | Landscape |
|-|-|
| ![Screenshot_1662397632](https://user-images.githubusercontent.com/80701113/188494950-76f89560-267e-42e8-9e46-45994298906a.png) | ![Screenshot_1662397637](https://user-images.githubusercontent.com/80701113/188494958-d486d2e5-f110-4b3b-a0ae-a9c21dac81ec.png) |
| Portrait | Landscape |
|-|-|
| ![Screenshot_1662397763](https://user-images.githubusercontent.com/80701113/188494967-56a0301a-3926-4682-b126-d553798650c4.pn …

[android] set bottom map buttons max width to 450dp

---

docs/STYLES.md

This is small a docs update to ease contributing to the project.
I added another option of installing required `protobuf` dependency. 
This is actually what allowed me to build the styles after following INSTALL.md on clean Linux (Windows WSL) installation. I guess I didn't have `pip` installed because INSTALL.md only tell to install `python3`, not `python3-pip`.

[docs] update STYLES.md about installing protobuf

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java
android/src/com/mapswithme/maps/downloader/DownloaderFragment.java
android/src/com/mapswithme/maps/maplayer/ToggleMapLayerFragment.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageController.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageControllerComposite.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
android/src/com/mapswithme/maps/widget/placepage/SimplePlacePageController.java
android/src/com/mapswithme/util/bottomsheet/MenuBottomSheetFragment.java

Properly handles lifecycle for all bottom sheets. Last time I refactored them I messed this up to it would crash/loose its content when rotating the screen.
With this PR, the activity or fragment showing the bottom sheet must implement either `MenuBottomSheetInterface` or `MenuBottomSheetInterfaceWithHeader`.
- When implementing the first interface, you have to create a function which receives the bottom sheet id and returns a list of `MenuBottomSheetItem` to populate the sheet.
- When implementing the second interface, you have to create the same function as before and an other which also receives the bottom sheet id and returns a custom fragment to use as a header for the list of items.
In practice the `MenuBottomSheetInterfaceWithHeader` is only implemented by the main activity as we …

[android] Fix bottom sheet lifecycle issues

---

android/res/layout/map_buttons_zoom.xml
android/res/values/styles.xml

Another step for https://github.com/organicmaps/organicmaps/issues/3406.
Zoom icons are now a bit bigger.

[android] increase size of zoom icons

---

android/res/drawable/ic_follow.xml
android/res/drawable/ic_follow_and_rotate.xml
android/res/values/dimens.xml
android/res/values/styles.xml
android/src/com/mapswithme/maps/widget/menu/MyPositionButton.java

First step of https://github.com/organicmaps/organicmaps/issues/3406.
Took the icons from [Material Design Icons](https://materialdesignicons.com/) and manually edited the _follow and rotate_ to add the line.
| not follow | pending | follow | follow and rotate |
|-|-|-|-|
| ![Screenshot_1663161694](https://user-images.githubusercontent.com/80701113/190165652-aef6304c-62ef-447b-a02a-1b4972603404.png) | ![Screenshot_1663161698](https://user-images.githubusercontent.com/80701113/190165667-41453d41-3bd0-4356-a856-be558e991ad9.png) | ![Screenshot_1663161711](https://user-images.githubusercontent.com/80701113/190165749-30db6b60-a0ab-457d-866a-ea0e27ea47c1.png) | ![Screenshot_1663161713](https://user-images.githubusercontent.com/80701113/190165827-f24146c7-2ba7-4abf-bcef-1e81796d5ad4.png) |
| | …

[android] update nav icons to match previous design

---

android/src/fdroid/play/release-notes/de-DE/default.txt
android/src/fdroid/play/release-notes/en-US/default.txt
android/src/fdroid/play/release-notes/tr-TR/default.txt
iphone/metadata/de-DE/release_notes.txt
iphone/metadata/en-US/release_notes.txt
iphone/metadata/tr/release_notes.txt

##
[strings] add missing translations for craft=*
[styles] Add driving_school, music_school and language_school
[editor] Fixed exception type.
[search] Better street's FeaturesLayer filtering logic.
[search] Decrease score for numeric streets like "2-й ...".
[search] Increased penalty for error; increased city rank factor.
[search] Added Shop POI type for ranking.
[search] Fixed category results ranking.
[search] Cleanup debug features fetching.
[search][tests] Correct affiliations initialization.
[desktop] Added "ru" locale and category checkbox.
[search] Fixed categories.
[strings] Add @501Ghost's NL translations
[android] set bottom map buttons max width to 300dp
[android] Adjust ruler and copyright to transparent nav bar
[android] Adjust …

Update release notes

---

android/src/com/mapswithme/maps/MwmActivity.java

Register in onResume instead of onSafeCreate.
This makes sure we do not miss the event by registering too late.
@rtsisyk can you confirm this fixes your issue?
Closes https://github.com/organicmaps/organicmaps/issues/3389

[android] fix missing window inset event on start

---

android/src/com/mapswithme/maps/MwmActivity.java

This patch moves updateViewsInsets() from `onResume()` back to `onSafeCreate()`. The #3389 issue happened because of premature return from onSafeCreate() when app was lanunched with an intent:
```
boolean isConsumed = savedInstanceState == null && processIntent(getIntent());
boolean isFirstLaunch = Counters.isFirstLaunch(this);
// If the map activity is launched by any incoming intent (deeplink, update maps event, etc)
// or it's the first launch (onboarding) we haven't to try restoring the route,
// showing the tips, etc.
if (isConsumed || isFirstLaunch)
return; <!-- Exited here.
if (savedInstanceState == null && RoutingController.get().hasSavedRoute())
addTask(new Factory.RestoreRouteTask());
updateViewsInsets(); <!-- never reached if launched with an intent.
```
Follow up #3389 …

[android] Install window insets handlers in onSafeCreate()

---

android/res/layout-land/layout_nav.xml
android/res/layout/layout_nav.xml
android/src/com/mapswithme/maps/MwmActivity.java

Improves on https://github.com/organicmaps/organicmaps/pull/3449
Window insets event registration is now done in `onStart`. Only one callback is used instead of one per view. Also fixes a UI issue with dark mode.
@vng what do you think? We can take the time to do a clean fix here.

[android] Window insets improvements

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/location/LocationHelper.java

The app displays "Current location is unknown. Do you want to continue detection your location?" dialog after if location wasn't found after 30 seconds. Before this patch, we disabled GPS even before the user pressed "Stop". With this patch, the app continue to search for location while the dialog is displayed, until "Stop" button is clicked explicitly.

[android] Don't stop location until Stop button is pressed

---

android/src/com/mapswithme/maps/editor/EditorFragment.java

Adds missing icons for `Email` & `Website` (not for address fields as it becomes messy), cleans up implementation of `Operator` (not a complex field so can just use InitBlock) ~~& fixes incorrect padding in the editor menu~~
fixes #3388 ~~and #3393~~
Signed-off-by: Harry Bond <endim8@pm.me>

[Android] Add missing icons in editor, refactor 'operator'

---

base/base_tests/buffer_vector_test.cpp
base/buffer_vector.hpp
base/string_utils.hpp
coding/var_record_reader.hpp
drape/bidi.cpp
generator/feature_builder.cpp
generator/generator_tests/feature_builder_test.cpp
generator/generator_tests_support/test_feature.cpp
geometry/point2d.hpp
geometry/point3d.hpp
indexer/interval_index.hpp
indexer/interval_index_builder.hpp
indexer/mwm_set.hpp
map/features_fetcher.cpp
map/search_mark.cpp
map/user_mark.hpp
routing/features_road_graph.cpp
search/locality_finder.cpp
transit/transit_serdes.hpp

Needs good manual testing in case if someone relied on implicit buffer zero initialization.

[Experimental] Avoid unneeded initialization in buffer_vector::resize.

---

android/jni/com/mapswithme/maps/Framework.cpp
android/jni/com/mapswithme/util/StringUtils.cpp
drape_frontend/gui/ruler_helper.cpp
map/framework.cpp
map/framework.hpp
map/routing_manager.cpp
map/routing_mark.cpp
map/routing_mark.hpp
platform/localization.cpp
platform/measurement_utils.cpp
platform/measurement_utils.hpp
platform/platform_tests/measurement_tests.cpp
platform/settings.hpp
qt/draw_widget.cpp

Adds information in the place page for incoming speed cameras (the ones shown in red).
For the moment, the place page shows the camera position and the title is the max speed if any.
I need help for this one as I have trouble retrieving the speed camera information. The `SpeedCameraMark` object does not contain a lot of information, and I was not able to retrieve the POI/Feature associated.
Here is what it looks like for the moment:
But here is how regular speed cameras look like:
I would like to retrieve the information from the regular speed camera and integrate it in the `SpeedCameraMark` but I am lost on how to proceed. Could please help me understand where to look?
Closes #1657

[navigation] populate incoming speed camera place page

---

data/replaced_tags.txt

Fixes https://github.com/organicmaps/organicmaps/issues/3517
This is my first time contributing to OM - sorry if something was done wrong. I hope overtaking assigned issues isn't bad. I did it because it was a simple fix.
The tag is used for managed, urban _natural=scrub_ s. The way OM renders natural=scrub currently fits this tag well enough, it's the same as grass, and the way scrub is used is close to natural=shrubbery, so I added it as a line to replaced_tags.txt as @biodranik said in https://github.com/organicmaps/organicmaps/issues/3517#issuecomment-1264608619. It will make the map easier to understand and look nicer, especially in certain European cities in which this tag is heavily used.
Signed-off-by Luna Rose luna@anarchy.center

[styles] Render natural=shrubbery

---

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java

This PR adds various improvements to the handling of the place page.
- Removes the `onLayoutChange` listener. All its logic has been moved outside to improve performance. For some reason this callback was called several times per seconds even when the place page was not shown, calling some unnecessary logic.
- Cleans up the code to remove warnings.
- Removes the custom peek height animation in favor of the native one.
As you can see in the following video, not much changed. The animation is slightly different but more consistent with the opening/closing ones. There is a visual artifact when you expand the bottom sheet then select a new map object, but it was already present before.
https://user-images.githubusercontent.com/80701113/194037067-dbafd45e-279a-4607-a782-0eafde48d2bb.mp4

[android] Place page performance improvements

---

android/src/com/mapswithme/maps/location/LocationHelper.java

Pass AppCompatActivity to AlertDialog instead of global Context.
```
FATAL EXCEPTION: main
Process: app.organicmaps.debug, PID: 17897
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:926)
at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:889)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:772)
at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
at …
```

[android] Fix a crash in "Location is disabled" dialog

---

android/src/com/mapswithme/maps/editor/OsmLoginFragment.java

The app was querying the intent's extras without checking if these were null and would only leave the login activity if the calling activity wanted to redirect to the profile.
So essentially login worked only when accessing the OSM profile from the settings.
Fixes https://github.com/organicmaps/organicmaps/issues/3597
Fixes https://github.com/organicmaps/organicmaps/issues/3498

[android] fix crash on login to osm after edits

---

android/AndroidManifest.xml

> Data tags should only declare unique attributes
> Consider splitting data tag into multiple tags
> with individual attributes to avoid confusion
All the `<data>` elements contained within the same `<intent-filter>` element contribute to the same filter. So, for example, the following filter specification,
```
<intent-filter . . . >
<data android:scheme="something" android:host="project.example.com" />
. . .
</intent-filter>
```
is equivalent to this one:
```
<intent-filter . . . >
<data android:scheme="something" />
<data android:host="project.example.com" />
. . .
</intent-filter>
```
https://developer.android.com/guide/topics/manifest/data-element

[android] Fix lint warnings for intent-filters

---

android/src/com/mapswithme/maps/routing/NavigationController.java
android/src/com/mapswithme/maps/widget/menu/NavMenu.java

Fixes issue mentioned in https://github.com/organicmaps/organicmaps/pull/3377#issuecomment-1272388581. The navigation bottom sheet cannot be hidden so the user cannot dismiss it and the whole navigation frame is hidden when the navigation stops. So it is pointless to try and set the bottom sheet to the "hidden" state.

[android] do not try to hide navigation bottom sheet

---

.github/workflows/linux-check.yaml

https://master.apis.dev.openstreetmap.org is working again
This reverts commit b3def7daf49b9034c2e13950910b8606d50a71d9.

Revert "Temporarily disable OSM auth tests"

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/maplayer/MapButtonsController.java

Sometimes the global layout listener is called when the fragment is not attached to a context so the `requireContext` call would crash the app. Also as the map buttons controller is a fragment itself, there is no need to call its `onResume` method from the main activity.
Fixes https://github.com/organicmaps/organicmaps/issues/3640

[android] fix crash on exit splitscreen

---

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
android/src/com/mapswithme/maps/widget/placepage/PlacePhoneAdapter.java

Steps to reproduce:
1. Select POI
2. Open POI details
3. Long click on website, email, phone, address
**Actual result:** Text is copied to clipboard with no UI notification
**Expected result:** Black snack bar should appear saying "Copied to clipboard: bla-bla-bla".
The problem probably is caused by #2258. Earlier `menu_frame` item contained bottom buttons bar:
I had to change it to `pp_buttons_layout`.
Fixes #3638

[Android] Changed Snack bar anchor view

---

android/res/values-v27/themes.xml
android/res/values/themes.xml
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/util/UiUtils.java

Hide status and navigation bar when tapping on an empty map space. When in fullscreen mode, the user can still swipe up/down where the system bars where to show them again (only temporary).
The fullscreen state is remembered when switching app or rotating the screen. This PR does NOT change when and how to enable the fullscreen mode.
https://user-images.githubusercontent.com/80701113/196030151-895aa654-4be4-45cb-9dfb-ce5fbd31ff4a.mp4
Fixes https://github.com/organicmaps/organicmaps/issues/3636
Fixes https://github.com/organicmaps/organicmaps/issues/950

[android] hide system bars on fullscreen mode

---

android/src/com/mapswithme/maps/widget/menu/MyPositionButton.java

Disables the strange logic hiding the position button. Might be a leftover/error from the refactoring.
Fixes https://github.com/organicmaps/organicmaps/issues/3694

[android] fix position button hidden in routing mode

---

android/src/com/mapswithme/maps/widget/placepage/BottomSheetChangedListener.java
android/src/com/mapswithme/maps/widget/placepage/DefaultBottomSheetCallback.java
android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
android/src/com/mapswithme/maps/widget/placepage/SimplePlacePageController.java

Only calls the onSlideFinish callback when the bottom sheet is settled. Before this patch the callback would get called on each frame when sliding the place page above its peek height.
The viewport animation is now sharper and fully opening the place page is less laggy.
https://user-images.githubusercontent.com/80701113/197361084-f6a6c1e8-c29a-475a-a311-d0817641ab45.mp4

[android] call onSlideFinish only when bottomsheet is settled

---

platform/CMakeLists.txt

We have `set -euo pipefail` set in `version.sh`, but the `set -e` that would normally report errors up the chain doesn't end up having any effect, since `cmake` just ignores the errors and proceeds.
I specifically ran into this error because I cloned the repo on my dev machine, but attempted to run the build in a container to fix some dependency bugs, and neglected to install Git. (In theory, why should I need it? I've already cloned the project! 😃)
This led to a reasonably annoying-to-debug error (for me, since I'm a bit rusty at C++ projects and debugging!)---the cmake does provide a non-fatal hint, but it's easy to miss:
```text
root@559a03f5281e:/organicmaps# tools/unix/build_omim.sh -r desktop
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU …
```

Fail cmake when execute_process fails

---

android/src/app/organicmaps/util/UiUtils.java

For some reason, setting the status bar to light when also showing them makes the screen blink on some Android configurations. No idea why so this patch simply checks if it is needed to set the status bar to light before actually doing it. So now this is not called when exiting fullscreen anymore as the status is already light (black text = light status bar).
Please tell me if this properly fixes the issue on your devices. @Jean-BaptisteC if you want to help testing it would be much appreciated!
Fixes https://github.com/organicmaps/organicmaps/issues/3727

[android] fix blink on exit fullscreen

---

android/src/app/organicmaps/bookmarks/BookmarkCategorySettingsFragment.java
android/src/app/organicmaps/bookmarks/BookmarksListFragment.java
android/src/app/organicmaps/editor/FeatureCategoryFragment.java
android/src/app/organicmaps/editor/HoursMinutesPickerFragment.java
android/src/app/organicmaps/util/Utils.java
android/src/app/organicmaps/widget/placepage/DirectionFragment.java
android/src/app/organicmaps/widget/placepage/ElevationProfileViewRenderer.java
android/src/app/organicmaps/widget/placepage/PlacePageControllerComposite.java
android/src/app/organicmaps/widget/placepage/RichPlacePageController.java

Fixes: #3757
But I really don't understand why 
```
ClassNotFoundException when unmarshalling: app.organicmaps.editor.data.FeatureCategory
```
appeared in 
```
at android.os.BaseBundle.getBoolean(BaseBundle.java:935)
at app.organicmaps.editor.EditorHostFragment.onViewCreated(EditorHostFragment.java:61)
```

[android] ClassNotFoundException in Parcelable fix

---

android/res/layout-land/onmap_downloader.xml
android/res/layout/onmap_downloader.xml

fixes https://github.com/organicmaps/organicmaps/pull/3733#issuecomment-1299086369
landscape expands, portrait is fixed size
also some small padding tweaks to reduce wasted space at the bottom
https://user-images.githubusercontent.com/26939824/199348045-1d77388e-839d-4ca6-ae8f-c90bb14433ea.mp4

[Android] Fix word wrapping & padding in download card

---

android/src/app/organicmaps/MwmActivity.java
android/src/app/organicmaps/search/SearchFragment.java

When going back to the search activity from the map view, the search was started before the activity retrieved the current location. This PR moves the query initialization from onCreateView to onResume. It also makes sure search is properly stopped when going from the map to the search activity.
Fixes https://github.com/organicmaps/organicmaps/issues/3763
@Jean-BaptisteC can you please confirm it fixes your issue?

[android] fix distance not shown on search results

---

android/res/layout-land/layout_nav.xml
android/res/layout/layout_nav.xml

Makes the navigation menu properly hidden behind the navigation bar on tablet.
| portrait | landscape |
|-|-|
| ![Screenshot_1667929718](https://user-images.githubusercontent.com/80701113/200639189-5fbd6514-64ff-4317-a2cb-41bb3c9052e4.png) | ![Screenshot_1667929724](https://user-images.githubusercontent.com/80701113/200639188-41fbc0ef-2137-424c-91f8-c1ab94946cf1.png) |
Fixes https://github.com/organicmaps/organicmaps/issues/3740

[android] fix navigation menu visible under navbar

---

xcode/expat/expat.xcodeproj/project.pbxproj
xcode/expat/expat_config.h

expat_config.h is generated by CMake, but for XCode project we don't use CMake at the moment. So the file, generated for Mac, is used there.

[3party] Updated expat to the latest released version R_2_5_0

---

indexer/categories_holder.hpp

For Estonian (#3833), translations should be also activated by adding values-et folder for Android and adding Estonian language in XCode before strings regeneration.

[categories] Enabled ca and et categories translations

---

iphone/Maps/UI/PlacePage/Components/PlacePagePreviewViewController.swift

Some time ago, I noticed that Organic Maps on iPhone doesn't show one specific case of relative time to opening/closing hours correctly. Specifically – when this time is exactly 1 hour.
---
**Example:**
<sup>(Distance from me is removed for privacy reasons)</sup>
<p>
</p>
---
So, this PR fixes that ;)

[ios] Display 1 hour to open/close properly

---

iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.h
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.mm
iphone/Maps/UI/PlacePage/Components/PlacePageHeader/PlacePageHeaderPresenter.swift
iphone/Maps/UI/PlacePage/Components/PlacePageHeader/PlacePageHeaderViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
map/place_page_info.cpp

Fixes #3756.
Before:
After:
Secondary title was missing in bookmark mode, that's why some `place_page_info.cpp` logic was changed.

[iOS][UI] Show local language secondary title in Place Page.

---

docs/INSTALL.md
docs/STYLES.md

I improved a bit the docs for WSL users and documented how to change styles in the desktop app.
It is quite easy to run the desktop app on Windows 10. I used this approach for quite some time without problems.
I'm on Windows 11 machine now and I checked that indeed running OM desktop app from WSL just works there :)

[docs] Improve docs about WSL and desktop app.

---

android/res/drawable/ic_follow.xml
data/resources-svg/ic_follow.svg

Now centred on shape centroid instead of bbox
before / after:
fixes https://github.com/organicmaps/organicmaps/issues/3926

[android] fix centring for follow icon

---

qt/draw_widget.cpp

At least on KDE trying to drag the map around would drag the whole application window.
Signed-off-by: Jaime Marquínez Ferrándiz <jaime.marquinez.ferrandiz@fastmail.net>
This is how it behaved on KDE:
https://user-images.githubusercontent.com/1239727/203256128-3ba6110d-ebcb-4d92-b00c-da3cac75eb92.mp4
With this change I can correctly drag the map around:
https://user-images.githubusercontent.com/1239727/203256241-50bc3eed-b4bb-42cd-b77d-f2b035522622.mp4

[desktop] Mark mouse move event as accepted

---

android/res/layout/place_page_preview.xml
android/src/app/organicmaps/widget/placepage/PlacePageView.java
android/src/app/organicmaps/widget/placepage/RichPlacePageController.java

Following https://github.com/organicmaps/organicmaps/pull/3544, I found the place page peek height was wrong in case the title was short enough to fit in one line without the direction arrow (position not known), but too long to fit when the direction is shown. As this arrow would blink when the sheet was opened, the logic would calculate a peek height without taking into account this arrow, and thus was not enough.
This PR aims to fix this issue by more reliably displaying the direction arrow. I also slightly modified the UI to place the arrow on top of the distance and centered, felt it was prettier. 
Going from no position to position known while the pp is open. The peek height is now correctly updated.
https://user-images.githubusercontent.com/80701113/202572365-fbecd838-3f24-4410-8817 …

[android] handle place page direction arrow more reliably

---

docs/INSTALL.md

I can add DCO by using squash. I used GH web editor for this change.

[docs] Mentioned workaround for not enough memory build errors

---

iphone/Maps/Classes/Components/MWMTableViewController.m

[ios] Settings and routing options table headers are visible now in the Dark Mode

---

.github/workflows/ios-check-metadata.yaml

* Previously the two workflows have had the same name and it was impossible to distinguish them by name when having to manually trigger the right one.

[github/workflows] Distinguish 'iOS Check' and 'iOS Check metadata'

---

iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm

The crash log (Top 1 now in AppStoreConnect):
```
_assertionFailure(_:_:file:line:flags:) + 656 (AssertCommon.swift:132) BottomTabBarInteractor.openMenu() + 252 
(BottomTabBarInteractor.swift:0) protocol witness for BottomTabBarInteractorProtocol.openMenu() in conformance 
BottomTabBarInteractor + 4 (BottomTabBarPresenter.swift:39) BottomTabBarPresenter.onMenuButtonPressed() + 4 
(<compiler-generated>:38) protocol witness for BottomTabBarPresenterProtocol.onMenuButtonPressed() in 
conformance BottomTabBarPresenter + 4 (<compiler-generated>:0) 
BottomTabBarViewController.onMenuButtonPressed(_:) + 40 (<compiler-generated>:65) @objc 
BottomTabBarViewController.onMenuButtonPressed(_:) + 88
```

[ios] Fixed crash with invalid menu state

---

indexer/feature_data.cpp

fixes cases where `shop=copyshop` is effectively a secondary tag, eg. `shop=copyshop` + `amenity=post_office`
(previously was `shop=copyshop` type)
partial fix for https://github.com/organicmaps/organicmaps/issues/4025

[indexer] Fix copyshop type priority

---

android/src/app/organicmaps/Map.java
android/src/app/organicmaps/MapFragment.java
geometry/area_on_earth.cpp
geometry/area_on_earth.hpp
geometry/distance_on_sphere.hpp
map/framework.cpp
map/framework.hpp
platform/platform.hpp
platform/platform_android.cpp
platform/platform_ios.mm
platform/platform_linux.cpp
platform/platform_mac.mm
platform/settings.cpp
platform/settings.hpp

Can't reproduce initial bug. Should test this change on Android 5-8.1 :
Crash log:
```
backtrace:
#00  pc 0x000000000006ba20  /system/lib64/libc.so (tgkill+8)
#01  pc 0x0000000000068ea4  /system/lib64/libc.so (pthread_kill+64)
#02  pc 0x0000000000024350  /system/lib64/libc.so (raise+24)
#03  pc 0x000000000001cd6c  /system/lib64/libc.so (abort+52)
#04  pc 0x0000000000ba8298  /data/app/app.organicmaps-1/lib/arm64/liborganicmaps.so (dp::TextureManager::Init(ref_ptr<dp::GraphicsContext>, dp::TextureManager::Params const&)+5064)
#05  pc 0x0000000000aa10c8  /data/app/app.organicmaps-1/lib/arm64/liborganicmaps.so (df::BackendRenderer::InitContextDependentResources()+532)
#06  pc 0x0000000000aa0e5c  /data/app/app.organicmaps-1/lib/arm64/liborganicmaps.so …
```

[android] Fixed map fragment flow.

---

base/mem_trie.hpp
generator/final_processor_utils.hpp
generator/generator_tests_support/test_with_custom_mwms.hpp
kml/serdes.cpp
map/framework.cpp
routing/routing_callbacks.hpp
search/region_info_getter.cpp
search/reverse_geocoder.cpp
storage/country_name_getter.cpp

See https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-no-automatic-move.html

Fix performance-no-automatic-move clang-tidy warnings

---

data/strings/types_strings.txt

Fixed a translation mistake from https://github.com/organicmaps/organicmaps/commit/578227e7f29f001153f6aabdf4f5e17b7e8fb18a - sorry!
—

[strings][Turkish] Minor translation fix

---

base/CMakeLists.txt
base/string_utils.cpp
xcode/base/base.xcodeproj/project.pbxproj

* For compiler diagnostics
* For dependency management

[base] Treat fast_double_parser as a system header

---

indexer/editable_map_object.cpp
indexer/indexer_tests/editable_map_object_test.cpp

fix for:
> I am trying to edit a place that is named "Lotto / Toto", but cannot. If I click anywhere to edit something it automatically jumps back to the naming field. I guess there is a problem with the "/", however, I did not put it in the name, it was already there. Any ideas? -Vinz (Matrix)
Although not a full fix, as pre-existing banned characters will still block name editing. Maybe that's how it should be though as users will have to remove incorrect characters
usage info for the characters in names in OSM:
`/` has `60 272` uses in the UK alone
`°` has `32 030` uses worldwide
`[ ]` has `17 190` uses worldwide

[indexer] allow names to contain `/`,`\`, `[`, `]` & `°`

---

platform/background_downloader_ios.mm
platform/http_uploader_background.mm
xcode/base/base.xcodeproj/project.pbxproj
xcode/coding/coding.xcodeproj/project.pbxproj
xcode/common.xcconfig
xcode/cppjansson/cppjansson.xcodeproj/project.pbxproj
xcode/drape/drape.xcodeproj/project.pbxproj
xcode/drape_frontend/drape_frontend.xcodeproj/project.pbxproj
xcode/editor/editor.xcodeproj/project.pbxproj
xcode/generator/generator.xcodeproj/project.pbxproj
xcode/geometry/geometry.xcodeproj/project.pbxproj
xcode/indexer/indexer.xcodeproj/project.pbxproj
xcode/kml/kml.xcodeproj/project.pbxproj
xcode/map/map.xcodeproj/project.pbxproj
xcode/mwm_diff/mwm_diff.xcodeproj/project.pbxproj
xcode/omim.xcworkspace/contents.xcworkspacedata
xcode/openlr/openlr.xcodeproj/project.pbxproj
xcode/platform/platform.xcodeproj/project.pbxproj
xcode/routing/routing.xcodeproj/project.pbxproj
xcode/routing_common/routing_common.xcodeproj/project.pbxproj
xcode/search/search.xcodeproj/project.pbxproj
xcode/shaders/shaders.xcodeproj/project.pbxproj
xcode/storage/storage.xcodeproj/project.pbxproj
xcode/tracking/tracking.xcodeproj/project.pbxproj
xcode/traffic/traffic.xcodeproj/project.pbxproj
xcode/transit/transit.xcodeproj/project.pbxproj

Looks like there are no benefits of using them with XCode builds

[xcode] Do not use precompiled headers

---

android/res/values/strings-tts.xml

Have enabled all languages with translated strings in sounds.txt, and ordered them alphabetically.
fixes https://github.com/organicmaps/organicmaps/issues/4199
Newly enabled languages are: 
- Belarusian (`be`)
- Basque (`eu`)
- Croatian (`hr`)
- Marathi (`mr`)
- Norwegian (`nb`)
- Swahili(`sw`)
(some langs not visible in screenshot because not supported by my device TTS)

[android] update list of supported TTS langs

---

qt/bookmark_dialog.cpp

[desktop] Allow importing of upper-case .KML and .KMZ files on case-sensitive Linux

---

android/AndroidManifest.xml

Add missing starting `/` as suggested by Google.
Tested on API 21, 24, 33 with different apps.
Closes #3884

[android] Fix a warning for `data://*.*\\..*\\..*\\..*\\.kml`

---

platform/platform_linux.cpp
private_default.h

* Considering, that organicmaps is advertised as:
"We protect your privacy from Big Tech's prying eyes"
It is perhaps a benefit if the user's IP address is not sent to Microsoft every time a status check is needed. Currently Microsoft is among the top five [Big Tech](https://en.wikipedia.org/wiki/Big_Tech) companies.
* With this change the code checks whether the host name resolution also works because by default the map downloading relies on host names instead of IP addresses and therefore does not work if name resolution doesn't work.
* Uses a meaningful target for checking the connectivity towards. For downloading maps, the connectivity has to work either towards the metaserver. (Or as a fallback towards a default server.)
* Specifies the protocol of the SOCK_STREAM more than before. …

[linux] Check connection to hostname

---

android/res/values/strings-tts.xml

fixes
@endim8 sv is Swedish, but below it was Slovenčina
_Originally posted by @biodranik in https://github.com/organicmaps/organicmaps/pull/4201#discussion_r1083258237_

fix reported TTS language for Slovenčina

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Look like PR #2484 has stuck.
I created simple issues templates: "Bug report" and "Feature request".
Got to my fork https://github.com/strump/organicmaps/ and try to create an issue:
Closes #2484

Github issues templates

---

drape_frontend/drape_engine.cpp
drape_frontend/drape_engine.hpp
drape_frontend/screen_animations.cpp
drape_frontend/user_event_stream.cpp
drape_frontend/user_event_stream.hpp

There is a bug with animation when a search result is selected. A better fix is needed.
Also one beta-tester has reported this:
I'm experiencing some weird behaviour where it zooms to the poi I was looking for but then zooms away from it unendlessly. Here are the steps to reproduce:
- start at poi x,
- click location button,
- search for same poi x again,
- click on said poi x from search results.
This reverts commit 19dc496a3571ca424cfc5c7057a92018914be6d3.

Revert "[drape] SetCenterEvent animation fix"

---

android/src/app/organicmaps/editor/OsmLoginFragment.java

During my tests, i have detect a bug
In OsmLoginFragment ->LoginButton use [string login_osm](https://github.com/organicmaps/organicmaps/blob/143086b451405c0824829c151ba6393a8363e0a2/android/res/layout/fragment_osm_login.xml#L93), like asked here https://github.com/organicmaps/organicmaps/pull/2909#issuecomment-1179559429
If i try to log in without fill connection informations, after skip pop-up, `Login to OpenStreetMap` is replaced by `Log In` in LoginButton
Signed-off-by: Jean-Baptiste CHARRON <jeanbaptiste.charron@outlook.fr>

[android] Fix wrong string used

---

android/src/app/organicmaps/car/SurfaceRenderer.java

Android Auto was updated and added a new layout for split-screen. This is a small fix to handle layout change properly.
There is no updated documentation yet. Perhaps, I didn't find it. So, I don't know what was added more.
Case: Entering split-screen mode
Before: crash
Now:
https://user-images.githubusercontent.com/10351358/218823589-2eb63dc9-c6cc-46e4-9540-6badd728a8b6.mp4
Google Maps for comparison:
https://user-images.githubusercontent.com/10351358/218823873-46bbfa61-ea2e-4a3e-a2df-ac9ec33efadc.mp4
As you can see from GMaps example, there is a possibility to select the route point from split-screen. No other apps like Yandex, OsmAnd, or 2GIS support this feature yet.

[android-auto] Layout change fix

---

drape_frontend/apply_feature_functors.cpp
indexer/drawing_rule_def.hpp
indexer/drawing_rules.cpp
indexer/drawing_rules.hpp

This code doesn't change anything.
It was commented as `obsolete for new styles, can be removed` in https://github.com/mapsme/omim/commit/6d4e795f01a7235be2df68babcf968f72dd95694, so probably haven't been working since then.
As far as I understand the point of this "apply_for_type: 1" rule was to disable drawing an icon for an area POI, while drawing it for point POIs of this type only.
E.g. a point `amenity-hospital` with an icon, but a filled area `amenity-hospital` without an icon.
So looks like its not needed really.
If we can remove it here then we'll be able to drop it in kothic and in protobuf format also. It looks like its the only thing in our style files that requires prepending node/area/line to style definitions still, see …

[drape] Remove obsolete apply_for_type icon drule attribute

---

drape/overlay_handle.cpp

Overlay priorities are always positive and way below 100000 anyway.

[drape] Don't add 100000 to overlay priorities and don't cap them

---

android/res/layout/downloader_item.xml
android/src/app/organicmaps/downloader/DownloaderAdapter.java

Signed-off-by: Gonzalo Pesquero <gpesquero@yahoo.es>
Fixes the cut of long map names in the map download search list, as reported in [issue 4449](https://github.com/organicmaps/organicmaps/issues/4449).
This commit also removes the limitation to 1 line of the _subtile_ (city list) of the maps in the list.

[android] Allow multiple lines in map name field of search list

---

iphone/Maps/UI/Editor/MWMEditorViewController.mm

Fixes #4516
Now notes to editors are displayed only if nothing can be edited for the selected object. This PR fixes it.

[ios] Enabled OSM editor notes for all places

---

android/src/app/organicmaps/widget/placepage/PlacePageWikipediaFragment.java

Fixes #4529 
Previously: 
Now:
And I guess it is draggable too:

[android] Made the Wikipedia article of any place page clickable

---

android/res/layout/place_page_description_layout.xml

(regression, doesn't need to be included in changelog)
Before/after
fixes #4563

[Android] fix whitespace in wikipedia description (regression fix)

---

tools/unix/version.sh

When trying to build from branches that were older than 30 days, the build failed with the following message:
`version.sh: line 12: COUNT_AND_DATE: unbound variable`
This commit fixes that.

[tools] Fix unbound variable in version.sh

---

android/src/app/organicmaps/bookmarks/BookmarkCategoriesAdapter.java
android/src/app/organicmaps/bookmarks/Holders.java
android/src/app/organicmaps/editor/CuisineAdapter.java
android/src/app/organicmaps/editor/FeatureCategoryAdapter.java
android/src/app/organicmaps/editor/LanguagesAdapter.java
android/src/app/organicmaps/editor/MultilanguageAdapter.java
android/src/app/organicmaps/editor/SimpleTimetableAdapter.java
android/src/app/organicmaps/editor/StreetAdapter.java
android/src/app/organicmaps/search/CategoriesAdapter.java

**Issue:**
getAdapterPosition() is deprecated
**Solution:**
Replaced it with getBindingAdapterPosition() which returns the position in the specific adapter.
**Source:** https://stackoverflow.com/questions/63068519/getadapterposition-is-deprecated

[android] Fix deprecated getAdapterPosition()

---

android/src/app/organicmaps/MwmActivity.java

From a UX point of view, I don't see why we should close it. Opening the search does not close the bottom sheet so this makes the behavior more consistent.
Could fix https://github.com/organicmaps/organicmaps/issues/4549. I can't reproduce it but from the video it seems to be the cause of the crash.

[android] do not close bottom sheet when opening bookmarks

---

android/res/values/themes-attrs.xml
android/res/values/themes-base.xml
android/res/values/themes.xml

Tested on Pixel 6 - Android 13, Honor 8 - Android 8
|---|---|
|<img src="https://user-images.githubusercontent.com/87148630/220699737-a01305b0-920b-4ad7-bddf-b94c638003e2.png" height=400 />|<img src="https://user-images.githubusercontent.com/87148630/222568679-f45f6cc6-567c-4c2c-b002-cb218a3fb5ff.png" height=400 />|
|<img src="https://user-images.githubusercontent.com/87148630/220700312-a9ee50c9-7bfb-4a68-964b-32e267f19b14.png" height=400 />|<img src="https://user-images.githubusercontent.com/87148630/222568952-bc067cae-d2d1-44a1-89fc-114ece104ef0.png" height=400 />|
|<img src="https://user-images.githubusercontent.com/87148630/220701015-8d00eef3-93b7-4b74-b8a3-3dbad9338ec6.png" height=400 />|<img src="https://user-images.githubusercontent.com/87148630/222569082-df3f725f …

[android] Improve theming in alertDialog on most recent devices

---

android/src/app/organicmaps/DownloadResourcesLegacyActivity.java
android/src/app/organicmaps/MapFragment.java
android/src/app/organicmaps/MwmActivity.java
android/src/app/organicmaps/SplashActivity.java
android/src/app/organicmaps/bookmarks/BookmarkCategorySettingsFragment.java
android/src/app/organicmaps/bookmarks/BookmarksSharingHelper.java
android/src/app/organicmaps/dialog/EditTextDialogFragment.java
android/src/app/organicmaps/downloader/DownloaderAdapter.java
android/src/app/organicmaps/downloader/MapManager.java
android/src/app/organicmaps/editor/EditorFragment.java
android/src/app/organicmaps/editor/EditorHostFragment.java
android/src/app/organicmaps/editor/HoursMinutesPickerFragment.java
android/src/app/organicmaps/editor/OsmLoginFragment.java
android/src/app/organicmaps/editor/ProfileFragment.java
android/src/app/organicmaps/editor/TimetableContainerFragment.java
android/src/app/organicmaps/location/LocationHelper.java
android/src/app/organicmaps/maplayer/traffic/widget/TrafficButtonController.java
android/src/app/organicmaps/routing/BaseRoutingErrorDialogFragment.java
android/src/app/organicmaps/routing/RoutingController.java
android/src/app/organicmaps/settings/SettingsPrefsFragment.java
android/src/app/organicmaps/settings/StoragePathFragment.java
android/src/app/organicmaps/util/Utils.java
android/src/app/organicmaps/widget/placepage/BookmarkColorDialogFragment.java

I have migrate all AlertDialog to MaterialAlertDialog
https://developer.android.com/reference/com/google/android/material/dialog/MaterialAlertDialogBuilder
Migrate to new AlertDialog have no impact because it's the same dialog with just support to used Material Theming
Tested on Pixel 6 - Android 13 and Honor 8 - Android 8
I have tested custom alert dialog (EditTextDialogFragment, missmapsdialog)
Screenshot are available here https://github.com/organicmaps/organicmaps/pull/4575

[android] Migrate AlertDialog to MaterialAlertDialog

---

docs/INSTALL.md

This is a neat little trick I found out which greatly improves performance. I don't need to wait 5min for android studio to start and it doesn't take 5GB of ram anymore. It now starts in a few seconds and "only" uses 2GB of ram.

[docs] disable cpp folder indexing on android

---

map/mwm_url.cpp
map/mwm_url.hpp

[api] Workaround for invalid API coordinates passed via om://search requests without lat lon

---

data/strings/types_strings.txt

I've put in use a more common designation for artworks where it was intended, instead of "szobor" which we use more often for statues and sculptures.
Signed-off-by: @d4f5409d

Fix misleading translations (hu)

---

kml/kml_tests/serdes_tests.cpp
kml/serdes.cpp

Closes: #3467
What do you think? Is it a valid solution?
TODO:
Here is how it looks inside a kml:
```xml
<Placemark id="placemark20">
<name><![CDATA[Кальянная Erenler Nargile ve Çay Bahçesi]]></name>
<styleUrl>#icon20</styleUrl>
<description><![CDATA[<table width="400"><tr><td></td></tr></table>]]></description>
<MultiGeometry>
<Point>
<coordinates>28.968447783842,41.009030507129,0</coordinates>
</Point>
<LineString id="line20">
<extrude>1</extrude>
<tessellate>1</tessellate>
<coordinates>28.968447783842,41.009030507129,0 28.965858,41.018449,0</coordinates>
</LineString>
</MultiGeometry>
</Placemark>
```

[kml] Correctly import bookmarks with track data

---

android/src/app/organicmaps/settings/SettingsPrefsFragment.java

Closes #4748
In some cases preferences could be removed at runtime. And `findPreference()` method returns `null` even if key is present in `prefs_main.xml`.
Added ↗ arrow symbol at the end. And the link changed color to blue (accent color).

[Android] Fix settings crashes

---

android/src/app/organicmaps/widget/placepage/PlacePageBookmarkFragment.java
android/src/app/organicmaps/widget/placepage/PlacePageLinksFragment.java
android/src/app/organicmaps/widget/placepage/PlacePageOpeningHoursFragment.java
android/src/app/organicmaps/widget/placepage/PlacePagePhoneFragment.java
android/src/app/organicmaps/widget/placepage/PlacePageView.java
android/src/app/organicmaps/widget/placepage/PlacePageWikipediaFragment.java

Subscribe to listeners in onResume and unsubscribe in onPause.
Should hopefully fix #4729, but I was not able to reproduce it.
According to the [doc](https://developer.android.com/guide/fragments/lifecycle), these are the first/last events from the create/destroy lifecycle. So the callbacks should never get called when the views are not ready.

[android] update listeners subscription lifecycle

---

android/AndroidManifest.xml

As explained in [18023cd](https://github.com/organicmaps/organicmaps/commit/18023cdb5f4c8869d4593ba1d44013e72b60e2a3), this fixes a bug that occured on the "download map" screen, typically on a first launch/after a cache reset.
The solution I found is to track a status variable between the activity destruction and its creation after the rotation.
This PR shoud fix #4496.
I look forward to your feedback regarding this matter :)

[android] fix "download world" systematic pause after phone rotation 

---

android/src/app/organicmaps/maplayer/MapButtonsController.java

[Android][Regression]
Fixed issue [#4680](https://github.com/organicmaps/organicmaps/issues/4680) , where the zoom buttons did not disable from the map. Also the earlier bug [#4458](https://github.com/organicmaps/organicmaps/pull/4458)  is not reintroduced.

[android] zoom buttons are not disabled fixed

---

.github/workflows/android-check.yaml
.github/workflows/ios-check.yaml
.github/workflows/linux-check.yaml
.github/workflows/macos-check.yaml

Should fix improperly cancelled jobs, for example, here: https://github.com/organicmaps/organicmaps/pull/4790

[github] Properly cancel only relevant workflows from the matrix build

---

android/src/app/organicmaps/bookmarks/BookmarkListAdapter.java

...more button is not clickable there yet.
Description was accidentally disabled when we cleaned up the project 2 years ago.

[android] Enabled displaying of bookmark list description

---

docs/INSTALL.md

Running Linux GUI apps from WSL2 requires GPU driver installation, otherwise segmentation faults arise (see #4834). As discussed, in this issue with @biodranik, documentation is being updated to include this as a requirement to run the desktop OM.

[docs] Updated WSL installation guide to include GPU driver installation

---

coding/sha1.hpp
map/power_management/power_management_schemas.hpp

With the current openSUSE Tumbleweed version it had started to fail.

Explicitly include cstdint when using uint8_t

---

android/res/layout/edit_bookmark_common.xml
android/res/layout/fragment_phone.xml
android/res/layout/fragment_timetable_advanced.xml
android/res/layout/item_add_street.xml
android/res/layout/position_chooser.xml

The text cuts out when the text size increased.
View scales with respect to the text size.
https://github.com/organicmaps/organicmaps/issues/4774
https://github.com/organicmaps/organicmaps/issues/4417

Fixed cut text in Views

---

drape/gl_extensions_list.cpp
drape/gl_functions.cpp
drape/gl_includes.hpp
openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.cpp
openlr/openlr_match_quality/openlr_assessment_tool/map_widget.cpp
openlr/openlr_match_quality/openlr_assessment_tool/map_widget.hpp
qt/draw_widget.cpp
qt/draw_widget.hpp
qt/main.cpp
qt/mainwindow.cpp
qt/mainwindow.hpp
qt/qt_common/map_widget.cpp
qt/qt_common/map_widget.hpp
search/search_quality/assessment_tool/main_view.cpp

Fixes flathub/app.organicmaps.desktop#1 for devices that are only capable of ES2.

[drape][gl_functions]: Handle ES2 scenario on Linux 

---

android/res/layout/place_page_email.xml

Makes email icon blue to match other interactive options:
before/after

[android] make email icon blue

---

tools/python/stylesheet/cat_stat.py

there was unlabelled extra column, better name for usage count
Now output goes like
```
type,is editable,can add,drawn,icon,area,name drawn,usage count in osm,source
aerialway-cable_car,,,v,,,n,1277,aerialway=cable_car
aerialway-chair_lift,,,v,,,n,8855,aerialway=chair_lift
aerialway-drag_lift,,,v,,,n,4342,aerialway=drag_lift
aerialway-gondola,,,v,,,n,1704,aerialway=gondola
aerialway-j-bar,,,v,,,n,221,aerialway=j-bar
aerialway-magic_carpet,,,v,,,n,2363,aerialway=magic_carpet
aerialway-mixed_lift,,,v,,,n,97,aerialway=mixed_lift
aerialway-platter,,,v,,,n,4169,aerialway=platter
aerialway-rope_tow,,,v,,,n,1539,aerialway=rope_tow
```

fix inconsistency

---

android/res/layout/activity_map.xml
android/res/layout/place_page_container_fragment.xml
android/src/app/organicmaps/MwmActivity.java
android/src/app/organicmaps/maplayer/MapButtonsController.java
android/src/app/organicmaps/maplayer/MapButtonsViewModel.java
android/src/app/organicmaps/maplayer/MapLayersController.java
android/src/app/organicmaps/maplayer/SearchWheel.java
android/src/app/organicmaps/maplayer/ToggleMapLayerFragment.java
android/src/app/organicmaps/routing/NavigationController.java
android/src/app/organicmaps/widget/menu/MyPositionButton.java
android/src/app/organicmaps/widget/placepage/PlacePageButtons.java
android/src/app/organicmaps/widget/placepage/PlacePageController.java
android/src/app/organicmaps/widget/placepage/PlacePageUtils.java
android/src/app/organicmaps/widget/placepage/PlacePageView.java
android/src/app/organicmaps/widget/placepage/PlacePageViewModel.java
android/src/app/organicmaps/widget/placepage/sections/PlaceOpeningHoursAdapter.java
android/src/app/organicmaps/widget/placepage/sections/PlacePageBookmarkFragment.java
android/src/app/organicmaps/widget/placepage/sections/PlacePageLinksFragment.java
android/src/app/organicmaps/widget/placepage/sections/PlacePageOpeningHoursFragment.java
android/src/app/organicmaps/widget/placepage/sections/PlacePagePhoneFragment.java
android/src/app/organicmaps/widget/placepage/sections/PlacePageWikipediaFragment.java
android/src/app/organicmaps/widget/placepage/sections/PlacePhoneAdapter.java
android/tests/java/app/organicmaps/widget/placepage/sections/PlaceOpeningHoursAdapterTest.java

Further improve place page and map buttons fragment abstraction by trying to follow [Android's best practices](https://developer.android.com/topic/architecture/ui-layer?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-architecture%23article-https%3A%2F%2Fdeveloper.android.com%2Ftopic%2Farchitecture%2Fui-layer#udf).
With these changes, the main activity does not call fragment functions directly, but instead updates their state using view models. Fragments send data back to the activity using event callbacks.
Saving the UI state between configuration changes is a lot easier as view models handle this natively, it is easier to sync multiple UI components to a single state and we better understand when the data is modified.
The menu bottom sheets would also benefit …

[android] Map fragments improvements

---

packaging/app.organicmaps.desktop.metainfo.xml

[packaging] Add 2023.05 release notes to .metainfo.xml

---

android/src/app/organicmaps/util/Config.java

In some cases, it causes a flickering bug.
Fixes #3967
Fixes #2857

[android] Disable showing maps on lockscreen on older devices

---

android/src/app/organicmaps/sound/TtsPlayer.java

This is something that I noticed while testing OM on a family trip in parallel to driver's GMaps. 1.2 speed is quite fast.
Not sure why [this was done](https://github.com/organicmaps/organicmaps/commit/29553bd25c81dfbc0bae29e1e735151e31a315db). Maybe back then built-in TTS was different (Pico TTS?). Now, for Google Speech Services a speed of 1.0 feels better to me. For Samsung TTS as well.
Fixes #1080

[android][routing] Decrease TTS speed from 1.2 to 1.0

---

android/src/app/organicmaps/widget/placepage/PlacePageView.java

Fixes #5140
Instead of attaching the country in onStart, we only do it when the map object observer gets called (which is done in onStart as we start observing there).
Also removed an unnecessary null check for the map object in `setCurrentCountry` which prevented the downloader icon to show when rotating the device. The map object gets assigned after the country is set so it was always null on the first call after rotating the screen.

[android] improve pp attach country behavior

---

android/src/app/organicmaps/widget/placepage/sections/PlacePageWikipediaFragment.java

Description was not reappearing when switching back from a map object with only a link.
Here are the steps to reproduce the issue fixed in this PR:
- Open the place page for an object **without** a wiki description
- Without closing the place page, click on an object **with** a wiki description: the description will not show
- Close the place page and open the object with the wiki description: the description will now show
The code only took care of hiding the description but there was nowhere to show it back. The description was shown by default when the fragment was created, so if you switched map object the fragment was kept and thus the description stayed hidden.

[android] fix wiki description not always shown

---

xcode/fastlane/Fastfile

Fixes Could not install WWDR certificate error for TestFlight.
Should fix https://github.com/organicmaps/organicmaps/actions/runs/4977609757/jobs/8906864764

[testflight] Manually import Apple WWDR certificate

---

android/src/app/organicmaps/widget/placepage/PlacePageController.java

Fixes issue raised in https://github.com/organicmaps/organicmaps/pull/4613#issuecomment-1545050797 where the last scroll position would be wrongly remembered.
To reproduce open the place page and scroll so content goes out of screen (you can add to bookmark and add a long description to create a large place page), then rotate the device.
When the place page opens (set to "collapsed" state), we check the scroll position and reset it to 0 if necessary.

[android] reset place page scroll on open

---

android/res/layout/place_page_container_fragment.xml
android/src/app/organicmaps/widget/placepage/PlacePageController.java

Complimentary to https://github.com/organicmaps/organicmaps/pull/4593 to fix https://github.com/organicmaps/organicmaps/issues/4565.
If the content is large enough, the place page will stop under the status bar/notch with a margin of 24dp. Users are still able to scroll the content when the max height is reached. 
https://user-images.githubusercontent.com/80701113/221383679-392bf62a-5153-4088-a3d9-1ce181e58265.mp4

[android] rework fullscreen place page

---

data/mapcss-mapping.csv
data/strings/types_strings.txt
data/styles/clear/include/Basemap.mapcss
data/styles/clear/include/Basemap_label.mapcss

Added support for waterway=fish_pass. Rendering is the same as for ditch and drain.
- should name be used as well?
- should rendering be like ditch and drain or rather like stream?
- (vehicle style not implemented yet)
Thanks for the review!
(before and after, https://www.openstreetmap.org/way/102490507)

[styles] rendering for waterway=fish_pass

---

3party/CMakeLists.txt
CMakeLists.txt

Small enhancement for cmake
* Moved 3party includes from `CMakeLists.txt` to `3party/CMakeLists.txt`.
* Created function `omim_add_subdirectory` that groups all targets under the subdirectory into one folder (for IDEs that support this feature). 
It won't break anything as it only affects the visual representation in the IDE
<details><summary>Before:</summary>
<p>
</p>
</details> 
<details><summary>After:</summary>
<p>
</p>
</details>

[cmake] Group targets into folders

---

android/src/app/organicmaps/bookmarks/data/BookmarkManager.java

An example of the exception after selecting Downloads folder:
java.lang.SecurityException: Document 4450 is not a descendant of downloads
Also fixes #3594

[android] Fixes security exception when bookmarks are imported

---

android/res/values-de/strings.xml
data/strings/strings.txt
iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
iphone/Maps/LocalizedStrings/pt-BR.lproj/Localizable.strings

Follow up change of #5057. Also changed "Erdweg" to "Unbefestigte Straße" in other strings to make the UX consistent.

Improved german translation for unpaved roads

---

android/src/app/organicmaps/MwmActivity.java
android/src/app/organicmaps/bookmarks/BookmarkCategoriesFragment.java
android/src/app/organicmaps/util/Utils.java
android/src/app/organicmaps/widget/placepage/PlacePageUtils.java
android/src/app/organicmaps/widget/placepage/PlacePageView.java
android/src/app/organicmaps/widget/placepage/sections/PlacePageBookmarkFragment.java
android/src/app/organicmaps/widget/placepage/sections/PlacePageLinksFragment.java
android/src/app/organicmaps/widget/placepage/sections/PlacePhoneAdapter.java

Fixes #4815 
Closes #5105
@arnaudvergnet showSnackbar's viewAbove was broken after refactorings. I've fixed other wrong viewAbove uses too.
This fix can be done better if the snack message is displayed above the map buttons. Would you happen to have any ideas on how to do it?
But there can also be a visible place page that may hide the toast, right?

[android] Fixes non-working "Bookmark import succeeded/failed" snackbar

---

iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.h
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.mm
iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
map/place_page_info.cpp
map/place_page_info.hpp

Added all supported coordinates to PlacePage. Tap to switch. Long tap to copy.
Closing issue #5204 and #1572

[iOS] Show all supported coordinates at PlacePage

---

kml/serdes_gpx.cpp
kml/serdes_gpx.hpp

@cyber-toad My bad, I didn't see on review that you _store_ string_views that may point to already destroyed strings.
Fixes this: https://github.com/organicmaps/organicmaps/actions/runs/5259411718/jobs/9504945838

Fixed UB/assert when parsing GPX

---

qt/mainwindow.cpp

I don't know how to fix artifacts on the left and on the right. They appeared after upgrading from Qt5 to Qt6

[qt] More contrast download button text color

---

android/src/app/organicmaps/intent/Factory.java

This allows the 'backurl' API argument to be used in all launch scenarios.

[Android] backurl API fixes

---

data/categories.txt

Hey folks. I kindly ask you to review _shop_ search category translations. This is very important for the good search experience.
Again faced with a situation when entering for example "Rodo store" (Rodo is a name), got a lot of dummy results, but not needed ones.
Please review common search categories:
- ```@shop``` - means _very generic_ shop (store) term that can be applied to food, tobacco, watch, convenience, etc ...
- ```@shopping``` - means _shopping_ category that is visible in search categories list. For clothes, watches, jewelry, etc ... It should match strings.txt translation. 
- ```@food``` - means shops with food (including beverages and alcohol :) )
Then review all shop types. The key point here is that **no need** to duplicate common terms like shop/store anymore. Only …

[search] Fixed shop categories.

---

android/src/app/organicmaps/widget/placepage/PlacePageController.java

Prevents user from grabbing the place page and clicking on its elements while the close animation is playing.
Before this PR, users could grab the place page before it was fully closed and reopen it. This would result in an invalid state where the code would think the place page is closed but it would still be visible on screen.
An other issue was that users could still click on elements while the place page was closing. For example open the PP, tap on an empty map area to close it and very quickly tap on the compass arrow in the place page. The tap on the button would register and you would see the full screen compass view. Again this is not a valid UI state.
Complements https://github.com/organicmaps/organicmaps/pull/5353
@biodranik @Jean-BaptisteC can you please try this PR?

[android] prevent interaction with place page on closing

---

data/strings/strings.txt
iphone/plist.txt

This PR replaces the German word "Strecke(n)" by "Track(s)".
It is a small followup of the latest change that added the information that tracks can also be imported (https://github.com/organicmaps/organicmaps/pull/5369#pullrequestreview-1487547552).
In the translation there is still one occurrence where "Strecke" is used:
https://github.com/Mr-Mime/organicmaps/blob/ea56b1f70cbdd50c8c941ad5df72655fc517f6f8/data/strings/strings.txt#L5494
`de = So können Sie die zurückgelegte Strecke für einen bestimmten Zeitraum aufzeichnen und auf der Karte sehen. Hinweis: Die Aktivierung dieser Funktion führt zu erhöhtem Batterieverbrauch. Die Aufzeichnung wird nach Ablauf des Zeitintervalls automatisch von der Karte entfernt.`
In my opinion in this case "Strecke" is the right word, and "Track" would not …

[strings] Update german translation

---

android/res/values-de/strings.xml
android/res/values-pl/strings.xml
data/strings/strings.txt
iphone/Maps/LocalizedStrings/de.lproj/InfoPlist.strings
iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
iphone/Maps/LocalizedStrings/de.lproj/Localizable.stringsdict

Small fix for https://github.com/organicmaps/organicmaps/pull/5369 ("utwory" actually means "music tracks" 😅)
Strings regeneration added also some german translations, probably because `tools/unix/generate_localizations.sh` was not run before 🤔.

[strings] Polish translation for "import bookmarks and tracks"

---

data/gpx_test_data/osmand1.gpx
data/gpx_test_data/osmand2.gpx
kml/kml_tests/gpx_tests.cpp
kml/serdes_gpx.cpp
kml/serdes_gpx.hpp

Add color support for OSMAnd #5287 
@biodranik - I noticed a strange thing - for kml also if we set up some hex color for waypoint (bookmark) it is displayed as red. I tested with Google Earth. Maybe it is because some pre-defined set of colors (available in choose color dialog) is used and hex are ignored?
But they are sucessfully parsed from bookmark file - see unit test.

Gpx osmand color

---

.gitmodules

Also change the git submodule to Gitlab, because Github is not kept in sync.
Required for #4281

[3party] Upgrade freetype to 2.13.1

---

.github/workflows/linux-check.yaml
.github/workflows/macos-check.yaml

Use ccache to store C++ caches for each build configuration
Stats:
| Build | Ccache | No Ccache | Increase |
|--------|--------|--------|--------|
| MacOs Debug | 4m44s | 18m41s | 3.9x |
| MacOs RelWithDebInfo | 1m8s | 23m50s | 21x |
| Linux no unity | 7m54s | 33m13s | 4.2x |
| Linux g++ Debug | 3m13s | 17m54s | 5.5x |
| Linux g++ RelWithDebInfo | 31m43s | 35m31s | 1.1x | 
| Linux clang Debug | 2m29s | 15m57s | 6.4x | 
| Linux clang RelWithDebInfo | 2m38s | 22m16s | 8.5x |

[ci] Use ccache to decrease build time

---

data/mapcss-mapping.csv

A combination of `highspeed=yes service=*` produces two types `railway-rail-highspeed railway-rail-service` - 5K cases.
Fixed such cases to produce `railway-rail-service` only.

[classif] Exclude service=* from railway-rail-highspeed

---

.github/workflows/linux-check.yaml
.github/workflows/macos-check.yaml

This PR should create a cache in the master branch that will be accessible for future PRs.
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
>Workflow runs can restore caches created in either the current branch or the default branch (usually main).

[ci] Trigger Linux and MacOS builds on push to master

---

android/src/app/organicmaps/intent/Factory.java

Reverts organicmaps/organicmaps#5322
Regression, It breaks simple geo: url open.

Revert "[Android] backurl API fixes"

---

editor/editor_tests/xml_feature_test.cpp
indexer/editable_map_object.cpp

The issue #5509 is caused by edits save/load. When POI is modified it's saved on device in OSM XML format using `editor::ToXML(...)` method with explicit social contacts processing. Function `editor::ApplyPatch(...)` loads OSM XML but skips social contacts normalization.
Method `EditableMapObject::UpdateMetadataValue` is used only within `xml_feature.cpp` so this fix should not affect OM functionality.
Closes #5509.

Fix social contacts parsing on edits loading

---

.github/workflows/android-check.yaml
.github/workflows/cleanup_caches.yml
.github/workflows/ios-check.yaml
.github/workflows/linux-check.yaml
.github/workflows/macos-check.yaml

* Add ccache for Android Build. Compile time decreased from ~16m to ~4m for Fdroid and from ~6m to ~3m for WebDebug.
* Add ccache for iOS Build. Compile time decreased from ~30m to ~10m
* Env var is enough. No need to pass `CMAKE_*_COMPILER_LAUNCHER` directly to cmake
* Add workflow to automatically cleanup caches for PR after close, like GitHub [recommends](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries)

[ci] Ccache improvements

---

generator/feature_sorter.cpp
generator/generator_tool/generator_tool.cpp
generator/geometry_holder.hpp
generator/statistics.cpp
generator/statistics.hpp
indexer/feature.cpp
indexer/feature.hpp

Closes #2927.
If a geometry is too similar to a more detailed geom scale then discard it and use the more detailed one for rendering.
Pros and cons:
`+` smaller mwms
`+` slightly better rendering quality as some features stay detailed on more zoom levels
`-` slightly slower reading and rendering (could be offset somewhat by more efficient file cache utilisation)
With the current settings (`kGeomMinDiff = 8` and `kGeomMinFactor=2.0`) some geom scales of my test mwms were reduced 3 times, though overall impact on geometry size and mwm size is quite modest. The biggest mwm size reduction I saw was 13%, but its w/o isolines, wiki descriptions, etc.
Isolines are likely to be well optimizable - I'm yet to test it.
Sample optimization stats for Auckland, NZ (4% mwm reduction):
(`similar` lines …

Discard similar geometry

---

kml/kml_tests/gpx_tests.cpp
kml/serdes_gpx.cpp

Some properties like name or colors were not applied to the entire "trk" track in GPX imports when the "trk" included multiple "trkseg" segments, but only to the first "trkseg" segment.
Now it imports multiple "trkseg" that are part of one "trk" as one
In the example below the color would have only applied to the first track segment, not the entire track
```
<trk>
<extensions>
<color>0000ff</color>
</extensions>
<trkseg>
<trkpt lat="58.208378" lon="26.374915">
</trkpt>
<trkpt lat="58.208407" lon="26.374831">
</trkpt>
</trkseg>
<trkseg>
<trkpt lat="55.208378" lon="25.374915">
</trkpt>
<trkpt lat="55.208407" lon="25.374831">
</trkpt>
</trkseg>
</trk>
```

Treat GPX track segments as part of the singular track they belong to

---

generator/feature_sorter.cpp
indexer/scales.cpp
indexer/scales.hpp
topography_generator/generator.cpp
topography_generator/utils/contours.hpp

The topography generator tool part from #5556.
Requires re-generation of `*.isolines` files to take effect.

[isolines] Filter geom3 closed degenerate and too small isolines

---

editor/server_api.cpp

See https://github.com/organicmaps/organicmaps/issues/2071#issuecomment-1099121205
The name of the operating system is similar to that used in changeset tags https://github.com/organicmaps/organicmaps/blob/f1021ed70b032621cd5088b40c50e4eb71ed1846/iphone/Maps/Core/Editor/MWMEditorHelper.mm#L36

[editor] add user's OS to the note text

---

iphone/Maps/Core/Theme/Extensions/UIColor+hexString.swift
iphone/Maps/Maps.xcodeproj/project.pbxproj
iphone/Maps/UI/PlacePage/Components/PlacePageDescriptionViewController.swift

Added CSS color property in PlacePageDescriptionViewController.swift that is being substituted by particular hexCode of color depending on whether night mode is active or not.
I have decided to retrieve colors from UIColor because in future theme accents might change and this would result in additional work for finding this controller and replacing colors in it.
Fixes: #5364, #3042
Dark theme:
Light theme:

[ios] Fixes wikipedia place description text in dark mode

---

map/routing_manager.cpp

When new point added/removed OM zooms to show all route points.
Removed this zoom. Only final zoom left (after route build finishes):
| ---- | ---- |
| <video src="https://github.com/organicmaps/organicmaps/assets/720808/17164931-c59c-4ca8-8e50-02dee8da54a5"/> | <video src="https://github.com/organicmaps/organicmaps/assets/720808/5e617120-4ec3-4337-b0fd-b8cf577c41ba" />|
Closes #5409

Removed annoying zoom in route planning mode

---

data/styles/clear/include/priorities_1_BG-by-size.prio.txt
data/styles/clear/include/priorities_2_BG-top.prio.txt
data/styles/clear/include/priorities_3_FG.prio.txt
data/styles/clear/include/priorities_4_overlays.prio.txt
data/styles/vehicle/include/priorities_1_BG-by-size.prio.txt
data/styles/vehicle/include/priorities_2_BG-top.prio.txt
data/styles/vehicle/include/priorities_3_FG.prio.txt
data/styles/vehicle/include/priorities_4_overlays.prio.txt

Depends on: https://github.com/organicmaps/kothic/pull/18
Optional captions with automatically set priorities and automatic casing lines with an auto -1 priorities are all visible in priorities files now. So now icons could be placed in-between or after them easily.
There are no actual priority changes here.

Display drules with automatic priorities as comments in priorities files

---

android/jni/CMakeLists.txt
android/jni/app/organicmaps/MapManager.cpp
android/jni/app/organicmaps/SearchRecents.cpp
android/jni/app/organicmaps/core/jni_java_methods.cpp
android/jni/app/organicmaps/core/jni_java_methods.hpp
android/jni/app/organicmaps/util/FeatureIdBuilder.hpp
android/jni/app/organicmaps/util/StringUtils.cpp
platform/country_file.cpp

Pros:
- clear code, avoid copy-paste in getting classes/methods
- function call has 1 static call/var initialization, instead of 3 or even 10+
- minimaze NewGlobalRef and global/static vars where possible
Want feedback here ..

[android] Refactoring of JNI class/method getters.

---

data/styles/clear/include/Icons.mapcss
data/styles/vehicle/include/Icons.mapcss

`icon-image: none;` for icons
`fill-color: none;` for areas
(for lines its remains `width: 0;` and `text: none;` for captions)
Kothic change: https://github.com/organicmaps/kothic/pull/19

[styles] Use a ': none;' syntax for disabling area and icon drules

---

data/categories.txt
data/strings/types_strings.txt

Some Arabic translations have special Unicode characters (e.g. ﻨ instead of the normal ن) which appear broken in the app, I manually replaced them with correct letters. Some Farsi words also have this issue but I didn't fix them because Farsi keyboard is different from Arabic.

Manually fix Arabic formatting

---

.github/workflows/android-monkey.yaml

These virtual devices are x86 VMs with broken OpenGL:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'generic/gce_x86_phone/gce_x86:5.0.2/LGR1.200331.001/6350401:userdebug/test-keys'
Revision: '0'
ABI: 'x86'
pid: 8947, tid: 9244, name: Thread-431  >>> app.organicmaps.debug <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
eax 00000000  ebx aaa2b8c8  ecx 00000019  edx 00000640
esi 00000640  edi 00000640
xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000013f  xss 0000007b
eip aa2ee380  ebp 8d90d4a8  esp 8d90d470  flags 00210202
backtrace:
#00 pc 00110380  /system/lib/egl/libGLESv2_swiftshader.so
#01 pc 00110c7d  /system/lib/egl/libGLESv2_swiftshader.so
#02 pc 000496fb  /system/lib/egl/libGLESv2_swiftshader.so
#03 pc 00041166 …
```

[android] Remove Nexus 6 and Nexus 7 from Android Monkey

---

android/flavors/gms-enabled/app/organicmaps/location/GoogleFusedLocationProvider.java
android/src/app/organicmaps/MwmActivity.java
android/src/app/organicmaps/location/AndroidNativeProvider.java
android/src/app/organicmaps/location/BaseLocationProvider.java
android/src/app/organicmaps/location/LocationHelper.java
android/src/app/organicmaps/location/LocationListener.java
android/src/app/organicmaps/location/LocationState.java
android/src/app/organicmaps/util/LocationUtils.java
docs/ANDROID_LOCATION_TEST.md

AlertDialogs are moved from LocationHelper back to parent MwmActivity. Initial idea of attaching LocationHelper to different activities failed and MwmActivity was the only one user of LocationHelper.attach().
Location permission checks are extracted from LocationHelper.start() to callers of LocationHelper.start() to avoid unnecessary inverted callbacks. LocationHelper.start() now has @RequiresPermission compile-time annotation to validate that required location permissions are checked before the call. LocationUtils.isLocationGranted() is replaced with direct calls to ActitivyCompat.checkSelfPermission() because Android Studio and Android Lint are not smart enough to detect it for @RequiresPermission check.
MwmActivity now checks for Acitivity.isDestroyed() in all callbacks from …

[android] Remove UI from LocationHelper

---

.gitmodules

freetype was forked into https://github.com/organicmaps/freetype

[3party] Fixed HTTP 504 for freetype git submodule

---

iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.xib

* Fix Open/Close sometimes showed in gray color. Closes https://github.com/organicmaps/organicmaps/issues/5832
The Color is set in dynamically in `iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm` so `styleName = regular12:blackSecondaryText` is unnecessary in `iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.xib`and was causing this conflict when rendering sometimes.

[search] Fix Open/Close sometimes showed in gray color

---

android/src/app/organicmaps/DownloadResourcesLegacyActivity.java
android/src/app/organicmaps/MwmActivity.java

This patch fixes `Activity app.organicmaps.MwmActivity has leaked window` when pausing MwmActivity during showing the following error dialogs:
- "Your location hasn't been determined yet"
- "No internet connection"
- "No object can be located here"
- "Update Maps"
- "Unable to calculate route"
- "When following the route, please keep in mind:"
- "Navigation is only available from your current location."
- Dialogs in DownloadResourcesLegacyActivity.
Fixes #5838
See also #4570 d4bf7a73 "Fix a crash on rotation"

[android] Dismiss all alert dialogs when pausing MwmActivity

---

android/src/app/organicmaps/widget/NestedScrollViewClickFixed.java

Specifically, stop an ongoing fling scrolling when tapping inside the view (or when starting another scrolling).
Steps to reproduce the problem fixed here:
- create/import some bookmark with a very long description
- click on the bookmark place on the map
- start scrolling the place description window swiftly (stop touching the display while still moving the finger)
- the scrolling continues by itself for a while - this is correct
- tap the screen - PROBLEM 1: the tap does not stop the scrolling
- OR start another scrolling - PROBLEM 2: the original scrolling is not stopped and it somehow continues alongside the new scrolling

Fix scrolling behavior in the place description window.

---

drape_frontend/base_renderer.hpp
drape_frontend/drape_engine.hpp
map/framework.cpp

When Vulkan rendering is used and e.g. `?vlight` entered in search the screen doesn't update to the new style until e.g. zoom level is changed. It doesn't happen with OGL.
This fixes it for Vulkan by forcing map style update.

[drape] Fix map style not updating automatically on Android with Vulkan

---

drape/overlay_handle.cpp
drape/overlay_handle.hpp
drape/overlay_tree.cpp
drape_frontend/apply_feature_functors.cpp
drape_frontend/apply_feature_functors.hpp
drape_frontend/colored_symbol_shape.cpp
drape_frontend/frontend_renderer.hpp
drape_frontend/path_text_shape.cpp
drape_frontend/poi_symbol_shape.cpp
drape_frontend/render_group.cpp
drape_frontend/rule_drawer.cpp
drape_frontend/rule_drawer.hpp
drape_frontend/stylist.cpp
drape_frontend/text_handle.cpp
drape_frontend/text_shape.cpp
indexer/classificator.cpp
indexer/classificator.hpp

1. Removed minVisibleScale param passing which is not used anymore (after #4645).
2. Removed overlays masks handling which is not used anymore (after 3e3d2d36a483beac319a2028fa5cbda79d672bb2).
3. Optimize determining of main overlays type by storing maxOverlaysPriority once per classificator type instead of doing it for every multi-type feature.
4. Try to re-enable some discard render bucket optimization. More on this later.
Upd: moved it from this PR to https://github.com/organicmaps/organicmaps/pull/5921

[drape] minVisibleScale-related cleanup and optimization

---

tools/unix/generate_localizations.sh

Android path was not correctly set in `generate_localizations.sh`in commit https://github.com/organicmaps/organicmaps/commit/b39a6dbb5f2278c3559036ece4c98ec3fd150a37. This PR fixes it.

[tools] Fix android path in generate_localizations.sh

---

android/app/src/main/java/app/organicmaps/routing/RoutingBottomMenuController.java
android/app/src/main/res/layout-land/altitude_chart_panel.xml
android/app/src/main/res/layout-w1020dp-land/altitude_chart_panel.xml
android/app/src/main/res/layout/altitude_chart_panel.xml
android/app/src/main/res/layout/menu_route_plan_line.xml

Closes #3320.
There are 6 dirrefent layouts:
* Pedestrian/Bycicle route Portrait
* Pedestrian/Bycicle route Landscape
* Vehicle route Portrait
* Vehicle route Landscape
* Pedestrian route Tablet
* Vehicle route Tablet
Portrait layout was implemented using simple vertical/horizontal layouts:
To switch Pedestrian-Vehicle mode we hide some elements:
Landscape layout was implemented using simple vertical/horizontal layouts:
To switch Pedestrian-Vehicle mode we hide some elements:
Instead of multiple files `routing_details.xml`, `start_button.xml`, and `altitude_chart_panel.xml` all layout is located in `altitude_chart_panel.xml`.
But we have `RoutingPlanFragment` class which uses `fragment_routing.xml` and `start_button.xml`. This `RoutingPlanFragment` is never used because we have flag …

[Android] Route info panel re-layout

---

map/routing_manager.cpp

When new point is added to ruler route no points reordering is applied.
| ----- | ----- |
| <video src="https://github.com/organicmaps/organicmaps/assets/720808/5620114f-7bb2-4e79-8e0d-671b3ab7408a"/> | <video src="https://github.com/organicmaps/organicmaps/assets/720808/ad8f6036-bb51-4b53-9fb8-c01995d266bf" /> |

Disable reordering when a point is appended to a ruler route

---

README.md

Images have disappeared from the main README.md of the repo. Here is a fix.

[docs] Fix README.md image urls

---

data/editor.config

Closes #5892
Note that FMD_WIKIPEDIA is not handled in `MWMEditorViewController`::`- (void)fillCell:(UITableViewCell * _Nonnull)cell atIndexPath:(NSIndexPath * _Nonnull)indexPath` and asserts there. 
The validation or transformation for Wiki URLs is also missing.
As a temporary workaround, Wikipedia fields can be removed from the editor.config.
Upd: looks like Wikipedia fields are enabled for a long time. So we can leave them as is.

[editor] Caves can be added

---

android/app/src/main/java/app/organicmaps/car/NavigationSession.java
android/app/src/main/java/app/organicmaps/car/screens/search/SearchOnMapScreen.java
android/app/src/main/java/app/organicmaps/car/screens/search/SearchScreen.java
android/app/src/main/java/app/organicmaps/car/util/IntentUtils.java
android/app/src/main/java/app/organicmaps/car/util/UiHelpers.java
android/app/src/main/java/app/organicmaps/intent/Factory.java
android/app/src/main/java/app/organicmaps/search/SearchEngine.java

>An [Intent](https://developer.android.com/reference/android/content/Intent.html) to navigate.
>
>The action must be [ACTION_NAVIGATE](https://developer.android.com/reference/androidx/car/app/CarContext#ACTION_NAVIGATE()).
>The data URI scheme must be either a latitude,longitude pair, or a + separated string query as follows:
>1) "geo:12.345,14.8767" for a latitude, longitude pair.
>2) "geo:0,0?q=123+Main+St,+Seattle,+WA+98101" for an address.
>3) "geo:0,0?q=a+place+name" for a place to search for.
Currently, the core functionality does not include support for queries 2 and 3. However, the logic for handling these queries has been already implemented and tested to the best extent possible.
I encountered an issue where I couldn't send an intent via ADB. Although the intent was successfully …

[android-auto] Navigation intents support

---

android/app/src/main/java/app/organicmaps/MwmActivity.java
android/app/src/main/java/app/organicmaps/routing/RoutingBottomMenuController.java
android/app/src/main/res/layout/routing_bottom_panel_transit.xml

In case of big number of ruler steps bottom panel becomes too big. See #5880 for sample
Added scrolling to the panel layout.
Result:
https://github.com/organicmaps/organicmaps/assets/720808/0ec1b719-588a-444d-a556-6bc167d3ff88
**Note:** this is temporary solution. The best approach is to draw segment length on the map itself.

[Android] Transit steps info is now scrollable.

---

android/app/src/main/java/app/organicmaps/MwmActivity.java
android/app/src/main/java/app/organicmaps/widget/menu/MainMenu.java

**Problem:** On Android zoom buttons disappear after phone is locked and unlocked.
**First change:** we don't need to adjust zoom buttons using `menuFrame.getTop()` when menu is hidden.
**Second change:** review of `public void updateMenu()` method. It shows and hides menu multiple times in its body. Changed to single action: hide menu once or show once.

[Android] Fixed zoom buttons position after Android unlock

---

map/routing_manager.cpp

Bug:
Intermediate points are numbered from 0 even if on the map we see them starting from 1.

Intermediate points fix with ruler

---

android/app/src/main/res/drawable/ic_follow.xml

by regenerating path data with https://shapeshifter.design/
Resolves #6063

[android] Fix corrupted GPS follow icon on Xperia E5

---

iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMiPhoneRoutePreview.xib
iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/TransportRoutePreviewStatus.swift

Closes #5880.
Demo:
https://github.com/organicmaps/organicmaps/assets/720808/96203ebe-9bc4-4639-9aea-11cca0c7646f
Also scrollable on iPad:
| Layout before | Layout after |
| ---- | ---- |
| <img alt="layout-before" src="https://github.com/organicmaps/organicmaps/assets/720808/0eb3205c-73c9-40f5-9685-00dc7a2d7261" width="300px"/> | <img alt="layout-after" src="https://github.com/organicmaps/organicmaps/assets/720808/afc2517e-17fa-431f-8a01-68fabdee0240" width="300px"/> |
**Question:** Is max height enough?

[ios] Transit panel scrollable

---

android/app/src/main/java/app/organicmaps/routing/NavigationService.java

RoutingController::cancel() calls MwmActivity::onNavigationCancelled() only if MwmActivity is attached to RoutingController.
Add explicit Service::stopSelf() to NavigationService to dismiss notification when route is finished.
Fixes #6084

[android] Force NavigationService to stop when a route finishes

---

drape/gl_functions.cpp
qt/qt_common/helpers.cpp
qt/qt_common/map_widget.cpp
shaders/gl_program_pool.cpp
shaders/gl_shaders_preprocessor.py

Fixes:
1. https://github.com/flathub/app.organicmaps.desktop/issues/50
2. The annoying `drape/gl_functions.cpp:1150 CheckGLError(): SrcPoint  drape/gl_functions.cpp:1126 glLineWidth():  GLError: GL_INVALID_VALUE` on the current `master` , which flooded the logs in debug mode.

[linux] Use OpenGL ES 3.0 instead of desktop OpenGL

---

generator/search_index_builder.cpp
indexer/search_string_utils.cpp
indexer/search_string_utils.hpp
search/features_layer_matcher.hpp
search/mwm_context.cpp
search/mwm_context.hpp
search/ranker.cpp
search/ranking_utils.hpp
search/reverse_geocoder.cpp
search/search_integration_tests/processor_test.cpp
search/search_quality/search_quality_tests/real_mwm_tests.cpp
search/street_vicinity_loader.cpp

Street + House Number match happens only with correctly mapped (OSM addr:street + addr:housenumber) addresses since now.
Pros:
- Speed
- Can increase kLookupRadiusM to fix some fancy cases like here https://github.com/organicmaps/organicmaps/issues/5971
- Prepare for addr:place (also only exact mapping)
Cons:
- Can't find some bad OSM-mapped addresses, but they may be ambiguous.
This approach is good since we are going to integrate other open address sources (like https://openaddresses.io/)

[search] Better streets ranking and matching.

---

drape_frontend/apply_feature_functors.cpp
drape_frontend/drape_frontend_tests/path_text_test.cpp
drape_frontend/line_shape.cpp
drape_frontend/line_shape.hpp
drape_frontend/path_text_handle.cpp
drape_frontend/path_text_handle.hpp
drape_frontend/shape_view_params.hpp
drape_frontend/user_mark_shapes.cpp
geometry/spline.cpp
geometry/spline.hpp

- One more case to optimize Spline::IsProlonging when simplify mode (z10-12). Need refactor ClipSpline routine for separate Spline and SplineEx cases.
- Make simplification in shape coordinates (LineShape::Construct) where we calculate normals and tangents?
Done: If the tile picture is good, can keep only the second commit and calculate reusable tangent/length always.
https://github.com/organicmaps/organicmaps/issues/6137
Closes https://github.com/organicmaps/organicmaps/issues/3295
Closes https://github.com/organicmaps/organicmaps/issues/1734
Closes https://github.com/organicmaps/organicmaps/issues/4702

[drape] Optimize Spline direction/length calculations.

---

drape/utils/projection.hpp
drape_frontend/apply_feature_functors.cpp
drape_frontend/apply_feature_functors.hpp
drape_frontend/rule_drawer.cpp
drape_frontend/rule_drawer.hpp
drape_frontend/stylist.cpp
drape_frontend/stylist.hpp
indexer/classificator.cpp
indexer/drawing_rule_def.cpp
indexer/drawing_rule_def.hpp
indexer/drawing_rules.cpp
indexer/drawing_rules.hpp
indexer/feature.cpp
indexer/feature_algo.cpp
map/style_tests/dashes_test.cpp
map/transit/transit_reader.cpp

Depends on housenumbers PRs, so please check the last commit only!
Simplify the structure, reduce same parameters passing and storing several times, better division of classes' responsibilities, many smaller optimizations (like don't do various pre-processing if there are no drules that will use it), get rid of TRuleWrapper...
I plan to continue refactoring the related code in subsequent PRs:
- optimize drules filtering in Stylist and get rid of Key.m_hatching
- simplify apply_feature_functors and its communication with the RuleDrawer

[drape] Refactor Stylist and RuleDrawer 

---

data/editor.config

- Removed `man_made=surveillance` ([Wiki](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurveillance)) form the editor as these features are not rendered on the map. Before you could add "invisible" features (which is asking for confusion and duplicates)
- Prevent users form adding new `tourism=alpine_hut` ([Wiki](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dalpine_hut)) and `tourism=wilderness_hut` ([Wiki](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dwilderness_hut)) locations as these places have quite strict/narrow OSM definitions that are not obvious from the name.

[editor] Removed surveillance and made alpine_hut and wilderness_hut can_add=no

---

android/app/src/main/AndroidManifest.xml

This doesn't cause any issues, just not needed.
From https://developer.android.com/guide/topics/manifest/service-element:
> Whether components of other applications can invoke the service or
> interact with it. It's "true" if they can, and "false" if not. When
> the value is "false", only components of the same application or
> applications with the same user ID can start the service or bind to it.

[android] Mark NavigationService as exported=false

---

android/app/build.gradle
android/app/proguard-mwm.txt
android/app/src/main/AndroidManifest.xml

API=21 is now supported [1], but we don't want to enable Auto on prod yet.
[1]: https://github.com/androidx/androidx/blob/8bfb531bcc16da2aeefb845c18f9748fae069e61/car/app/app/build.gradle#L81

[android-auto] Add a compile-time flag for Android Auto

---

drape_frontend/line_shape.cpp
drape_frontend/line_shape.hpp

https://github.com/organicmaps/organicmaps/issues/4971, but still not good.
Good example here: https://www.openstreetmap.org/#map=19/53.34621/-6.24165
| Before  | After |
| ------------- | ------------- |
| <img width="217" alt="Screenshot 2023-10-04 at 13 23 40" src="https://github.com/organicmaps/organicmaps/assets/175612/e3e3867d-baaa-49ea-b572-a1a993287a3f">  | <img width="266" alt="Screenshot 2023-10-04 at 13 22 51" src="https://github.com/organicmaps/organicmaps/assets/175612/10835c8d-7478-4a8f-b345-09280cd4bf41">  |

[drape] Fixed LineJoin processing.

---

android/app/src/main/java/app/organicmaps/MwmActivity.java
android/app/src/main/java/app/organicmaps/location/LocationHelper.java
android/app/src/main/java/app/organicmaps/routing/NavigationService.java

For all location modes other than NOT_FOLLOW location should be updated as soon as possible. Also, keep in mind that Android updates GPS data only once every second.
Add a comment why NavigationService cannot be STICKY. Remove LocationHelper::restart() from NavigationService::onDestroy() as asked by @vng.
Fixes #6091

[android] Improve the changing of location refresh intervals and fix NavigationService

---

android/app/src/main/java/app/organicmaps/Map.java
android/app/src/main/java/app/organicmaps/car/SurfaceRenderer.java
drape_frontend/gui/layer_render.cpp
iphone/Maps/Classes/Widgets/MWMMapWidgets.mm
qt/qt_common/map_widget.cpp

Fixed compass widget displaying after switching from AA
Adjusted FPS widget offset for AA and device
| AA | AA |
| <img width="399" alt="image" src="https://github.com/organicmaps/organicmaps/assets/10351358/a5f443d8-adb6-4795-abea-59012752f558"> | <img width="566" alt="image" src="https://github.com/organicmaps/organicmaps/assets/10351358/9bf14749-7d94-4b87-902c-cee5980f5c27"> | 
| <img width="200" alt="image" src="https://github.com/organicmaps/organicmaps/assets/10351358/737be337-c0ad-4f2e-9397-2797aa245b47"> | <img width="200" alt="image" src="https://github.com/organicmaps/organicmaps/assets/10351358/931c1029-818f-4667-88a7-a12d618b9b37"> |
| <img width="300" alt="image" …

[android-auto] Widgets fix

---

iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarInteractor.swift
iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarPresenter.swift
iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarViewController.swift
iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarViewController.xib

Fixes: https://github.com/organicmaps/organicmaps/issues/5954
Fix: remove button from tabbar and associated action that handle opening of point2point vc (which is not used anywhere else exept tabbar)

[ios] fix: remove point-to-point button from tabbar

---

indexer/scales.hpp

closes #6182
improves #5976
- This PR displays address nodes from z17 on to make the rendering of address nodes more consistent with the rendering of address areas.
Current rendering for areas displays "small" buildings at z18, "medium" at z17 and "big" ones at z16. For nodes, where the size of the coresponding building is unknown, it is now assumed that they are "medium" sized instead of "small". 
Nodes are often used for big residential buildings with several entrances, so mapping as nodes is no indicator for low importance.
| Now | Before |
| ![Screenshot_2023-10-05-17-07-44-472_app organicmaps beta](https://github.com/organicmaps/organicmaps/assets/79519062/4aef6aa4-5b2c-40ac-9ecf-686f73a61241) | ![Screenshot_2023-10-05-15-47-03-274_app …

[styles] Display address nodes from z17

---

android/app/src/main/java/app/organicmaps/intent/Factory.java

This allows the 'backurl' API argument to be used in all launch scenarios.
Tested with the following commands:
om://
adb shell am start -a android.intent.action.VIEW -d 'om://?backurl=wunderlinq://datagrid'
geo:
adb shell am start -a android.intent.action.VIEW -d 'geo:0,0?q=44.241100,-70.829180'

[Android] Fix backurl usage

---

data/strings/types_strings.txt

Added the Arabic translations for:
Grocery Store
Marina
RV Dealership      
__________________
This is a follow up on [pull/6229](https://github.com/organicmaps/organicmaps/pull/6229) when I mistakenly edited:    
iphone/Maps/LocalizedStrings/ar.lproj/Localizable.strings    
instead of: data/strings/types_strings.txt     
Thanks to [biodranik](https://github.com/biodranik) for putting me on the right direction.       
Regards.

Update types_strings.txt Added Arabic translation for 3 tags.

---

iphone/Maps/Core/Theme/Renderers/UITableViewHeaderFooterViewRenderer.swift
iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/IPlacePageLayout.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageElevationLayout.swift
iphone/Maps/UI/PlacePage/PlacePageViewController.swift

Closes https://github.com/organicmaps/organicmaps/issues/5088
Closes #3454
Problems:
1. **Unexpected grey spacing**
Bug caused by changing spacings in UISackView header in PlacePageViewController
```swift
func addHeader(_ headerViewController: UIViewController) {
addToStack(headerViewController)
// TODO: workaround. Custom spacing isn't working if visibility of any arranged subview
// changes after setting custom spacing
DispatchQueue.main.async {
self.stackView.setCustomSpacing(0, after: headerViewController.view)
}
}
```
Solving:
Change layout of header. Now place page header is array of VCs (see IPlacePageLayout protocol) in stack view with zero spacing and proper layout. And every PlacePageLayout object should build content of a header.
No runtime changing of spacings.
2. **unexpected …

[ios] Inconsistent layout in place page on iOS

---

data/faq.html

Added Ukrainian translation. Tested in browser. 
Some places in the FAQ are outdated. E.g. Button "Routes" is available only in iOS. Taxi routing is removed. Phrase "You can add up to 3 intermediate points to a route." is outdated. The same regarding "On Android, please make sure that you have granted network access for Organic Maps and system Download Manager (Download Provider)."

Added Ukrainian translation to built-in FAQ page

---

drape_frontend/apply_feature_functors.cpp
drape_frontend/apply_feature_functors.hpp
drape_frontend/line_shape.cpp
drape_frontend/rule_drawer.cpp
drape_frontend/rule_drawer.hpp
drape_frontend/shape_view_params.hpp
drape_frontend/stylist.cpp
drape_frontend/stylist.hpp
drape_frontend/visual_params.cpp
drape_frontend/visual_params.hpp
geometry/rect2d.hpp
indexer/drawing_rule_def.hpp
indexer/drawing_rules.cpp
indexer/drawing_rules.hpp
map/transit/transit_reader.cpp

Follow-up to #6034.
Optimizations:
- don't parse a road ref if there is no shield drule
- don't process a shield drule if there are no road shields in a ref
- call ClipSplineByRect() once per linear feature (not for each line drule)
- calculate areaDepth for BG-by-size areas only
...and many minor things like replace redundant checks with asserts, less params wrapping and passing, simpler structure, etc.
P.S. I'll squash and sign commits after review.

[drape] Refactor apply_feature_functors

---

android/app/src/main/cpp/app/organicmaps/bookmarks/data/BookmarkManager.cpp
android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java
android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkManager.java
map/bookmark_manager.cpp
map/bookmark_manager.hpp
map/search_api.cpp
map/search_api.hpp

Closes #5544 
It looks like this limit was originally placed for performance reasons (though I do not know why only on Android) but it is clear that this limit does not make much sense currently. Indexing and searching through 5000+ bookmarks should not crash a device given that this restriction didn't even apply to the iPhone in the first place without any problems.

[bookmarks][android] Remove max limit of searchable bookmarks

---

android/app/build.gradle

This PR fixes deprecations in build.gradle:
- compileSdkVersion was replaced by compileSdk https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/dsl/CommonExtension#compileSdkVersion(kotlin.Int)
- buildToolsVersion was replaced by buildToolsVersion = https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/dsl/CommonExtension#buildToolsVersion(kotlin.String)
- minSdkVersion was replaced minSdk, just more shorter, same for targetSdkVersion https://stackoverflow.com/questions/67250362/what-is-difference-between-compilesdk-and-compilesdkversion-in-android-studio-gr/67251145#67251145
- noCompress was replaced by noCompress = [Collection] https://developer.android.com/reference/tools/gradle-api/8.1/com/android/build/api/dsl/AndroidResources …

Fix deprecations in gradle script

---

platform/qt_location_service.cpp

I am running openSuse Tumbleweed and I have geoclue 2.7.1 installed. I was getting a crash with `'OMaps' terminated by signal SIGSEGV (Address boundary error)` and I traced it back to QGeoPositionInfoSource::createSource returning a null pointer. When starting the service it tries to access its source name, causing the crash.

[qt] Correctly handle the case when QGeoPositionInfoSource::createSource return a null pointer

---

android/app/src/main/res/layout/place_page_container_fragment.xml
android/app/src/main/res/layout/place_page_preview.xml

fixes #6215
The bottom sheet of the places page did not have round corners due to unnecessary implementations of a few drawables as backgrounds. I solved this issue.
IMAGES :

fix/[android] Smoother corners for the place page.

---

iphone/Maps/Classes/CarPlay/CarPlayRouter.swift
iphone/Maps/Classes/CarPlay/CarPlayService.swift
iphone/Maps/Classes/CarPlay/Template Builders/MapTemplateBuilder.swift

Closes https://github.com/organicmaps/organicmaps/issues/6379
Closes https://github.com/organicmaps/organicmaps/issues/2706
1. Change the background color for CarPlay instructions to green, so all maneuver icon in the light/dark theme is visible and have good contrast according to WCAG.
2. Fix the trip estimates view background (black bottom view that always starts with black style) so it now has the correct theme style and reacts to theme changing properly (by adding the `rootTemplateStyle` property that helps to update the style of the view, which by default always use .dark style).
---
Tested only in the simulator, so it needs to be tested on real CarPlay!

[ios] [carplay] fix CarPlay instructions UI colors ans style

---

android/app/build.gradle

Currently the last step of gradle build is
```shell
adb shell am start -n "app.organicmaps.debug/app.organicmaps.SplashActivity"
```
But this command fails with Android 13
```
Starting: Intent { cmp=app.organicmaps.debug/app.organicmaps.SplashActivity }
Error type 3
Error: Activity class {app.organicmaps.debug/app.organicmaps.SplashActivity} does not exist.
```
Found solution here: https://stackoverflow.com/a/29931521
App is started with `adb shell monkey -p app.organicmaps.debug -c android.intent.category.LAUNCHER 1`.
Tested with Android 13 and 11.
Replaced `adb monkey` with:
`adb shell am start -n "app.organicmaps.debug/app.organicmaps.DownloadResourcesActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER`
Verified with Android 13 and 11.

[android] Fixing application launch on Android 13.

---

android/app/src/main/java/app/organicmaps/SplashActivity.java

```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.activity.result.ActivityResultLauncher.launch(java.lang.Object)' on a null object reference
at app.organicmaps.SplashActivity.processNavigation (SplashActivity.java)
at app.organicmaps.MwmApplication.nativeProcessTask (MwmApplication.java)
at app.organicmaps.MwmApplication.lambda$forwardToMainThread$0 (MwmApplication.java)
at android.os.Handler.handleCallback (Handler.java:809)
at android.os.Handler.dispatchMessage (Handler.java:102)
at android.os.Looper.loop (Looper.java:166)
at android.app.ActivityThread.main (ActivityThread.java:7555)
at java.lang.reflect.Method.invoke
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
at …
```

[android] Fix a crash in processNavigation() called after onDestroy()

---

android/app/src/main/java/app/organicmaps/bookmarks/BookmarkCategorySettingsFragment.java
android/app/src/main/java/app/organicmaps/dialog/EditTextDialogFragment.java
android/app/src/main/java/app/organicmaps/editor/AdvancedTimetableFragment.java
android/app/src/main/java/app/organicmaps/editor/EditorFragment.java
android/app/src/main/java/app/organicmaps/editor/MultilanguageAdapter.java
android/app/src/main/java/app/organicmaps/editor/OsmLoginFragment.java
android/app/src/main/java/app/organicmaps/editor/PhoneListAdapter.java
android/app/src/main/java/app/organicmaps/editor/ReportFragment.java
android/app/src/main/java/app/organicmaps/widget/SearchToolbarController.java
android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java
android/app/src/main/res/layout/dialog_edit_text.xml
android/app/src/main/res/layout/edit_bookmark_common.xml
android/app/src/main/res/layout/fragment_bookmark_category_settings.xml
android/app/src/main/res/layout/fragment_edit_description.xml
android/app/src/main/res/layout/fragment_editor.xml
android/app/src/main/res/layout/fragment_osm_login.xml
android/app/src/main/res/layout/fragment_report.xml
android/app/src/main/res/layout/fragment_timetable_advanced.xml
android/app/src/main/res/layout/item_editor_input.xml
android/app/src/main/res/layout/item_localized_name.xml
android/app/src/main/res/layout/item_phone.xml
android/app/src/main/res/layout/toolbar_search_controls.xml

Closes #2117
This PR migrated EditText to Material TextInputEditText
I have tested:
- Login Fragment
- Edit bookmarks
- Edit list bookmarks
- Edit number phone
- Edit opening_hours
- Edit name POI
- DialogFragment to add street name in editor
- DialogFragment to add new list

[android]Migrate EditText to TextInputEditText

---

iphone/Maps/Classes/CarPlay/CarPlayService.swift
iphone/Maps/Classes/MapsAppDelegate.mm

Fix bug in PR: https://github.com/organicmaps/organicmaps/pull/6408 when light estimates view (at the bottom) appears on dark maps.
There are 3 possible states that the user can choose in CarPlay Settings:
1.  `Always dark` is Selected, `Always Show Dark Map` is `On`: Interface and maps are dark.
2. `Always dark` is Selected, `Always Show Dark Map` is `Off`: Interface is  dark, and maps+instructions can be set light/dark by CarPlay
3. `Automatic` is Selected: CarPlay set automatically Interface and maps+instructions theme styles.

[ios] [carplay] fix bug when light estimates view appears on dark maps

---

platform/qt_location_service.cpp

* Certain GUI Shells like [Phosh](https://en.wikipedia.org/wiki/Phosh) implement a `geoclue` agent in which the `desktopId` of the application, that requested positioning is checked against the desktop file of the same application for authorization purposes. See the [location manager of Phosh]( https://gitlab.gnome.org/World/Phosh/phosh/-/blob/main/src/location-manager.c?ref_type=heads#L239)
* Needed for https://github.com/flathub/app.organicmaps.desktop/issues/61

[qt][platform]: Synchronize geoclue desktopId with desktop file name

---

data/editor.config

Reference issue: https://github.com/organicmaps/organicmaps/issues/6453
Temporarily remove unsupported types `elevation` and `wikipedia` from `data/editor.config`
So unsupported data will not break the layout of the Details section.
Supporting these types will be implemented in the future.
Before:
After:

[ios] fix broken details cells on Editing place screen

---

android/app/src/main/java/app/organicmaps/MwmApplication.java

People don't buy the idea that Organic Maps disables location when goes into the background. Tickets are constantly filed, and I have become tired of explaining that this is a feature rather than a bug.
What happens typically:
1. The user launches Organic Maps.
3. Organic Maps subscribes to GPS updates.
4. The Android system tries to do the cold start of GPS if there were no other GPS-enabled apps before.
5. In certain cases, GPS takes too long to warm up and location doesn't arrive even after 10-20 seconds or even a minute.
6. The user gets tired and switches to other apps to do something productive.
7. Organic Maps disconnects from location services in the background.
8. The Android system deactivates GPS if there are no other apps using it (this is the most important part of the …

[android] Keep location in the background in PENDING_LOCATION mode

---

docs/ANDROID_LOCATION_TEST.md
drape_frontend/my_position_controller.cpp

Keep PendingLocation mode when the user touch or drag the map.
Please see a new test case added to docs/ANDROID_LOCATION_TEST.md. iPhone hasn't been tested—please validate also.

[drape] Don't change location icon when the map is dragged

---

iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarInteractor.swift
iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarPresenter.swift
iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarViewController.swift
iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarViewController.xib
iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.m
iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.xib

Closes https://github.com/organicmaps/organicmaps/issues/6256
The point-to-point button was removed, so it needs to educate users to build routes.
In this PR as mentioned in https://github.com/organicmaps/organicmaps/issues/6256 was added:
1. tint for RouteTo tab when the user tap on some location
2. red badge to the "?" (help) tab that routes the user to the FAQ screen
Both hints **appear once** only for:
- the first app launch after installation 
or 
- the first launch after the app is updated from the previous version to the current

[ios] Hint for RouteTo button to make routes without Point2Point tab

---

data/strings/strings.txt

Some translations used letters that don't exist in the Romanian alphabet, replaced them with the correct ones. Some places used the definite article form of nouns, where it was not needed.

Fix some typos in ro translation

---

android/app/src/main/res/layout/fragment_bookmark_category_settings.xml

Closes #6468
I have re-used style using in [fragment_edit_bookmark](https://github.com/organicmaps/organicmaps/blob/master/android/app/src/main/res/layout/fragment_edit_bookmark.xml)
||Before|After|
|-|-|-|
|Hint|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/722d63bc-839d-420b-b893-a09ec2d77bfe" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/e3251769-a426-447a-81f5-a2eed6087f86" height=300 />
|Filled|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/256bf860-5789-433b-bd26-7df95301f8a7" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/99ced0cf-812b-4f9f-8d66-fafe5455ebfa" height=300 />|

[android] Fix text color in dark mode in bookmark category settings

---

data/categories.txt
data/strings/types_strings.txt

Closes #6423
A simple attempt to fix the aforementioned problem. It is the same solution as used in Portuguese. Does not change the way things are searched (Bank category, for example), but solves the 2 raised points in the first comment.

[strings] Fix Spanish 'bench' translation

---

data/strings/strings.txt

The Arabic language was wrong, as the script places the letters from left to right, while the Arabic language is written and read from right to left. And any Arabic reader will not understand it as it look like gibberish. I corrected the Arabic and made it right to left, and the name of the OpenStreetMaps was written in English instead of Arabic, which may have been the reason for reversing the entire Arabic text to start from the left.

Fix the Arabic language in a string in strings.txt

---

android/app/src/main/res/values/themes.xml

This PR updates parent themes using by AlertDialog themes, following this guide https://material.io/blog/migrate-android-material-components
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/0938723b-66d2-414d-b4f7-da8811b9a77c" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/552294e1-2d7a-40b4-bebe-bad5086c23c6" height=300 />
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/059c06f3-a832-4f7f-a80c-05cacfbfbf1b" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/ea988a4f-938a-4910-acb7-dbf0a68b8e8c" height=300 />|
Tested on
- Pixel 6 - Android 14
- Samsung Galaxy Tab S6 Lite - Android 13
- Honor 8 - Android 8
- Lenovo Yoga Tab 2 - Android 5
I have see that …

[android] Migrate Alert Dialog themes to Material Theming

---

android/app/src/main/res/values/styles.xml

This PR updates parent themes using by Top bar themes, following this guide https://material.io/blog/migrate-android-material-components.
No difference on UI
Tested on
- Pixel 6 - Android 14
- Samsung Galaxy Tab S6 Lite - Android 13
- Honor 8 - Android 8
- Lenovo Yoga Tab 2 - Android 5

[android] Migrate top bar themes to MaterialComponents

---

tools/unix/generate_localizations.sh

On Ubuntu via WSL the current code complains that `.` is not a command. Presumably sed doesn't like whitespace between `-i` and `.bak` and interprets `.bak` as a sed command instead of an argument to `-i`.
Some websites suggest `sed -i".bak"` as proper syntax, @biodranik suggests that `sed -i.bak` is more portable cross-platform. Either way proper syntax will allow no errors and proper generation of the supportedLocalizations line in the gradle.properties file.

Fix sed syntax error

---

android/app/src/main/java/app/organicmaps/bookmarks/BookmarkCategoriesFragment.java
android/app/src/main/java/app/organicmaps/bookmarks/BookmarksSharingHelper.java
android/app/src/main/java/app/organicmaps/settings/StoragePathFragment.java
android/app/src/main/res/values/themes.xml

Fixes #6469
I have created a new style because add textColor property on the main alertDialog style applies color also on buttons text.
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/051c3389-5fb5-455c-9099-31abbefbd298" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/e7a29d59-dc4c-4d4d-ad77-b8e712ab01ea" height=300 />|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/b927d747-5e10-4b62-bc7c-80ef27776fb1" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/b96489fb-5023-4049-9df4-3c26e2844a9f" height=300 />|
Tested on
- Pixel 6 - Android 14
- Samsung Galaxy Tab S6 Lite - Android 13
- Honor 8 - Android 8
- Lenovo Yoga Tab 2 - Android 5

[android] Fix text color on ProgressDialog

---

android/app/build.gradle
android/build.gradle
android/gradle.properties

The project automatically uses a default version of the build tools that Gradle plugin specifies.

[android] Remove buildToolsVersion

---

android/app/src/main/res/layout/routing_plan.xml
android/app/src/main/res/layout/toolbar_with_search.xml
android/app/src/main/res/layout/toolbar_with_search_no_elevation.xml
android/app/src/main/res/values/styles.xml

This PR remove useless properties of Toolbar themes:
- Is not necessary to specify `android:elevation=4dp` in themes because the default value in material theme is 4dp.
- `contentInsetStart` property has no effect on elements in the toolbar (this property specifies where elements start in the toolbar), I have kept 0dp value for all layouts because somes layouts already 0dp value.
- `android:contentInsetStart` property has no effect (During tests on device and Android Studio Preview)
Tested on Pixel 6 - Android 14 and Honor 8 - Android 8 in Light and Dark mode and in RTL

[android] Clean ToolbarStyle themes

---

android/app/proguard-rules.pro

The source line numbers in the log messages are transformed by R8 in the complex way, that requires `mapping.txt` to recover the real number. Disable R8 optimizations for now until we figure out how to maintain the history of `mapping.txt` for all releases.
Closes #6559

[android] Disable R8 optimizations

---

iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarInteractor.swift
iphone/Maps/UI/Help/AboutController.swift

Fix to https://github.com/organicmaps/organicmaps/pull/6446
In this PR when the red badge on the first ("?") tab is active About screen will be opened first, and then FAQ.

[ios] Fix: show FAQ sceen after About when educational hint is enabled

---

drape_frontend/debug_rect_renderer.cpp

#5914 made lines thicker in `?debug-rect` mode used for debugging of overlays displacement on linux desktop (it didn't reproduce on android device neither with GL, nor with Vulkan renderer).
The lines are supposed to be 1px wide here:
Looks like width for these lines was never set explicitly, so some OGL defaults were used or rather line widths set by some other lines drawing functions (and actually ?debug-rect lines were thin still on lower zooms <z12).
This fix sets line width explicitly and also reduces arrows' sizes a bit:

[drape] Fix OGL ES ?debug-rect line widths

---

android/app/src/main/java/app/organicmaps/editor/EditorFragment.java
android/app/src/main/java/app/organicmaps/editor/OsmLoginFragment.java
android/app/src/main/java/app/organicmaps/editor/ProfileFragment.java
android/app/src/main/java/app/organicmaps/help/HelpFragment.java

This PR:
- Update string used in pop-up to disconnect OSM account (replace OK by yes because we ask a question)
- Remove methods to start web Intent and use directly Utils.openUrl (That reduces the number of code lines and better management of catch because some methods use directly start activity without try catch)
Tested in Pixel 6 - Android 14

[android] Remove useless methods to start Web Intent and use Utils

---

android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java
android/app/src/main/res/layout/fragment_edit_bookmark.xml
android/app/src/main/res/layout/fragment_edit_description.xml
android/app/src/main/res/layout/position_chooser.xml

This PR replaces TextView in the toolbar by ImageView with the done icon.
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/34c36226-5e85-47a5-b6e2-9eac69e7af22" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/540288bd-0b97-41d3-ab41-93029937faaa" height=300 />|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/99e0a1c6-2250-424a-8703-70af75b18a77" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/c63f5330-29aa-4b8c-a8ac-df523a86f051" height=300 />
Tested on Pixel 6 - Android 14 in Light and Dark mode

[android] Migrate TextView button in toolbar to Image View

---

android/app/src/main/cpp/app/organicmaps/LocationState.cpp
android/app/src/main/java/app/organicmaps/MwmActivity.java
android/app/src/main/java/app/organicmaps/MwmApplication.java
android/app/src/main/java/app/organicmaps/car/CarAppSession.java
android/app/src/main/java/app/organicmaps/car/util/UiHelpers.java
android/app/src/main/java/app/organicmaps/location/LocationHelper.java
android/app/src/main/java/app/organicmaps/location/LocationState.java
android/app/src/main/java/app/organicmaps/routing/NavigationService.java
android/app/src/main/java/app/organicmaps/widget/menu/MyPositionButton.java

[android] Make Drape the source of truth for the location mode changes
Drape changes the location mode under the hood in multiple cases, which
creates the discrepancy between Android <-> Drape state. Trust Drape
and do all location mode transitions only via onMyPositionModeChanged().
Follow up #1128 #4376 #6098 #6465 #6466

[android] Make Drape the source of truth for the location mode changes

---

coding/coding_tests/url_tests.cpp
coding/url.cpp
map/map_tests/mwm_url_tests.cpp

`123+Main+St,+Seattle,+WA+98101` is equvivalent to `123%20Main%20St,%20Seattle,%20WA+98101` and should be decoded as `123 Main St, Seattle, WA 98101`.

[coding] UrlDecode the plus sign '+' as a space

---

android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageUtils.java
android/app/src/main/java/app/organicmaps/widget/placepage/sections/PlacePageBookmarkFragment.java
android/app/src/main/java/app/organicmaps/widget/placepage/sections/PlacePhoneAdapter.java

Android 13 introduces a pop-up to confirm, that text was copied to the clipboard -> more information [here](https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#Feedback)
This PR generates snackbar only on devices with Android 12 and lower

[android] Don't show snackbar on Android 13 after copy

---

3party/utf8cpp/include/utf8cpp
base/internal/message.cpp
base/string_utils.hpp
cmake/OmimConfig.cmake
coding/coding_tests/string_utf8_multilang_tests.cpp
indexer/search_string_utils.cpp
shaders/CMakeLists.txt
xcode/common.xcconfig
xcode/cppjansson/cppjansson.xcodeproj/project.pbxproj

* For compiler diagnostics
* For dependency management
* Extra symlink directory 3party/utf8cpp/include/utf8cpp/ added for xcode iPhone builds to have the same directory structure, (utf8cpp/utf8/unchecked.h) which would be created by CMake. See: https://github.com/nemtrif/utfcpp/blob /925e7147ece348a170f4fea3a7f94ee72b433030/CMakeLists.txt And: https://github.com/nemtrif/utfcpp/issues/54

[3party] Treat utfcpp as a system header

---

android/app/src/main/java/app/organicmaps/downloader/CountrySuggestFragment.java
android/app/src/main/java/app/organicmaps/downloader/OnmapDownloader.java
android/app/src/main/java/app/organicmaps/util/StringUtils.java

On Android, make use of system locale decimal separator for the formatting of strings of map size and strings of map download progress.

[android] Use system locale for map size and download progress strings

---

map/framework.cpp
map/framework.hpp
map/mwm_url.cpp

Re-add lost trackVisibleViewport=true from the original implementation.
Original code:
https://github.com/organicmaps/organicmaps/blob/3fc5d227ff7131a993c8fafc09b8fe3249d9a6ab/map/framework.cpp#L1811-L1812

[map] Fix the viewport when opening a geo: link

---

qt/res/OrganicMaps.desktop

So on mobile Linux UIs like Phosh and Plasma,
the Organic Maps icon shows up immediately,
without the need for the user to tap on "Show All Apps".

[linux] Indicate compatibility with mobile form factor

---

ge0/parser.hpp

Fixes the following compiler error & note:
```
parser.hpp:10:13: error: 'array' in namespace 'std' does not name a template type
parser.hpp:6:1: note: 'std::array' is defined in header '<array>'; did you forget to '#include <array>'?
```

[ge0] Fix compilation on gcc 11 when unity build is off

---

android/app/build.gradle

Almost all the new Java 12-17 **language** features can be used now:
- Text Blocks
https://docs.oracle.com/en/java/javase/15/text-blocks/index.html
- Pattern Matching for switch Expressions and Statements
https://docs.oracle.com/en/java/javase/17/language/pattern-matching-switch-expressions-and-statements.html
- Pattern Matching for instanceof
https://docs.oracle.com/en/java/javase/16/language/pattern-matching-instanceof-operator.html
- Sealed Classes
https://docs.oracle.com/en/java/javase/17/language/sealed-classes-and-interfaces.html
- Record Classes
https://docs.oracle.com/en/java/javase/16/language/records.html
This feature requires `java.lang.Record` class which is not available on old devices, but R8/D8 compiler in Android does so-called 'desugaring'. …

[android] Enable Java 17 language features

---

iphone/Maps/UI/PlacePage/Components/PlacePageHeader/PlacePageHeaderViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard

Closes https://github.com/organicmaps/organicmaps/issues/6702
Remove the grabber from the PlacePage view on the iPad in two steps:
1. make the grabber hidden 
2. set the spacing constraint between the title and the grabber to zero (in the storyboard for specific traits)

[ios] Remove the grabber for the PlacePage view on iPad

---

iphone/Maps/Core/Theme/GlobalStyleSheet.swift

Closes https://github.com/organicmaps/organicmaps/issues/6703
This PR implements a background color for the `"Backgroung" styleName` from the custom style managing system.
This change will affect all elements that have selected state and the `"Backgroung" styleName`.
Another approach is to create a new style for the current cell class, but it causes different selected styles for different cells and affects the consistence of an app UI.

[ios] Fix background color for search cells selected state

---

android/app/src/beta/AndroidManifest.xml
android/app/src/debug/AndroidManifest.xml

GWP-ASan is a native memory allocator feature that helps find use-after-free and heap-buffer-overflow bugs. Its informal name is a recursive acronym, "GWP-ASan Will Provide Allocation SANity". Unlike HWASan or Malloc Debug, GWP-ASan does not require source or recompilation (that is, works with prebuilts), and works on both 32- and 64-bit processes (although 32-bit crashes have less debugging information).
Closes #6633

[android] Enable Address Sanitizer (ASAN) for debug and beta

---

iphone/Maps/Core/Search/MWMSearch.mm
iphone/Maps/UI/Search/MWMSearchView.xib

Closes https://github.com/organicmaps/organicmaps/issues/6618
When the user types in the search textfield the searching process starts on every new char, but ends a few times later.
But the button should be visible due the whole searching process (except not found or empty field).
This PR fixes that problem.
Bug was in this method in MWMSearch:
```swift
- (void)setSearchCount:(NSInteger)searchCount {
NSAssert((searchCount >= 0) && ((_searchCount == searchCount - 1) || (_searchCount == searchCount + 1)),
@"Invalid search count update");
if (_searchCount == 0) // <--- CAUSE BUG
[self onSearchStarted];
else if (searchCount == 0)
[self onSearchCompleted];
_searchCount = searchCount;
}
```
`_searchCount` stores previous search count and can be greater or equal than 0 (because searching …

[ios] Fix "View on map" button visibility on search screen

---

iphone/Maps/Classes/CustomAlert/Toast/Toast.swift
iphone/Maps/UI/PlacePage/PlacePageViewController.swift

Fix PR https://github.com/organicmaps/organicmaps/pull/6200
The app freezes on iOS 14 when the user taps someplace (probably the main thread became deadlocked when scrollView.contentInsets initial values are set to new value and viewDidLayoutSubviews leaves scope).
This PR fixes this issue but it needs some additional test!
App tested and works well now on simulators iOS 14.4, 15.5, 16.4, 17.0.1:

[ios] Fix the app freezing when the PlacePage screen is opening on iOS 14

---

android/app/src/main/java/app/organicmaps/bookmarks/data/Metadata.java
android/app/src/main/java/app/organicmaps/widget/placepage/sections/PlacePageLinksFragment.java
data/editor.config
iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift

Let's make OM a bit more beautiful.
|Before | After|
|---|---|
|<img width="272" alt="выява" src="https://github.com/organicmaps/organicmaps/assets/170263/3f3a1c50-39b0-4d12-b364-8972dac6e0b5">|<img width="272" alt="выява" src="https://github.com/organicmaps/organicmaps/assets/170263/220ffb57-9f03-48e8-b264-bf83ad6f04c4">|

Display website in Place Page without http(s):// prefixes and trailing slashes

---

iphone/Maps/Classes/MapViewController.h
iphone/Maps/UI/Search/MWMSearchManager+Layout.m
iphone/Maps/UI/Search/MWMSearchManager.h
iphone/Maps/UI/Search/MWMSearchManager.mm
iphone/Maps/UI/Storyboard/Main.storyboard

When the Search screen is opened on the iPad and the user taps on some place PlacePage covers the search.
1. Pin the PlacePage screen to the trailing border so it always appears on the right side (also it needs to change the disappearing animation)
2. Pin the Search screen to the trailing border (see 1st commit)

[ios] fix the Search screen layout on iPad

---

iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.m

When the user taps on the PP TabButton the only inner button reacts on tap (see the blue rect). And if the tap hits the text label interaction fails.
This PR increases the "tap zone" and includes both the button and the label.

[ios] Increase PlacePage TabButton tap interaction area

---

3party/CMakeLists.txt
CMakeLists.txt

Follow up of PR #6801.
Enables the usage of external gflags library.

CMake: enable usage of external gflags

---

android/app/src/main/res/layout/activity_splash.xml
android/app/src/main/res/layout/elevation_profile_internal.xml
android/app/src/main/res/layout/fragment_bookmark_category_settings.xml
android/app/src/main/res/layout/routing_action_panel.xml

This PR updates app layouts to improve performance following Android Studio guidelines/warnings.
- `android:layout_height="0dp"` = When only a single widget in a LinearLayout defines a weight, it is more efficient to assign a width/height of 0dp to it since it will absorb all the remaining space anyway. With a declared width/height of 0dp it does not have to measure its own size first.
- `android:baselineAligned` = When a LinearLayout is used to distribute the space proportionally between nested layouts, the baseline alignment property should be turned off to make the layout computation faster.
Explanations are from Android Studio
- In fragment_bookmark_category_settings, I have removed `LinearLayout` because this item was used before when layout contained an independent button to clear …

[android] Improve layout performance

---

android/app/src/main/java/app/organicmaps/bookmarks/data/MapObject.java
android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
android/app/src/main/res/drawable/ic_atm_white.xml
android/app/src/main/res/layout/place_page_atm.xml
android/app/src/main/res/layout/place_page_details.xml
android/app/src/main/res/values-ca/strings.xml
android/app/src/main/res/values-es/strings.xml
android/app/src/main/res/values-et/strings.xml
android/app/src/main/res/values-eu/strings.xml
android/app/src/main/res/values-fi/strings.xml
android/app/src/main/res/values-fr/strings.xml
android/app/src/main/res/values-nl/strings.xml
data/strings/strings.txt
indexer/feature_utils.cpp
indexer/feature_utils.hpp
indexer/map_object.cpp
indexer/map_object.hpp
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.h
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm
iphone/Maps/Images.xcassets/Place Page/ic_placepage_atm.imageset/Contents.json
iphone/Maps/Images.xcassets/Place Page/ic_placepage_atm.imageset/ic_atm_white.svg
iphone/Maps/LocalizedStrings/ca.lproj/Localizable.strings
iphone/Maps/LocalizedStrings/es.lproj/Localizable.strings
iphone/Maps/LocalizedStrings/et.lproj/Localizable.strings
iphone/Maps/LocalizedStrings/eu.lproj/Localizable.strings
iphone/Maps/LocalizedStrings/fi.lproj/Localizable.strings
iphone/Maps/LocalizedStrings/fr.lproj/Localizable.strings
iphone/Maps/LocalizedStrings/nl.lproj/Localizable.strings
iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
map/place_page_info.cpp

* This PR adds ATM description to the Place Page subtitle of features that have an `atm=yes` tagging. Closes https://github.com/organicmaps/organicmaps/issues/3209
This PR is similar to https://github.com/organicmaps/organicmaps/pull/5883 but in this case we are using the already existing ATM type, not new metadata properties.

[core] Add ATM to Place Page

---

android/app/src/main/java/app/organicmaps/DownloadResourcesLegacyActivity.java
android/app/src/main/res/layout/button_with_progress.xml

This PR migrate appcompat progressbar to Material LinearProgressIndicator.
I have also tried to migrate the circular progress bar to CircularProgressIndicator but he has an issue [#2116](https://github.com/material-components/material-components-android/issues/2116)
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/5be9b5a0-207f-43a3-989f-3e1f2ac73b25" height=100 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/09ce7977-fe2a-40b4-bd11-50236240038a" height=100 />|
I have added a new property to keep the same indicate color (default property uses colorPrimary app)
The margin under Progress Indicator has been reduced and Track color is in default in blue.
More information here -> …

[android] Migrate to Material LinearProgressIndicator

---

map/map_tests/bookmarks_test.cpp

Without this commit, it just compiles with Clang.
Closes #6802.

[map] Fix compilation with GCC for bookmarks_test.

---

drape_frontend/apply_feature_functors.cpp
drape_frontend/apply_feature_functors.hpp
drape_frontend/user_mark_shapes.cpp
geometry/clipping.cpp
geometry/geometry_tests/clipping_test.cpp
geometry/geometry_tests/spline_test.cpp
geometry/spline.cpp
geometry/spline.hpp

This reverts commit 38b1053dc4d86533a90a24d47bc270f4704fb0a9.
The logic with
```
point.SquaredLength(m_lastAddedPoint) < m_minSegmentSqrLength
...
point.SquaredLength(lastAddedPoint) < minSqrLength
```
is broken and the tracks are drawing badly now.

Revert "[drape] Added Spline::AddOrProlongPoint."

---

android/app/src/main/java/app/organicmaps/Map.java

Closes https://github.com/organicmaps/organicmaps/issues/6695

[android] Do not call Framework::UpdateVisualScale after initial surface creation.

---

android/app/src/main/java/app/organicmaps/sound/TtsPlayer.java

TextToSpeech.OnInitListener() is called from a binder thread on LineageOS '20.0-20231127-RELEASE-thyme' 'Xiaomi/thyme/thyme'.
Closes #6900
Closes #6903

[android] Fix TTS initialization on LineageOS

---

android/app/src/main/java/app/organicmaps/MwmActivity.java
android/app/src/main/java/app/organicmaps/settings/SettingsPrefsFragment.java
android/app/src/main/java/app/organicmaps/util/Utils.java

Closes #6669
Also fixes some bugs introduced in #6053 
1. have the setting ON, location current and map centered  - the screen will stay on
- switch to some other app
- switch back to OM, the screen will go to sleep after some time (in case there was no location mode change)
2. start navigation - the screen will stay on
- go to settings, switch the setting to OFF
- go back to the navigation, the screen will go to sleep after some time (in case there was no location mode change)

[android] Respect the 'Keep the screen on' setting regardless of the current location mode + fixes

---

iphone/Maps/UI/PlacePage/PlacePageViewController.swift

This PR fixes https://github.com/organicmaps/organicmaps/issues/6917
For some reason https://github.com/organicmaps/organicmaps/commit/92c7b90c596f7c8702fdff2ab81a5b1e0b0d9457
breaks PP screen on iOS12 so for iOS<13.0 the implementation code will be used.
Needs to be tested on iOS12!

Fix the PP screen freezing on ios 12

---

android/app/src/main/res/values/strings-tts.xml

https://github.com/organicmaps/organicmaps/assets/55664068/002361d3-8490-404c-b1cc-477e37630f07
Please turn on the volume to listen to the voices in different languages.

[Android] Fix Spanish and Portugal TTS       #100thPR🥳🥳🥳

---

map/bookmark_helpers.cpp

**Overview:**
This pull request fixes #6665, where an incorrect bookmark icon (Entertainment) was displayed instead of the appropriate one (Park) for 'leisure-playground.'
**Changes Made:**
- Updated the code in `map/bookmark_helpers.cpp` to use the correct bookmark icon for 'leisure-playground.'
- Replaced the previous icon assignment (Entertainment) with the appropriate one (Park).
**Testing:**
- Tested the updated code to ensure that the correct icon (Park) is now displayed for 'leisure-playground.'
- Verified that other bookmark icons and functionalities remain unaffected.
**Dependencies:**
No dependencies on other pull requests.

Fix bookmark icon for playground

---

data/strings/sound.txt

The previous translation was not exactly wrong, but unnatural. This commit makes the navigation sound more like a fluent speaker.

Update Polish translation in sound.txt

---

android/app/src/main/res/layout/activity_download_resources.xml

From maps.me has been forked, custom illustrations have been removed from different layout.
This PR adds icon like illustration on the download layout.
|Nexus 5 - Portrait|Pixel 7 - Landscape|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/46d433fd-b00b-4727-8cf1-68c430e84039" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/1a9d9d25-f6b3-4f3c-a0e4-3d5d10a5923a" height=200 />|
I have set a fixed size, I know it's not the best option, but I'm not sure is necessary to use a custom size following the size of devices.

[android] Add icon on dowload layout

---

android/app/src/main/res/values-sw600dp/dimens.xml

Fixes #6409
`margin_direction_big` property is used on layer bottom sheet layout and fragment direction layout like the value of `layout_marginTop` property.
Now on all form factors margin_direction_big has 20dp like value.
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/d3c46f12-6faa-4256-bb8e-9920f7f974ea" height=150 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/6e7c8e87-d2a1-4add-a215-d80f63bb96d9" height=150 />|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/bdf69cc9-1951-4442-8b39-bbabe2a7c26b" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/20069ee7-6c57-4f28-8e51-c763f7ea8641" height=300 />|
|<img src="https://github.com/organicmaps/organicmaps/assets/871486 …

[android] Improve layer bottomsheet on tablet

---

iphone/Maps/UI/Editor/MWMEditorViewController.mm

Closes https://github.com/organicmaps/organicmaps/issues/6760
This PR adds the Notes section to the 'Add place to OSM' screen (not only for the Edit screen).
The notes will be sent to the OSM.

[ios] Add the Notes section to the 'Add place to OSM' screen

---

android/app/src/main/cpp/app/organicmaps/SearchEngine.cpp
android/app/src/main/java/app/organicmaps/car/screens/search/SearchOnMapScreen.java
android/app/src/main/java/app/organicmaps/car/screens/search/SearchScreen.java
android/app/src/main/java/app/organicmaps/search/SearchAdapter.java
android/app/src/main/java/app/organicmaps/search/SearchResult.java
indexer/map_object.cpp
indexer/map_object.hpp
iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
iphone/Maps/UI/Search/TableView/MWMSearchTableViewController.mm
map/framework.cpp
map/place_page_info.cpp
map/place_page_info.hpp
map/search_mark.cpp
map/search_mark.hpp
search/intermediate_result.cpp
search/result.cpp
search/result.hpp

When I was working on PR https://github.com/organicmaps/organicmaps/pull/5883 I noticed that there was some duplicate code for generating the description details in the search results. There was basically the same code in Objective-C++ for iOS and in Java for Android. So I had to make the changes in two separate places, one for each platform.
In this PR I have moved all the description details generation code to the C++ core to make it simpler. This will make it easier for future PRs as changes will have to be done only in one place. 
Search results user-facing behavior should be the same as before, no changes there.

Search results description refactor to move code to c++ core

---

coding/writer.hpp

Follow up #6961
```if (freeSize <= 0)``` is not a good strategy because it calls resize every time regular Write is called.
CC @Osyotr

[coding] Simplify MemWriter::Write.

---

map/place_page_info.cpp

In https://github.com/organicmaps/organicmaps/pull/6842 I inadvertently added an unneeded extra `kFieldsSeparator` in the elevation info in the Place Page description.  My mistake. This PR fixes it, going back to the previous behavior by removing the extra `" • "`.
Before #6842:
--
After #6842:

[placepage] Remove extra kFieldsSeparator in elevation

---

android/app/src/main/res/layout/place_page_preview.xml
android/app/src/main/res/values/dimens.xml
android/app/src/main/res/values/font_sizes.xml

This PR:
- Increase the size of the roundabout exit number (As requested by user in Telegram)
- Reduce the size place page button (Roman has seen the height of the place page increase after this PR #6776)
|Before|After|Max size font|
|-|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/a54dff5a-2d06-457d-b8a3-acc64a220af6" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/b58107f9-7993-46b5-b799-8c4c7579321c" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/7888e39c-d172-48ba-9139-1b92956d4892" height=300 />|
|Before 6776|January release|After|
|-|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/1d5a154f-2bd5-495f-aab3-214690db978e" height=300 />|<img …

[android] Update dimensions to improve roundabout exit number and place page

---

generator/osm2meta.cpp
indexer/ftypes_matcher.cpp
indexer/ftypes_matcher.hpp

This PR adds the operator tag to parkings. This can be specially useful for paid parkings where you may want to know which parking app you are gonna have to use to pay before getting there.

Add operator to parkings

---

android/app/src/main/res/values/strings-tts.xml

This PR fixes [Issue 7154](https://github.com/organicmaps/organicmaps/issues/7154), using the correct language code for plain Spanish & Portuguese language codes for the selection of TTS texts for driving instructions.
This change has been tested on the Android Studio emulator and on an actual Android device running Android 9.

[android] Fix Spanish and Portuguese TTS text selection

---

android/app/src/main/res/values-uk/strings.xml
data/strings/strings.txt
iphone/Maps/LocalizedStrings/uk.lproj/Localizable.strings

Replaced "Додовання" with "Додавання":

[strings] Small fix in Ukrainian translation

---

android/app/build.gradle

This PR removes lint rule about unused resources.
I have checked with Android Studio we don't have unused resources and Lint doesn't generate errors or warnings about this.

[android] Remove lint rule about unused resources

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

I see some OM users create issues to report bugs or ask new features, without checking if the repository have already similar issues.
And manage issues take a lot of time and sometimes it's harder to find similar or duplicates issues
This PR adds the new text in templates, to tell to users to search issues before creating (I hope users read the text template).

Add new text in issue templates to reduce duplicate

---

android/app/src/main/res/drawable/ic_atm_white.xml
android/app/src/main/res/drawable/ic_capacity_white.xml
android/app/src/main/res/drawable/ic_storage_permission.xml
android/app/src/main/res/layout-land/fragment_direction.xml
android/app/src/main/res/layout/fragment_prefs_faq.xml
android/app/src/main/res/layout/indeterminated_progress_dialog.xml
android/app/src/main/res/layout/item_search_recent.xml
android/app/src/main/res/layout/menu_route_plan_line.xml
android/app/src/main/res/layout/place_page_fat_shadow.xml
android/app/src/main/res/layout/place_page_rating_records.xml
android/app/src/main/res/layout/placeholder_image.xml

This PR cleans resources by using warnings given by Android Studio.
Changes in resources:
- Removes unused declaration namespaces
- Removes unnecessary FrameLayout -> these changes have a good impact on performance
- Removes/updates tools properties that use removed resources
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/f1a2ad35-76db-40d1-91f9-4d8ac77f3ac4" height=150 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/43b0d73c-546a-4175-bd5c-99dcd0ad8a71" height=150 />|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/16cb4b82-cf78-48da-9eb8-5f4fa06a7dab" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/8d3cb468-6713-46bd-ae8c-e0d9175de18e" height=300 />|
|<img …

[android] Clean layouts and drawables

---

docs/INSTALL.md

It is still possible to run Organic Maps in the iOS simulator, but if you want to run the app on a real device you need to be part of the development team to get access to the bundle identifier. I've tried with a diffrent identifier but the the app won't compile because the CarPlay entitlement is missing.
I've updated INSTALL.md to clarify that because it cost me a couple of hours to figure that out.

[ios] Add instructions to run Organic Maps on a real device

---

android/app/src/main/java/app/organicmaps/bookmarks/BookmarkCategorySettingsFragment.java
android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java
android/app/src/main/res/layout/edit_bookmark_common.xml

This PR following changes here #6549:
- Add a new end icon in TextInput in edit bookmark fragment with logic to clear the field and give focus
- Add a new listener to hide/see clear button if length is up 0 in two fragment uses clear button

[android] Implement new logic to hide clear button in bookmark edit fragments

---

android/app/src/main/res/layout/item_timetable_closed_hours.xml

On the latest version, in editor button to remove closed hours is not visible in light mode.
I have added `iconTint`property to be sure the icon has the right color in light and dark mode.
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/68edf8f7-7aa7-49dd-a871-62c30b92be0b" height=350 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/8de44d58-ee59-41e5-a8b6-03740d4b1441" height=350 />|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/d8c5f98f-6a52-44d8-bd86-aed41c6f0d55" height=350 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/d470dd09-2ec1-484f-9236-64fedef6c039" height=350 />|
Tested on Pixel 6 - Android 14

[android] Fix button to remove closed hours
