- android/jni/app/organicmaps/Framework.cpp
- map/bookmark_helpers.cpp
- map/bookmark_helpers.hpp
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/map_tests/bookmarks_test.cpp
- platform/platform.cpp
- platform/platform.hpp
https://github.com/organicmaps/organicmaps/pull/5166/files#r1194353821
> [gpx] Use string_view for bookmark file extensions

- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarkGroup.h
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarkGroup.m
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListInfoViewController.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListInfoViewController.xib
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListInterfaces.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListPresenter.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListRouter.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListViewController.swift
> [ios] Fixed bookmark list descriptions

- data/gpx_test_data/color.gpx
- kml/kml_tests/gpx_tests.cpp
- kml/serdes_gpx.cpp
- kml/serdes_gpx.hpp
> [gpx] Support Garmin color schema

- android/AndroidManifest.xml
Adjust resize on FeatureCategoryActivity while opening on-screen keyboard.
Fixes: #5128
> [android] Adjust resize on FeatureCategoryActivity

- android/src/app/organicmaps/widget/placepage/PlacePageController.java
Fixes #5124
I also added the check on the avoid button just to be sure and consistent with the other functions.
@biodranik @Jean-BaptisteC please confirm it fixes the issue on your end
> [android] fix crash on bookmark when pp is closing

- indexer/indexer_tests/search_string_utils_test.cpp
- indexer/search_string_utils.cpp
- search/intermediate_result.hpp
- search/ranker.cpp
- search/ranking_utils.cpp
- search/ranking_utils.hpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
- search/search_tests/ranking_tests.cpp
Closes https://github.com/organicmaps/organicmaps/issues/3401
Closes https://github.com/organicmaps/organicmaps/issues/5251
> [search] Some fixes

- data/mapcss-mapping.csv
- defines.hpp
- generator/osm2type.cpp
- generator/utils.cpp
Needs https://github.com/organicmaps/kothic/pull/13 merged first.
> Allow comments in mapcss-mapping.csv

- android/res/values-de/strings.xml
- android/res/values-en-rGB/strings.xml
- android/res/values/strings.xml
- data/categories.txt
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/be.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/bg.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/ca.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/cs.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/da.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/de.lproj/InfoPlist.strings
- iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/de.lproj/Localizable.stringsdict
- iphone/Maps/LocalizedStrings/en-GB.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/en.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/fr.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/he.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/hu.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/ro.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/sk.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/sv.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/sw.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/vi.lproj/Localizable.strings
Updated the german translations in types_strings.txt
> Updated german translations

- docs/INSTALL.md
https://github.com/orgs/organicmaps/discussions/5138
> [docs] Add note regarding cpp dev

- search/ranker.cpp
- search/ranking_info.cpp
- search/ranking_info.hpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
- search/search_tests/ranking_tests.cpp
Added famous cities ranking test.
Better, but still https://github.com/organicmaps/organicmaps/issues/5358
> [search] Fixed search rank for the population rank.

- docs/OBJC_STYLE.md
- docs/RELEASE_MANAGEMENT.md
- docs/TRANSLATIONS.md
this PR is in reference to the issue #4721
> links updated in documentation

- data/countries_names.txt
This PR update:
- List of cities foreach department (i have take 3 biggest cities foreach department)
- translations in other languages with wikidata and wikipedia
- Remove fr translations when en language is same
- Remove invisible characters after name of department in French
> Update country and cities translations

- routing/routing_session.cpp
> [core] Fix #5437

- kml/kml_tests/gpx_tests.cpp
- kml/serdes_gpx.cpp
- kml/serdes_gpx.hpp
> [gpx] Extract altitude values from GPX

- data/strings/types_strings.txt
This PR improve french type translations.
> Update french translations

- xcode/fastlane/Fastfile
Fixes this: https://github.com/organicmaps/organicmaps/actions/runs/5498289716/jobs/10019638188
> [github] Fixed Could not install WWDR certificate Fastlane error for beta builds

- qt/qt_common/map_widget.cpp
Fixes https://github.com/flathub/app.organicmaps.desktop/issues/36
> [qt] Take the correct path depending on GL version

- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm
- platform/distance.cpp
- platform/platform_tests/distance_tests.cpp
Closes https://github.com/organicmaps/organicmaps/issues/5501
Closes https://github.com/organicmaps/organicmaps/issues/5507
> [platform] Simplify Distance::GetFormattedDistance().

- android/src/app/organicmaps/car/NavigationSession.java
- android/src/app/organicmaps/car/screens/BookmarksScreen.java
- android/src/app/organicmaps/car/screens/NavigationScreen.java
- android/src/app/organicmaps/car/screens/PlaceScreen.java
- android/src/app/organicmaps/car/screens/search/SearchOnMapScreen.java
- android/src/app/organicmaps/car/screens/search/SearchUiHelpers.java
- android/src/app/organicmaps/car/screens/settings/DrivingOptionsScreen.java
- android/src/app/organicmaps/car/screens/settings/SettingsScreen.java
- android/src/app/organicmaps/car/util/Colors.java
- android/src/app/organicmaps/car/util/LanesDrawable.java
- android/src/app/organicmaps/car/util/RoutingHelpers.java
- android/src/app/organicmaps/car/util/RoutingUtils.java
- android/src/app/organicmaps/car/util/UiHelpers.java
- android/src/app/organicmaps/routing/SingleLaneInfo.java
- android/src/app/organicmaps/util/Distance.java
Implemented Navigation Screen.
Some refactoring for other classes.
Here are some examples for day and night modes.
Night mode is implemented only for template UI and lanes.
Full night mode support will be implemented in a separate PR.
> [android-auto] Navigation Screen

- android/res/values-ca/strings.xml
- android/res/values-es/strings.xml
- data/strings/strings.txt
A follow-up to https://github.com/organicmaps/organicmaps/pull/5369#discussion_r1257645189 comment by @fitojb 
You may double-check all tracks translations in strings.txt
> [strings] Fixed es and ca tracks translation

- data/strings/types_strings.txt
The previous pull request didn't fix the issue, so I made a new one that will fix it.
> Fix pastry translation in :hungary: 

- data/countries.txt
- routing/routing_integration_tests/route_test.cpp
- routing/routing_integration_tests/turn_test.cpp
Closes https://github.com/organicmaps/organicmaps/issues/5468
> [planet] New data from 230710.

- drape_frontend/rule_drawer.cpp
- generator/generator_tests/feature_builder_test.cpp
- generator/geometry_holder.hpp
- indexer/drawing_rules.cpp
- indexer/drules_selector.cpp
- indexer/drules_selector.hpp
- indexer/feature.cpp
- indexer/feature_algo.cpp
- indexer/feature_visibility.cpp
- indexer/map_object.cpp
- indexer/scale_index_builder.hpp
- indexer/scales.cpp
- storage/storage.hpp
Mostly from https://github.com/organicmaps/organicmaps/pull/2798.
> [indexer] Comment geometry scale levels code and refactor it a bit

- generator/generator_tests/osm_type_test.cpp
Follow-up to https://github.com/organicmaps/organicmaps/pull/5491#issuecomment-1627507992
> [tests] Add more mapping tests for highspeed and branch railways

- android/src/app/organicmaps/car/NavigationSession.java
- android/src/app/organicmaps/car/screens/NavigationScreen.java
- android/src/app/organicmaps/car/screens/PlaceScreen.java
- android/src/app/organicmaps/car/util/RoutingHelpers.java
Fixed some bugs:
* displayDistance must be a positive value
* Maneuver does not include roundaboutExitNumber
* Do not show "Build Route" and "Bookmark" actions for my position in PlacePage
* PlacePage. Route is built and new point selected on the map. Cancel route in RoutingController
* Added notification that navigation is finished
> [android-auto] Fix bugs

- drape/support_manager.cpp
Closes https://github.com/organicmaps/organicmaps/issues/5539
> [drape] Forbid Vulkan for Adreno 418.

- data/editor.config
Closes #4297
https://master.apis.dev.openstreetmap.org/changeset/265669#map=19/49.11923/6.16999
> Add leisure=dog_park in editor

- search/geocoder.cpp
- search/ranking_utils.cpp
- search/search_integration_tests/processor_test.cpp
- search/streets_matcher.cpp
- search/streets_matcher.hpp
https://github.com/organicmaps/organicmaps/issues/4421#issuecomment-1652149018
> [search] Fixed "relaxed" street match.

- generator/geometry_holder.hpp
- indexer/feature.cpp
- indexer/feature.hpp
- map/mwm_tests/multithread_mwm_test.cpp
Follow up https://github.com/organicmaps/organicmaps/pull/5540
> [feature][generator] Added "service" geometry offset flag.

- drape/glyph_manager.cpp
- drape/glyph_manager.hpp
> [drape] Fix kDynamicGlyphSize declaration

- indexer/classificator.cpp
- indexer/classificator.hpp
- indexer/feature_decl.cpp
- indexer/feature_decl.hpp
- qt/draw_widget.hpp
- search/features_layer_matcher.hpp
- search/house_numbers_matcher.cpp
- search/house_numbers_matcher.hpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
- search/search_tests/house_numbers_matcher_test.cpp
First patch to replace obsolete https://github.com/organicmaps/organicmaps/pull/1708
https://github.com/organicmaps/organicmaps/issues/579
Still a lot of work ahead.
> [search] Conscription numbers for Czech and Slovakia.

- 3party/opening_hours/opening_hours.cpp
Fixes #5635
@maddin200 thank you!
> Fixed wrong Timespan comparison for opening hours

- kml/kml_tests/gpx_tests.cpp
- kml/serdes_gpx.cpp
- kml/serdes_gpx.hpp
> [gpx] Support cmt tag

- android/res/layout/item_category_description.xml
- android/res/values/strings.xml
- android/src/app/organicmaps/bookmarks/BookmarkListAdapter.java
Fixes #4813
The "...more" button is now functional and is only visible for descriptions more than 2 lines.
> [android] Fixed "...more" button in bookmark's list description

- data/categories.txt
Makes returned types much more relevant and useful
fixes https://github.com/organicmaps/organicmaps/issues/5660
Before, After
> remove some types from tourism category

- routing/index_router.cpp
- routing/routing_integration_tests/route_test.cpp
- routing/routing_integration_tests/routing_test_tools.cpp
- routing/routing_integration_tests/routing_test_tools.hpp
- routing/routing_options.cpp
- routing/routing_options.hpp
https://github.com/organicmaps/organicmaps/issues/5695
> [routing] Cross-MWM, updated leaps candidates processing.

- base/dfa_helpers.hpp
- base/levenshtein_dfa.hpp
- generator/search_index_builder.cpp
- search/ranker.cpp
- search/ranking_utils.cpp
- search/ranking_utils.hpp
- search/search_integration_tests/smoke_test.cpp
- search/search_tests/ranking_tests.cpp
- search/types_skipper.cpp
- search/types_skipper.hpp
> [search] Do not index entrance numbers (common for CIS countries). 

- data/countries.txt
https://github.com/organicmaps/organicmaps/pull/5540
> [planet] New data from 230814.

- generator/feature_builder.cpp
- generator/feature_builder.hpp
- generator/feature_sorter.cpp
- generator/filter_world.cpp
- generator/generator_tests/metalines_tests.cpp
- generator/geometry_holder.hpp
- generator/world_map_generator.hpp
- indexer/feature.cpp
- indexer/scale_index_builder.hpp
> [generator] Add comments and minor refactoring

- search/reverse_geocoder.cpp
> [search] fix typo in reverse_geocoder.cpp

- kml/kml_tests/gpx_tests.cpp
- kml/serdes_gpx.cpp
> [gpx] Fix for decs/cmt duplication

- coding/coding_tests/mem_file_reader_test.cpp
- coding/coding_tests/zip_creator_test.cpp
- coding/reader.hpp
- data/gpx_test_data/osmand1.gpx
- kml/kml_tests/gpx_tests.cpp
- kml/kml_tests/serdes_tests.cpp
- kml/serdes.cpp
- kml/serdes_gpx.cpp
- kml/serdes_gpx.hpp
Fixes #5800
Supersedes and closes #5824
@cyber-toad
> Fix invisible GPX tracks after the import

- search/house_numbers_matcher.cpp
- search/intermediate_result.cpp
- search/pre_ranker.cpp
- search/pre_ranker.hpp
- search/ranker.cpp
- search/ranking_info.cpp
- search/ranking_utils.cpp
- search/ranking_utils.hpp
- search/search_integration_tests/pre_ranker_test.cpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
- search/search_tests/house_numbers_matcher_test.cpp
- search/search_tests/ranking_tests.cpp
https://github.com/organicmaps/organicmaps/issues/5756
2x times faster now https://github.com/organicmaps/organicmaps/issues/5694
> [search] Ranking, speed, accuracy

- android/res/values-ar-rSY/colors.xml
- android/res/values-mcc286/colors.xml
- android/res/values-mcc417/colors.xml
- android/res/values-tr/colors.xml
- android/res/values/colors.xml
- android/res/values/ic_launcher_background.xml
Reverts organicmaps/organicmaps#4440 and resolves #5819
> [android] Change logo to green again for Turkey and Syria

- android/src/app/organicmaps/car/screens/search/SearchOnMapScreen.java
- android/src/app/organicmaps/car/screens/search/SearchUiHelpers.java
> [android-auto] Fix non-browsable rows crash

- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/es.lproj/Localizable.strings
Fix "carplay_roundabout_exit" string in Spanish
> [strings] Fix "carplay_roundabout_exit" string in Spanish

- map/routing_manager.cpp
Return back route preview commented out in PR #5744
> Return back route preview

- docs/TRANSLATIONS.md
- tools/python/translate.py
- Also added Hindi
- strings.txt format is printed last as more relevant
Used it in #5796
> [tools] Support custom source language in translate.py

- generator/generator_tests_support/test_feature.cpp
- generator/generator_tests_support/test_feature.hpp
- indexer/road_shields_parser.cpp
- search/features_layer_matcher.cpp
- search/features_layer_matcher.hpp
- search/filtering_params.hpp
- search/geocoder.cpp
- search/geocoder.hpp
- search/geocoder_context.cpp
- search/geocoder_context.hpp
- search/locality_scorer.cpp
- search/result.cpp
- search/search_integration_tests/processor_test.cpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
- search/search_tests/locality_scorer_test.cpp
- search/streets_matcher.cpp
- search/streets_matcher.hpp
Also closes https://github.com/organicmaps/organicmaps/issues/3083
There are too many Red minor road H-shields in Belarus.
> [search] Fixed GetMatchingStreet.

- tools/python/maps_generator/utils/file.py
> [generator] fix building of osmctools

- docs/STYLES.md
Added a link to the icon overview to STYLES.md
> [docs] Added link to icon overview

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/MwmApplication.java
- android/app/src/main/java/app/organicmaps/SplashActivity.java
- android/app/src/main/java/app/organicmaps/car/NavigationSession.java
- android/app/src/main/java/app/organicmaps/car/screens/ErrorScreen.java
- android/app/src/main/java/app/organicmaps/car/screens/MapPlaceholderScreen.java
- android/app/src/main/java/app/organicmaps/car/screens/RequestPermissionsScreen.java
- android/app/src/main/java/app/organicmaps/car/util/Colors.java
- android/app/src/main/java/app/organicmaps/car/util/RoutingHelpers.java
- android/app/src/main/java/app/organicmaps/car/util/UiHelpers.java
- android/app/src/main/java/app/organicmaps/location/LocationHelper.java
- android/app/src/main/java/app/organicmaps/util/LocationUtils.java
- android/app/src/main/res/layout/fragment_map_placeholder.xml
- android/app/src/main/res/values-fr/strings.xml
- android/app/src/main/res/values-ru/strings.xml
- android/app/src/main/res/values/strings.xml
- data/strings/strings.txt
Closes: https://github.com/organicmaps/organicmaps/issues/5767
Closes: https://github.com/organicmaps/organicmaps/issues/5758
Closes: https://github.com/organicmaps/organicmaps/pull/4918
Demo:
1. Request permission:
2.  Click button -> Show request on the phone screen:
3. Deny -> Error screen shown:
4. Close -> goto 1.
Once permission is granted, the MapScreen will be displayed.
> [android auto] permissions request screen

- android/app/src/main/java/app/organicmaps/MapRenderingListener.java
- android/app/src/main/java/app/organicmaps/car/NavigationSession.java
- android/app/src/main/java/app/organicmaps/car/SurfaceRenderer.java
- android/app/src/main/java/app/organicmaps/car/util/RoutingHelpers.java
- android/app/src/main/java/app/organicmaps/car/util/RoutingUtils.java
Closes: https://github.com/organicmaps/organicmaps/issues/5763
Closes: https://github.com/organicmaps/organicmaps/issues/5766
Closes: https://github.com/organicmaps/organicmaps/issues/5757
Closes: https://github.com/organicmaps/organicmaps/issues/5758
> [android-auto] Fix TTS

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/MwmApplication.java
- android/app/src/main/java/app/organicmaps/base/MediaPlayerWrapper.java
- android/app/src/main/java/app/organicmaps/routing/NavigationController.java
- android/app/src/main/java/app/organicmaps/routing/NavigationService.java
- android/app/src/main/java/app/organicmaps/sound/TtsPlayer.java
Follow up 528ffaf "Enable navigation in background mode"
> [android] Move camera beeps into NavigationService

- map/framework.cpp
If there's bookmark near tap position then continue route to that bookmark:
| ---- | ---- |
| <video src="https://github.com/organicmaps/organicmaps/assets/720808/dd003406-7178-41be-8cd4-39a2a3929a73" /> | <video src="https://github.com/organicmaps/organicmaps/assets/720808/d82136d3-c3b5-4575-b03f-14e14bcf02e7" /> |
Closes #5966
> [ruler] Snap next point to the closest bookmark

- indexer/drawing_rule_def.hpp
- indexer/drawing_rules.cpp
- indexer/drawing_rules.hpp
Simplified/optimized how drules are indexed. Now fetching them will be faster.
Also deleted some obsolete unused code.
> [indexer] Optimize RulesHolder

- .github/workflows/linux-check.yaml
- android/app/src/main/java/app/organicmaps/location/LocationState.java
- docs/INSTALL.md
- iphone/Maps/Core/Location/MWMLocationObserver.h
- platform/CMakeLists.txt
- platform/location.hpp
- platform/location_service.cpp
- platform/qt_location_service.cpp
- platform/qt_location_service.hpp
- qt/mainwindow.cpp
Fixes https://github.com/flathub/app.organicmaps.desktop/issues/19
> [linux][qt] Add positioning support via GeoClue2

- android/app/src/main/res/values-be/strings.xml
- android/app/src/main/res/values-mr/strings.xml
- android/app/src/main/res/values-nl/strings.xml
- android/app/src/main/res/values-ru/strings.xml
- android/app/src/main/res/values-uk/strings.xml
- android/app/src/main/res/values-zh/strings.xml
- data/categories.txt
- data/strings/types_strings.txt
- indexer/indexer_tests/search_string_utils_test.cpp
- indexer/search_string_utils.cpp
- iphone/Maps/LocalizedStrings/be.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/ca.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/mr.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/nl.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/ru.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/uk.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/zh-Hans.lproj/Localizable.strings
Added 'houseware' category only for English/Russian. I don't like straightforward translations like de = Haushaltswarengeschäft :) to be used in search terms.
If somebody can advise good short search definitions for shop=houseware in his native language, I will add them.
> [search] shop-houseware category.

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/cpp/app/organicmaps/Framework.hpp
- android/app/src/main/cpp/app/organicmaps/MwmApplication.cpp
- android/app/src/main/java/app/organicmaps/MwmApplication.java
- android/app/src/main/java/app/organicmaps/SplashActivity.java
- editor/osm_editor.cpp
- map/framework.cpp
- map/framework.hpp
- search/engine.cpp
- storage/storage.cpp
- storage/storage.hpp
A good solution is to refactor Storage and make a separate message queue for it.
Mass Android/iOS testing is appreciated.
@Jean-BaptisteC 
@AndrewShkrob 
@strump
> [storage] Async maps loading on startup.

- .github/ISSUE_TEMPLATE/bug_report.md
tested for Android - maybe this instructions are correct for Apple devices?
> fix instructions where to find OM version

- data/strings/strings.txt
"捐款" would make more sense in zh-Hans and zh-Hant
> Update strings.txt for "donate" translation

- docs/TRANSLATIONS.md
- tools/ruby/category_consistency/omim_parsers.rb
Hopefully translators won't do it manually anymore :)
> [strings] Updated category consistency checker and documented it

- android/app/src/main/res/values-ar-rLY/colors.xml
- android/app/src/main/res/values-ar-rMA/colors.xml
- android/app/src/main/res/values-ar/colors.xml
- android/app/src/main/res/values-mcc604/colors.xml
- android/app/src/main/res/values-mcc606/colors.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/ic_launcher_background.xml
This PR updated the logo icon for devices in Morocco and Libya following natural disasters.
Help is appreciated to test changes. I'm on vacation
I hope so, these changes will be merged before the next version.
Fixes #5994
> [Android]Update logo to black for Morocco and Libya

- data/countries.txt
- routing/routing_integration_tests/bicycle_route_test.cpp
- routing/routing_integration_tests/pedestrian_route_test.cpp
- routing/routing_integration_tests/route_test.cpp
Closes https://github.com/organicmaps/organicmaps/issues/5842
Closes https://github.com/organicmaps/organicmaps/issues/5841
Closes https://github.com/organicmaps/organicmaps/issues/5803
> [planet] New data from 230920.

- android/app/src/main/java/app/organicmaps/location/LocationHelper.java
- docs/ANDROID_LOCATION_TEST.md
> [android] Fix Google Location Dialog on the start

- README.md
Link is already fixed on OM website
> Fix Tracker Control link

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/Bookmark.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/MapObject.java
- android/app/src/main/java/app/organicmaps/routing/RoutingController.java
- android/app/src/main/java/app/organicmaps/util/SharingUtils.java
- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageController.java
- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
- android/app/src/main/java/app/organicmaps/widget/placepage/sections/PlacePageBookmarkFragment.java
Move few preliminary checks from RoutingController to MwmActivity.
> [android] Remove few useless callbacks from RoutingController

- android/app/src/main/java/app/organicmaps/Map.java
- android/app/src/main/java/app/organicmaps/MapFragment.java
- android/app/src/main/java/app/organicmaps/car/NavigationCarAppService.java
- android/app/src/main/java/app/organicmaps/car/NavigationSession.java
- android/app/src/main/java/app/organicmaps/car/SurfaceRenderer.java
- android/app/src/main/java/app/organicmaps/car/hacks/PopToRootHack.java
- android/app/src/main/java/app/organicmaps/car/screens/NavigationScreen.java
- android/app/src/main/java/app/organicmaps/car/screens/PlaceScreen.java
- android/app/src/main/java/app/organicmaps/car/util/IntentUtils.java
- android/app/src/main/java/app/organicmaps/car/util/LanesDrawable.java
Rebased version of https://github.com/organicmaps/organicmaps/pull/5998
> [android-auto] Refactoring of PlaceScreen and NavigationScreen

- docs/INSTALL.md
- tools/unix/build_omim.sh
various small text fixes like:
apk -> APK
XCode -> Xcode (apple spelling)
and other stuff
> [docs] some small improvements

- android/app/src/main/res/values-pl/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/pl.lproj/Localizable.strings
Mostly aligning with English which I presume was updated at some point, as well as converting infinitive verbs to imperative (typical auto-translation blunder)
> Minor fixes to UI translation

- generator/routing_index_generator.cpp
- routing/edge_estimator.cpp
- routing/index_graph_starter_joints.hpp
- routing/joint_segment.cpp
- routing/joint_segment.hpp
- routing/routing_integration_tests/route_test.cpp
- routing/segment.cpp
- routing/segment.hpp
- routing/single_vehicle_world_graph.cpp
- routing_common/pedestrian_model.cpp
Still keep open:
https://github.com/organicmaps/organicmaps/issues/6035
https://github.com/organicmaps/organicmaps/issues/5927
https://github.com/organicmaps/organicmaps/issues/5695
Can be closed, I think:
https://github.com/organicmaps/organicmaps/issues/5238
https://github.com/organicmaps/organicmaps/issues/3695
https://github.com/organicmaps/organicmaps/issues/1728
https://github.com/organicmaps/organicmaps/issues/1150
> [routing] Reduced ferry landing penalty.

- drape/visual_scale.hpp
- drape_frontend/drape_engine.cpp
- drape_frontend/kinetic_scroller.cpp
- drape_frontend/kinetic_scroller.hpp
- drape_frontend/user_event_stream.cpp
- drape_frontend/user_event_stream.hpp
- drape_frontend/visual_params.cpp
- drape_frontend/visual_params.hpp
Closes https://github.com/organicmaps/organicmaps/issues/2652
Please, test on your Android devices.
> [drape] Fixed inertial kinetic scroll.

- .github/workflows/android-beta.yaml
- .github/workflows/android-check-metadata.yaml
- .github/workflows/android-check.yaml
- .github/workflows/android-monkey.yaml
- .github/workflows/android-release-metadata.yaml
- .github/workflows/android-release.yaml
- .github/workflows/appstream-check.yaml
- .github/workflows/cleanup_caches.yml
- .github/workflows/ios-beta.yaml
- .github/workflows/ios-check-metadata.yaml
- .github/workflows/ios-check.yaml
- .github/workflows/ios-release.yaml
- .github/workflows/linux-check.yaml
- .github/workflows/macos-check.yaml
- .github/workflows/strings-check.yaml
Releases notes: https://github.com/actions/checkout/releases
> Bump actions/checkout to v4

- drape_frontend/visual_params.cpp
- iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
- map/mwm_url.cpp
Fixes #5107
Fixes #510
Need to test it with https://omaps.app/api and other examples.
> [ios] Fixed non-working API calls

- data/strings/sound.txt
- data/strings/strings.txt
- data/strings/types_strings.txt
This PR improve:
- TTS strings
- App translations
- Types translations
> Improve french translations

- .github/workflows/ios-beta.yaml
- .github/workflows/ios-check.yaml
- .github/workflows/ios-release.yaml
- .github/workflows/macos-check.yaml
> [github] Use Xcode 15 for iOS and Mac OS X builds

- base/base_tests/string_utils_test.cpp
- base/internal/message.cpp
- base/internal/message.hpp
- base/string_utils.cpp
- base/string_utils.hpp
It is needed for #4281 task to use icu bidi that requires UTF-16.
> strings::ToUtf16

- android/app/src/main/res/values-fr/strings.xml
- data/sound-strings/fr.json/localize.json
- data/strings/strings.txt
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/fr.lproj/Localizable.strings
This PR fixes comments in #6296 and regenerates translations
> Fix french translations

- iphone/Maps/Classes/MapViewController.mm
This fixes keyboard input on iPadOS 15+
> Fix keyboard input on iPadOS 15+

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/SplashActivity.java
- android/app/src/main/java/app/organicmaps/util/Config.java
- data/categories.txt
Search:
shop -> suggest "shopping"
шоп -> suggest "шоппинг"
> [android] Fixed isFirstLaunch regression.

- routing/geometry.cpp
- routing/routing_integration_tests/bicycle_route_test.cpp
- routing/routing_integration_tests/bicycle_turn_test.cpp
- routing/routing_integration_tests/pedestrian_route_test.cpp
- routing/routing_integration_tests/route_test.cpp
- routing/routing_integration_tests/turn_test.cpp
Follow up 6d3e7db0896c3b36265014c9a2bcfc248fbe1f60.
> [routing][tests] Updated integration tests.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
- docs/COMMIT_MESSAGES.md
- docs/CONTRIBUTING.md
- docs/DCO.md
- docs/PR_GUIDE.md
- docs/RELEASE_MANAGEMENT.md
- docs/STRUCTURE.md
- docs/STYLES.md
- docs/SUBWAY_GENERATION.md
lots of small fixes, some rewording for better flow
> [docs] various docs improvements

- data/conf/isolines/README.md
- data/conf/isolines/add_missing_countries.py
- data/conf/isolines/countries-to-generate.json
Closes https://github.com/organicmaps/organicmaps/issues/6271
> [generator] Updated isolines profile.

- data/faq.html
> Remove route button in FAQ

- docs/INSTALL.md
See https://github.com/organicmaps/organicmaps/issues/6328#issuecomment-1774674736
> [docs] Recommend the minimum geoclue version of 2.5.7

- tools/unix/build_omim.sh
Intends to fix https://github.com/organicmaps/organicmaps/issues/6401
> [tools] Remove former SKIP_QT_GUI from CMake cache

- shaders/Metal/map.metal
Closes https://github.com/organicmaps/organicmaps/issues/6398
Needs good testing, can break something else.
> [drape][iOS] Fixed depth. Follow up fb7480bf2a2982c63ffe443d9676fa0478c37ea8.

- .github/workflows/android-monkey.yaml
- android/app/build.gradle
Crashlytics has been removed from all debug versions. Let's test betas instead.
> [android] Fix Monkey

- android/app/src/main/java/app/organicmaps/help/HelpFragment.java
- android/app/src/main/res/layout-land/about.xml
- android/app/src/main/res/values-land/dimens.xml
- android/app/src/main/res/values-sw720dp-land/dimens.xml
- android/app/src/main/res/values/dimens.xml
Tested on Pixel 6 - Android 14 and Samsung Galaxy Tab S6 Lite - Android 13
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/13713fc5-c440-4290-a150-bfbecb4af103" height=150 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/018dfe4c-557c-45fd-a3c3-e6238533fedb" height=150 />|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/03ab8d75-6318-47cf-9c62-2ef65e9c9848" height=200 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/558911f4-8c83-4eee-9bd1-599dd4517819" height=200 />
TODO:
> [android] Implement new About layout land

- .github/CODEOWNERS
> [github] Require legal review for all new graphics

- data/editor.config
I have an assert on the desktop, because looks like a comment inside a comment is a bad-formed xml.
> [editor] Removed comment inside comments in editor.config xml.

- data/categories.txt
It seems Italians 🤌🏻 have lot of weird ways to indicate a letter box.
Let's add a reasonable number of new keywords to find letter box even more efficiently.
> [strings] 📮 Italian: improve "Post Box" and friends

- android/app/src/main/java/app/organicmaps/bookmarks/data/MapObject.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/Metadata.java
@rtsisyk Should ensure that there are no more false unused.
> [android] Restore deleted function which is called from JNI only.

- drape_frontend/kinetic_scroller.cpp
Please, test kinetic scrolling.
> [drape] Added min-drag-time to the kinetic scroller.

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- drape_frontend/my_position_controller.cpp
> [android][drape] Don't show "location timeout" in NotFollowNoPosition

- data/categories.txt
> [categories.txt] Update it translation

- android/app/src/main/java/app/organicmaps/location/LocationHelper.java
Subscribe to the low-level GnssStatus/GpsStatus updates to keep the green dot location indicator in the Android system tray always firing when the location is used by the app. Otherwise, it fires only AFTER the GPS has been acquired.
Fixes #4223
Fixes #5999
> [android] Keep green dot location indicator firing

- data/categories.txt
- data/strings/strings.txt
- data/strings/types_strings.txt
Hi!
Trying to fix WC category in PT-BR, which is broken a long time. Also improved PT and ES, and fixed PT translation of Public bath.
Signed-off-by: Matheus Gomes <86851490+matheusgomesms@users.noreply.github.com>
> [strings] Fix search in PT-BR

- android/app/src/main/res/layout-land/about.xml
- android/app/src/main/res/layout/about.xml
See this comment https://github.com/organicmaps/organicmaps/pull/6440#issuecomment-1793024387
> [android] Move FAQ in about fragment

- android/app/src/main/java/app/organicmaps/MwmActivity.java
It is not clear how to reproduce this bug. Add a workaround and a log entry.
See #3945
See #3593
> [android] Add explicit check for PointChooserMode

- android/app/src/main/java/app/organicmaps/car/screens/PlaceScreen.java
> [android-auto] fix start routing

- android/app/src/main/res/layout/fragment_timetable_picker.xml
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/c6047d5b-14a2-4af9-a6d4-efeff58a4730" height=400 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/daffca4c-a4b3-43fd-b8ac-4f2ed6fce1ed" height=400 />|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/598a64c7-6c8c-4e57-b200-b3ff376cb748" height=400 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/beb8439a-7e77-41a8-90ad-46c406a59a78" height=400 />
Tested on Pixel 6 - Android 14
> [android] Fix color in time picker

- android/app/src/main/java/app/organicmaps/help/FaqFragment.java
I have forgot to migrate AlertDialog using FAQ Fragment in #4665
Tested on Pixel 6 - Android 14
> Migrate AlertDialog in FAQ Fragment to MaterialAlertDialogBuilder

- drape_frontend/my_position_controller.cpp
- routing/routing_integration_tests/route_test.cpp
- routing_common/car_model_coefs.hpp
Closes https://github.com/organicmaps/organicmaps/issues/6510
https://github.com/organicmaps/organicmaps/issues/3033#issuecomment-1798343531
> [routing] Decreased "residential" factor.

- android/app/src/main/res/layout-land/fragment_osm_login.xml
This PR fix this crash:
```
FATAL EXCEPTION: main
Process: app.organicmaps.debug, PID: 20183
java.lang.ClassCastException: androidx.appcompat.widget.AppCompatEditText cannot be cast to com.google.android.material.textfield.TextInputEditText
at app.organicmaps.editor.OsmLoginFragment.onViewCreated(OsmLoginFragment.java:49)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
at …
```
> [android] Fix crash when you rotate device in Login Fragment

- android/app/src/main/res/values/styles.xml
This PR update TextView style.
No impact on UI, just better compatibility with material theming -> more information here https://m2.material.io/develop/android/supporting/text-view.
I am making little changes to reduce style regressions.
My objective is migrate all themes/styles to material (material 2) and fix wrong colors in dark mode
Tested on Pixel 6 - Android 14
> Migrate TextView to Material theming

- android/app/src/main/res/layout/fragment_osm_login.xml
This PR add a button in TextFieldInput password to hide/see password
|Hide|See|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/913656ea-82b6-4d1c-b161-2e1a1e4d7902" height=400 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/cd3d3faf-29cf-407a-bf3c-d04a5d366722" height=400 />|
Tested on Pixel 6 - Android 14 in Light and Dark mode
> [android] Add new button in textFieldPassword

- docs/INSTALL.md
- Add commands to enable Outdoors style
- Update information about Android
> [docs] Somes improvements

- data/strings/sound.txt
Small fixes for Hungarian voice instructions.
> Fix Hungarian TTS

- android/app/src/main/java/app/organicmaps/util/log/Logger.java
> [android] Fix ArrayIndexOutOfBoundsException in Logger

- indexer/editable_map_object.cpp
- indexer/map_object.hpp
> [meta] Do not process EXTERNAL_URI field as from OSM.

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/cpp/app/organicmaps/Framework.hpp
- android/app/src/main/java/app/organicmaps/Framework.java
- android/app/src/main/java/app/organicmaps/MwmActivity.java
Keep this state only on C++ side without duplicating in Java.
**Test cases:**
1. Open the Editor and choose a point and try to rotate the screen.
2. https://github.com/organicmaps/api-android/tree/master/sample-pick-point - click "Pick Point" and try to rotate the screen.
See #3945
See #6437
Closes #6575
> [android] Fix inconsistent ChoosePositionMode

- data/countries.txt
Closes https://github.com/organicmaps/organicmaps/issues/6315
https://github.com/organicmaps/organicmaps/issues/6271
> [planet] New data from 231113.

- android/app/src/main/cpp/app/organicmaps/UserMarkHelper.cpp
- descriptions/loader.cpp
- descriptions/loader.hpp
- iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
- map/framework.cpp
- map/place_page_info.hpp
- qt/place_page_dialog.cpp
> [qt] Wiki descriptions in tooltips

- android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java
- android/app/src/main/java/app/organicmaps/dialog/EditTextDialogFragment.java
- android/app/src/main/java/app/organicmaps/editor/EditorFragment.java
- android/app/src/main/java/app/organicmaps/settings/StoragePathAdapter.java
This PR updates the syntax suggested by Android Studio with the default inspection profile.
I didn't have update everything, because I don't know the impact of all the changes and some suggested changes reduced visibility of code.
Todo:
> [android] Improve syntax

- android/app/src/main/java/app/organicmaps/util/LocationUtils.java
Regression by 86bbe48 "[android] Add Android Auto support"
> [android] Fix coding error in checkCoarseLocationPermission()

- drape_frontend/apply_feature_functors.cpp
- drape_frontend/apply_feature_functors.hpp
- indexer/drawing_rule_def.hpp
- indexer/drawing_rules.cpp
- indexer/drawing_rules.hpp
- indexer/feature_data.cpp
- indexer/feature_data.hpp
- indexer/indexer_tests/feature_types_test.cpp
- map/style_tests/classificator_tests.cpp
@pastk post_office should be better than copyshop, agree?
> [feature] Select the best POI's type by drawing rule's priority.

- android/app/src/main/java/app/organicmaps/bookmarks/BookmarkCategorySettingsFragment.java
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarkListActivity.java
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java
- android/app/src/main/java/app/organicmaps/editor/FeatureCategoryFragment.java
- android/app/src/main/java/app/organicmaps/editor/HoursMinutesPickerFragment.java
- android/app/src/main/java/app/organicmaps/util/Utils.java
- android/app/src/main/java/app/organicmaps/widget/placepage/DirectionFragment.java
Regression by 4cadc09
Related to #143 and #3757
Closes #6629
> [android] Fix ClassNotFoundException .bookmarks.data.BookmarkCategory

- android/app/src/main/java/app/organicmaps/routing/RoutingErrorDialogFragment.java
> [android] Dismiss spinner when user aborts downloading area

- docs/INSTALL.md
> [docs][android] Add Android Auto development instructions

- android/app/src/main/res/values-es/strings.xml
- data/categories.txt
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/es.lproj/Localizable.strings
Just some more synonyms for parking categories in Spanish to improve searchability
> [strings] Add some more parking translations in Spanish

- android/app/build.gradle
- android/build.gradle
Upgrade other dependencies too
> [android] Upgrade agp to 8.1.4

- android/app/src/main/java/app/organicmaps/routing/TransitStepView.java
This PR fix color step distance in dark mode
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/64d298de-a338-47d2-84b7-237a2635c54e" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/23016877-3887-4425-89d2-525c0a8b149f" height=300 />|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/389211cc-7a4d-4f36-88cd-ab77fa0624f3" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/3d800b33-f2e0-40c6-9f49-17a36455e8da" height=300 />|
> [android] Fix step distance color in ruler mode

- generator/generator_tests_support/test_feature.cpp
- generator/generator_tests_support/test_feature.hpp
- indexer/feature_meta.hpp
- indexer/mwm_set.hpp
- map/framework.cpp
- search/categories_cache.cpp
- search/features_layer.hpp
- search/features_layer_matcher.cpp
- search/features_layer_matcher.hpp
- search/geocoder.cpp
- search/geocoder.hpp
- search/geocoder_locality.cpp
- search/geocoder_locality.hpp
- search/intersection_result.cpp
- search/locality_scorer.cpp
- search/locality_scorer.hpp
- search/processor.cpp
- search/processor.hpp
- search/ranker.cpp
- search/reverse_geocoder.cpp
- search/reverse_geocoder.hpp
- search/search_integration_tests/processor_test.cpp
- search/search_tests/house_numbers_matcher_test.cpp
- search/search_tests/locality_scorer_test.cpp
Should review and test addresses described in the issues below. Should work in 90%, remains some very exotic cases.
https://github.com/organicmaps/organicmaps/issues/2689: Mannheim works; HOPFENBURG is not, because of place without actual tag place=*
Closes https://github.com/organicmaps/organicmaps/issues/5075
Closes https://github.com/organicmaps/organicmaps/issues/5890
https://github.com/organicmaps/organicmaps/issues/557: Everything should work, but there are problems with duplicating "СНТ Вишенка"
Closes https://github.com/organicmaps/organicmaps/issues/579
Closes https://github.com/organicmaps/organicmaps/issues/603
Meta issue: https://github.com/organicmaps/organicmaps/issues/5307
Update wiki here: https://github.com/organicmaps/organicmaps/issues/557#issuecomment-1732262276
> [search] addr:place matching.

- coding/coding_tests/value_opt_string_test.cpp
- coding/value_opt_string.hpp
- generator/generator_tests/feature_builder_test.cpp
- indexer/feature_data.cpp
Closes https://github.com/organicmaps/organicmaps/issues/4259
> [generator] Do not erase leading zeros in house number.

- data/osm_test_data/railway_station.osm
- generator/generator_tests/raw_generator_test.cpp
- generator/osm2type.cpp
- generator/osm2type.hpp
Closes https://github.com/organicmaps/organicmaps/issues/4120
> [generator] Assign railway/highway station types to Nodes and Ways.

- android/app/src/main/res/values-zh-rTW/strings.xml
- android/app/src/main/res/values-zh/strings.xml
- data/strings/strings.txt
thanks to 南山少帅Felix on telegram
> [strings] add zh strings for  "download the world map"

- drape_frontend/frontend_renderer.cpp
- drape_frontend/my_position_controller.cpp
- drape_frontend/path_text_handle.cpp
- feature_list/feature_list.cpp
- generator/dumper.cpp
- indexer/drules_selector.cpp
- indexer/feature.cpp
- indexer/feature.hpp
- indexer/indexer_tests/drules_selector_parser_test.cpp
- platform/preferred_languages.cpp
Turned out that languages::GetSystemPreferred can be a serious bottleneck in iOS.
Better to review preferred_languages.cpp with hide whitespaces enabled.
Probably should fix:
https://github.com/organicmaps/organicmaps/issues/6160
https://github.com/organicmaps/organicmaps/issues/6085
> [feature] Faster name selector.

- android/app/src/main/java/app/organicmaps/MapPlaceholderActivity.java
- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/car/CarAppSession.java
> [android-auto] Fix PendingIntent crash

- android/app/src/main/java/app/organicmaps/help/FaqFragment.java
- android/app/src/main/res/drawable/ic_feedback.xml
- android/app/src/main/res/layout/feedback_fab.xml
- android/app/src/main/res/layout/fragment_prefs_faq.xml
This PR replaces the old Feedback button with a new Feedback floating action button.
Closes #5594
|Before|After|
|--|--|
|![image](https://github.com/organicmaps/organicmaps/assets/84731134/13310699-ffbc-42cd-9f5d-fce425595c1a)|![image](https://github.com/organicmaps/organicmaps/assets/84731134/236368f5-1038-450c-af6e-6003629b6ebf)|
> [android] Add feedback fab

- qt/place_page_dialog.cpp
- qt/qt_common/CMakeLists.txt
- qt/qt_common/text_dialog.cpp
- qt/qt_common/text_dialog.hpp
> [desktop] Show wikipedia articles in a separate dialog

- android/app/src/main/res/layout/edit_bookmark_common.xml
This PR position of color picker when app is in arabic (This issue was reported in Telegram channel).
> [android] Fix bookmarks color picker in RTL

- android/app/src/main/res/values-nl/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/nl.lproj/Localizable.strings
There are a few (computer translation?) mistakes in the Dutch strings.
I fixed some strange phrases and wrong uses of words.
> [strings] Fixes to the Dutch translation

- .github/workflows/macos-check.yaml
Fixes failures like this one: https://github.com/organicmaps/organicmaps/actions/runs/7174629060/job/19536425212
> [github] Fix failing Mac builds and made builds faster

- iphone/Maps/Classes/CarPlay/CarPlayService.swift
Currently the keyboard is blocking the search results in CarPlay. The keyboard cannot be minimized but this commits implements the search button action which shows a list of search results.
Fixes: #2241
> [ios] CarPlay search button shows search results

- search/ranker.cpp
- search/ranking_utils.hpp
> [search] Fixed possible crash.

- qt/draw_widget.cpp
- qt/mainwindow.cpp
- qt/qt_common/map_widget.cpp
- qt/qt_common/map_widget.hpp
Thanks to @AndrewShkrob 
@Ferenc- @pastk Please, check how it works on your Linux.
> [desktop][qt] 60 fps update freq.

- generator/generator_tests_support/test_with_custom_mwms.cpp
- generator/generator_tests_support/test_with_custom_mwms.hpp
- indexer/ftypes_matcher.cpp
- indexer/ftypes_matcher.hpp
- indexer/search_string_utils.cpp
- search/ranker.cpp
- search/ranking_info.cpp
- search/ranking_info.hpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
Closes https://github.com/organicmaps/organicmaps/issues/5964
Closes https://github.com/organicmaps/organicmaps/issues/6127
> [search] Fixed ranking, added tests.

- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.h
- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
- iphone/Maps/Classes/CarPlay/CarPlayService.swift
The panning is not as smoothly as in other navigation apps, so this PR is just a draft until it works better.
Fixes: #833, #3482
> [ios] Support touch panning gestures in CarPlay

- drape_frontend/apply_feature_functors.cpp
- drape_frontend/apply_feature_functors.hpp
- drape_frontend/area_shape.cpp
- drape_frontend/rule_drawer.cpp
- indexer/feature.hpp
Generator fix will follow later.
> [drape] Better crutch to fix crash in abnormal buildings.

- iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
It was accidentally added in clipboard implementation in #6941
Fixes #6977
> [ios] Removed duplicate address

- data/strings/strings.txt
Some were written back to front, some were strangely mixed up in other ways. I've also done a small amount of misc rewrites and corrections.
I'm sorry the signed-off-by has my nickname instead of real name, it was added automatically by GitHub and I can't easily change it now. If you are able to change that on your end, my real name is Nitai Sasson.
> [strings] fix some existing Hebrew strings

- android/app/src/main/res/values-en-rGB/strings.xml
- android/app/src/main/res/values-fi/strings.xml
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/en-GB.lproj/Localizable.strings
> [strings] sidewalk -> pavement for en-GB

- android/app/src/main/res/values-ru/strings.xml
- data/categories_cuisines.txt
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/ru.lproj/Localizable.strings
> Minor strings

- data/strings/strings.txt
Went over all of strings.txt and translate pretty much all untranslated strings, as well as corrected a bunch of existing ones. I had to skip a small few - color names in particular are well beyond my abilities!
As I went through the whole file, I wrote down some notes, comments, suggestions, and childish nitpicks I noticed throughout. I'll open an issue for that soon.
> [strings] translate all strings to Hebrew

- android/app/src/main/java/app/organicmaps/routing/NavigationController.java
- android/app/src/main/java/app/organicmaps/routing/TransitStepView.java
- android/app/src/main/java/app/organicmaps/settings/BaseSettingsFragment.java
- android/app/src/main/java/app/organicmaps/util/UiUtils.java
- android/app/src/main/java/app/organicmaps/widget/FlatProgressView.java
- android/app/src/main/java/app/organicmaps/widget/WheelProgressView.java
- android/app/src/main/java/app/organicmaps/widget/recycler/SpanningLinearLayoutManager.java
- android/app/src/main/res/layout-h400dp/map_buttons_layout_navigation.xml
- android/app/src/main/res/layout-h400dp/map_buttons_layout_regular.xml
- android/app/src/main/res/layout-h400dp/map_buttons_search_frame.xml
- android/app/src/main/res/layout-land/fragment_osm_login.xml
- android/app/src/main/res/layout-land/map_buttons_bottom.xml
- android/app/src/main/res/layout/layout_nav_top.xml
- android/app/src/main/res/layout/map_buttons_bottom.xml
- android/app/src/main/res/layout/map_buttons_layout_navigation.xml
- android/app/src/main/res/layout/map_buttons_layout_planning.xml
- android/app/src/main/res/layout/map_buttons_layout_regular.xml
- android/app/src/main/res/layout/map_buttons_search_frame.xml
My first PR in 2024 🎉
Fixes #4850
This PR updates properties in layouts to full support RTL in app.
This PR:
- replace Left and Right with Start and End in constraint properties
- remove layoutDirection properties to force in LTR.
This PR affect:
- Bottom bar app
- Login connection screen in landscape
- Navigation screen in portrait and landscape
- Map button in portrait and landscape
Need tests in RTL, can be integrated in the next beta?
> [android] Add full RTL support

- .github/workflows/android-check.yaml
- .github/workflows/android-monkey.yaml
- .github/workflows/android-release-metadata.yaml
- .github/workflows/coverage-check.yaml
- .github/workflows/ios-beta.yaml
- .github/workflows/ios-release.yaml
Releases notes: 
- https://github.com/actions/checkout/releases
- https://github.com/actions/upload-artifact/releases
> Update Github Actions

- android/app/src/main/res/values-ar-rLY/colors.xml
- android/app/src/main/res/values-ar-rMA/colors.xml
- android/app/src/main/res/values-ar/colors.xml
- android/app/src/main/res/values-mcc604/colors.xml
- android/app/src/main/res/values-mcc606/colors.xml
Revert changes introduced here #6072
> [android] Remove custom color for logo in Morocco and Libya

- android/app/src/main/res/layout/nav_lanes.xml
|Before|After
|-|-|
|![Screenshot_20240105-130658](https://github.com/organicmaps/organicmaps/assets/87148630/f00598bf-3b4c-43b8-a985-3137a8090c17)|![Screenshot_20240105-132230](https://github.com/organicmaps/organicmaps/assets/87148630/fc2e8559-8f76-43a7-8bd3-aa19c069b19e)|
> Fix turns lanes in RTL

- data/categories.txt
- data/strings/types_strings.txt
Fixed arts center and lottery tickets strings in PT and PT-BR.
Signed-off-by: Matheus Gomes <86851490+matheusgomesms@users.noreply.github.com>
> [strings] Fixed PT translation

- data/strings/sound.txt
- data/strings/strings.txt
I added missing Japanese translations and updated wrong or confusingly-worded ones. 
also edited some source English ones: "Parkings" is not a word, as "parking" is an uncountable noun.
> [strings] update Japanese translations and edit some English ones for grammar

- map/bookmark_helpers.cpp
> [bookmarks] Display swim icon for leisure-water_park

- routing/routing_tests/turns_tts_text_tests.cpp
- routing/turns_notification_manager.cpp
- routing/turns_notification_manager.hpp
- routing/turns_sound_settings.cpp
- routing/turns_tts_text.cpp
Please, review my rounding logic. Probably, you know how other navigators make it better.
> [turns] More precise small distance notifications.

- android/app/src/main/java/app/organicmaps/car/screens/NavigationScreen.java
> [android-auto] NavigationScreen loading fix.

- android/app/src/main/cpp/app/organicmaps/SearchEngine.cpp
- iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
* Fixes https://github.com/organicmaps/organicmaps/issues/7197
> [search] Fix crash when searching coordinates

- routing/index_graph_loader.cpp
- routing/route.cpp
- routing/route.hpp
Closes https://github.com/organicmaps/organicmaps/issues/7093
> [routing] Fixed invalid camera.

- android/app/build.gradle
- android/build.gradle
Also, update a few other libraries.
> [android] Update AGP to 8.2.1

- platform/utm_mgrs_utils.cpp
- platform/utm_mgrs_utils.hpp
- search/search_tests/utm_mgrs_coords_match_test.cpp
- search/utm_mgrs_coords_match.cpp
> Fixed memory corruption with UTM coordinates search

- search/processor.cpp
now search both from user position (when valid) and viewport position.
> [Search] search plus code from viewport and user location

- android/app/src/main/java/app/organicmaps/search/SearchFragment.java
- android/app/src/main/java/app/organicmaps/search/SearchResult.java
Closes https://github.com/organicmaps/organicmaps/issues/7211
@Jean-BaptisteC @dvdmrtnz Please, take a look at todo.
> [android] Fixed localized Feature type.

- platform/qt_location_service.hpp
https://github.com/organicmaps/organicmaps/actions/runs/7762370161/job/21172687629#step:9:497
> [linux] Fix build error caused by missing pragma

- generator/feature_segments_checker/feature_segments_checker.cpp
- generator/routing_index_generator.cpp
- routing/features_road_graph.cpp
- routing/features_road_graph.hpp
- routing/geometry.cpp
- routing/routing_benchmarks/helpers.hpp
- routing_common/bicycle_model.cpp
- routing_common/bicycle_model.hpp
- routing_common/car_model.cpp
- routing_common/car_model.hpp
- routing_common/pedestrian_model.cpp
- routing_common/pedestrian_model.hpp
- routing_common/routing_common_tests/bicycle_model_test.cpp
- routing_common/routing_common_tests/vehicle_model_test.cpp
- routing_common/vehicle_model.cpp
- routing_common/vehicle_model.hpp
- track_analyzing/track_analyzer/cmd_table.cpp
- track_analyzing/track_matcher.cpp
- traffic/traffic_info.cpp
Closes https://github.com/organicmaps/organicmaps/issues/3929
Closes https://github.com/organicmaps/organicmaps/issues/7257
Can check after new data generation.
> [generator][routing] Ignore "highway=construction".

- android/app/src/main/res/layout/bottom_sheet_handle.xml
- android/app/src/main/res/layout/current_location_marker.xml
- android/app/src/main/res/layout/edit_bookmark_common.xml
- android/app/src/main/res/layout/fragment_bookmark_list.xml
- android/app/src/main/res/layout/fragment_edit_bookmark.xml
- android/app/src/main/res/layout/fragment_edit_description.xml
- android/app/src/main/res/layout/fragment_phone.xml
- android/app/src/main/res/layout/fragment_timetable_advanced.xml
Continue works started here  #7267
Tested in Pixel 6 - Android 14 with max text size and max UI size
> [android] Remove RelativeLayout in layouts

- packaging/app.organicmaps.desktop.metainfo.xml
error:
[appstream-missing-developer-name](
https://docs.flathub.org/docs/for-app-authors/linter/#appstream-missing-developer-name):
Added the `developer_name` name tag.
warning:
[appstream-summary-too-long](
https://docs.flathub.org/docs/for-app-authors/linter/#appstream-summary-too-long):
Shortened the summary to less than 35 characters.
> [packaging] Fix flathub linter findings

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/java/app/organicmaps/ChartController.java
- android/app/src/main/java/app/organicmaps/Framework.java
- android/app/src/main/java/app/organicmaps/util/Distance.java
- android/app/src/main/java/app/organicmaps/widget/placepage/AxisValueFormatter.java
- android/app/src/main/java/app/organicmaps/widget/placepage/ElevationProfileViewRenderer.java
- android/app/src/main/java/app/organicmaps/widget/placepage/FloatingMarkerView.java
- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
- indexer/map_object.cpp
- iphone/Maps/Core/Routing/MWMRouter.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
- platform/distance.cpp
- platform/distance.hpp
- platform/platform_tests/distance_tests.cpp
How is better?
Android:
▼50 m
iOS:
▲ -50 m
> Fixed negative altitude display.

- map/framework.cpp
fixes https://github.com/organicmaps/organicmaps/issues/7051
> [core] disable ?gl on ios

- android/app/src/main/java/app/organicmaps/bookmarks/data/Metadata.java
- generator/osm2meta.cpp
- generator/osm2meta.hpp
- indexer/feature_meta.cpp
- indexer/feature_meta.hpp
- indexer/map_object.cpp
- indexer/map_object.hpp
- map/place_page_info.cpp
- map/place_page_info.hpp
MWM with local_ref generated: https://drive.proton.me/urls/Z8DNCTPSY8#I02Sto5fzfdp
to-do:
use the formatted title in search results
use the formatted title in default bookmark title
>  Display local ref for transport stops in place page

- android/app/src/main/cpp/app/organicmaps/UserMarkHelper.cpp
- android/app/src/main/java/app/organicmaps/bookmarks/data/MapObject.java
- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.h
- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.mm
- iphone/Maps/UI/PlacePage/Components/PlacePagePreviewViewController.swift
- map/framework.cpp
- map/place_page_info.cpp
- map/place_page_info.hpp
It does not have any sense now, because popularity calculation is experimental at this moment.
> [iOS][android] Comment out popularity label.

- data/strings/types_strings.txt
Follow up #7052, and additional translations and fixes.
Signed-off-by: Matheus Gomes [86851490+matheusgomesms@users.noreply.github.com](mailto:86851490+matheusgomesms@users.noreply.github.com)
> [strings] Fixed PT types_strings

- android/app/src/main/res/values-es-rMX/strings.xml
- android/app/src/main/res/values-es/strings.xml
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/es.lproj/Localizable.strings
Improve spanish wheelchair translations
> [strings] Improve spanish wheelchair translations

- indexer/feature_data.cpp
- map/place_page_info.cpp
Closes https://github.com/organicmaps/organicmaps/issues/6652
> Fixed PP and classifier types prio.

- base/base_tests/CMakeLists.txt
- base/base_tests/message_test.cpp
- base/internal/message.hpp
Follow up https://github.com/organicmaps/organicmaps/pull/7316
> Don't use DebugPrint like sequence for char[].

- android/app/src/main/res/values-iw/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/he.lproj/Localizable.strings
This is fix to the https://github.com/organicmaps/organicmaps/pull/7371
Thanks to @NeatNit !
> [strings] Fix hebrew translation for "Appearance" in settings

- data/strings/strings.txt
Simple Portuguese strings adjustments.
> [strings] Update PT strings opening hours editor

- android/app/src/main/res/layout-land/about.xml
- android/app/src/main/res/values-land/dimens.xml
- android/app/src/main/res/values-sw720dp-land/dimens.xml
- android/app/src/main/res/values/dimens.xml
Fixes #7421 
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/fb34e142-b782-4f0c-9295-227ea77c1b5c" height=150 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/23a9eb38-ed6c-4628-a10d-92dbc6560801" height=150 />|
> [android] Fixed text overlapping in about screen

- android/app/src/main/java/app/organicmaps/DownloadResourcesLegacyActivity.java
- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/SplashActivity.java
- android/app/src/main/java/app/organicmaps/base/BaseMwmFragmentActivity.java
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarksSharingHelper.java
- android/app/src/main/java/app/organicmaps/bookmarks/ChooseBookmarkCategoryAdapter.java
- android/app/src/main/java/app/organicmaps/downloader/BottomPanel.java
- android/app/src/main/java/app/organicmaps/downloader/DownloaderAdapter.java
- android/app/src/main/java/app/organicmaps/downloader/MapManager.java
- android/app/src/main/java/app/organicmaps/downloader/OnmapDownloader.java
- android/app/src/main/java/app/organicmaps/editor/EditorFragment.java
- android/app/src/main/java/app/organicmaps/editor/LanguagesFragment.java
- android/app/src/main/java/app/organicmaps/editor/MultilanguageAdapter.java
- android/app/src/main/java/app/organicmaps/editor/SimpleTimetableAdapter.java
- android/app/src/main/java/app/organicmaps/editor/StreetAdapter.java
- android/app/src/main/java/app/organicmaps/routing/BaseRoutingErrorDialogFragment.java
- android/app/src/main/java/app/organicmaps/routing/RoutingPlanInplaceController.java
- android/app/src/main/java/app/organicmaps/search/SearchHistoryAdapter.java
- android/app/src/main/java/app/organicmaps/util/HttpClient.java
- android/app/src/main/java/app/organicmaps/widget/placepage/BookmarkColorDialogFragment.java
- android/app/src/main/java/app/organicmaps/widget/placepage/DirectionFragment.java
This PR improve code style and reduce Android Studio warnings:
- Removed unused imports
- Replaced new object with lambda
- Use [try with resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html)
> [android] Fix Android Studio warnings

- generator/generator_tool/generator_tool.cpp
- generator/popular_places_section_builder.cpp
- generator/popular_places_section_builder.hpp
Closes https://github.com/organicmaps/organicmaps/issues/7415
> [generator] Removed popularity checks.

- android/app/src/main/java/app/organicmaps/widget/placepage/PlaceDescriptionActivity.java
- android/app/src/main/java/app/organicmaps/widget/placepage/sections/PlacePageWikipediaFragment.java
fixes https://github.com/organicmaps/organicmaps/issues/5783 for android
before, after
> [android] poi name in wikipedia page header

- coding/coding_tests/zip_creator_test.cpp
- coding/zip_creator.cpp
- coding/zip_creator.hpp
- data/gpx_test_data/Üφήが1.gpx
- data/gpx_test_data/Üφήが2.gpx
- data/kml_test_data/kmz_index.kml
- map/bookmark_manager.cpp
- map/map_tests/bookmarks_test.cpp
@biodranik I tried to implement remaining c++ part of the code for #995, could you please have a look. Once core part is done I'll try to add Android changes.
Also I need some help with tests - I tried to add a new test ExportAll but debugger is not stopped in handler inner code where I had a plan to put some checks (but export code is called). I suspect it is because of threading in PrepareFileForSharing - could you please advice, how such code should be tested - I was not able to see something similar.
> [bookmarks] Add code to export multiple files

- android/app/src/main/res/values/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/en-GB.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/en.lproj/Localizable.strings
Fix the "osm_presentation" string for English.
> [strings] Fix osm_presentation string for english

- data/strings/strings.txt
- data/strings/types_strings.txt
Fixed some Slovak translations and added some missing ones.
> Updated Slovak translations

- android/app/src/main/res/values-es/strings.xml
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/es.lproj/Localizable.strings
More updates of style translations in Spanish, following comments raised by other users in the (already merged) [PR 7474](https://github.com/organicmaps/organicmaps/pull/7474).
Please review @organicmaps/translations-es & @organicmaps/translations-es-mx users !!!
> [strings] Update of Spanish style translations

- data/categories.txt
Signed-off-by: Muralito <muralito@montevideo.com.uy>
> Update categories.txt (add spanish translations)

- android/app/src/main/res/values-be/strings.xml
- android/app/src/main/res/values-bg/strings.xml
- android/app/src/main/res/values-ru/strings.xml
- android/app/src/main/res/values-uk/strings.xml
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/be.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/bg.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/ru.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/uk.lproj/Localizable.strings
Basically `shop-doityourself` is a bigger and more universal version of `shop-hardware`.
> [strings] Fix hardware and DIY shops translations 

- android/app/src/main/res/raw/keep.xml
- Fixes https://github.com/organicmaps/organicmaps/issues/7617
> [android] Keep all string resources from R8 shrinking

- data/categories.txt
- data/strings/strings.txt
- data/strings/types_strings.txt
Please add the regenerate commit, I encountered some errors. Thanks!
> [strings] add all missing Hindi strings in editor and some error messages

- .github/workflows/ios-check.yaml
Need to test if it really caches/speeds up builds. @AndrewShkrob can you please help?
https://github.com/irgaly/xcode-cache
> [github] Fixed failed iOS action due to removed repo dependency

- android/app/src/main/java/app/organicmaps/car/screens/PlaceScreen.java
Closes: https://github.com/organicmaps/organicmaps/issues/7457
> [android-auto] Auto-start navigation

- data/editor.config
- editor/editor_tests/config_loader_test.cpp
Added some missing types from the list in #6796 
Added some comments and removed unused "preferred_types" section.
```
shop-agrarian
shop-appliance
shop-auction
shop-bathroom_furnishing
shop-bed
shop-boutique
shop-cannabis
shop-carpet
shop-collector
shop-curtain
shop-fashion_accessories
shop-gas
shop-herbalist
shop-hifi
shop-lottery
shop-medical_supply
shop-money_lender
shop-motorcycle_repair
shop-paint
shop-pet_grooming
shop-storage_rental
shop-tea
shop-trade
craft-caterer
craft-grinding_mill
craft-key_cutter
craft-locksmith
amenity-compressed_air
amenity-food_court
amenity-bbq
amenity-language_school
amenity-money_transfer
amenity-stripclub
amenity-gambling
amenity-vehicle_inspection
man_made-cairn
man_made-lighthouse
man_made-mast
man_made-survey_point
man_made-windmill
```
Closes …
> [editor] Add some missing types 

- android/app/build.gradle
- android/build.gradle
A few bugs were fixed in AGP: https://developer.android.com/studio/releases/fixed-bugs/studio/2023.2.1
> [android] Update AGP to 8.3.1

- .github/workflows/appstream-check.yaml
As requested in https://github.com/organicmaps/organicmaps/pull/7527#issuecomment-1987144789
> [github/workflows]: Use the linter of flathub

- drape/support_manager.cpp
> [android] Use GL on Samsung A50 to fix subway layer hanging

- android/app/src/main/res/values-de/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
The German translation has been reviewed, and many terms have been asked to the DACH (German speaking) community. 
A brief review from another German speaker is requested and appreciated.
> All German translations in strings have been reviewed

- drape/CMakeLists.txt
- drape/drape_tests/glyph_mng_tests.cpp
- drape/font_texture.cpp
- drape/font_texture.hpp
- drape/glyph.hpp
- drape/glyph_generator.cpp
- drape/glyph_generator.hpp
- drape/glyph_manager.cpp
- drape/glyph_manager.hpp
Also did small refactoring in a GlyphManager.
Based on #7855 that should be merged first.
> [drape] Moved Glyph out of GlyphManager

- data/strings/strings.txt
> Shorten English recent_track_help_text

- android/app/src/main/res/values-pt-rBR/strings.xml
- android/app/src/main/res/values-pt/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/pt-BR.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/pt.lproj/Localizable.strings
As explained in #7568, I've wrongly changed the PT strings in #7425. Now I reverted these small changes, until we find a proper solution for #7568.
> Revert part of #7425

- shaders/gl_shaders_preprocessor.py
This is a fix for annoying shaders library relinking/rebuilding in C++, Android and XCode. @kirylkaveryn can you please confirm that Xcode now launches the already built project immediately, without a rebuild?
> [drape] Avoid unnecessary shaders rebuild when no modifications

- search/processor.cpp
The idea is to test it in the release mode on real devices.
Related to https://github.com/organicmaps/organicmaps/issues/7886
> Experimental ?wiki and ?description search

- iphone/Maps/Classes/Components/MWMNavigationController.m
This PF fixes the issue caused by https://github.com/organicmaps/organicmaps/pull/7918#pullrequestreview-2004249129 when a theme isn't changed automatically when Auto is selected.
> [ios] fix: user interface auto theme changing issue

- data/editor.config
> [editor] allow editing some values for railway-station

- drape/support_manager.cpp
> Unfortunately, instead of map, I only get a black screen with controls buttons.
`?gl` has confirmed to fix the issue.
> [android] Disable Vulkan for another reported Adreno 506 Xiaomi Redmi Note 5

- map/routing_manager.cpp
- map/routing_mark.hpp
Change name to m_replaceWithMyPositionAfterRestart in accordance to what was suggested in my previous PR
> [routing] Update m_replaceWithMyPosition variable name

- drape/support_manager.cpp
- drape/support_manager.hpp
> [drape] Minor constexpr warning fix

- generator/generator_tests_support/test_feature.cpp
- generator/generator_tests_support/test_feature.hpp
- search/features_layer_matcher.hpp
- search/geocoder.cpp
- search/ranking_info.cpp
- search/search_integration_tests/processor_test.cpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
Also updated category ranking policy.
> [search] Fixed Place-HN matching bug.

- data/strings/strings.txt
- data/strings/types_strings.txt
Fixed several Portuguese and Brazilian Portuguese strings, especially related to recent PRs. Removed lots of duplicated PT and PT-BR strings, which should not affect the strings regen at all.
> [strings] Fixed PT translations

- android/app/src/main/java/app/organicmaps/MwmActivity.java
Apply suggestion from code review in PR https://github.com/organicmaps/organicmaps/pull/8073#discussion_r1589942194
> [android] Apply code suggestion

- coding/writer.hpp
- data/gpx_test_data/export_test.gpx
- data/gpx_test_data/export_test_empty.gpx
- kml/kml_tests/gpx_tests.cpp
- kml/serdes.cpp
- kml/serdes.hpp
- kml/serdes_common.cpp
- kml/serdes_common.hpp
- kml/serdes_gpx.cpp
- kml/serdes_gpx.hpp
- map/bookmark_helpers.cpp
Draft PR to gather early feedback. 
Initial work for https://github.com/organicmaps/organicmaps/issues/5271 - I want to add it to core first, UI and bridge methods later.
WDYT?
TODO:
> [gpx] Add gpx export to core

- coding/coding_tests/file_data_test.cpp
- coding/file_reader.cpp
- coding/internal/file64_api.hpp
- coding/internal/file_data.cpp
- coding/internal/file_data.hpp
- coding/sha1.cpp
- coding/zip_creator.cpp
- generator/generator_tests/speed_cameras_test.cpp
- platform/platform_tests/platform_test.cpp
> Minor refactoring and warning fix for gcc

- indexer/ftypes_matcher.cpp
> Fixed missing address for fitness centers

- android/app/src/main/res/values-en-rGB/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/en-GB.lproj/Localizable.strings
> [strings] use 'Postcode' instead of 'Postal Code' for en-GB 

- map/framework.cpp
- qt/mainwindow.cpp
Closes https://github.com/organicmaps/organicmaps/issues/8202
> [desktop] Disable traffic switch and TrafficManager initialization.

- platform/platform_android.cpp
- platform/platform_linux.cpp
All fonts are printed anyway at the end
> Removed unnecessary system font logs

- data/strings/strings.txt
> Quick fix PT-BR string

- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
Closes https://github.com/organicmaps/organicmaps/issues/8184
> [ios] Fix: do not hide the side buttons during the new place adding

- .github/workflows/android-check-metadata.yaml
- .github/workflows/appstream-check.yaml
- .github/workflows/cleanup_caches.yml
- .github/workflows/ios-check-metadata.yaml
1st step of CI speed improvements, requested by @biodranik in https://github.com/organicmaps/organicmaps/pull/8255#pullrequestreview-2075205019.
> [github] Use sparse checkout & shallow clone where it's reasonable

- generator/generator_tests/metadata_parser_test.cpp
- indexer/feature_meta.cpp
> Fixed non-working Wikipedia links with ? character in a title

- packaging/app.organicmaps.desktop.metainfo.xml
Preparing for a new flatpak release. Kindly let me know if packaging steps have changed since last release or there are any other concerns. Thanks!
> Add 2024.05.11 release notes to .metainfo.xml

- indexer/map_object.cpp
- indexer/map_object.hpp
- map/place_page_info.cpp
This reverts commit 10b01c93d82fd2950437c59c4c62dce33b273a65.
see discussion at https://github.com/organicmaps/organicmaps/pull/8238
> Revert "[placepage] Show all types"

- editor/editor_tests/ui2oh_test.cpp
- editor/ui2oh.cpp
This reverts commit ff703e83d60a5f9c3cee9b97919397c9b08f6e2d.
Reopens #1612
> Revert "[editor] Fix parsing of 'off' opening hours (#7652)"

- editor/editor_tests/ui2oh_test.cpp
- editor/ui2oh.cpp
- iphone/Maps/UI/Editor/OpeningHours/MWMOpeningHoursModel.mm
Closes https://github.com/organicmaps/organicmaps/issues/8198 
Fixes #1612
This PR includes the previously reverted #7652
> [ios] Fix opening hours simple mode

- iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
Closes https://github.com/orgs/organicmaps/projects/6/views/3?filterQuery=assignee:kirylkaveryn&pane=issue&itemId=61445222
Closes https://github.com/organicmaps/organicmaps/issues/4800
In this PR the deeplink handling flow was changed by splitting into two main cases:
1. handle imported file
2. handle the regular deeplink
The file importing process shouldn't be delayed to the `viewDidAppear` (as done for the regular deeplink that requires the map initialization) because we can lose the permission to take control over the file (when the file is shared from the Files app).
Also, the `fileCoordinator` is used to take control over the provided file ([recommended by Apple](https://developer.apple.com/documentation/foundation/nsfilecoordinator/1407416-coordinate)).
The regular deeplinks …
> [ios] Fix the issue importing a file from the Files app during the cold start

- android/app/src/main/res/values-uk/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/pt-BR.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/pt.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/ru.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/uk.lproj/Localizable.strings
Fixed PT and PT-BR strings after #7641.
> [strings] Fixed iCloud

- drape/drape_tests/CMakeLists.txt
- drape/drape_tests/harfbuzz_shaping_test.cpp
- drape/harfbuzz_shaping.cpp
- drape/harfbuzz_shaping.hpp
This is a pre-requisite for https://github.com/organicmaps/organicmaps/issues/4281
> [drape] Fixed text segmentation and added a test

- drape/glyph_manager.cpp
Rendered fonts look exactly the same after this change.
This is a pre-requisite for https://github.com/organicmaps/organicmaps/issues/4281
> [drape] Remove redundant Freetype calls

- iphone/Maps/Categories/UIKitCategories.h
- iphone/Maps/Categories/UIKitCategories.m
- iphone/Maps/UI/BottomMenu/Menu/BottomMenuInteractor.swift
- iphone/Maps/UI/Help/AboutController/AboutController.swift
- iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm
Closes https://github.com/organicmaps/organicmaps/issues/6264
Some social media links (as facebook) still cant be opened... it seems that it is the FB problem. Other apps open link correctly.
https://github.com/organicmaps/organicmaps/assets/79797627/c6ab98cf-6e53-4442-849a-59af80f81073
> [ios] Open social media links in installed applications from the Place Page

- data/strings/strings.txt
Sources: 
- https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$XPKT4hTHXIb2uZGJBJcfH00lhtqx-ckpKYOOo3ri63g?via=matrix.org&via=grin.hu&via=beeper.com
- https://matrix.to/#/!ZbAzRWrkAuUXOsukYa:grin.hu/$oNatZ9ywrWBAjrDHdGr1vueuCwhlgAqaxapSjSOIumY?via=grin.hu&via=matrix.org&via=hackliberty.org
> Updating hu from community feedback

- android/app/src/main/res/values-zh-rTW/strings.xml
- android/app/src/main/res/values-zh/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/zh-Hans.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/zh-Hant.lproj/Localizable.strings
Please help with the Chinese translation review.
> [strings] Replaced Chinese translation of OM with English letters

- docs/TRANSLATIONS.md
Reviewing translations in pull requests is very helpful. Let's make it easier to discover.
> [docs] Update TRANSLATIONS.md

- android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkManager.java
Fixes #8543
@strump or @Jean-BaptisteC can you please test this fix?
> [android] Fix GPX import from WhatsApp

- data/strings/strings.txt
This makes the Dutch translation more clear, more consistent and more action-focused.
I am a native Dutch speaker and checked the whole strings.txt file. Please review.
> [strings] Improve Dutch (NL) translations

- data/categories.txt
- search/geocoder.cpp
- search/pre_ranker.hpp
- search/search_integration_tests/processor_test.cpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
Closes https://github.com/organicmaps/organicmaps/issues/8527
Closes https://github.com/organicmaps/organicmaps/issues/8521
> [search] Fixed early MWMs processing break.

- search/geocoder.cpp
- search/search_integration_tests/processor_test.cpp
Closes https://github.com/organicmaps/organicmaps/issues/8411
> [search] Fixed 'name is a number' POI search.

- generator/feature_builder.cpp
- generator/osm2meta.cpp
- generator/search_index_builder.cpp
- indexer/ftypes_matcher.cpp
- indexer/ftypes_matcher.hpp
Closes https://github.com/organicmaps/organicmaps/issues/8430
> [generator] Combine post office, post box, parcel locker into IsPostPoiChecker selector.

- 3party/harfbuzz/CMakeLists.txt
- drape/vulkan/vulkan_layers.cpp
- drape/vulkan/vulkan_utils.hpp
- qt/qt_common/map_widget.cpp
Some fixes from the #8473 branch, including https://github.com/organicmaps/organicmaps/issues/7838#issuecomment-2183571066 comment.
> Minor fixes from the Harfbuzz branch

- generator/generator_tests/metadata_parser_test.cpp
- generator/osm2meta.cpp
Also slightly reduces the size of map files
> [generator] Strip the last slash from URLs after the hostname to beautify them

- android/app/src/main/res/values-zh-rTW/strings.xml
- android/app/src/main/res/values-zh/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/zh-Hans.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/zh-Hant.lproj/Localizable.strings
> [strings] Updated Chinese "avoid..." translations

- data/strings/types_strings.txt
Added Arabic translations in Update types_strings.txt
> Added Arabic translations in Update types_strings.txt

- android/app/src/main/res/values-en-rGB/strings.xml
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/en-GB.lproj/Localizable.strings
> Replaced en-GB Ironmongers with Hardware Store

- data/strings/strings.txt
This is the start of the Maltese translations for Organic Maps. 
Thought it would be better to create multiple parts so that these can get vetted quicker due to the large amount of translations needed.
> [strings] MT (Maltese) translations part 1

- generator/generator_integration_tests/features_tests.cpp
- generator/generator_tool/generator_tool.cpp
- generator/osm2meta.cpp
- generator/popular_places_section_builder.cpp
- indexer/ftypes_matcher.cpp
- indexer/ftypes_matcher.hpp
- indexer/indexer_tests/checker_test.cpp
- indexer/indexer_tests/editable_map_object_test.cpp
- search/features_layer_matcher.hpp
- search/intersection_result.cpp
- search/model.cpp
- search/model.hpp
- search/search_integration_tests/smoke_test.cpp
- search/types_skipper.hpp
Merge after the upcoming release.
> Unify IsPoiChecker and use it for 'operator'.

- android/app/src/fdroid/play/listings/tr-TR/full-description.txt
Current translation quality is really awful. Please don't accept Turkish translations from Weblate.
> Fixed Turkish Full Description

- android/app/src/fdroid/play/listings/tr-TR/short-description.txt
- data/strings/strings.txt
> [strings] Improved and Fixed Turkish Translation

- platform/remote_file.cpp
small fix to follow redirects, needed for downloading profile picture for OSM account page
> [platform] make RemoteFile handle redirects when told to

- NOTICE
- docs/CPP_STYLE.md
- docs/INSTALL.md
- docs/STYLES.md
- docs/TRANSLATIONS.md
This PR:
- Fix broken links
- Update year copyright in notice
> [doc] Update documentations

- iphone/metadata/ar-SA/description.txt
Translate the AppStore Arabic description in Update description.txt
> Translate the AppStore Arabic description in Update description.txt

- drape/glyph_manager.cpp
This system font (found and used by OM on the start) reports too big line height (normal bbox.yMax, and too big negative bbox.yMin).
The previous implementation could wrongly mix vertical advance with bbox.yMin calculation that leads to way too high line height (e.g. 55px when 22px have been specified). This caused wrongly layouted text in some cases.
Fixes #8708
> [drape] Fixed wrong line height for NotoSansCJK on Android

- data/categories.txt
adds "Tip" and "Dump" to categories.txt, as these are common terms for a recycling centre
> [categories] alt names for "recycling centre"

- packaging/app.organicmaps.desktop.metainfo.xml
As requested [here](https://github.com/organicmaps/organicmaps/pull/8783#pullrequestreview-2203567212).
> Cherry-pick appstream metadata changes from master

- android/app/src/main/java/app/organicmaps/DownloadResourcesLegacyActivity.java
- android/app/src/main/res/values/themes.xml
First impressions count 😉
before/after
> [Android] fix bars on world download page

- android/app/src/main/java/app/organicmaps/SplashActivity.java
Allows people to send logs about the fatal errors, hopefully will help solve the case of the phantom MicroSD card 🕵️‍♂️
> [Android] button for bug report on fatal error

- android/app/src/main/java/app/organicmaps/car/screens/PlaceScreen.java
> [android-auto] Fix route building

- android/app/src/main/java/app/organicmaps/SplashActivity.java
utils.sendBugReport refactoring added mShareLauncher as a parameter. Because the two PRs were created at the same time, my code didn't have it. Now fixed :) 
also fixed indentation
> [Android] make sendbugreport use mShareLauncher

- docs/INSTALL.md
As a consequence of https://github.com/organicmaps/organicmaps/pull/8177#issuecomment-2116304430
> [docs] Document new minimum Qt version 6.4

- android/app/src/main/java/app/organicmaps/util/SharingUtils.java
- map/bookmark_manager.cpp
> [android] Fixed invalid mime types for shared gpx and kmz

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/cpp/app/organicmaps/Framework.hpp
- android/app/src/main/java/app/organicmaps/Framework.java
- android/app/src/main/java/app/organicmaps/car/screens/PlaceScreen.java
- map/framework.cpp
- map/framework.hpp
Better fix for https://github.com/organicmaps/organicmaps/pull/8789
Kudos to @strump
> [android-auto] New map deselection api

- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.xib
- iphone/Maps/Core/Theme/Extensions/UIFont+monospaced.swift
- iphone/Maps/Maps.xcodeproj/project.pbxproj
Fix issue #8519
https://github.com/user-attachments/assets/c3b99f6a-c137-454c-8faa-32e9ee6abeab
> [ios] Use fixed size font when showing download progress on a map

- iphone/Maps/Core/iCloud/SynchronizationFileWriter.swift
This PR fixes the updating the file content by the `iCloud manager` by using the `safe replace` approach (the same way as c++ does) using the native [FileManager's method](https://developer.apple.com/documentation/foundation/filemanager/1412432-replaceitem). 
This approach will preserve both the source file _metadata and content_ while replacing and don't force updating the file's `lastModified` date manually.
> [ios] iCloud sync - update the file's content using the `safe replace`

- iphone/Maps/Core/iCloud/CloudStorageManager.swift
- iphone/Maps/Core/iCloud/DefaultLocalDirectoryMonitor.swift
- iphone/Maps/Core/iCloud/MetadataItem.swift
- iphone/Maps/Core/iCloud/SynchronizationFileWriter.swift
- iphone/Maps/Core/iCloud/SynchronizationStateManager.swift
- iphone/Maps/Core/iCloud/iCloudDocumentsDirectoryMonitor.swift
> [ios] Add more logs to the iCloud sync process

- data/strings/strings.txt
No. 1 https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$sm2Jxq2C3xQQILdf_pGovFW5TBHlS8whg0rIWRjCwiI?via=matrix.org&via=grin.hu&via=beeper.com 
No. 2 https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$UZtI2M0-Exv0DsPWYnSjeBW3ZDh0dWdQkM5nzWthxs0?via=matrix.org&via=grin.hu&via=beeper.com 
No. 3 https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$afurYF52XwVynyO0cWaoGsEaum3DLGrLhyFOYmZoJgU?via=matrix.org&via=grin.hu&via=beeper.com 
No. 4 https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$GLz2K4YHKMQ9oq0JC1x417W7cA6qRgT88NtSkvQOXzQ?via=matrix.org&via=grin.hu&via=beeper.com 
No. 5 https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$leLIAV_PWGiMxRVkPvDaOnNDWUTnHvHiN38Vyfk3OHY?via=matrix.org&via=grin.hu&via=beeper.com
> Community feedback for :hungary: 

- tools/unix/generate_localizations.sh
Before this fix, it worked only if run from the repo root
> [tools] generate_localizations.sh can be run from any directory

- android/app/src/main/java/app/organicmaps/car/util/LanesDrawable.java
- android/app/src/main/java/app/organicmaps/routing/LanesAdapter.java
- android/app/src/main/res/layout/nav_single_lane.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/themes-attrs.xml
- android/app/src/main/res/values/themes-base.xml
> [Android] better colour for inactive lane icons

- android/app/src/main/java/app/organicmaps/maplayer/LayersButton.java
- android/app/src/main/java/app/organicmaps/maplayer/MapButtonsController.java
- android/app/src/main/java/app/organicmaps/maplayer/Mode.java
- android/app/src/main/java/app/organicmaps/maplayer/ToggleMapLayerFragment.java
- android/app/src/main/java/app/organicmaps/maplayer/isolines/IsolinesManager.java
- android/app/src/main/java/app/organicmaps/maplayer/subway/SubwayManager.java
- android/app/src/main/res/color/accent_color_selector.xml
- android/app/src/main/res/color/accent_color_selector_night.xml
- android/app/src/main/res/layout/map_buttons_layers.xml
- android/app/src/main/res/values/attrs.xml
https://github.com/user-attachments/assets/b4ca6cde-431f-488e-b25c-d3a2aabe63e8
Closes https://github.com/organicmaps/organicmaps/pull/8821
Workarounds https://github.com/organicmaps/organicmaps/issues/3508
> [Android] Highlight layers button when it is activated

- data/strings/strings.txt
Source: https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$iUnAL7bAh3GtvIjOJ9_bY3CSQkSvqwp9dWLbd1jTiHA?via=matrix.org&via=grin.hu&via=beeper.com
> Update search strings in hu lang

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/java/app/organicmaps/car/util/RoutingUtils.java
- android/app/src/main/java/app/organicmaps/routing/RoutingInfo.java
- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm
- iphone/Maps/Core/Framework/ProxyObjects/Routing/MWMRoutingManager.mm
- qt/draw_widget.cpp
- routing/following_info.hpp
- routing/route.cpp
- routing/route.hpp
- routing/routing_session.cpp
Current street replaced with next street
Next street replaced with next next street
> [android-auto] Fix turn directions

- android/app/src/main/java/app/organicmaps/util/SharingUtils.java
Fix issue https://github.com/organicmaps/organicmaps/issues/8806
> [android] Fix saving to Google Drive

- routing/turns_notification_manager.cpp
- routing/turns_sound_settings.hpp
> Pass NextStreet to TTS for pedestrians as well as "cars" (everyone else)

- data/strings/types_strings.txt
I told @MbTy1 about Organic Maps and about the recent call to action at #8854, and he actually decided to get to work on it! He has a bit of trouble dealing with git and GitHub which is why I'm making the PR for him.
I did not go through all the changes, but I did check a few random translations and they are great.
> Hebrew translations of type_strings.txt (not by me)

- data/faq.html
- tools/unix/refresh-embedded-faq.sh
Our intent in #8876 is to minimize duplicates between repos.
In this PR I updated `/data/faq.html` from `organicmaps/organicmaps.github.io` repo using:
```
curl -o data/faq.html https://organicmaps.app/faq/embedded-faq/
```
Let's not update embedded faq manually but only via `organicmaps/organicmaps.github.io` repo.
**How to test:** FAQ page withing mobile app should look the same after PR is merged.
One can build `faq.html` locally:
1. Clone https://github.com/organicmaps/organicmaps.github.io locally
2. Run `zola build`
3. Copy `organicmaps.github.io/public/faq/embedded-faq/index.html` into `organicmaps/data/faq.html`
> Updated embedded FAQ using organicmaps.app content

- routing/routing_integration_tests/cross_country_routing_tests.cpp
- routing/routing_integration_tests/route_test.cpp
- routing_common/car_model_coefs.hpp
- routing_common/routing_common_tests/vehicle_model_test.cpp
- routing_common/vehicle_model.cpp
- routing_common/vehicle_model.hpp
Will merge after integration tests update.
Closes #8823
Closes #8729
Closes #8541
> [routing] Highway factor fixes.

- kml/serdes_gpx.cpp
> [gpx] Correctly export modified bookmark name

- indexer/road_shields_parser.cpp
The Indian highway road network comprises of National Expressways (NE), National Highways (NH) and State Highways (SH). On OSM the relations are tagged with `network` = `in:ne`, `in:nh` and `in:sh` respectively. For the individual ways, they are tagged as `ref=NH44`, `ref=NE1` etc. Route numbers may contain numbers and letters. National Highways follow the same numbering scheme that US interstates follow, while National Expressways are just numbered 1-8. State Highways are numbered based on state preferences, but are usually just sequentially numbered, and may contain trailing alphabets.
This PR adds support for parsing the network values and the ref values, while also cleaning up any unexpected spaces or dashes (neither are present in Indian route numbers).
The shields are based on the …
> Add Indian route shields

- android/app/src/main/res/values-zh-rTW/strings.xml
- android/app/src/main/res/values-zh/strings.xml
- data/categories.txt
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/zh-Hans.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/zh-Hans.lproj/Localizable.stringsdict
- iphone/Maps/LocalizedStrings/zh-Hant.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/zh-Hant.lproj/Localizable.stringsdict
Thanks to @felixng1988 !
@dwaynebailey this workflow with editing a large text file works for some contributors.
> Large Chinese translations update from Felix

- iphone/Maps/Core/Location/MWMLocationManager.mm
The `LocationManager` updates the framework location quite complicated. On every location update the `LocationManager` sets the `frameworkUpdateMode` property. The setter of this property calls `updateFrameworkInfo` and passes the update to the framework. A quick test revealed that calling the framework directly without going over the property also works. Removing the `frameworkUpdateMode` property and the `updateFrmeworkInfo` method makes the code clearer and easier to read.
> [ios] Remove updateFrameworkInfo from LocationManager

- android/app/src/main/java/app/organicmaps/widget/menu/NavMenu.java
> [Android] Fixed always red speedometer in navigation mode

- android/app/src/main/res/layout/item_bookmark_button.xml
- android/app/src/main/res/layout/item_bookmark_category.xml
Something simpler. ;)  Fixes #8600 
Original:
Fixed:
Fixed (normal fonts):
> [android] size vertically based on children

- map/framework.cpp
Fixes #8996
This is a regression that should go into a hotfix.
@strump can you please re-test if it properly works in the original case that you fixed in #8687 ?
> Fixed wrongly selected bookmarks instead of search results

- data/countries.txt
- routing/routing_integration_tests/route_test.cpp
- routing/routing_integration_tests/turn_test.cpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
Merge after https://github.com/organicmaps/organicmaps/pull/8864
> [planet] New data from 240810.

- tools/python/google_maps_bookmarks.py
This script converts a CSV file exported from Google Takeout to a KML file. A user can import this KML file to Organic Maps to transfer saved places in Google Maps to Organic Maps bookmarks. The script requires an API key because it needs to look up the coordinates from the Google Places API.
See https://github.com/orgs/organicmaps/discussions/928
> [bookmarks] Script to convert Google Maps Places to KML

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/cpp/app/organicmaps/Framework.hpp
- android/app/src/main/java/app/organicmaps/Framework.java
- drape_frontend/drape_engine.cpp
- drape_frontend/drape_engine.hpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/message_subclasses.hpp
- iphone/Maps/Categories/MWMMapViewControlsManager+AddPlace.h
- iphone/Maps/Classes/Components/MWMAddPlaceNavigationBar.h
- iphone/Maps/Classes/Components/MWMAddPlaceNavigationBar.mm
- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
- iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm
- map/framework.cpp
- map/framework.hpp
- qt/draw_widget.cpp
Related https://github.com/organicmaps/organicmaps/pull/9002
It makes the meaning of passed parameters more obvious.
> Refactored optional position parameter passing

- data/strings/strings.txt
Update basque (eu) translation
> Update Basque translation in strings.txt

- android/app/src/main/res/values-iw/strings.xml
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/he.lproj/Localizable.strings
> Hebrew translations

- iphone/Maps/Core/iCloud/SynchronizationFileWriter.swift
Closes https://github.com/organicmaps/organicmaps/issues/9020
When the file doesn't exist in the iCloud directory and the fileManager attempts to move this file into the trash the exception will be thrown and the sync will be stopped. 
This issue was fixed by the additional file existence check before the trashing.
> [ios] Fix the icloud trashing bug

- android/app/src/main/res/values-zh-rTW/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/zh-Hant.lproj/Localizable.strings
@felixng1988 Please take a look
Thanks to @Sylvia0476
> [strings] Updated zh-Hant from Edison Lu

- drape_frontend/gps_track_renderer.cpp
- iphone/Maps/UI/EditBookmark/legacy_bookmark_colors.h
- kml/types.cpp
- kml/types.hpp
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/framework.cpp
- map/framework.hpp
- map/gps_track.cpp
- map/gps_track.hpp
- map/gps_tracker.cpp
- map/gps_tracker.hpp
This is the cpp part of the https://github.com/organicmaps/organicmaps/pull/8972 feature.
This PR adds functionality to parse the recorded GPS track to the `Track` instance and save it to the latest lists (collection).
> [core] Save the recorded track to the bookmarks

- data/strings/types_strings.txt
Hi, just a very quick PR to add two Italian translations.
> [strings] Add IT translation for difficult and expert hiking paths

- platform/measurement_utils.cpp
Replacement of `std::ostringstream` with `std::snprintf` in function `ToStringPrecisionLocale()`, as proposed by @biodranik in [PR 8896](https://github.com/organicmaps/organicmaps/pull/8896), in order to obtain a better performance.
Columns:
* Old: `std::ostringstream`
* New: `std::snprintf`
* Ratio: New / Old * 100
Sample of values:
```
Old: 61269 ns, New:  8961 ns (Ratio 15 %)
Old: 65807 ns, New: 11539 ns (Ratio 18 %)
Old: 82231 ns, New: 10500 ns (Ratio 13 %)
Old: 37308 ns, New:  6847 ns (Ratio 18 %)
Old: 59884 ns, New:  9384 ns (Ratio 16 %)
Old: 66462 ns, New: 11885 ns (Ratio 18 %)
Old: 55923 ns, New:  8961 ns (Ratio 16 %)
Old: 60616 ns, New:  9500 ns (Ratio 16 %)
Old: 55731 ns, New:  7923 ns (Ratio 14 %)
Old: 25577 ns, New:  5039 ns (Ratio 20 %)
Old: 53923 ns, New:  8346 ns (Ratio 15 …
```
> Use snprintf in ToStringPrecisionLocale()

- .github/workflows/ios-beta.yaml
- .github/workflows/ios-check.yaml
- .github/workflows/ios-release.yaml
- .github/workflows/macos-check.yaml
> [github][ios] Increase Xcode version to 15.4 on Github runners

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/res/values/donottranslate.xml
Closes: https://github.com/organicmaps/organicmaps/issues/7263
> [android-auto] Remove android:foregroundServiceType="location" from CarAppService

- android/app/build.gradle
- android/build.gradle
- docs/INSTALL.md
No change to the target SDK here, only updating ndk, gradle and dependencies. SDK update is in the separate PR https://github.com/organicmaps/organicmaps/pull/9087
> Update Android NDK and gradle plugin

- iphone/Maps/Categories/MWMMapViewControlsManager+AddPlace.h
- iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManagerHelper.h
- iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManagerHelper.mm
- map/framework.cpp
- map/framework.hpp
- xcode/base/base.xcodeproj/project.pbxproj
- xcode/drape/drape.xcodeproj/project.pbxproj
- xcode/icu/icu.xcodeproj/project.pbxproj
Fixes https://github.com/organicmaps/organicmaps/issues/9063
There are many similar crashes reported by several users and visible in AppStore.
There is also a commit with a few minor fixes discovered when debugging this issue.
> Fixed crash on selecting a non-bookmark UserMark by tapping on feature's text label

- data/osm_test_data/addr_area_street.osm
- generator/generator_tests/raw_generator_test.cpp
- search/reverse_geocoder.cpp
- search/street_vicinity_loader.cpp
- search/street_vicinity_loader.hpp
Closes https://github.com/organicmaps/organicmaps/issues/9029
> [search] Process area highways for address matching.

- data/categories.txt
- Try to fix https://github.com/organicmaps/organicmaps/issues/9179 
- Add some missing translations in catalan
> Fix sarch and add some catalan translations

- android/app/src/main/java/app/organicmaps/editor/EditorFragment.java
All is in the title.
Related to #9049
> [android] Remove `outdoor_seating` support

- data/strings/strings.txt
PR #8972 was closed before I had a chance to check the translation.
> update hebrew translations for track recording

- data/gpx_test_data/export_test.gpx
- kml/serdes.cpp
- kml/serdes_gpx.cpp
This PR adds timestamps to the track points when export to GPX is used.
> [gpx] Implement GPX export for the tracks with timestamps

- android/app/src/google/java/app/organicmaps/location/GoogleFusedLocationProvider.java
- android/app/src/main/java/app/organicmaps/util/log/LogsManager.java
This helps to immediately see if there is a non-granted location permission issue when analyzing logs.
> [android] Improved logs and report permissions in bug reports

- editor/config_loader.cpp
- editor/config_loader.hpp
- editor/editor_tests/config_loader_test.cpp
Online loader was disabled long time ago, but some leftovers are still in the code
> [editor] Cleanup online config loader

- android/app/src/main/res/layout/place_page_phone_item.xml
display before: 0987 6543 21 44+
display now: +44 12 3456 7890
fixes https://github.com/organicmaps/organicmaps/pull/9298#issuecomment-2365052198
> [Android] fix phone number in RTL placepage

- kml/kml_tests/gpx_tests.cpp
- kml/serdes_gpx.cpp
- kml/serdes_gpx.hpp
Closes https://github.com/organicmaps/organicmaps/issues/9365
CC @cyber-toad
> [gpx] Fixed missing timestamps.

- android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp
- android/app/src/main/cpp/app/organicmaps/platform/AndroidPlatform.cpp
- android/app/src/main/cpp/app/organicmaps/platform/AndroidPlatform.hpp
- android/app/src/main/cpp/app/organicmaps/platform/GuiThread.hpp
- android/app/src/main/java/app/organicmaps/util/log/Logger.java
- base/thread.cpp
https://github.com/organicmaps/organicmaps/issues/9397
https://github.com/organicmaps/organicmaps/issues/6139
> [android] An attempt to fix GetEnv() == nullptr

- data/strings/strings.txt
Per title, updating Portuguese (PT-BR mainly) strings related to the new function of Track Record.
> [strings] Updating Portuguese strings

- android/app/src/main/java/app/organicmaps/downloader/BottomPanel.java
> [Android] Handle insets inside DownloaderFragment

- platform/qt_location_service.cpp
- platform/qt_location_service.hpp
Fixes https://github.com/flathub/app.organicmaps.desktop/issues/61
> platform: Track `Active` property of geoclue2

- android/app/src/main/java/app/organicmaps/downloader/BottomPanel.java
In case when action button is hidden, we should update margins of FAB. Otherwise keep the original value
Closes #9423
> [Android] Fix insets handling

- docs/INSTALL.md
A follow-up for https://github.com/organicmaps/organicmaps/pull/9377
> [docs] Minor follow-up fix

- .github/workflows/ios-beta.yaml
- .github/workflows/ios-check.yaml
- .github/workflows/ios-release.yaml
- .github/workflows/macos-check.yaml
This may be the cause of https://github.com/organicmaps/organicmaps/issues/9449
> [github] Use Xcode 16 for checks and release builds

- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/Maps.xcodeproj/xcshareddata/xcschemes/OMaps.xcscheme
- qt/main.cpp
- xcode/base/base.xcodeproj/project.pbxproj
- xcode/drape/drape.xcodeproj/project.pbxproj
- xcode/icu/icu.xcodeproj/project.pbxproj
- xcode/minizip/minizip.xcodeproj/project.pbxproj
> Print QT version on startup

- data/strings/strings.txt
Correction in basque language (eu) for `stop_without_saving` in line 31419
> Update basque translation

- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageController.java
> Only use inserts when available

- data/categories.txt
add keyword FR "École de conduite" to amenity=driving_school.
fix #9238
> add keyword FR "École de conduite" to amenity=driving_school

- indexer/ftypes_matcher.cpp
- indexer/ftypes_matcher.hpp
- search/ranking_info.cpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
Closes https://github.com/organicmaps/organicmaps/issues/9302
> [search] Treat "taxi" as Transport.

- iphone/Maps/Bookmarks/Categories/Category settings/CategorySettingsViewController.swift
> [ios] Allow saving empty bookmark list descriptions

- data/strings/strings.txt
Quick fix: PT and PT-BR were mixed here.
> [strings] Fix PT strings

- data/test_data/gpx/export_test.gpx
- kml/serdes.cpp
- kml/serdes_common.cpp
- kml/serdes_common.hpp
- kml/serdes_gpx.cpp
Fixes #9535 
Also added export of cmt tag for tracks
> [gpx] Use CDATA for name/cmt, export cmt for tracks

- data/strings/strings.txt
- data/strings/types_strings.txt
Source: [Organic Maps Translate - HU Matrix room](https://matrix.to/#/#organicmapstranslate_hu:matrix.org)
> Update hungarian strings.txt and types_strings.txt

- android/app/src/main/res/values/strings.xml
- data/categories.txt
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/ca.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/en-GB.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/en.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/mr.lproj/Localizable.strings
Synced EN types_strings and search categories to solve #8290 for the English language.
> Synced EN types_strings and search categories

- android/app/src/main/res/values-eu/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/eu.lproj/Localizable.strings
Update of "Add stop" and "Remove Stop" strings in eu (Euskara) language, following [PR 9583](https://github.com/organicmaps/organicmaps/pull/9583)
> [strings] Update 'stop' strings in eu (Euskara)

- kml/kml_tests/serdes_tests.cpp
- kml/serdes.cpp
> [kml] Fixed bug with invalid (empty) tracks.

- data/categories.txt
- Fix sarch in catalan
- Improve catalan translations 
Related with https://github.com/organicmaps/organicmaps/issues/9179
> Fix search in catalan and improve translations

- drape/vulkan/vulkan_object_manager.cpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/postprocess_renderer.cpp
- platform/trace.hpp
> [drape] Minor warning fixes.

- drape_frontend/frontend_renderer.cpp
- drape_frontend/user_event_stream.hpp
- qt/draw_widget.cpp
- qt/draw_widget.hpp
- qt/mainwindow.cpp
- qt/qt_common/map_widget.cpp
- qt/qt_common/map_widget.hpp
* This adds the features for https://github.com/organicmaps/organicmaps/issues/5306
- two finger pinch rotate gesture
- pan
- swipe
* Makes the previous two finger pinch zoom gesture feautre smoother and the zooming is now proportional to the gesture motion.
> [qt] feat: Implement correct touch handling

- map/framework.cpp
- map/framework.hpp
- platform/preferred_languages.cpp
Closes https://github.com/organicmaps/organicmaps/issues/9630
@dvdmrtnz Please, test. You should completely uninstall the previous app (to remove bad settings.ini).
> Fixed language code setting.

- data/countries.txt
- routing/routing_integration_tests/bicycle_route_test.cpp
- routing/routing_integration_tests/pedestrian_route_test.cpp
- routing/routing_integration_tests/route_test.cpp
- routing/routing_integration_tests/transit_route_test.cpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
India, Iceland, Marocco - normal profile for isolines.
> [planet] New data from 241107.

- iphone/Maps/Classes/MapViewController.mm
Closes https://github.com/organicmaps/organicmaps/issues/2524
This PR implements:
1. mouse zoom
2. trackpad 2-finger pinch to zoom
3. trackpad 2-finger rotation
https://github.com/user-attachments/assets/cf90df5c-93fa-45c3-b32b-8ce5ee975cad
> [ios] Implement macOS trackpad and mouse events (scroll, rotate, zoom) support

- android/app/src/main/cpp/app/organicmaps/SearchEngine.cpp
- android/app/src/main/java/app/organicmaps/search/SearchAdapter.java
- android/app/src/main/java/app/organicmaps/search/SearchResult.java
- search/highlighting.cpp
- search/ranker.cpp
- search/result.cpp
- search/result.hpp
Fixed #6932
Closes #7114
Implemented Bold feature in search suggestion address section
> [android] Implements Address Bold in Search Suggestion

- drape_frontend/read_manager.cpp
- editor/editor_tests/osm_editor_test.cpp
- geometry/geometry_tests/bounding_box_tests.cpp
- geometry/geometry_tests/diamond_box_tests.cpp
- geometry/geometry_tests/robust_test.cpp
- search/ranking_utils.hpp
Extracted from https://github.com/organicmaps/organicmaps/pull/9634
> Minor warning fixes

- android/app/src/main/cpp/app/organicmaps/SearchRecents.cpp
- android/app/src/main/java/app/organicmaps/search/SearchRecents.java
- android/app/src/main/java/app/organicmaps/search/SearchResult.java
- platform/string_storage_base.cpp
- search/highlighting.cpp
- storage/storage.cpp
https://github.com/organicmaps/organicmaps/pull/9707
Closes https://github.com/organicmaps/organicmaps/issues/9022
> [android] Search history order fix and some other minors.

- drape_frontend/route_shape.cpp
Closes https://github.com/organicmaps/organicmaps/issues/9721
> [drape] Fixed arrow drawing for dense polyline.

- platform/duration.cpp
- platform/platform_tests/duration_tests.cpp
> [platform] Fix less than minute duration formatting

- iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
Closes #9660
Fixes the bug and implements a context menu.
> [ios] Add the context menu to the coordinates accessory button

- android/app/src/main/java/app/organicmaps/routing/NavigationController.java
- android/app/src/main/java/app/organicmaps/widget/SpeedLimitView.java
- android/app/src/main/java/app/organicmaps/widget/menu/NavMenu.java
- android/app/src/main/res/layout-land/layout_nav_top.xml
- android/app/src/main/res/layout/layout_nav_top.xml
- android/app/src/main/res/values/attrs.xml
Rebase, original by AndrewShkrob: #7005
Also related: #5233 #9353
Notable issues: Not the correct sign for American people, can be fixed in a follow-up.
I couldn't make the speed limit appear in the emulator, might be that I'm too dumb or the code has an issue, will check in the real world tomorrow. I just rebased it for now.
I rebased it and made the sign a bit smaller.
Screenshots:
> [android] SpeedLimitView (rebase)

- android/app/src/main/res/values-tr/strings.xml
- iphone/Maps/LocalizedStrings/tr.lproj/Localizable.strings
> [strings] Regenerate for Turkish fixes

- platform/platform_tests/measurement_tests.cpp
>  Fixed unit tests. Follow up df258d545f0b1b6b9ba3bab27ba200164a841c62 .

- docs/TRANSLATIONS.md
Add more guidance for the POI category translation files (see: https://github.com/organicmaps/organicmaps/issues/8290#issuecomment-2459408903)
> Update POI category section in TRANSLATIONS.md

- routing_common/vehicle_model.hpp
see https://github.com/organicmaps/organicmaps/pull/9692#pullrequestreview-2447577894
as a newbie in this code I was unsure what is the meaning of these parameters
> clarify meaning of route parameters

- data/countries_names.txt
Added Russian name for the City of San Marino
> [strings] Added Russian name for San Marino

- iphone/Maps/LocalizedStrings/sr.lproj/InfoPlist.strings
- iphone/Maps/LocalizedStrings/sr.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/sr.lproj/Localizable.stringsdict
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/Maps.xcodeproj/xcshareddata/xcschemes/OMaps.xcscheme
A follow-up to https://github.com/organicmaps/organicmaps/pull/9857
> Enable Serbian (Cyrillic) translations on iOS

- android/app/src/main/java/app/organicmaps/settings/DrivingOptionsFragment.java
Simple implementation of https://github.com/organicmaps/organicmaps/issues/9696
Route will be updated automatically, when routing options chaned.
> Recalculate route automatically when routing options are changed

- qt/mainwindow.cpp
- qt/mainwindow.hpp
Requested in https://github.com/organicmaps/organicmaps/pull/9848#issuecomment-2531875694
> [qt] Remove defunct Traffic layer button

- android/app/src/main/java/app/organicmaps/maplayer/MapButtonsController.java
- android/app/src/main/java/app/organicmaps/routing/RoutingPlanController.java
- android/app/src/main/java/app/organicmaps/util/WindowInsetUtils.java
- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageButtons.java
> [Android] Fix for wrong ime insets on some devices

- android/app/src/main/res/values-ca/strings.xml
- android/app/src/main/res/values-es/strings.xml
- android/app/src/main/res/values-eu/strings.xml
- android/app/src/main/res/values-fi/strings.xml
- android/app/src/main/res/values-pt-rBR/strings.xml
- android/app/src/main/res/values-pt/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/fi.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/pt-BR.lproj/Localizable.strings
And regenerated for other PRs recently merged.
> [strings] Translations updates for the Kayak setting #9820 

- indexer/ftypes_matcher.cpp
- indexer/ftypes_matcher.hpp
- search/search_integration_tests/smoke_test.cpp
- search/types_skipper.cpp
- search/types_skipper.hpp
Following https://github.com/organicmaps/organicmaps/pull/9851 and https://github.com/organicmaps/organicmaps/pull/9854
> [search] Update list of features skipped from search

- iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtons.mm
Similar to the https://github.com/organicmaps/organicmaps/pull/9902#event-15722788265
> [ios] Show a toast every time FS mode is entered

- android/app/src/main/res/values-sr/strings.xml
- data/categories.txt
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/sr.lproj/Localizable.strings
Intensively tested Serbian translation of OM in the past couple of days, and fixed all errors that I was able to found.
> Serbian strings corrections

- iphone/Maps/OMapsWidgetExtension/LiveActivity/TrackRecordingLiveActivityView.swift
> [ios] Fix LiveWidget background color

- android/app/src/fdroid/play/listings/sr/full-description.txt
Added Serbian description file, authored by ZeljkoBG, with minor corrections from my side.
CC: @ZeljkoBG @zyphlar
> [strings] Serbian description added

- data/categories_cuisines.txt
Added cuisines translations to Serbian (authored by ZeljkoBg), with minor corrections from my side.
I also added all terms both in Serbian cyrillic and in Serbian latin alphabets, becuase they are both used on mobile devices.
CC: @ZeljkoBG, @zyphlar
> [strings] Serbian translations for cuisines added (by ZeljkoBG)

- android/app/src/main/java/app/organicmaps/car/CarAppSession.java
- android/app/src/main/java/app/organicmaps/car/screens/download/DownloaderHelpers.java
Closes: #8852
Previous attempt: #7670
> [android-auto] Check for world maps after init

- android/app/src/main/java/app/organicmaps/car/CarAppSession.java
- android/app/src/main/java/app/organicmaps/car/screens/download/DownloaderScreen.java
> [android-auto] Fix maps downloading in planning mode

- android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkManager.java
- android/app/src/main/java/app/organicmaps/car/screens/bookmarks/BookmarksLoader.java
- android/app/src/main/java/app/organicmaps/car/screens/bookmarks/BookmarksScreen.java
- android/app/src/main/java/app/organicmaps/car/screens/bookmarks/SortingScreen.java
Closes: #8509 
There is a chance that this PR will fix #8508 
Sorting screen:
By default:
By type:
By distance:
> [android-auto] Add bookmarks sorting

- android/app/src/main/res/values-de/strings.xml
- data/categories.txt
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
Improved four German category translations
~(strings regeneration also includes "Map Point")~
> DE category translations

- android/app/src/fdroid/play/listings/sr/release-notes.txt
- android/app/src/fdroid/play/listings/sr/short-description.txt
- android/app/src/fdroid/play/listings/sr/title-google.txt
- android/app/src/fdroid/play/listings/sr/title.txt
Serbian translations for descriptions and release notes (by @ZeljkoBG) with minor corrections from my side.
CC: @pastk
> [strings] Serbian descriptions and release notes

- .github/CODEOWNERS
- docs/TEAMS.md
Require the code review from Android, iOS, Styles and Design teams folks before merging relevant changes.
> [docs] Add TEAMS and update CODEOWNERS

- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageUtils.java
> [android] Fix crash if coordinates are copied after bottom bar is closed

- iphone/Maps/Core/iCloud/CloudDirectoryMonitor.swift
Fixes https://github.com/organicmaps/organicmaps/issues/10041
When the user deletes the file locally with the enabled iCloud:
1. the file is moved to the local trash dir
2. the `LocalDirectoryMonitor` sends an event to delete the file from the iCloud
3. the `SynchronizationFileWriter` trashes the remote file using the system API `try fileManager.trashItem`
4. the file is moved to the device's trash
5. the iCloud sends _asynchronously_ updates to the metadataQery's `queryDidUpdate` with the updated state
This update is tricky - it calls the method **twice**: 
- on the first call the deleted file appears in the **updated** list (`userInfo[NSMetadataQueryUpdateChangedItemsKey]`) 
- on the second call the deleted file appears in the **deleted** list …
> [ios] Fix iCloud bug with the missed file recreation during the cloud `update` event

- android/app/src/main/res/layout/fragment_categories.xml
Added a scrollbar to make navigating through the long list easier.
| Now | Before |
| <img width="300" src="https://github.com/user-attachments/assets/c1295ed5-95e5-42e3-a3dc-fc2d53b19757" /> | <img width="300" src="https://github.com/user-attachments/assets/4d87399f-ecf8-43b1-9115-15dbaa5a9b32" /> |
> Display a scrollbar for the category list

- android/app/src/main/res/values-sr/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/sr.lproj/Localizable.strings
Corrected and added some Serbian translations after testing 2025-01 beta version (by @ZeljkoBG and myself).
> Serbian corrections after 2025 01 beta

- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageController.java
This fixes the following crash for me:
```
2024-12-06 20:45:08.299  4915-4915  AndroidRuntime          app.organicmaps.debug                E  FATAL EXCEPTION: main
Process: app.organicmaps.debug, PID: 4915
java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.core.graphics.Insets androidx.core.view.WindowInsetsCompat.getInsets(int)' on a null object reference
at app.organicmaps.widget.placepage.PlacePageController.animatePeekHeight(PlacePageController.java:286)
at app.organicmaps.widget.placepage.PlacePageController.setPeekHeight(PlacePageController.java:272)
at app.organicmaps.widget.placepage.PlacePageController.lambda$onPlacePageContentChanged$3(PlacePageController.java:331)
at app.organicmaps.widget.placepage.PlacePageController.$r8$lambda$ejBTUtQkwpAHbrtKjzm_WcIj …
```
> Check for null before animation

- android/app/src/main/res/values-de/strings.xml
- android/app/src/main/res/values-tr/strings.xml
- data/sound-strings/it.json/localize.json
- iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/tr.lproj/Localizable.strings
For various previous already merged changes.
> [strings] Regenerate

- data/countries.txt
- routing/routing_integration_tests/bicycle_route_test.cpp
- routing/routing_integration_tests/pedestrian_route_test.cpp
- routing/routing_integration_tests/route_test.cpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
Includes integration tests fixes from the prev generation https://github.com/organicmaps/organicmaps/pull/10055
Still there are failures (too many for routing!) that need checking.
search:
```
2  tests failed:
real_mwm_tests.cpp::MwmTestsFixture_Famous_Cities_Rank
real_mwm_tests.cpp::MwmTestsFixture_BA_SanMartin
```
routing:
```
24  tests failed:
absent_regions_finder_tests.cpp::TestAbsentRegionsFinder_Germany_Belgium
absent_regions_finder_tests.cpp::TestAbsentRegionsFinder_Russia_SPB_Pechory
bicycle_route_test.cpp::CrossMwmKaliningradRegionToLiepaja
bicycle_route_test.cpp::London_GreenwichTunnel
bicycle_route_test.cpp::IgnoreCycleBarrier_WithoutAccess
bicycle_route_test.cpp::UK_Canterbury_UseDismount
bicycle_turn_test.cpp::Russia_Moscow_SalameiNerisPossibleTurnCorrectionBicycleWay_TurnTes …
```
> [planet] New data from 250121.

- iphone/Maps/Common/WebViewController.m
- iphone/Maps/UI/PlacePage/Components/PlacePageDescriptionViewController.swift
Closes #9943 
Changes
- Add padding
- Fix them change font color mismatch issue
| ![Simulator Screenshot - iPhone 16 - 2025-01-18 at 00 50 59](https://github.com/user-attachments/assets/dd115aba-af7c-4bfe-9168-0d71ef41179f) | ![Simulator Screenshot - iPhone 16 - 2025-01-18 at 00 50 06](https://github.com/user-attachments/assets/3a861315-2e48-4a3a-8895-8339f9d69a4a) |
||![After](https://github.com/user-attachments/assets/d2ebd7f6-bd6e-4a15-b5de-a7663307cbf8)|
> [ios] Improve the UI for displaying the Wikipedia description

- android/app/src/main/res/values-pt-rBR/strings.xml
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/pt-BR.lproj/Localizable.strings
Per title, fixing PT-BR strings.
> [strings] Fixed PT-BR translation of suburb and village

- android/app/src/main/res/values-lv/strings.xml
- android/app/src/main/res/values-pt-rBR/strings.xml
- data/categories.txt
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/lv.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/pt-BR.lproj/Localizable.strings
Added German translation for bike charging to categories.txt file.
> Added German translation for bike charging

- docs/TRANSLATIONS.md
clearer instructions, AppStore -> App Store
> [docs] improve translation instructions a bit

- data/styles/default/dark/colors.mapcss
- data/styles/default/light/colors.mapcss
- data/styles/vehicle/dark/colors.mapcss
- data/styles/vehicle/light/colors.mapcss
> [styles] Fix unused color vars warnings

- docs/INSTALL.md
omim_test is wrong, it's omim-test
> [docs] install.md: omim_test to omim-test

- iphone/Maps/Core/TrackRecorder/TrackRecordingManager.swift
Closes https://github.com/organicmaps/organicmaps/issues/10222 
When the user closes the LAW it will be hidden until the next track recording start.
Also this PR fixes the issue when the Live Activity is Disabled in the settings then the start recording fails.
> [ios] Fix Live activity widget issue when it recreates on every app opening

- iphone/Maps/Core/iCloud/SynchronizationFileWriter.swift
Attempt to fix the https://github.com/organicmaps/organicmaps/issues/10042
Due to the working with the sync it is recommended to use the file coordinator. The issue is hard to reproduce. 
If the fix doesn't work I suggest using the guard `fileManager.fileExist` check before starting to download.
> [ios] Start downloading icloud item with coordination

- iphone/Maps/Core/iCloud/SynchronizationStateResolver.swift
- iphone/Maps/Tests/Core/iCloudTests/DefaultLocalDirectoryMonitorTests/DefaultLocalDirectoryMonitorTests.swift
- iphone/Maps/Tests/Core/iCloudTests/SynchronizationStateManagerTests.swift
Closes https://github.com/organicmaps/organicmaps/issues/10221
The initial sync when the file is not downloaded:
https://github.com/user-attachments/assets/3d2eeb8b-1a8d-43e9-bf4b-954359d8535f
> [ios] FIix the iCloud initial sync bug when the some files are not downloaded at start

- android/app/src/main/java/app/organicmaps/editor/EditorFragment.java
- android/app/src/main/res/drawable/ic_building.xml
- android/app/src/main/res/drawable/ic_floor.xml
- android/app/src/main/res/drawable/ic_operating_hours.xml
- android/app/src/main/res/drawable/ic_street_address.xml
- android/app/src/main/res/layout/fragment_editor.xml
- android/app/src/main/res/layout/item_opening_hours.xml
Fixes : #6933 
Icons used : [Google Fonts](https://fonts.google.com/icons?icon.size=24&icon.color=%23e8eaed) 
| Before | After  |
|---------|---------|
| ![before](https://github.com/user-attachments/assets/d07df24c-ec18-4024-863d-5ac5976b0830)| ![After](https://github.com/user-attachments/assets/8474e492-cc13-455d-9cb0-054da87cf746) |
> [Editor] Added icons to editor for better consistency  

- data/countries.txt
I can't choose the `release/2025.01.24` branch to merge to.
Where should it go?
@rtsisyk
> [planet] New data from 250213.

- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
Make BookmarkManager a bit smaller with unused code removed
> [bookmarks] Remove unused code from BookmarkManager

- android/app/src/main/res/values-ja/strings.xml
- iphone/Maps/LocalizedStrings/ja.lproj/Localizable.strings
Hello. Here are the regenerated files after #10292
Also small fix about the cross from previous commits (it was in a source code but not generated)
> [strings] Regenerate after #10292

- android/app/src/main/cpp/app/organicmaps/bookmarks/data/BookmarkManager.cpp
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarksSharingHelper.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkManager.java
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/map_tests/bookmarks_test.cpp
Closes #9580 #9283 
Add option to export single track as GPX or KMZ file.
> [bookmarks] Share single track

- iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
The PlacePageInfoVC was not released properly because the nested functions hold the self. 
This PR fix it.
> [ios] Fix memory leak in the PlacePageInfoViewController

- iphone/Maps/UI/PlacePage/Components/ActionBarViewController.swift
Closes https://github.com/organicmaps/organicmaps/issues/10293
> [ios] show `add stop` button to the selected track point during the navigation mode

- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListInteractor.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
- iphone/Maps/UI/PlacePage/Components/PlacePageHeader/PlacePageHeaderBuilder.swift
- iphone/Maps/UI/PlacePage/Components/PlacePageHeader/PlacePageHeaderPresenter.swift
- iphone/Maps/UI/PlacePage/Components/PlacePageHeader/PlacePageHeaderViewController.swift
- iphone/Maps/UI/PlacePage/PlacePageBuilder.swift
- iphone/Maps/UI/PlacePage/PlacePageInteractor.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/IPlacePageLayout.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageTrackLayout.swift
- iphone/Maps/UI/PlacePage/PlacePagePresenter.swift
Closes #1286 
Closes #9939
Continues #10278
> [ios] Share single track from the Place Page screen

- android/app/src/main/java/app/organicmaps/downloader/DownloaderAdapter.java
Fixes : #6102
- Before
https://github.com/user-attachments/assets/4cd680b4-8772-4e89-9d08-a159b2e28189
- After
https://github.com/user-attachments/assets/536a9005-9153-4e51-9e12-6d04678c1a95
> [android] Status Icon Fix

- data/strings/strings.txt
Mostly I wanted to correct the capitalization of "Open in Another App" but I read through all the English strings while I was at it.
> English strings fixes, Capitalization

- data/categories.txt
Added italian search term for car repair shop.
"Meccanico" is the most commonly used term for this kind of shops.
> [categories] Update categories.txt

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/widget/placepage/DirectionFragment.java
- android/app/src/main/res/values/themes.xml
before/after
https://github.com/user-attachments/assets/8ad25b19-e9ce-4823-8c3e-b9362ee3a01a
fixes https://github.com/organicmaps/organicmaps/issues/8869
> [Android] hide UI in big direction mode

- .github/CODEOWNERS
> [github] Do not require POI PR reviews from design and data teams

- data/editor.config
> [editor] Make new POIs editable

- .github/CODEOWNERS
- follow-up to https://github.com/organicmaps/organicmaps/pull/10330#discussion_r1975951224
> [github] Add leading slash (root) to all CODEOWNERS dirs

- drape/vulkan/vulkan_context_factory.cpp
- drape/vulkan/vulkan_utils.cpp
Removal of annoying compilation warnings related to Vulkan.
> [drape] Remove Vulkan warnings

- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapViewController.swift
> [ios] fix search header radius small for iphone

- android/app/src/main/res/values-mt/strings.xml
- iphone/Maps/LocalizedStrings/mt.lproj/InfoPlist.strings
- iphone/Maps/LocalizedStrings/mt.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/mt.lproj/Localizable.stringsdict
- iphone/Maps/LocalizedStrings/mt.lproj/LocalizableTypes.strings
- iphone/Maps/Maps.xcodeproj/project.pbxproj
The language was present in strings.txt but was never generated.
> [strings] Generate Maltese (mt) from strings.txt

- .github/workflows/stale.yml
> [github] Add stale bot to close very old PRs

- .gitignore
It's generated when making edits on desktop
> [github] Add edits.xml to .gitignore

- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageController.java
Fixes #9335
|--------|-------|
| ![image](https://github.com/user-attachments/assets/a3aa3833-9ae5-4f87-af44-dba1a9716348) | ![image](https://github.com/user-attachments/assets/c9b9c9f6-0bb5-4be3-a505-1623216cbfd6) |
https://github.com/user-attachments/assets/55aa9d15-d199-47ba-89a0-75669e24cf10
> [android] Fix tiny transparent PP edges after it fills the screen

- 3party/CMakeLists.txt
- coding/sha1.cpp
- dev_sandbox/CMakeLists.txt
- xcode/common.xcconfig
- CMake 4 compatibility fix
- XCode 16.3 build fix
- Sha digest (boost) fix
- Fixed paths to fonts to silence cp warnings when configuring the project
> Various build fixes

- android/app/src/main/java/app/organicmaps/util/ThemeSwitcher.java
ported from the big PR. Addresses the issue of the theme not changing when there's no location fix by setting to night at 6pm (still checks when sunset is if you have a location fix)
> [android] improve auto theming

- iphone/Maps/Tests/UI/SearchOnMapTests/SearchOnMapTests.swift
Fix search tests when they are running on the mac or on the ipad.
> [ios] Fix search on map tests for ipad

- android/app/src/main/java/app/organicmaps/widget/placepage/DirectionFragment.java
- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
- android/app/src/main/res/layout/fragment_direction.xml
- android/app/src/main/res/layout/place_page_preview.xml
Implements Android part of #7917
https://github.com/user-attachments/assets/7ac92355-f2cb-4da2-bda0-c5c1729e837c
Test Azimuth Angle : https://doc.forecast.solar/find_your_azimuth
> [UI] Displays Azimuth angle from north in in the compass arrow view 

- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
Closes https://github.com/organicmaps/organicmaps/issues/10568
> [ios] Fix the bookmark's wiki section visibility on the Place Page

- iphone/Maps/UI/Search/SearchOnMap/Presentation/ModalPresentationAnimator.swift
This small PR improves the search screen animation appearance.
before (slomo)
https://github.com/user-attachments/assets/38c849a1-e33a-4f7d-8291-4d51fe6bd759
after (slomo)
https://github.com/user-attachments/assets/3d82c81f-734d-4181-a011-2ec794147832
> [ios] Make modal screen appearanсe animation smoother

- android/app/src/main/res/layout/place_page_phone_item.xml
Fixes the first issue mentioned in #9624
Thanks to @batterydotac for the investigation and testing!
> Fix crash on Android 5 on PP with phone numbers

- android/app/src/main/java/app/organicmaps/bookmarks/data/Metadata.java
- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
- android/app/src/main/res/layout/item_opening_hours.xml
- android/app/src/main/res/layout/place_page_atm.xml
- android/app/src/main/res/layout/place_page_capacity.xml
- android/app/src/main/res/layout/place_page_cuisine.xml
- android/app/src/main/res/layout/place_page_drive_through.xml
- android/app/src/main/res/layout/place_page_email.xml
- android/app/src/main/res/layout/place_page_facebook.xml
- android/app/src/main/res/layout/place_page_instagram.xml
- android/app/src/main/res/layout/place_page_latlon.xml
- android/app/src/main/res/layout/place_page_level.xml
- android/app/src/main/res/layout/place_page_line.xml
- android/app/src/main/res/layout/place_page_network.xml
- android/app/src/main/res/layout/place_page_open_in.xml
- android/app/src/main/res/layout/place_page_opening_hours_fragment.xml
- android/app/src/main/res/layout/place_page_operator.xml
- android/app/src/main/res/layout/place_page_phone_item.xml
- android/app/src/main/res/layout/place_page_self_service.xml
- android/app/src/main/res/layout/place_page_twitter.xml
- android/app/src/main/res/layout/place_page_vk.xml
- android/app/src/main/res/layout/place_page_website.xml
- android/app/src/main/res/layout/place_page_website_menu.xml
- android/app/src/main/res/layout/place_page_wheelchair.xml
- android/app/src/main/res/layout/place_page_wikimedia.xml
@batterydotac can you please test this change? Build locally, or maybe installing pre-built artifacts from Android checks would be the easiest way.
> [android] Fixed drive_through => self_service typo in PP layout

- data/categories.txt
- indexer/ftypes_matcher.cpp
- search/processor.cpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
Closes https://github.com/organicmaps/organicmaps/issues/10615
Follow up to https://github.com/organicmaps/organicmaps/commit/92aa8863387542d99ce477f67713294147d726b5
TODO: Fallback to En for the languages that don't exist in categories.txt (for example Estonian).
> [categories] Fit categories with translations.

- android/app/src/main/res/layout/item_bookmark_category.xml
Fixes #9649 
Increases the touchable area of eye and options button (3 dots) of bookmarks
https://github.com/user-attachments/assets/f73984db-f13c-4f73-8fa5-dad1d62971bb
> [android] Increases touch area of eye and 3 dot

- .github/workflows/ios-check.yaml
Fixes https://github.com/organicmaps/organicmaps/issues/9867
> [ios] [github] Add simulator pre-boot before running the tests

- iphone/Maps/Core/iCloud/SynchronizationFileWriter.swift
Closes https://github.com/organicmaps/organicmaps/issues/10041
> [ios] Prevent iCloud sync from failing when the cloud file doesn't exist

- android/app/src/main/java/app/organicmaps/location/RouteSimulationProvider.java
Fixes issue introduced in #10658
> [android-auto] Fix RouteSimulationProvider

- iphone/Maps/UI/Editor/MWMEditorViewController.mm
Closes https://github.com/organicmaps/organicmaps/issues/10253#issuecomment-2980757327
Tested on 
iPhone 15 Pro (18.5) dev
iPhone 16 Pro (18.2) sim
iPhone 6s (15) sim
> [ios] Fix editor notes jumping

- android/app/src/main/AndroidManifest.xml
Fixes https://github.com/organicmaps/organicmaps/issues/5432
Tested on a real device.
> Fix EACCESS PermissionDenied error when opening files on Android 5

- drape_frontend/gps_track_renderer.cpp
Android crash from the dev console. Probably, because of memory fragmentation.
```
#06  pc 0x00000000004243c0  /data/app/~~EUUMW3ez7f-M7F-phtrEVw==/app.organicmaps-JDOmYxiQ2kNwvS7WBMVd2Q==/split_config.arm64_v8a.apk!liborganicmaps.so (std::__ndk1::__throw_length_error[abi:ne180000](char const*)+16384) (BuildId: 389808acdf1d92d7c8872582907093d3b9991971)
#07  pc 0x00000000004277b8  /data/app/~~EUUMW3ez7f-M7F-phtrEVw==/app.organicmaps-JDOmYxiQ2kNwvS7WBMVd2Q==/split_config.arm64_v8a.apk!liborganicmaps.so (std::__ndk1::vector<m2::Point<double>, std::__ndk1::allocator<m2::Point<double>>>::__throw_length_error[abi:ne180000]() const+16384) (BuildId: 389808acdf1d92d7c8872582907093d3b9991971)
#08  pc 0x0000000000afb188  /data/app/~~EUUMW3ez7f-M7F-phtrEVw==/app.organicmaps-JDOmYxiQ2kNwvS7WBMVd2Q==/sp …
```
> [drape] Relaxed GPS track Spline update.

- .github/workflows/cleanup_caches.yml
Reverts organicmaps/organicmaps#10670
Turns out we need this :)
> Revert "[ci] Remove cleanup caches workflow"

- android/app/src/main/res/layout/altitude_chart_panel.xml
Fixes #10772
The problem:
Fixed layout by adding `layout_weight` attribute:
**TODO:** test with multiple locales, screen sizes, font settings.
> [Android] Route planning lower panel fix

- iphone/Chart/Chart/Views/ChartLineView.swift
- iphone/Chart/Chart/Views/ChartPreviewView.swift
Closes https://github.com/organicmaps/organicmaps/issues/10719
> [ios] Fix elevation chart failing on update

- android/app/build.gradle
> [android] explicitly configure debug symbols

- .github/workflows/update-caches.yml
It's not possible to verify it during PR. We'll have to merge it to check that it works
> [ci] Add update caches workflow

- android/app/src/main/AndroidManifest.xml
https://github.com/organicmaps/organicmaps/issues/10843
The issue should not be closed as this is only a workaround
> [android] Hot fix for broken OnBackPressed

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/app/organicmaps/downloader/DownloaderActivity.java
- android/app/src/main/java/app/organicmaps/downloader/DownloaderAdapter.java
- android/app/src/main/java/app/organicmaps/downloader/DownloaderFragment.java
- android/app/src/main/java/app/organicmaps/widget/SearchToolbarController.java
https://github.com/organicmaps/organicmaps/issues/10843
> [android] Migrate DownloaderActivity to OnBackPressedCallback

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/MwmApplication.java
- android/app/src/main/java/app/organicmaps/background/OsmUploadWork.java
- android/app/src/main/java/app/organicmaps/editor/EditorHostFragment.java
- android/app/src/main/java/app/organicmaps/editor/OsmLoginFragment.java
- android/app/src/main/java/app/organicmaps/editor/ProfileFragment.java
- android/app/src/main/java/app/organicmaps/maplayer/LayersAdapter.java
- android/app/src/main/java/app/organicmaps/maplayer/ToggleMapLayerFragment.java
- android/app/src/main/java/app/organicmaps/sdk/OrganicMaps.java
- android/app/src/main/java/app/organicmaps/sdk/editor/Editor.java
- android/app/src/main/java/app/organicmaps/sdk/editor/OsmOAuth.java
- android/app/src/main/java/app/organicmaps/sdk/util/Config.java
- android/app/src/main/java/app/organicmaps/sdk/util/SharedPropertiesUtils.java
- android/app/src/main/java/app/organicmaps/sdk/util/log/LogsManager.java
- android/app/src/main/java/app/organicmaps/search/SearchFragment.java
- android/app/src/main/java/app/organicmaps/settings/SettingsPrefsFragment.java
- android/app/src/main/res/values/donottranslate.xml
- android/sdk/src/main/res/values/donottranslate.xml
Refactoring of SharedPreferences to make it usable in the library.
Current refactoring is just a "copy/move/replace" without any changes in the logic.
The application is using shared preferences from the library. It should be changed later.
> [android][sdk] Refactor shared preferences

- android/app/build.gradle
- android/app/src/main/java/org/chromium/base/ObserverList.java
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/sdk/build.gradle
- android/settings.gradle
> [android] Updated AGP to 8.11.0 and other deps

- iphone/Maps/Core/Search/SearchResult.mm
Fixes https://github.com/organicmaps/organicmaps/issues/10896
@vng add it to release?
> [ios] Fixed wrong coordinates access for pure suggestion search results

- android/gradle.properties
> [android] Increase gradle heap to 2Gb to fix linter OOM

- android/app/src/main/java/app/organicmaps/widget/placepage/BookmarkColorDialogFragment.java
- android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java
> [android] Fix collor selector issue

- android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java
- android/app/src/main/java/app/organicmaps/bookmarks/ColorsAdapter.java
- android/app/src/main/java/app/organicmaps/sdk/bookmarks/data/Icon.java
- android/app/src/main/java/app/organicmaps/widget/placepage/BookmarkColorDialogFragment.java
- android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java
> [android] Show bookmark icon in color selector

- android/app/build.gradle
- android/sdk/build.gradle
https://github.com/android/ndk/wiki/Changelog-r28#r28c
> [android] Update NDK to R28c

- .github/workflows/code-style-check.yaml
This is needed to work in PRs from forks
> [ci] Add PR write perms to code style workflow

- libs/map/bookmark_manager.cpp
- libs/map/gps_track.cpp
- libs/map/gps_track.hpp
- libs/map/gps_track_collection.cpp
- libs/map/gps_track_collection.hpp
- libs/map/gps_track_filter.cpp
- libs/map/gps_track_filter.hpp
- libs/map/gps_track_storage.cpp
- libs/map/gps_track_storage.hpp
- libs/map/gps_tracker.cpp
- libs/map/gps_tracker.hpp
Closes https://github.com/organicmaps/organicmaps/issues/9685
> [track] Track recording fixes.

- data/sound-strings/ru.json/localize.json
> При уходе с тропы если язык подсказок русский, говорит - «преращик маршрута».
> [TTS] Clearer pronouncement of route recalculation in ru

- libs/drape_frontend/apply_feature_functors.cpp
- libs/drape_frontend/apply_feature_functors.hpp
- libs/drape_frontend/color_constants.cpp
- libs/drape_frontend/frontend_renderer.cpp
- libs/drape_frontend/relations_draw_info.cpp
- libs/drape_frontend/relations_draw_info.hpp
- libs/drape_frontend/rule_drawer.cpp
- libs/drape_frontend/stylist.cpp
- libs/drape_frontend/stylist.hpp
- libs/indexer/classificator.cpp
- libs/indexer/classificator.hpp
- libs/indexer/displacement_manager.hpp
- libs/indexer/drawing_rules.cpp
- libs/indexer/drawing_rules.hpp
- libs/indexer/feature_visibility.cpp
- libs/indexer/feature_visibility.hpp
- libs/map/style_tests/dashes_test.cpp
- libs/map/style_tests/style_symbols_consistency_test.cpp
- libs/map/transit/transit_reader.cpp
> [drape] Force use Outdoor style for the hiking/cycling routes related Features.

- android/app/src/main/java/app/organicmaps/downloader/DownloaderNotifier.java
- android/app/src/main/java/app/organicmaps/downloader/DownloaderService.java
- android/app/src/main/java/app/organicmaps/util/Utils.java
I can't reproduce, but read from here https://t.me/OrganicMapsRu/85557 and below.
> [android] setSound(null, null) for the Downloader notification channel.

- libs/drape_frontend/gui/gui_text.cpp
While working on https://github.com/organicmaps/organicmaps/pull/5233
Fixed text's pixel length calculation. It is needed for a proper alignment when anchor is set to `dp::Center`
Before
https://github.com/user-attachments/assets/8081fd5f-9a2b-46a0-b779-9a4878962ed7 
After
https://github.com/user-attachments/assets/6cded207-31d0-4041-930b-7c28eb4278a4
> [drape] Fix gui text alignment

- android/sdk/src/main/cpp/app/organicmaps/sdk/bookmarks/data/PredefinedColors.cpp
- libs/base/stl_helpers.hpp
- libs/kml/types.hpp
> [android] Fix colors order

- libs/map/framework.cpp
- libs/map/routing_manager.cpp
https://github.com/organicmaps/organicmaps/issues/10926
> [map] Fixed invalid route saving.

- .gitmodules
- android/app/build.gradle
- data/copyright.html
- xcode/common.xcconfig
Glaze-related commits from https://github.com/organicmaps/organicmaps/pull/11188 to unblock @hemanggs and @strump
> [3party] Glaze fix for iOS, and a few other minor fixes

- android/app/src/main/res/layout/bottom_sheet_handle.xml
- android/app/src/main/res/layout/place_page_preview.xml
> [android] Improved PP preview margins

- libs/editor/server_api.cpp
Version is already written for edits, but not for notes. Should help in debugging https://github.com/organicmaps/organicmaps/issues/2071
> Add OM version to uploaded OSM notes

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
- android/app/src/main/java/app/organicmaps/widget/placepage/WikiArticleActivity.java
- android/app/src/main/java/app/organicmaps/widget/placepage/WikiArticleFragment.java
- android/app/src/main/java/app/organicmaps/widget/placepage/sections/PlacePageWikipediaFragment.java
- android/app/src/main/res/layout/place_page_description_layout.xml
- android/app/src/main/res/values/integer.xml
- android/sdk/src/main/cpp/app/organicmaps/sdk/UserMarkHelper.cpp
- android/sdk/src/main/java/app/organicmaps/sdk/bookmarks/data/Bookmark.java
- android/sdk/src/main/java/app/organicmaps/sdk/bookmarks/data/MapObject.java
Pre-requisite for osm descriptions to avoid confusion.
C++-related renaming can also be done separately.
> [android] Renamed description to wikiArticle to avoid confusion

- dev_sandbox/main.cpp
Got broken in https://github.com/organicmaps/organicmaps/commit/15b66d567b1abdd798f18382eeacfebb94e2ebc3
> Fix issue after clang-format

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/app/organicmaps/routing/NavigationService.java
Fixes: #9395
We have tts player in service. It requires specifying `mediaPlayback` service type
> [android] Add missing service type to NavigationService

- android/app/src/main/java/app/organicmaps/routing/NavigationController.java
- android/app/src/main/res/layout/layout_nav_top.xml
> [android] Fix SpeedLimitView margin

- libs/drape/symbols_texture.cpp
- libs/drape/symbols_texture.hpp
- libs/drape/texture.hpp
- libs/drape/texture_manager.cpp
- libs/drape/texture_manager.hpp
- libs/drape_frontend/backend_renderer.cpp
- libs/drape_frontend/backend_renderer.hpp
- libs/drape_frontend/drape_engine.cpp
- libs/drape_frontend/frontend_renderer.cpp
- libs/drape_frontend/frontend_renderer.hpp
- libs/drape_frontend/message.cpp
- libs/drape_frontend/message.hpp
- libs/drape_frontend/message_subclasses.hpp
Inspired:
Closes https://github.com/organicmaps/organicmaps/pull/10905
Issues:
Closes https://github.com/organicmaps/organicmaps/issues/4760
Closes https://github.com/organicmaps/organicmaps/issues/5761
Closes https://github.com/organicmaps/organicmaps/issues/5760
> [drape] Reload symbols texture when DPI changed.

- android/app/src/main/res/values-es-rMX/strings.xml
- android/app/src/main/res/values-es/strings.xml
- iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/es.lproj/Localizable.strings
A user gave bad review for "incorrect zum" translation :)
> [strings] Changed zum to zoom in Spanish

- android/app/src/main/java/app/organicmaps/car/renderer/SurfaceCallback.java
- android/app/src/main/java/app/organicmaps/car/renderer/SurfaceRenderer.java
Move arrow from center to bottom in navigation mode
> [android-auto] Fix routing arrow offset

- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapInteractor.swift
Caused by the 5e98dfb630260a6ebe8429ef8c81c36f7f9505fa
> [ios] Fix search result selection issue

- android/app/src/main/java/app/organicmaps/car/CarAppSession.java
- android/app/src/main/java/app/organicmaps/car/screens/NavigationScreen.java
- android/app/src/main/java/app/organicmaps/car/screens/PlaceScreen.java
Fixes: https://github.com/organicmaps/organicmaps/issues/11418
Fixes: https://github.com/organicmaps/organicmaps/issues/10188
Fixes: https://github.com/organicmaps/organicmaps/issues/9184
Fixes: https://github.com/organicmaps/organicmaps/issues/6716 (2 of 3 are already fixed, this is the fix for 1st issue - switching between apps)
Should fix: https://github.com/organicmaps/organicmaps/issues/10340
> [android-auto] Fix display switching in navigation mode

- iphone/Maps/Core/TrackRecorder/TrackRecordingManager.swift
- iphone/Maps/UI/PlacePage/Components/ActionBarViewController.swift
- iphone/Maps/UI/PlacePage/PlacePageInteractor.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.h
- iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.m
This PR implements track recording deletion UI:
1. button in the action bar
2. alert to prevent accidental deletion
> [ios] Delete track recording

- android/app/src/main/java/app/organicmaps/car/renderer/Renderer.java
- android/app/src/main/java/app/organicmaps/car/renderer/SurfaceCallback.java
- android/app/src/main/java/app/organicmaps/car/renderer/SurfaceCallbackBase.java
- android/app/src/main/java/app/organicmaps/car/renderer/SurfaceRenderer.java
- android/app/src/main/java/app/organicmaps/car/renderer/SurfaceRendererLegacy.java
- android/app/src/main/java/app/organicmaps/car/screens/NavigationScreen.java
- android/app/src/main/java/app/organicmaps/widget/SpeedLimitView.java
Closes: #9193
https://github.com/user-attachments/assets/f29068e3-9a05-4546-b378-d4c0e9734061
> [android-auto] Show speed limit

- qt/osm_auth_dialog.cpp
- qt/osm_auth_dialog.hpp
Also store/display the account used for the login.
@Ferenc- does OpenStreetMap.org login hang on Linux too?
> [desktop] Fix hanging on Mac OS X when log in to OSM

- libs/editor/editor_notes.cpp
- libs/editor/editor_notes.hpp
- libs/editor/osm_editor.cpp
- libs/editor/osm_editor.hpp
Should fix this https://github.com/organicmaps/organicmaps/issues/2071
> [editor] Fixed notes uploader.

- android/app/src/main/java/app/organicmaps/car/screens/NavigationScreen.java
- android/sdk/src/main/java/app/organicmaps/sdk/location/LocationHelper.java
> [android-auto] Create route simulation button
