organicmaps/organicmaps

README.md
=> Remove CLA mention

android/gradle.properties, android/jni/com/mapswithme/platform/Platform.cpp, android/src/com/mapswithme/util/BatteryState.java
Follow up aa7ef4a189ea81892f5c1caca90b28bef6236020
Fixes #60
Fixes #81
=> [android] Fix crash in GetBatteryLevel()/GetBatteryLevel()

iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarViewController.xib
=> [ios]: bookmark button returned

iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMRoutePreview.mm, iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
=> [ios] taxi button deleted

iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift, iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
=> [ios] disable bookmark synchronization

android/res/layout/place_page_details.xml, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java, android/src/com/mapswithme/util/statistics/PlacePageTracker.java
**Changed**   :
1.  Disabled from map layout view's "order a taxi"  
2.  Disabled logic for "order a taxi"
=>  [Android] Disable/hide "order a taxi" button

android/res/layout/layout_nav_bottom.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/routing/NavigationController.java, android/src/com/mapswithme/maps/widget/menu/NavMenu.java
**Changed**  :  
Disabled the traffic button and logic in navigation mode
=> [Android]Disable/hide the traffic button in navigation mode

android/res/layout/place_page_preview_rating.xml, android/src/com/mapswithme/maps/ugc/UGCController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
**Changes**  :
Disabled the place reviews  logic and view's from layout.
=> [Android] Disabled the place reviews 

android/res/layout/routing_plan.xml, android/src/com/mapswithme/maps/routing/RoutingPlanController.java
**Changes**  :  
- Disabled the taxi option in routing logic and view's from layout.
=> [Android] Disabled the taxi option in routing

android/res/layout/fragment_ugc_route_edit.xml, android/res/menu/menu_bookmark_categories.xml, android/res/menu/menu_bookmarks_list.xml, android/src/com/mapswithme/maps/bookmarks/BaseBookmarkCategoriesFragment.java, android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java, android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java, android/src/com/mapswithme/maps/ugc/routes/UgcRouteEditSettingsFragment.java
**Changes**  :
1.   Disabled logic and view's for  bookmark synchronization #75
=> [Android] Disable bookmark synchronization #75

android/res/layout/menu_buttons_line.xml, android/src/com/mapswithme/maps/tips/ClickInterceptorFactory.java, android/src/com/mapswithme/maps/tips/Tutorial.java, android/src/com/mapswithme/maps/widget/menu/MainMenu.java
**Changes**  :  
1. Disabled the discovery button and logic to open Activity #103
=> [Android] Disabled the discovery button #103

drape_frontend/gui/layer_render.cpp, generator/generator_tests_support/test_feature.cpp, map/transit/transit_reader.hpp, platform/local_country_file.cpp, routing/index_graph.hpp
https://github.com/omapsapp/omapsapp/issues/127
=> Removed watermark.

.github/workflows/android-beta.yaml, .github/workflows/android-check.yaml, .github/workflows/desktop-check.yaml, .github/workflows/ios-check.yaml
Get rid of self-hosted CI runner and use GitHub servers instead.
=> [ci] Use shared GitHub runners

.github/workflows/android-beta.yaml, .github/workflows/android-check.yaml, .github/workflows/desktop-check.yaml, .github/workflows/ios-check.yaml
- Enable CI only for PR.
- Add missing keys for Android Beta.
=> [ci] Minor fixes

android/src/com/mapswithme/maps/background/NotificationService.java
**Changes :**   
1. [android] disabled notification's "rate the place" and "leave a review through authorization with the help of accounts in social networks" #145 && #100
=> [Android] [Android] A crash on Google Sign In #145 &&  [Android] Remove "rate the place" screen #100

iphone/Maps/Images.xcassets/Promo/img_booking_popup_pholder_light.imageset/Contents.json, iphone/Maps/TipsAndTricks/SearchTutorialBlur.xib, iphone/Maps/UI/Promo/PromoAfterBookingViewController.swift, iphone/Maps/UI/Promo/PromoAfterBookingViewController.xib
Revert ae4bc37 "Remove graphics" for iphone/ directory
=> [iOS] Fix a compilation error

android/AndroidManifest.xml
Keep library, but revoke the permission.
Closes https://github.com/omapsapp/omapsapp/issues/48
=> [Android] Disable in-app purchases

iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuLayersCell.swift
=> [ios] Fixed crash on isolines click

docs/INSTALL.md
Add actual instructions for desktop/android/ios.
=> [docs] Rewrite INSTALL.md

generator/booking_quality_check/booking_quality_check.cpp, openlr/decoded_path.cpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_mode.cpp, openlr/openlr_stat/openlr_stat.cpp, routing/routing_tests/maxspeeds_tests.cpp, transit/world_feed/subway_converter.cpp
Signed-off-by: vng <viktor.govako@gmail.com>
=> Minor warning fix.

android/build.gradle
TODO: Integrate the latest Android NDK
=> [android] Set required NDK in build.gradle (the latest version does not compile yet)

platform/background_downloader_ios.mm
Without this patch, corrupted maps (HTTP pages) were downloaded.
=> [ios] Properly handle HTTP errors for map downloads

xcode/omim.xcworkspace/contents.xcworkspacedata, xcode/partners_api/partners_api.xcodeproj/project.pbxproj
=> [ios] Minor cleanup

data/countries.txt, data/external_resources.txt
Signed-off-by: vng <viktor.govako@gmail.com>
=> New data from 210317

CMakeLists.txt
Also see https://github.com/mapsme/omim/pull/8825#issuecomment-804592797
=> Explicitly disable C/C++ gnu extensions, we never rely on them

base/condition.cpp, coding/mmap_reader.cpp, indexer/centers_table.cpp, indexer/metadata_serdes.cpp, map/framework.cpp, partners_api/utils.cpp, search/house_to_street_table.cpp
=> 32-bit warning fixes

docs/INSTALL.md
Did something wrong with previous branch for request, here is new fixed request
=> Lon docs install

map/routing_manager.cpp, map/routing_manager.hpp
Signed-off-by: vng <viktor.govako@gmail.com>
=> Fixed routing.

android/AndroidManifest.xml, android/gradle.properties
Do what the latest Gradle ask me to do.
=> [android]: Fix Gradle warnings

iphone/Maps/OMaps.plist
=> [ios] Removed unused permission for remote push notifications

android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java, android/src/com/mapswithme/maps/location/TrackRecorderWakeService.java, android/src/com/mapswithme/maps/maplayer/traffic/widget/TrafficButton.java, android/src/com/mapswithme/maps/tips/ImmersiveModeCompatPromptBackground.java, android/src/com/mapswithme/maps/widget/SubscriptionButton.java, android/src/com/mapswithme/util/UiUtils.java, android/src/com/mapswithme/util/Utils.java
=> [android]: Remove checks for JellyBean and Lollipop

base/base_tests/buffer_vector_test.cpp, base/buffer_vector.hpp, openlr/graph.cpp, openlr/router.cpp, routing/index_graph_starter.cpp, routing/index_graph_starter_joints.hpp, routing/road_graph.cpp, routing/transit_world_graph.cpp
https://github.com/organicmaps/organicmaps/issues/323
=> Fixed routing bug.

iphone/Maps/UI/Storyboard/Main.storyboard
=> [ios] Fixed message renamed by error :)

drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/gps_track_renderer.cpp, drape_frontend/route_renderer.cpp, drape_frontend/route_shape.cpp, drape_frontend/route_shape.hpp, drape_frontend/selection_shape.cpp, drape_frontend/traffic_renderer.cpp, drape_frontend/transit_scheme_builder.cpp, drape_frontend/transit_scheme_builder.hpp, drape_frontend/user_mark_generator.cpp, drape_frontend/user_mark_shapes.cpp, drape_frontend/visual_params.cpp, drape_frontend/visual_params.hpp
- use `std::array` instead of `std::vector` for constants
- use atomic increment instead of mutex
=> Little optimizations

drape/overlay_tree.cpp, drape/overlay_tree.hpp, drape/render_bucket.cpp, drape/render_bucket.hpp, drape_frontend/render_group.cpp, drape_frontend/render_state_extension.cpp, drape_frontend/render_state_extension.hpp, shaders/program_manager.hpp
=> fix work with TRACK_POINTERS enabled

tools/python/stylesheet/drules_merge.py, tools/python/transit/transit_colors_export.py, tools/unix/generate_symbols.sh
Marked as work in progress, because of it requires merged of https://github.com/organicmaps/kothic/pull/1 ,
then I update link to submodule and only then it would be possible to merge.
=> WIP: make possible run of tools/unix/generate_styles.sh without python2

android/build.gradle, iphone/Maps/Maps.xcodeproj/project.pbxproj
=> [android][ios] Change application name to "Organic Maps"

android/src/com/mapswithme/maps/settings/BaseSettingsFragment.java
=> [android] Fix NPE in android.view.View.setPadding

android/res/layout/menu_buttons_line.xml
=> [android] Swapped search and routing buttons

android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/MwmBroadcastReceiver.java, android/src/com/mapswithme/maps/MwmJobIntentService.java, android/src/com/mapswithme/maps/SplashActivity.java
=> [android] Remove lazy initialization of platform

drape_frontend/gui/copyright_label.cpp
=> Show OSM contribution for 10 seconds instead of 2

.github/workflows/linux-check.yaml
I suggest also check `clang` in addition to standard `gcc` build.
=> [ci] Also build using clang

configure.sh
Follow up 13e769af Update applicationId.
=> [android] Fix configure.sh

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/SplashActivity.java, android/src/com/mapswithme/maps/base/BaseMwmFragmentActivity.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/util/Config.java
=> [Android] Work without location permission granted

.gitignore
Network policy is created by ./configure.sh script
=> [android] Updated gitignore

.github/workflows/android-release.yaml, android/build.gradle
=> [android][ci] Actualize stores

indexer/feature_data.cpp
https://github.com/organicmaps/organicmaps/issues/421
=> Fixed PP types to display.

NOTICE, data/copyright.html
=> [legal] Update copyright notices graphics files

android/AndroidManifest.xml, android/src/com/mapswithme/maps/intent/Factory.java, ge0/ge0_tests/parser_tests.cpp, ge0/parser.cpp, iphone/Maps/OMaps.plist, search/search_integration_tests/processor_test.cpp
Followup for this github.com/organicmaps/organicmaps/pull/427
=> Followup review fixes.

.github/workflows/android-beta.yaml, .github/workflows/android-release.yaml, .gitignore, android/.gitignore, android/build.gradle
=> [android][ci] Upload to stores automatically

iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/NavigationControlView.swift, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/NavigationControlView.xib, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/BaseRoutePreviewStatus.swift, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/TransportRoutePreviewStatus.swift, iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm, iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.xib, iphone/Maps/UI/PlacePage/Components/PlacePageDividerViewController.swift, iphone/Maps/UI/PlacePage/PlacePage.storyboard, iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
=> [ios] Fixed navigation bar

private_default.h
Fixes #451
@rtsisyk how to push update to F-Droid? But also please merge my another PR first
=> [android][ios] Added public credentials for OSM login to make it work on FDroid

android/AndroidManifest.xml
Настроил на домене верификацию для айоса и ведра.
=> [android] Added verification for deep linking

android/jni/com/mapswithme/maps/Framework.cpp, android/res/layout/about.xml, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, iphone/Maps/Core/Location/MWMLocationManager.mm, iphone/Maps/Core/Routing/MWMCoreRouterType.h, iphone/Maps/Core/Routing/MWMRouter.mm, iphone/Maps/Core/Routing/MWMRouterType.h, iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm, iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManagerHelper.h, iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManagerHelper.mm, map/framework.cpp, map/routing_manager.cpp, qt/routing_settings_dialog.cpp, routing/router.cpp, routing/router.hpp
Closes https://github.com/organicmaps/organicmaps/issues/461
Closes https://github.com/organicmaps/organicmaps/issues/310
Closes https://github.com/organicmaps/organicmaps/issues/458
=> [android] Fixed minor bugs.

android/build.gradle
=> [android] Allow x86 builds for emulator

android/AndroidManifest.xml
=> [android] Fix TTS on Android 11+

android/AndroidManifest.xml, android/src/com/mapswithme/maps/intent/Factory.java, ge0/parser.cpp
=> [android] Fix ge0.me registration

drape_frontend/screen_operations.cpp, drape_frontend/screen_operations.hpp, geometry/geometry_tests/common_test.cpp, geometry/rect2d.hpp, routing/base/astar_algorithm.hpp
Closes https://github.com/organicmaps/organicmaps/issues/544
=> Fixed some issues.

android/AndroidManifest.xml
=> [android] Fix kmz/kml/kmb registration

data/categories.txt
Signed-off-by: Luca Finizio <luca.finizio.mgbx@hotmail.it>
=> Updated categories (2nd version)

android/src/com/mapswithme/maps/settings/StoragePathManager.java
=> [android] Fix crash in buildStorageItem()

android/res/drawable-v23/splash.xml, android/res/drawable/splash.xml
Works on my Android 5. Please check on newer versions too.
=> [android] Fixed crash on startup for Android 5 (API 21)

android/res/values-de/strings.xml, data/strings/strings.txt, iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
Thanks to @Sebbl0508 
Closes #650
=> [Android] Fixed german translation

iphone/Maps/Core/Location/MWMLocationManager.mm
Should fix this https://github.com/organicmaps/organicmaps/issues/625
Testing  ..
=> [iOS] Request InUse location instead of always.

iphone/Maps/OMaps-Debug.entitlements, iphone/Maps/OMaps-Release.entitlements
После установки билда из тестфлайта в General->CarPlay->Car->Customise не появилась наша аппа всё равно.
=> [ios] Added missing CarPlay entitlements

android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
=> [android] Fix bookmark sharing from Categories screen

.github/workflows/android-monkey.yaml, android/build.gradle
=> [android] Run Monkey in debug mode

platform/country_file.cpp, platform/country_file.hpp, routing/index_router.cpp, routing/regions_router.cpp, routing/regions_sparse_graph.cpp
Fixed crash here https://github.com/organicmaps/organicmaps/issues/729 but TODO remains.
=> Fixed routing crash

iphone/Maps/Categories/UIColor+MapsMeColor.h, iphone/Maps/Categories/UIFont+MapsMeFonts.h
TODO: investigate the reason behind them and fix them properly.
=> [ios] Removed annoying deprecation warnings

README.md, docs/DCO.md
=> [docs] Reformat DCO.md

android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
=> [android] Hide "Tracking" section on F-Droid

android/res/values/string-arrays.xml, android/res/xml/prefs_main.xml, android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java, android/src/com/mapswithme/util/Config.java, android/src/com/mapswithme/util/NetworkPolicy.java
=> [android] Fix "Mobile Internet" settings

android/AndroidManifest.xml, android/src/com/mapswithme/maps/downloader/MapDownloadManager.java
https://user-images.githubusercontent.com/1799054/123542592-15077600-d753-11eb-9bf2-5483310f21e9.mp4
Display the downloading progress in Android UI.
=> [android] Enable DownloadManager notifications

android/src/com/mapswithme/maps/bookmarks/ChooseBookmarkCategoryFragment.java
#344 
Signed-off-by: Endem10n <dzmitry.yarmolenka.1986@gmail.com>
=> [android] fixed issue when new bookmark set is not assigned to the bookmark after creation

android/res/layout/activity_map.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
=> [android] removed duplicating top panel for place page

data/faq.html
@laralem Can you please take a look at Portuguese strings? We don't have here pt_BR yet.
=> Fixed texts in FAQ

android/HOW_TO_USE_GRADLE.txt
Replaced `<omim>` with `<organicmaps>`
=> Removed 'omim'  from HOW_TO_USE_GRADLE.txt

android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
Follow up 5f09e5c3 "Hide "Tracking" section on F-Droid"
=> [android] Fix regression in preferences

android/res/layout-land/layout_nav_bottom_numbers.xml, android/res/layout/layout_nav_bottom.xml, android/res/layout/layout_nav_bottom_numbers.xml
Closes #693
Fixed issue with broken toolbar in navigation mode. Additionally deleted RTL errors from three layout files I touched.
=> [android] Fixed issue with broken toolbar in navigation mode.

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Closes #715 
Better UX while adding new bookmarks.
=> [android] swap "bookmarks" and "route from" buttons on place page. 

android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
=> [android] Fix NPE at BookmarkManager.getBookmarksFilenameFromUri

android/res/values/themes-attrs.xml, android/res/values/themes-base.xml, android/src/com/mapswithme/maps/widget/placepage/PlacePageUtils.java
Fixed broken invisible chevron for BottomSheet in day theme on PlacePageView.
Before:
After:
=> [android] Fix for chevron in place page view.

android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
#closes https://github.com/organicmaps/organicmaps/issues/722
Did not find the reason: found workaround.
=> [android] fix for place page layout breakdown. 

iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
Set canShowMenu's value to true for address view
Relates to  #736
=> [ios] Enabled address copying for bookmarks

android/src/com/mapswithme/maps/settings/AboutFragment.java
Signed-off-by: Akshit Mangotra <akshitmangotra@gmail.com>
=> Fix #885: Added Instagram Clickable item in About Fragment

data/strings/strings.txt
=> Bulgarian translation of strings.txt

data/categories.txt
=> Bulgarian translation of categories.txt

map/search_mark.cpp, map/search_mark.hpp, routing/index_router.cpp, routing_common/car_model_coefs.hpp
https://github.com/organicmaps/organicmaps/issues/902
=> Routing fixes.

data/strings/strings.txt
I added some updates to Ukrainian locale. But can't run this script `./tools/unix/generate_localizations.sh`
I followed this steps:
1. Run `git submodule update --init --recursive`
2. Run `brew install ruby`
3. Run `./tools/unix/generate_localizations.sh`
4. Get error:
```
+ case $OSTYPE in
+ '[' -x /usr/local/opt/ruby/bin/ruby ']'
+ PATH=/usr/local/opt/ruby/bin:/Users/edbond/.nvm/versions/node/v14.16.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
++ dirname ./tools/unix/generate_localizations.sh
+ OMIM_PATH=./tools/unix/../..
+ TWINE=./tools/unix/../../tools/twine/twine
+ STRINGS_PATH=./tools/unix/../../data/strings
++ mktemp
+ MERGED_FILE=/var/folders/mp/_qdv23fx6tlgdjkx69nk94l40000gn/T/tmp.wOzPX7dx
+ cat ./tools/unix/../../data/strings/strings.txt …
```
=> [strings] Update Ukrainian locale

android/src/com/mapswithme/maps/sound/AudioFocusManager.java, android/src/com/mapswithme/maps/sound/TtsPlayer.java
Closes https://github.com/organicmaps/organicmaps/issues/793
[example video](https://drive.google.com/file/d/18LmT5OcPo35Ni_iZ9KykY0n3SFZJWfBZ/view?usp=sharing)
=> [android] silence media volume while announcing navigation directions

android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java, android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java, android/src/com/mapswithme/maps/bookmarks/Holders.java, android/src/com/mapswithme/maps/bookmarks/OnItemMoreClickListener.java
Signed-off-by: Sean Connelly seanconn256@protonmail.com
=> connect bookmark more button to context menu

iphone/Maps/Bookmarks/Categories/Category settings/CategorySettingsViewController.swift
=> [ios] Close List Settings on Save

generator/srtm_parser.cpp
Actually, from highly compressed files inside a squashfs container which takes significantly less space.
I'll mount squashfs container later.
=> [generator] Read elevations data from uncompressed files

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/Utils.java
Needs confirmation from the user by email.
=> [android] Fixed wrong encoding for Russian text in bookmarks description

search/search_params.hpp
Test case: "Rua Ari Carneiro Fernandes, São Paulo"
See https://t.me/organicmaps/6073
=> [android] Increased search timeout to improve search results on slow devices

tools/python/transit/gtfs/download_gtfs.py
Added support for transitland API V2 with the api key.
=> Added support for transitland api V2

routing/cross_border_graph.cpp, routing/cross_border_graph.hpp, routing/routing_integration_tests/absent_regions_finder_tests.cpp
=> [generator] Fixed CrossBorderGraphSerializer.

android/AndroidManifest.xml, android/src/com/mapswithme/maps/intent/Factory.java
Fixes integration with Export file in MAPS.ME.
=> [android] Add support for ACTION_SEND intents

kml/CMakeLists.txt, kml/kmb_to_kml/CMakeLists.txt, kml/kmb_to_kml/kmb_to_kml.cpp
It helped one user, maybe help someone else too.
=> Console tool to convert KMB to KML

routing/index_graph_starter.cpp, routing/index_graph_starter.hpp
Closes https://github.com/organicmaps/organicmaps/issues/1008
=> [routing] Fixed bug with detecting no-pass-through on start/finish.

.gitignore, data/strings/strings.txt
Terminology translation:
- Download -- спампоўка, спампаваць
- Upload -- запампоўка, запампаваць
- Loading -- загрузка
- Map -- мапа
- Location Services -- геалакацыя
- Device -- прылада
- Routing -- пракладка маршрута
- Route -- маршрут
- Application -- дадатак
- Connection -- злучэнне
- Settings -- налады
- Set up -- наладзіць
- Set -- група
- Bookmark -- закладка
- Pin -- метка
- Install -- усталяваць
- Back Screen -- задні экран
- Track -- сцежка
- Offline -- offline
- Starting point -- пункт адпраўлення
- Destination (point) -- пункт прызначэння
- Calculate the route -- пракласці маршрут
- Location -- месцазнаходжанне
- Projected path -- шлях
- Feedback -- водгук
- Email -- email
- Edit -- правіць
- Valid -- правільны
- Traffic -- рух
- Traffic data -- інфармацыя пра рух
- Log -- …
=> Belarusian localization

tools/unix/generate_symbols.sh
=> Improved symbols generator script: added png recompressing step.

android/res/values-fr/strings.xml, data/strings/types_strings.txt, iphone/Maps/LocalizedStrings/fr.lproj/Localizable.strings
Signed-off-by: Christophe Bastin <christophe.bastin@posteo.net>
=> Fix wrong french translation

.github/workflows/android-beta.yaml, .github/workflows/android-check.yaml, .github/workflows/android-monkey.yaml, .github/workflows/android-release.yaml, CMakeLists.txt, android/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties, docs/INSTALL.md
Android Studio 2021.3.1 is out
=> [android] Update to the latest Android Gradle Plugin

android/jni/com/mapswithme/maps/MapManager.cpp, android/src/com/mapswithme/maps/downloader/CountryItem.java, android/src/com/mapswithme/maps/downloader/CountrySuggestFragment.java, android/src/com/mapswithme/maps/downloader/DownloaderStatusIcon.java, android/src/com/mapswithme/maps/downloader/OnmapDownloader.java
=> [android] Use fractional progress in downloads

android/res/drawable/ic_menu_report.xml, android/res/layout/menu_content.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/widget/menu/MainMenuOptionListener.java, android/src/com/mapswithme/maps/widget/menu/MainMenuRenderer.java
=> [android] Add "Report a bug" button to main menu

android/src/fdroid/play/release-notes/en-US/default.txt
Будем и этот и гугловый файлы обновлять в будущем в одном PR? Или как?
=> [fdroid][android] Updated whats new

android/build.gradle
And minor update of android gradle plugin
=> [android] Use build tools version from gradle.properties

android/res/values-de/strings.xml, data/strings/strings.txt, iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
=> Fixed German translation for avoid roads

android/build.gradle
Use the number of commits in the current day for version
=> [android] Unify version generation with iOS

android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
=> [android] Don't download maps automatically on F-Droid

android/jni/com/mapswithme/maps/DownloadResourcesLegacyActivity.cpp, platform/platform.cpp, platform/platform.hpp, private_default.h
=> [platform] Remove RESOURCES_METASERVER_URL artifact

.github/workflows/android-release.yaml
=> [ci][android] Enable automatic Android releases

editor/editor_tests/osm_editor_test.cpp, editor/osm_editor.cpp, editor/osm_editor.hpp, map/framework.cpp, tools/unix/build_omim.sh
=> Editor typo fix

android/src/com/mapswithme/maps/editor/EditorFragment.java
Greetings of the day, 
Please review the pr and let me know in case of any changes if required.
Thanks & Regards 
Shikhar Vashistha
Fixed : #1255
=> Fixed wifi toggling using edit phone

android/res/values-cs/strings.xml, data/strings/strings.txt, iphone/Maps/LocalizedStrings/cs.lproj/Localizable.strings
Previous "Day and Night" didn't make a sense.
=> Fix Czech translation of twentyfour_seven

android/src/google/play/listings/en-US/full-description.txt
=> [android] Updated store description

android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java, android/src/com/mapswithme/util/Utils.java
Follow up 1f8c0667b "fix for place page layout breakdown".
=> [android] Add a workaround for broken PlacePageView after Search/Edit

generator/routing_world_roads_generator.cpp, generator/world_roads_builder/world_roads_builder.cpp, routing/absent_regions_finder.cpp, routing/absent_regions_finder.hpp, routing/base/astar_algorithm.hpp, routing/cross_border_graph.cpp, routing/cross_border_graph.hpp, routing/directions_engine.cpp, routing/edge_estimator.cpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_graph_starter_joints.hpp, routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/leaps_graph.cpp, routing/leaps_graph.hpp, routing/regions_decl.hpp, routing/regions_router.cpp, routing/regions_router.hpp, routing/regions_sparse_graph.hpp, routing/routing_helpers.cpp, routing/routing_helpers.hpp, routing/routing_options.cpp, routing/world_graph.hpp, routing_common/num_mwm_id.hpp
Closes https://github.com/organicmaps/organicmaps/issues/333
=> [routing] Fixed crash in cross-mwm checks for long distance.

3party/stb_image/stb_image.h, 3party/stb_image/stb_image_write.h, generator/world_roads_builder/CMakeLists.txt, generator/world_roads_builder/world_roads_builder_tool/CMakeLists.txt, routing/routes_builder/CMakeLists.txt, routing/routes_builder/routes_builder_tool/CMakeLists.txt, routing/routing_benchmarks/CMakeLists.txt, routing/routing_consistency_tests/CMakeLists.txt, routing/routing_integration_tests/CMakeLists.txt, routing/routing_quality/CMakeLists.txt, routing/routing_quality/routing_quality_tests/CMakeLists.txt, routing/routing_quality/routing_quality_tool/CMakeLists.txt
At least, this patch fixes routing_integration_tests compilation on Ubuntu.
=> [3party] Updated stb_image.

data/categories.txt, data/categories_cuisines.txt, data/strings/strings.txt
Reviewed and updated french translation, I will continue with data/strings/types_strings.txt and do another PR later
=> update french translation in strings.txt categories.txt categories_cuisines.txt 

data/strings/types_strings.txt
Reviewed and updated french translation
=> update french translations in types_strings.txt

data/strings/strings.txt
Signed-off-by: Leonardo Alcaraz leoalcaraz130@gmail.com
=> I add and fix Spanish translations

docs/INSTALL.md
Signed-off-by: Konstantin Pastbin <konstantin.pastbin@gmail.com>
=> [docs] Update Android dev environment setup

android/res/layout/search_filter_panel.xml
=> [android] Do not pass clicks to the hidden bottom bar

android/build.gradle
Now we have some unnecessary vulkan libs in the apk. This PR removes them.
=> [android] Removed unnecessary libs for x86 archs from apk

android/gradle.properties
See discussion https://github.com/organicmaps/organicmaps/discussions/1538
=> [build] Disable parallel builds and reduce JVM heap

android/res/layout/menu_buttons_line.xml, android/res/layout/menu_news_marker.xml, android/src/com/mapswithme/maps/widget/menu/MainMenu.java
=> [android] Restored back accidentally removed "updated maps" indicator

data/strings/sound.txt
Use a longer and clearer version.
=> Improve chinese translation for destination

data/strings/strings.txt, data/strings/types_strings.txt
All translations by nautilusx (https://hosted.weblate.org/user/nautilusx/)
=> [strings] Import German translations from Weblate

android/HOW_TO_USE_GRADLE.txt, docs/INSTALL.md, tools/python/maps_generator/README.md, tools/unix/build_omim.sh
As per https://github.com/organicmaps/organicmaps/discussions/1538
WIP
=> Improve build/dev environment setup instructions

data/strings/types_strings.txt
Update Russian translations in types_strings.txt
Signed-off-by: dbf <dbf256@gmail.com>
=> [strings] Update Russian translations in types_strings.txt

android/res/values-ru/strings.xml, data/strings/types_strings.txt, iphone/Maps/LocalizedStrings/ru.lproj/Localizable.strings
Fix https://github.com/organicmaps/organicmaps/pull/1601#pullrequestreview-813522777
=> Fix translations

data/countries.txt, data/external_resources.txt, map/map_tests/countries_names_tests.cpp
Closes https://github.com/organicmaps/organicmaps/issues/1524
Closes https://github.com/organicmaps/organicmaps/issues/1389
Closes https://github.com/organicmaps/organicmaps/issues/1206
=> [planet] New data from 211122.

data/categories.txt, data/strings/types_strings.txt
@vng 
Is it better to add `generate_localizations.sh` changes to this PR or as a separate one?
=> [strings] Added natural.water.* and natural.beach.* types

CONTRIBUTORS, data/strings/types_strings.txt
Translation to Ukrainian courtesy of Karina Kordon.
To help choose between translation variants we consulted
relevant OSM wiki articles (and Wikipedia sometimes).
E.g. changed "Раскопки" to "Археологический памятник"
according to https://wiki.openstreetmap.org/wiki/RU:Tag:historic%3Darchaeological_site
=> [strings] UK and RU translation additions and changes

android/src/google/play/listings/en-US/title.txt, android/src/google/play/release-notes/en-US/default.txt, iphone/metadata/en-US/release_notes.txt
=> [android][ios] Update whatsnew

data/strings/strings.txt
The Turkish translation has been corrected and updated.
=> Update Turkish translation

data/strings/types_strings.txt
Signed-off-by: Lukas Kronberger j13m126@posteo.de
=> added German translations

data/strings/types_strings.txt
Added german (de) and greek (el) translations for aerialway.
Signed-off-by: Christos Sidiropoulos <csidirop@runbox.com>
=> Updated translations in types_strings.txt

data/categories_cuisines.txt
Added/Updated strings for german (de) and greek (el). And hopefully fixed my previous DCO mistake.
Signed-off-by: Christos Sidiropoulos <csidirop@runbox.com>
=> Updated de and el translations categories_cuisines.txt

android/res/layout-land/routing_details.xml, android/res/layout-w1020dp-land/routing_details.xml, android/res/layout/routing_details.xml, android/src/com/mapswithme/maps/routing/RoutingBottomMenuController.java, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/util/Utils.java
=> [android] Ellipsize routing time & distance strings from the end

docs/INSTALL.md
Add a way to switch map language.
Needed-for: #1638
=> [docs] Update desktop app running options

android/jni/com/mapswithme/maps/sound/tts.cpp, android/src/com/mapswithme/maps/sound/AudioFocusManager.java
=> Android: do not stop music playback for announced TTS voice directions

data/strings/strings.txt, data/strings/types_strings.txt
[type.leisure.beach_resort] was missing.
=> [strings] Added leisure.beach_resort; minor fixes

data/strings/strings.txt, data/strings/types_strings.txt
I checked and 16 Norwegian "no" strings are Norwegian Bokmål "nb" actually (like all other Norwegian translations we have).
=> [strings] Re-sort and change "no" to a more correct "nb"

routing/route_weight.cpp, routing/route_weight.hpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/turn_test.cpp
Closes https://github.com/organicmaps/organicmaps/issues/1788
=> [routing] New RouteWeight::operator<

data/strings/types_strings.txt
=> [strings] Ukrainian types_strings.txt translations

data/strings/strings.txt, tools/python/clean_strings_txt.py, tools/unix/generate_localizations.sh
=> Don't add android localization strings into ios files and vice versa

android/AndroidManifest.xml, android/build.gradle, android/gradle.properties
=> [android] Bump SDK versions and update dependencies

data/faq.html
@pastk Should fix https://github.com/organicmaps/organicmaps/pull/1819#discussion_r781267347
=> [android] Fixed FAQ not working on Android 5.0 emulator

android/res/xml/prefs_main.xml, android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
=> [android] Fix "Help" menu in settings

android/AndroidManifest.xml
Issue was caused by Android 12 requirements to define exported: https://developer.android.com/about/versions/12/behavior-changes-12
=> [android] Fixed regression with opening KML files

generator/region_meta.cpp, indexer/feature.cpp, indexer/feature.hpp, routing/async_router.cpp, routing/base/astar_algorithm.hpp, routing/cross_mwm_connector.hpp, routing/index_graph_starter_joints.hpp, routing/index_router.cpp, routing/route.cpp, routing/routing_integration_tests/route_test.cpp, search/search_quality/matcher.cpp
Fixing routing issues here, assuming that all needed MWMs are downloaded.
Getting a valid set of MWMs to download is a tricky task now and should be solved separately. Issues stay open until this moment.
https://github.com/organicmaps/organicmaps/issues/1627
https://github.com/organicmaps/organicmaps/issues/1736
https://github.com/organicmaps/organicmaps/issues/1721
https://github.com/organicmaps/organicmaps/issues/338
=> [routing] Cross MWM fixes + tests.

data/categories.txt
=> Updated TR translations categories.txt

iphone/metadata/tr-TR/name.txt
=> Name Translated to Turkish

android/src/google/play/release-notes/tr-TR/default.txt
=> Release Notes translated to Turkish

android/src/fdroid/play/listings/tr-TR/full-description.txt
=> Full Description Translated to Turkish

android/src/fdroid/play/listings/tr-TR/short-description.txt
=> Short-Description Translated to Turkish

android/src/fdroid/play/listings/tr-TR/title.txt
=> Title Translated to Turkish

iphone/metadata/tr-TR/subtitle.txt
=> Translated to Turkish

data/strings/types_strings.txt, indexer/feature_data.cpp
=> [core] Lower priority of public_transport=platform type

generator/generator_tests/osm_type_test.cpp, generator/osm2type.cpp
Closes https://github.com/organicmaps/organicmaps/issues/1957
=> [generator] Road's smoothness and paving updates.

iphone/Maps/UI/Help/FaqController.swift
=> [ios] Open FAQ links in Safari

data/categories.txt
Signed-off-by: Luca Finizio <luca.finizio.mgbx@hotmail.it>
=> Add it translations for category [Bakery]

data/faq.html
=> Added Turkish to FAQ

data/categories.txt
Signed-off-by: Luca Finizio luca.finizio.mgbx@hotmail.it
=> Added [it] translation for sport-equestrian

data/categories.txt
Signed-off-by: Luca Finizio luca.finizio.mgbx@hotmail.it
=> Add translations

data/strings/sound.txt
Signed-off-by: Lukas Kronberger j13m126@posteo.de
=> fix german translation

data/categories.txt
Signed-off-by: Luca Finizio luca.finizio.mgbx@hotmail.it
=> Add translation

android/AndroidManifest.xml, android/res/xml/backup_content_v31.xml
See https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-12
=> [android] Support autobackup on Android 12+

data/countries.txt, data/external_resources.txt, map/mwm_tests/CMakeLists.txt, map/mwm_tests/world_map_test.cpp
Closes https://github.com/organicmaps/organicmaps/issues/1271
Closes https://github.com/organicmaps/organicmaps/issues/2020
Closes https://github.com/organicmaps/organicmaps/issues/2057
=> [planet] New data from 220204.

android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/src/com/mapswithme/maps/bookmarks/data/Metadata.java, indexer/feature_meta.hpp
Closes https://github.com/organicmaps/organicmaps/issues/2072
=> [android] Skip description metadata processing.

data/strings/types_strings.txt
Signed-off-by: Lukas Kronberger j13m126@posteo.de
=> added some zh-Hant translations

map/caching_address_getter.hpp, map/framework.cpp, map/framework.hpp
Needed to get the address at my position.
=> [search] Pass threshold in meters as a parameter in GetAddressAtPoint

routing/index_router.cpp, routing/routing_integration_tests/absent_regions_finder_tests.cpp, routing/routing_integration_tests/cross_country_routing_tests.cpp, routing/routing_integration_tests/route_test.cpp
Closes https://github.com/organicmaps/organicmaps/issues/2085
=> [routing] Proper fix in Cross-MWMs loops.

android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java, android/src/com/mapswithme/maps/intent/Factory.java, android/src/com/mapswithme/maps/intent/IntentProcessor.java
=> [android] Refactor intent processing

data/welcome.html
Signed-off-by: Aidan Ueda <little.banana.peel@gmail.com>
=> Fixed wording and typos for welcome page

3party/freetype/CMakeLists.txt, base/stats.hpp, base/timer.hpp, coding/bwt_coder.hpp, coding/coding_tests/bwt_coder_tests.cpp, coding/reader_cache.hpp, coding/text_storage.hpp, drape/binding_info.hpp, drape/overlay_handle.cpp, drape/overlay_handle.hpp, drape/overlay_tree.cpp, drape/overlay_tree.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/shape_view_params.hpp, drape_frontend/user_event_stream.cpp, generator/feature_builder.cpp, generator/feature_builder.hpp, indexer/classificator.cpp, indexer/classificator.hpp, indexer/editable_map_object.cpp, indexer/feature.cpp, indexer/feature.hpp, indexer/feature_data.cpp, indexer/feature_data.hpp, indexer/feature_meta.cpp, indexer/feature_meta.hpp, indexer/types_mapping.hpp, map/framework.cpp, storage/storage_tests/country_info_getter_tests.cpp
=> A bunch of performance fixes.

android/src/com/mapswithme/maps/location/AndroidNativeProvider.java
=> [android] Fix a regression on Android 11 and older

docs/INSTALL.md
Updated SDK version in accordance with targetSdk. Order of paragraphs was changed to prevent inability to change heap size when gradle already started building and made Studio hang. Made suggestion for initial emulator configuration for novice contributors.
Signed-off-by: Vladislav Tchyornyy <votcher@protonmail.com>
=> [docs] Updated Android environment documentation

platform/downloader_defines.hpp, storage/storage.cpp
Fixed possible crash when SHA calculating is long and blocks main thread.
=> [storage] Calculate and check SHA in separate thread.

data/categories.txt, data/strings/strings.txt, data/strings/types_strings.txt
Signed-off-by: Babin Ion <ionbabin123@mail.ru>
Closes https://github.com/organicmaps/organicmaps/issues/2163
=> Improved romanian translation

data/categories_cuisines.txt, data/mapcss-mapping.csv, data/strings/types_strings.txt
Signed-off-by: Aidan Ueda <little.banana.peel@gmail.com>
=> Add cuisine=bubble_tea

android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
Closes #2149
##
Not tested yet.
See https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest#setMaxWaitTime(long) for details.
=> [android] Wait a few seconds for accurate locations initially

android/jni/com/mapswithme/platform/Platform.cpp, base/base_tests/file_name_utils_tests.cpp, base/base_tests/string_utils_test.cpp, base/file_name_utils.cpp, base/file_name_utils.hpp, base/string_utils.cpp, base/string_utils.hpp, generator/generator_tests/camera_collector_tests.cpp, generator/generator_tests/osm_type_test.cpp, generator/generator_tests/speed_cameras_test.cpp, generator/generator_tests_support/test_mwm_builder.cpp, generator/world_roads_builder/world_roads_builder_tool/world_roads_builder_tool.cpp, indexer/transliteration_loader.cpp, platform/local_country_file.cpp, platform/localization.cpp, platform/platform.cpp, platform/platform.hpp, platform/platform_android.cpp, platform/platform_ios.mm, platform/platform_linux.cpp, platform/platform_mac.mm, platform/platform_tests/apk_test.cpp, platform/platform_tests/platform_test.cpp, platform/platform_win.cpp, routing/routing_tests/cross_border_graph_tests.cpp, search/search_tests/house_detector_tests.cpp, storage/storage.cpp, track_analyzing/track_analyzer/cmd_gpx.cpp, track_analyzing/track_analyzer/cmd_unmatched_tracks.cpp
=> Better platform directories handling

android/src/fdroid/play/release-notes/en-US/default.txt, android/src/fdroid/play/release-notes/tr-TR/default.txt, iphone/metadata/en-US/release_notes.txt, iphone/metadata/tr/release_notes.txt
Did I forget something?
@MetehanOzyurek You can translate it into Turkish and paste texts here, I'll change files.
=> Updated WhatsNew

iphone/Maps/LocalizedStrings/es-MX.lproj/InfoPlist.strings, iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/pt-BR.lproj/Localizable.strings
=> Twine base lang

android/res/layout-land/layout_nav_search.xml, android/res/layout-land/map_navigation_buttons.xml, android/res/layout/layout_nav_search.xml
Надо протестить, фиксил без теста.
=> [android] Fixed RTL zoom buttons covered by Search and Bookmarks in Routing mode

data/categories.txt
Signed-off-by: Luca Finizio <luca.finizio@protonmailcom>
=> [strings] it traslations in categories.txt

data/strings/types_strings.txt
=> [strings] it translations in type_strings.txt

data/strings/types_strings.txt
=> [strings] Fix typing error

data/strings/types_strings.txt
Signed-off-by: Lukas Kronberger j13m126@posteo.de
=> [strings] DE update

3party/sdf_image/sdf_image.cpp, drape/glyph_manager.cpp
Closes https://github.com/organicmaps/organicmaps/issues/2313
After:
=> [drape] Fixed bug with glyph's heights.

data/categories.txt
=> [strings] Additions to categories.txt

data/editor.config, indexer/editable_map_object.cpp, indexer/feature_meta.cpp, indexer/interval_index.hpp
Fixes #2349 (but empty changesets will still be created in case of strange errors like this one, unfortunately, it's not feasible to fix).
=> [editor] Fixed wrong descriptions serialization in the edits.xml

data/strings/types_strings.txt
=> [strings] Add it translation

android/src/com/mapswithme/maps/background/Notifier.java
=> [android] Add missing PendingIntent.FLAG_IMMUTABLE flag

routing/turns_generator.cpp
Fixes: #2262
Signed-off-by: Anton Makouski anton.makouski@gmail.com
=> [routing] Remove unnecessary "keep left/right" directions from the route

platform/platform_linux.cpp
=> [desktop] Use XDG path for settings

data/editor.config, editor/xml_feature.cpp, indexer/feature_meta.cpp
Этой правки достаточно, чтобы при генерации данные из этого тега сохранились?
=> Get phone from "mobile" OSM tag

README.md
=> Add Flathub badge to README

storage/storage_helpers.cpp
=> [storage] Fix updates free space regression

tools/python/transit/transit_graph_generator.py
It is used now in our subway generator.
=> Save space in JSON for subways

android/src/google/play/listings/ru-RU/full-description.txt, android/src/google/play/listings/ru-RU/short-description.txt, android/src/google/play/listings/ru-RU/title.txt
Finally I was able to create symlinks in git!
I spend a lot of time reading stackoverflow/trying different option/etc but was not able to do a valid symlinks on Windows and finally made a checkout to unix vps. Do you think I should update install.md doc with suggestion to use linux for such change or you know a valid way to do it on Windows (I think it should be added to docs in this case to make it easier for future devs).
=> Add symlinks for google play

data/categories.txt, indexer/mwm_set.hpp, indexer/rank_table.cpp, map/framework.cpp, search/intermediate_result.cpp, search/intermediate_result.hpp, search/lazy_centers_table.cpp, search/pre_ranker.cpp, search/pre_ranker.hpp, search/ranker.cpp, search/ranker.hpp, search/result.cpp, search/result.hpp, search/search_quality/search_quality_tests/CMakeLists.txt, search/search_quality/search_quality_tests/benchmark_tests.cpp, search/search_quality/search_quality_tests/sample_test.cpp, search/search_tests/ranking_tests.cpp, search/search_tests/results_tests.cpp, search/search_tests_support/helpers.cpp, search/search_tests_support/test_search_engine.cpp, search/search_tests_support/test_search_request.cpp, search/suggest.cpp, search/suggest.hpp
Measured by simple benchmark test (also in PR) on downloaded Germany.
=> [search] Speed-up search results processing (approx - 10%).

android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java, android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/jni/com/mapswithme/maps/LocationState.cpp, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/util/LocationUtils.java, base/base_tests/small_set_test.cpp, drape/overlay_tree.cpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.hpp, drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp, iphone/Maps/Core/Location/MWMLocationHelpers.h, iphone/Maps/Core/Routing/MWMRouter.mm, map/framework.cpp, map/framework.hpp, platform/settings.cpp, platform/settings.hpp, routing/routing_tests/opening_hours_serdes_tests.cpp
Closes https://github.com/organicmaps/organicmaps/issues/2454
Closes https://github.com/organicmaps/organicmaps/issues/2400
Closes https://github.com/organicmaps/organicmaps/issues/1128
=> [android] Ignore possible false-positive location availability.

android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java, android/src/com/mapswithme/maps/settings/StoragePathManager.java, android/src/com/mapswithme/util/StorageUtils.java, platform/platform.hpp, platform/platform_unix_impl.cpp
Also removed unused GetWritableStorageSpace() and added debug logging for free space checks
Needed for #2441
=> Make 'Save maps to' menu item always visible

generator/intermediate_elements.hpp, generator/relation_tags.cpp
Closes https://github.com/organicmaps/organicmaps/issues/2462
=> [generator] Fixed regression after adding std::string_view.

routing/index_graph_loader.cpp
Closes https://github.com/organicmaps/organicmaps/issues/2463
=> [routing] Do not use Restrictions for pedestrian routing.

android/src/google/play/listings/tr-TR/full-description.txt
=> Changed description after Google Play rejection

android/src/fdroid/play/listings/tr-TR/full-description.txt
=> Fixed a typo

iphone/Maps/Categories/UIKitCategories.m
=> [ios] Open URLs without http(s)

data/strings/strings.txt
Hello,
I've saw this text mistake in French translation while trying the app, so here is a fix.
=> loc: fixed a mistake in French text

docs/TRANSLATIONS.md
=> [docs] Link to the raw strings.txt

data/strings/strings.txt
Hopefully it fixes #2512 PR, where I worked on non-raw file
=> small fixes + new strings (ptbr)

base/limited_priority_queue.hpp, generator/transit_generator.cpp, generator/transit_generator_experimental.cpp, qt/draw_widget.cpp, qt/routing_settings_dialog.cpp, qt/routing_settings_dialog.hpp, routing/base/astar_algorithm.hpp, routing/base/astar_progress.cpp, routing/base/routing_result.hpp, routing/cross_mwm_graph.cpp, routing/cross_mwm_graph.hpp, routing/index_graph_loader.cpp, routing/index_router.cpp, routing/index_router.hpp, routing/leaps_postprocessor.cpp, routing/nearest_edge_finder.cpp, routing/nearest_edge_finder.hpp, routing/regions_router.cpp, routing/road_graph.hpp, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/guides_tests.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/transit_route_test.cpp, routing/routing_session.hpp, routing/routing_tests/astar_algorithm_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/routing_algorithm.cpp, routing_common/pedestrian_model.cpp
Updates (ToDo: Upgrade IsFencedOff function with lakes, fences, ...):
https://github.com/organicmaps/organicmaps/issues/788
https://github.com/organicmaps/organicmaps/issues/2546
Closes https://github.com/organicmaps/organicmaps/issues/2199
Closes https://github.com/organicmaps/organicmaps/issues/2492
Closes https://github.com/organicmaps/organicmaps/issues/1773
Closes https://github.com/organicmaps/organicmaps/issues/2494
=> [routing] Fixed start/finish points snapping on graph.

routing/car_directions.cpp, routing/routing_integration_tests/turn_test.cpp
Fixed #2570. 
Test added.
Assert fixed.
=> [Routing] Don't ignore service roads on small roundabouts.

tools/unix/version.sh
The previous version wasn't stable and didn't work in some cases.
=> Fixed version and commits number script

generator/maxspeeds_builder.cpp, generator/mini_roundabout_transformer.cpp, generator/routing_helpers.hpp, routing/routing_integration_tests/route_test.cpp
=> [generator] Do not reduce speeds from parent links in MaxspeedsMwmCollector.

docs/TRANSLATIONS.md
Signed-off-by: dbf <dbf256@gmail.com>
=> [docs] Fix typo

routing/data_source.hpp, routing/directions_engine.cpp, routing/directions_engine_helpers.cpp, routing/directions_engine_helpers.hpp, routing/features_road_graph.cpp, routing/features_road_graph.hpp, routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/index_router.cpp, routing/road_graph.cpp, routing/road_graph.hpp, routing/routing_tests/astar_algorithm_test.cpp, routing/routing_tests/astar_router_test.cpp, routing/routing_tests/road_graph_builder.hpp, routing/routing_tests/routing_algorithm.cpp, routing/routing_tests/routing_algorithm.hpp
https://github.com/flathub/app.organicmaps.desktop/issues/2
https://github.com/flathub/app.organicmaps.desktop/issues/3
Closes https://github.com/organicmaps/organicmaps/issues/2604
=> [routing] Fixed possible out_of_range error and free MwmHandles.

android/src/com/mapswithme/maps/settings/StoragePathManager.java, android/src/com/mapswithme/util/StorageUtils.java
=> [android] Removed excess SecurityException catch

routing/base/astar_algorithm.hpp, routing/index_router.cpp
Closes https://github.com/organicmaps/organicmaps/issues/2646
=> [routing] Fixed minor bug in LeapsMode.

generator/intermediate_data.hpp
Signed-off-by: Jeroen Hoek <mail@jeroenhoek.nl>
Fixes #2667.
=> Fix build error on Ubuntu 20.04/g++ 9.4.0

docs/INSTALL.md
=> Add note about cmake on Ubuntu 20.04

3party/opening_hours/CMakeLists.txt, android/build.gradle, android/proguard-mwm.txt, docs/INSTALL.md, routing_common/vehicle_model.cpp
=> Fixed R8 release/beta issues, switched to a newer NDK

data/categories.txt
=> Add shorthand search terms 'Uni' and 'Hbf'

android/src/com/mapswithme/maps/settings/StoragePathManager.java, android/src/com/mapswithme/util/StorageUtils.java
=> [android] Add extra storage writability logging to ease debugging

android/src/fdroid/play/release-notes/en-US/default.txt, android/src/fdroid/play/release-notes/tr-TR/default.txt, iphone/metadata/en-US/release_notes.txt, iphone/metadata/tr/release_notes.txt
@MetehanOzyurek Please add Turkish translations.
=> Updated release notes

data/categories.txt, data/strings/strings.txt, data/strings/types_strings.txt
Reviewed and completed french translations
=> [strings] update french translations

data/strings/types_strings.txt
=> [strings] Added italian translations 2°

3party/opening_hours/opening_hours_integration_tests/CMakeLists.txt
As suggested by @biodranik [in this comment](https://github.com/flathub/app.organicmaps.desktop/pull/8#discussion_r895190182)
=> [cmake][opening_hours] Replace dependency on rsync

CMakeLists.txt
=> [android] Fixed build on Mac

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/MwmApplication.cpp, android/jni/com/mapswithme/platform/Platform.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/settings/StoragePathFragment.java, android/src/com/mapswithme/maps/settings/StoragePathManager.java, android/src/com/mapswithme/util/Config.java
- don't use separate native code for setting StoragePath
- single source for "StoragePath" setting name
=> [android] Refactor: Move saving of StoragePath setting to android code

android/res/values-es/strings.xml, data/categories.txt, data/strings/strings.txt, data/strings/types_strings.txt, iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/es.lproj/Localizable.strings
=> [strings] Improved Spanish translations

CONTRIBUTORS
=> Added myself to contributors

data/strings/strings.txt
=> [strings] Add italian translations

data/categories.txt, search/processor.cpp, search/search_integration_tests/processor_test.cpp, search/search_integration_tests/utils_test.cpp
Closes https://github.com/organicmaps/organicmaps/issues/2826
=> [search] Match categories with possible stop-words.

qt/draw_widget.cpp, routing/following_info.hpp, routing/route.cpp, routing/route.hpp, routing/routing_tests/route_tests.cpp, routing/routing_tests/routing_helpers_tests.cpp, routing/routing_tests/routing_session_test.cpp, routing/routing_tests/turns_generator_test.cpp
Mostly code style and comments.
=> Small changes for review of #2796

data/strings/types_strings.txt
=> Translated types strings to TR

android/src/com/mapswithme/maps/editor/EditorFragment.java
Should make it easier to modify long mail or website addresses.
Relevant issue: https://github.com/organicmaps/organicmaps/issues/2721
Resolves #2721
Signed-off-by: David Jung <jungwdk@pm.me>
=> [android] Add word-wrapping to text-type editor fields

android/res/values-de/strings.xml, data/strings/strings.txt, data/strings/types_strings.txt, iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
- removed cuisine from strings in order to save space
- some small corrections
=> [strings] de: corrections and small changes

drape/gl_functions.cpp, qt/main.cpp
Fixes flathub/app.organicmaps.desktop#1 only for ES3 capable devices
=> [drape][gl_functions]: Fix assertion failure in ES3 scenario on Linux

data/strings/strings.txt
- false friends (e.g. place: Platz instead of Ort; map layer: Kartenschicht instead of Kartenebene)
- anglizisms (e.g. downloaden instead of herunterladen, loggen instead of auszeichnen)
- stylistics (e.g. Warten Sie mal... instead of Bitte warten...)
- non-grammatical sentences (versuchen Sie den Versuch es erneut; Fahren wir)
- errors (unpaved road: Landstraße instead of unbefestiger Weg)
- add some missing translations
- add singular/plural forms where needed
=> [strings] de: minor fixes and some additions

android/jni/com/mapswithme/maps/editor/Editor.cpp, android/jni/com/mapswithme/util/StringUtils.cpp, android/src/com/mapswithme/maps/editor/CuisineAdapter.java, android/src/com/mapswithme/maps/editor/Editor.java
Moved `osm::Cuisines::Instance()` out of the loop for `Editor.nativeTranslateCuisines(...)` method.
After PR #2921 is closed I found that Editor.cpp could be improved a little too.
Is it possible to create new PR from a branch which was previously merged to master?
=> Cuisine UI speed improvement

data/strings/strings.txt
fix typo introduced in 3b93416
I'm very sorry about it but I only now spotted the typo by chance.
Signed-off-by: Steffen Rehberg <steffen.rehberg@googlemail.com>
=> [strings] de: fix typo

qt/res/app.organicmaps.desktop.metainfo.xml
=> [desktop] Release notes for 2022.07.01-6

tools/python/SiblingKiller.py, tools/python/run_desktop_tests.py, tools/python/testserver.py
Python2 is not installed on latests MacOS and is deprecated since 2020.
Made changes to `run_desktop_tests.py`, `testserver.py` and `SiblingKiller.py`
=> Migrate run_desktop_tests.py to Python3 

drape/stipple_pen_resource.cpp, drape/stipple_pen_resource.hpp, drape/support_manager.cpp, drape/texture_of_colors.cpp, drape/texture_of_colors.hpp
Confirmed by HUAWEI CLT-L29 (HWCLT) user.
=> [drape] Disable vulkan in Mali-G72 to fix pattern drawing.

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardEntity.h, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardEntity.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/NavigationControlView.swift
Next step for #952
Basic attempt.
Show 
`speed / speedLimit`
instead of
`speed`
if speedLimit is known.
=> Show speed limit for iPhone

.github/workflows/android-beta.yaml, .github/workflows/android-check-metadata.yaml, .github/workflows/android-check.yaml, .github/workflows/android-monkey.yaml, .github/workflows/ios-beta.yaml, .github/workflows/ios-check-metadata.yaml, .github/workflows/ios-check.yaml, .github/workflows/ios-release.yaml, .github/workflows/linux-check.yaml, .github/workflows/strings-check.yaml
=> [tools] Properly run GH actions on tool script changes

docs/SUBWAY_GENERATION.md, tools/python/airmaps/sandbox/airmaps/airmaps.ini, tools/python/airmaps/var/etc/airmaps.ini.default, tools/python/maps_generator/README.md, tools/python/maps_generator/var/etc/map_generator.ini.default
Replaced obsolete subways URL with nice and tasty OrganicMaps link.
=> [Docs] Update URL to subways JSON

generator/statistics.cpp, tools/python/maps_generator/generator/statistics.py
Closes https://github.com/organicmaps/organicmaps/issues/3019
=> [generator][script] Fixed stats.

routing/base/astar_progress.cpp, routing/cross_mwm_connector.hpp, routing/cross_mwm_graph.cpp, routing/cross_mwm_graph.hpp, routing/cross_mwm_index_graph.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/leaps_graph.cpp, routing/leaps_graph.hpp, routing/pedestrian_directions.cpp, routing/route.cpp, routing/route.hpp, routing/routing_helpers.cpp, routing/turns.cpp, routing/turns.hpp
This https://github.com/organicmaps/organicmaps/issues/2998 should work faster.
=> [routing] Calculate only start/end sub-routes when resolving best cross-mwm candidate.

android/src/fdroid/play/listings/pt-BR/full-description.txt, android/src/fdroid/play/listings/pt-BR/short-description.txt, android/src/fdroid/play/listings/pt-BR/title.txt, android/src/fdroid/play/release-notes/pt-BR/default.txt, iphone/metadata/pt-BR/description.txt, iphone/metadata/pt-BR/keywords.txt, iphone/metadata/pt-BR/marketing_url.txt, iphone/metadata/pt-BR/name.txt, iphone/metadata/pt-BR/privacy_url.txt, iphone/metadata/pt-BR/promotional_text.txt, iphone/metadata/pt-BR/release_notes.txt, iphone/metadata/pt-BR/subtitle.txt, iphone/metadata/pt-BR/support_url.txt
Hi,
I just added and improved metadata for Portuguese-Brazil (and tried to keep same translations between iPhone and Android strings).
For _what's new_ I already used PR #3003. You can ping me there if there's something else to add (and on next updates, of course).
I couldn't add Symlinked URLs, but feel free to add!
Best,
Signed-off-by: Matheus Correia matheus.gomes03@hotmail.com
=> [strings] - Adding and improving metadata pt-BR

android/src/fdroid/play/release-notes/en-US/default.txt, android/src/fdroid/play/release-notes/tr-TR/default.txt, iphone/metadata/en-US/release_notes.txt, iphone/metadata/tr/release_notes.txt
=> Updated whats new

data/strings/strings.txt
Corrected many translation in terms of grammar and coherency as well as consistency throughout the app. Added a few new translations
Signed-off-by: Michael Roustom <michael.rostom@hiast.edu.sy>
=> Updated Arabic translation

data/strings/strings.txt
few corrections on arabic translations
=> more arabic translations

data/strings/strings.txt
Some new translations, some small edits, and changed from English numbers into Arabic numbers. Also translated OpenStreetMap into the Arabic official name : "خريطة الشارع المفتوحة". Got to 11k line in the file(side note: there are so many strings😩)
Signed-off-by: Michael Rostom <michael.rostom@hiast.edu.sy>
=> Another Arabic translation session

android/res/layout/layout_nav_bottom_numbers.xml
Fixes #3078
Signed-off-by: Harry Bond <endim8@pm.me>
=> [android] fixed routing progress bar covering travel info

qt/res/app.organicmaps.desktop.metainfo.xml
=> [desktop] Release notes for 2022.07.27-3

data/strings/strings.txt
Updated/corrected/added a lot of Arabic translations
Signed-off-by: Michael_Roustom <michael.rostom@hiast.edu.sy>
=> Finished improving the Arabic Translations

data/strings/sound.txt
Signed-off-by: MichaelRoustom michael.rostom@hiast.edu.sy
=> very small changes on some Arabic TTS translation

data/strings/types_strings.txt
As usual I used these tools in following order: wikidata, deepl, google translate.
Also looked for pt-BR and removed pt-BR translations identical to pt
=> [strings] added missing translations for place.*

search/processor.cpp, search/processor.hpp
=> Ignore non-relevant search results (coordinates)

data/faq.html
* Changed "Samsung Apps" to "Galaxy Store"
=> [FAQ] Changed "Samsung Apps" to "Galaxy Store"

data/categories.txt
=> [categories] Added en,it translations

iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/NavigationControlView.swift
=> Fix of #3169

iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
=> [iPhone] Side buttons UI fixes

android/jni/com/mapswithme/maps/DownloadResourcesLegacyActivity.cpp, platform/platform_tests/downloader_utils_tests.cpp, platform/servers_list.cpp, platform/servers_list.hpp, platform/settings.hpp, platform/string_storage_base.cpp, platform/string_storage_base.hpp, search/search_integration_tests/downloader_search_test.cpp, storage/map_files_downloader.cpp, storage/map_files_downloader.hpp, storage/map_files_downloader_with_ping.cpp, storage/map_files_downloader_with_ping.hpp, storage/storage_tests/downloader_tests.cpp
=> [downloader] Extend meta server protocol

platform/servers_list.hpp, storage/storage_tests/downloader_tests.cpp
Как чеки прошли??? Или вы мержили не глядя??
=> Fixed compiler errors

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/intent/Factory.java, iphone/Maps/Classes/MapViewController.mm, iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
Some fixes for backurl handling support.
Previous discussion/PR attempt: https://github.com/organicmaps/organicmaps/pull/3039
=> Backurl fixes

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://github.com/organicmaps/organicmaps/issues/3220
=> [android] Fixed links.

iphone/Maps/Classes/MapViewController.mm
Closes #3236
A proper fix instead of #3236
=> [ios] Fixed assert

data/categories.txt
Fixes #3250
Signed-off-by: Harry Bond <endim8@pm.me>
=> [Categories] Separate furniture & kitchen types

qt/res/app.organicmaps.desktop.metainfo.xml
=> [desktop] Release notes for 2022.08.23-5

data/categories.txt
As german user sometimes stumble over rather "exotic" words
to search for specific things. i.e. "Essensautomat" for
"food vending machine": I promise - nobody, really nobody
would come with that on their own.
This time i also introduced some suggestions hint.
I hope my changes are sane and don't break any things.
=> [categories] Improve german category word coverage

generator/generator_tests_support/test_with_custom_mwms.cpp, generator/generator_tests_support/test_with_custom_mwms.hpp, indexer/mwm_set.cpp, search/geocoder.cpp, search/geocoder.hpp, search/search_quality/helpers.cpp, search/search_quality/search_quality_tests/real_mwm_tests.cpp, search/search_tests_support/helpers.cpp, search/search_tests_support/helpers.hpp, search/search_tests_support/test_search_engine.cpp, search/search_tests_support/test_search_engine.hpp
https://github.com/organicmaps/organicmaps/issues/3307
=> [search] Process viewport MWM first always.

iphone/Maps/Classes/MapsAppDelegate.mm
Reproduced by opening Downloader and zooming to any downloaded country.
=> [ios] Fixed assert when controller is there but in a wrong order

iphone/Maps/OMaps.plist, iphone/Maps/UI/Help/AboutController.swift
Fixes #3281
It would be great to test it first )
=> [ios] Use default mail app on iOS 14 to report a bug

android/src/com/mapswithme/maps/maplayer/SearchWheel.java
Minor refactoring following https://github.com/organicmaps/organicmaps/pull/2905#discussion_r962525996
=> [android] Minor search wheel clean up

android/res/anim/search_fade_in.xml, android/res/anim/search_fade_out.xml, android/res/values/integer.xml, android/src/com/mapswithme/maps/search/SearchActivity.java, android/src/com/mapswithme/maps/search/SearchFragment.java
Use the default Android activity animation to align with the behavior from other activities.
=> [android] remove custom search activity fade

android/res/mipmap-anydpi-v26/ic_launcher.xml
=> [android] Add themed icon for Android 13

android/res/values-it/strings.xml, android/res/values-nl/strings.xml, data/strings/types_strings.txt, iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/it.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/nl.lproj/Localizable.strings
merge `nl` + 1 `it` translations from https://github.com/organicmaps/organicmaps/pull/3338#issuecomment-1237238719 with current file 
closes https://github.com/organicmaps/organicmaps/issues/3365
=> [strings] Add @501Ghost's NL translations

data/categories.txt, data/strings/strings.txt
=> Basque translation corrections

base/timer.cpp, drape_frontend/drape_engine.cpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/my_position.cpp, drape_frontend/my_position.hpp, drape_frontend/my_position_controller.cpp
Also fixed grey position arrow, if user has invalid time settings.
I can't reproduce, but also should fix useless "Continue detecting your current location" in iOS.
=> [drape] Fixed OnEnterBackground notification.

iphone/metadata/tr/release_notes.txt
It has already approved but I edited translations anyway
=> Fixed AppStore Release Notes Turkish Translation 

data/faq.html
* Minor typo fixes for Turkish
* Added Turkish website link
——
=> [FAQ] Minor edits & localized link

drape_frontend/my_position_controller.cpp
=> [android] Fix my position arrow during navigation

android/res/layout/place_page_description_layout.xml, android/res/values/values.xml, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
=> [android] Improve wikipedia description in the place page

android/build.gradle
=> [android] Updated Android Gradle plugin to 7.3.0

iphone/Maps/UI/PlacePage/Components/PlacePagePreviewViewController.swift
Change time format to be dependent on locale instead of hardcoded to 24 hour system in response to issue #3272
Fixes  #3272
=> [iOS] 24 vs 12 hour

map/viewport_search_callback.cpp, qt/search_panel.cpp, qt/search_panel.hpp, search/filtering_params.hpp, search/geocoder.cpp, search/geocoder_locality.hpp, search/locality_scorer.cpp, search/locality_scorer.hpp, search/search_integration_tests/processor_test.cpp, search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_model.hpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/assessment_tool/view.hpp, search/search_tests_support/helpers.cpp, search/search_tests_support/test_search_request.cpp, search/search_tests_support/test_search_request.hpp
https://github.com/organicmaps/organicmaps/issues/3187
https://github.com/organicmaps/organicmaps/issues/3527
=> [search] Fixed villages search.

android/res/layout/map_buttons_help.xml, android/res/layout/map_buttons_menu.xml, android/res/values-pl/strings.xml, android/res/values-ru/strings.xml, android/res/values-uk/strings.xml, android/res/values/strings.xml, data/strings/strings.txt
Sorry if this should be an [android] commit instead of a [strings] one.
Signed-off-by: Alex Gorichev <Alex.Gorichev@protonmail.com>
=> [strings] Add contentDescription to bottom buttons for accessibility

android/build.gradle, android/gradle.properties, android/jni/CMakeLists.txt, docs/INSTALL.md
@rtsisyk please check if API 32 or API 33 have any specific requirements that we should properly support. And of course, please test it on your devices.
Required for #3537 to customize a language per app.
=> [android] Upgraded to target API 33

map/bookmark_helpers.cpp, map/bookmark_helpers.hpp, map/map_tests/bookmarks_test.cpp
I honestly do not know how it worked before.
=> Do not strip non-ASCII characters from exported bookmarks

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/intent/Factory.java, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/my_position_controller.cpp, drape_frontend/user_event_stream.cpp, iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkSearchData.mm, iphone/Maps/Classes/EAGLView.mm, map/framework.cpp, map/framework.hpp, map/map_tests/mwm_url_tests.cpp, map/mwm_url.cpp, map/mwm_url.hpp, qt/qt_common/map_widget.cpp
```
adb shell am start -a android.intent.action.VIEW -d '"om://crosshair?appname=qqqqqqq&cll=35.174897,33.363857"'
```
=> [android] Add `cll=lat,lon` argument to Crosshair API

data/strings/types_strings.txt
=> [strings] Minor Turkish translation fix

CONTRIBUTORS, android/res/values/strings-tts.xml
Closes #3568 
Signed-off-by: Joan Montané [joan@montane.cat)
=> Enable Catalan TTS, related with issue #3568

android/src/com/mapswithme/maps/location/LocationHelper.java
=> [android] Fix IllegalStateException in AndroidNativeProvider

android/build.gradle
=> [android] Supress lint warnings we can't fix now

android/src/com/mapswithme/maps/editor/HoursMinutesPickerFragment.java, android/src/com/mapswithme/maps/search/CategoriesAdapter.java, android/src/com/mapswithme/util/UiUtils.java, android/src/com/mapswithme/util/Utils.java
All inspected cases are legitimate and can't be removed quickly.
=> [android] Supress DiscouragedApi lint warning

android/src/com/mapswithme/maps/dialog/EditTextDialogFragment.java, android/src/com/mapswithme/maps/downloader/BottomPanel.java, android/src/com/mapswithme/maps/downloader/CountryItem.java, android/src/com/mapswithme/maps/downloader/CountrySuggestFragment.java, android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java, android/src/com/mapswithme/maps/downloader/OnmapDownloader.java, android/src/com/mapswithme/maps/editor/data/HoursMinutes.java, android/src/com/mapswithme/maps/help/HelpFragment.java, android/src/com/mapswithme/maps/intent/Factory.java, android/src/com/mapswithme/maps/maplayer/SearchWheel.java, android/src/com/mapswithme/maps/routing/NavigationService.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/HttpClient.java, android/src/com/mapswithme/util/StringUtils.java, android/src/com/mapswithme/util/Utils.java, android/src/com/mapswithme/util/log/LogsManager.java
=> [android] Add mandatory `locale` argument to Java string functions

android/res/layout/fragment_driving_options.xml, android/res/layout/item_search_clear_history.xml, android/res/layout/item_search_my_position.xml, android/res/layout/item_search_recent.xml, android/res/layout/item_search_suggest.xml, android/src/com/mapswithme/maps/bookmarks/Holders.java, android/src/com/mapswithme/maps/bookmarks/IconsAdapter.java, android/src/com/mapswithme/maps/editor/HoursMinutesPickerFragment.java, android/src/com/mapswithme/maps/maplayer/traffic/widget/TrafficButton.java, android/src/com/mapswithme/maps/settings/DrivingOptionsFragment.java, android/src/com/mapswithme/maps/widget/placepage/EditBookmarkFragment.java, android/src/com/mapswithme/maps/widget/recycler/DividerItemDecorationWithPadding.java, android/src/com/mapswithme/util/Graphics.java
=> [android] Fix compatibility issues reported by lint

generator/generator_tests_support/test_feature.cpp, generator/generator_tests_support/test_feature.hpp, indexer/search_string_utils.cpp, search/ranker.cpp, search/ranking_utils.cpp, search/search_integration_tests/processor_test.cpp
Closes https://github.com/organicmaps/organicmaps/issues/3616
Closes https://github.com/organicmaps/organicmaps/issues/3422
=> [search] Fixed street synonyms for nordic langs.

data/strings/strings.txt
2 missing translations for NL locale.
=> [strings] Add missing NL (Dutch) translations for yes/no

data/strings/types_strings.txt
Types of roads (hiking and cycling), certain amenities and some highway links.
=> [strings] Translations for NL (Dutch) types strings

data/strings/types_strings.txt
PR with content of https://github.com/organicmaps/organicmaps/issues/3635
Fixes https://github.com/organicmaps/organicmaps/issues/3635
@501Ghost
=> [strings] Italian translations and Dutch translation improvements from #3635

android/src/com/mapswithme/maps/bookmarks/ChooseBookmarksSortingTypeFragment.java, android/src/com/mapswithme/maps/dialog/EditTextDialogFragment.java, android/src/com/mapswithme/maps/editor/EditorHostFragment.java, android/src/com/mapswithme/maps/editor/HoursMinutesPickerFragment.java, android/src/com/mapswithme/maps/editor/SimpleTimetableAdapter.java, android/src/com/mapswithme/maps/editor/TimetableContainerFragment.java, android/src/com/mapswithme/maps/intent/Factory.java, android/src/com/mapswithme/maps/search/SearchFragment.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Documentation https://developer.android.com/guide/fragments/fragmentmanager#java
=> Solve `Fragment#instantiate` deprecations

map/framework.cpp
Closes https://github.com/organicmaps/organicmaps/issues/3653
=> [drape] Correct resize with visible viewport update.

data/categories.txt
=> [categories] Minor fixes in Turkish translations

android/res/layout/activity_splash.xml, android/res/values/styles-text.xml
The bug was introduced in https://github.com/organicmaps/organicmaps/pull/3020 by https://github.com/organicmaps/organicmaps/pull/3020/files#diff-105c3dfcf45b59ef3889833fb6f3909f97b1713ad9b9448daee7e21b66f22048
Fixes https://github.com/organicmaps/organicmaps/issues/3708
=> [android] fix place page bold title

map/framework.cpp, map/framework.hpp, qt/qt_common/map_widget.cpp, qt/search_panel.cpp, search/engine.cpp, search/engine.hpp, search/pre_ranker.cpp, search/ranker.cpp, search/search_integration_tests/utils_test.cpp
Closes https://github.com/organicmaps/organicmaps/issues/3680
=> [search] Viewport filtering fix.

CONTRIBUTORS, android/res/values-es-rMX/strings.xml, android/res/values-pl/strings.xml, data/faq.html, data/strings/strings.txt, data/strings/types_strings.txt, iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/pl.lproj/Localizable.strings
[old] This pull request fixes most unnatural-sounding polish strings, grammatical errors, and inaccuracies to their english counterparts. It also revamps the polish FAQ which was in a terrible state and adds several new polish strings.
I added myself to CONTRIBUTORS - I wasn't sure where to put myself, but I am willing to maintain the polish language so I'm currently under translation.
[new] New pull request to fix DCO issues and mexican spanish translations which were reverted to english by the first regeneration, possibly because someone edited the xml files without editing strings.txt. These match their `es` counterparts and I don't think they're wrong, though I don't speak spanish.
=> [strings] Fix and add polish translations, fix es-MX translations

android/res/values-es/strings.xml, android/res/values-eu/strings.xml, data/strings/strings.txt, iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/es.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/eu.lproj/Localizable.strings
Same as https://github.com/organicmaps/organicmaps/pull/3726, I fixed the string in Spanish and Euskara.
=> [strings] Fix subway exit translation

android/src/app/organicmaps/routing/NavigationController.java
=> [android] Don't cut off top elements in navigation mode

map/framework.cpp
Closes https://github.com/organicmaps/organicmaps/issues/3751
=> [android] Removed assert.

android/src/app/organicmaps/bookmarks/ChooseBookmarksSortingTypeFragment.java, android/src/app/organicmaps/downloader/CountrySuggestFragment.java, android/src/app/organicmaps/editor/AdvancedTimetableFragment.java, android/src/app/organicmaps/editor/EditorFragment.java, android/src/app/organicmaps/editor/ReportFragment.java, android/src/app/organicmaps/editor/SimpleTimetableAdapter.java, android/src/app/organicmaps/maplayer/SearchWheel.java, android/src/app/organicmaps/routing/RoutingBottomMenuController.java, android/src/app/organicmaps/widget/SearchToolbarController.java, android/src/app/organicmaps/widget/StackedButtonsDialog.java, android/src/app/organicmaps/widget/placepage/EditBookmarkFragment.java, android/src/app/organicmaps/widget/placepage/PlacePageView.java
Closes: #3552
Here I found info on why is it needed and how to fix it: http://tools.android.com/tips/non-constant-fields
=> [android] Fix NonConstantResourceId

generator/generator_tests/osm_type_test.cpp, generator/osm2type.cpp, routing/edge_estimator.cpp, routing/geometry.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/turn_test.cpp, routing_common/bicycle_model.cpp, routing_common/bicycle_model.hpp, routing_common/car_model.cpp, routing_common/car_model.hpp, routing_common/car_model_coefs.hpp, routing_common/maxspeed_conversion.cpp, routing_common/pedestrian_model.cpp, routing_common/pedestrian_model.hpp, routing_common/routing_common_tests/vehicle_model_test.cpp, routing_common/vehicle_model.cpp, routing_common/vehicle_model.hpp
Closes https://github.com/organicmaps/organicmaps/issues/3502
Closes https://github.com/organicmaps/organicmaps/issues/3033
https://github.com/organicmaps/organicmaps/issues/3363
=> [routing] Reduced links factors.

data/strings/types_strings.txt
Signed-off-by: Timeo Gut <timeo.gut@gmail.com>
=> [strings] fixed en translation for trunk roads

android/res/values-hu/strings.xml, data/categories.txt, data/strings/strings.txt, data/strings/types_strings.txt, iphone/Maps/LocalizedStrings/hu.lproj/Localizable.strings
continuing @d4f5409d's work
Closes #3668
=> Add @d4f5409d s translations 

indexer/mwm_set.cpp, map/framework.cpp, search/pre_ranker.cpp, search/ranker.cpp, search/ranker.hpp, search/result.cpp, search/result.hpp, search/search_tests/results_tests.cpp
Should fix https://github.com/organicmaps/organicmaps/issues/3788
=> [search] Fixed possible bug when canceling request.

cmake/OmimHelpers.cmake, drape/drape_tests/CMakeLists.txt
* Following the approved patter in https://github.com/organicmaps/organicmaps/pull/2863#issuecomment-1262797057
=> [3party] Optionally allow building with packaged googletest

qt/res/app.organicmaps.desktop.metainfo.xml
=> [desktop] Release notes for 2022.11.02

android/src/fdroid/play/release-notes/tr-TR/default.txt
Fixed Turkish Release notes for Android
=> Fixed Turkish Release Notes

data/strings/types_strings.txt
New, corrected and improved translations for norwegian (nb).
=> [strings] Norwegian (nb) translation update

data/categories.txt
New, corrected and improved translations for norwegian (nb).
=> [categories] Norwegian (nb) translation update

android/jni/app/organicmaps/Framework.cpp, android/jni/app/organicmaps/core/jni_helper.cpp, android/jni/app/organicmaps/platform/HttpThread.cpp
=> [android] Potential ANR fix

indexer/feature_data.cpp, indexer/indexer_tests/CMakeLists.txt, indexer/indexer_tests/feature_names_test.cpp, indexer/indexer_tests/feature_types_test.cpp
Closes https://github.com/organicmaps/organicmaps/issues/3873
=> [feature] Separate building process as "shown type".

routing_common/vehicle_model.cpp
Closes https://github.com/organicmaps/organicmaps/issues/3893
=> [routing] Fixed bug in bicycle's speed selector.

kml/kmb_to_kml/kmb_to_kml.cpp
I'm constantly asked by users to help with kmb files conversion )
=> [tools] Convert more than one kmb to kml with one call

.github/workflows/android-beta.yaml, .github/workflows/android-monkey.yaml, android/build.gradle
=> [android] Update the list of devices in TestLab

android/src/fdroid/play/listings/pl-PL/full-description.txt, android/src/fdroid/play/listings/pl-PL/short-description.txt, android/src/fdroid/play/listings/pl-PL/title.txt, android/src/fdroid/play/listings/pl-PL/video-url.txt, android/src/google/play/listings/pl-PL/full-description.txt, android/src/google/play/listings/pl-PL/short-description.txt, android/src/google/play/listings/pl-PL/title.txt, android/src/google/play/listings/pl-PL/video-url.txt, iphone/metadata/pl/description.txt, iphone/metadata/pl/keywords.txt, iphone/metadata/pl/marketing_url.txt, iphone/metadata/pl/name.txt, iphone/metadata/pl/privacy_url.txt, iphone/metadata/pl/promotional_text.txt, iphone/metadata/pl/release_notes.txt, iphone/metadata/pl/subtitle.txt, iphone/metadata/pl/support_url.txt
Signed-off-by: Jacek <uaie_wljjw94@jyplo.com>
Translate-URL: https://hosted.weblate.org/projects/organicmaps/fdroid-metadata/pl/
Translate-URL: https://hosted.weblate.org/projects/organicmaps/apple-appstore-metadata/pl/
=> Translated using Weblate (Polish)

android/res/values-be/strings.xml, android/res/values-tr/strings.xml, android/res/values-uk/strings.xml, data/strings/strings.txt, iphone/Maps/Core/Settings/MWMSettings.mm, iphone/Maps/LocalizedStrings/be.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/tr.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/uk.lproj/Localizable.strings
=> Strings regen

qt/qt_common/map_widget.cpp
Signed-off-by: Jaime Marquínez Ferrándiz <jaime.marquinez.ferrandiz@fastmail.net>
=> [desktop] Accept the "+" key for zooming the map

data/categories.txt
=> [strings][categories] Updated Italian translations

data/strings/sound.txt, data/strings/types_strings.txt
Signed-off-by: Gonzalo Pesquero <gpesquero@yahoo.es>
=> [strings] Spanish (es) translation update

data/strings/sound.txt
Given we are working on #3972 and #3976, I just fixed a couple of strings in Portuguese TTS.
=> Update sound.txt PT and PT-BR

README.md
Signed-off-by: ddpasa <emailformygitacc@proton.me>
=> Readme: Add Mastodon link

CMakeLists.txt, coding/internal/xmlparser.hpp
=> [3party] Optionally allow building with packaged expat

packaging/app.organicmaps.desktop.metainfo.xml
=> [packaging] Add 2022.11.24-3 release notes to .metainfo.xml

CMakeLists.txt, cmake/OmimHelpers.cmake
TODO: Detect installed packages for Mac OS.
CC @Ferenc-
=> [3party] Fixed expat compile errors for Android

qt/CMakeLists.txt
Signed-off-by: Jaime Marquínez Ferrándiz <jaime.marquinez.ferrandiz@fastmail.net>
=> [desktop] Fix reference to app.organicmaps.desktop.metainfo.xml

drape_frontend/drape_engine.cpp, drape_frontend/user_mark_generator.cpp, drape_frontend/user_mark_shapes.cpp, drape_frontend/user_mark_shapes.hpp, drape_frontend/user_marks_provider.hpp, geometry/point_with_altitude.cpp, geometry/point_with_altitude.hpp, geometry/spline.cpp, kml/kml_tests/serdes_tests.cpp, kml/serdes.cpp, kml/serdes.hpp, kml/type_utils.cpp, kml/type_utils.hpp, kml/types.cpp, kml/types.hpp, kml/types_v3.hpp, kml/types_v6.hpp, kml/visitors.hpp, map/bookmark_manager.cpp, map/bookmark_manager.hpp, map/elevation_info.cpp, map/framework.cpp, map/framework.hpp, map/map_tests/bookmarks_test.cpp, map/track.cpp, map/track.hpp, openlr/openlr_tests/decoded_path_test.cpp, routing/features_road_graph.cpp, routing/routing_quality/routing_quality_tool/utils.cpp, track_generator/utils.cpp
Closes https://github.com/organicmaps/organicmaps/issues/3895
Should fix this https://github.com/organicmaps/organicmaps/issues/3880
=> [kml] Support multiple track's geometry.

.github/workflows/macos-check.yaml
=> [github/workflows] Add CI jobs for building on macOS

android/src/fdroid/play/listings/cs-CZ/full-description.txt
Third attempt at trying to improve OM, haha. I'm sorry if I did it wrong again, but from what I've found, I should change this file. Also I'm not sure how to make strikethrough in .txt file.
Signed-off-by: Jan Podhorsky grreby@proton.me
=> [strings] Improve Czech Android translations

data/editor.config
I have again add new type in editor.config
@biodranik I have some questions about this file:
- Is it possible to arrange by alphabetical order foreach types for better visibility ?
-  Order is use in code ? https://github.com/organicmaps/organicmaps/blob/6600f3fb5f35d956eb879bf3d7d2226ea0c838aa/data/editor.config#L157
- Can i add missing group in types ?
- We have missing this :) https://github.com/organicmaps/organicmaps/blob/6600f3fb5f35d956eb879bf3d7d2226ea0c838aa/data/editor.config#L2
- Do you think it's necessary to include field internet for shop ?
=> [editor]Add new POI in editor

android/src/app/organicmaps/help/HelpFragment.java, android/src/app/organicmaps/util/DateUtils.java, android/src/app/organicmaps/util/Graphics.java
Usage: https://github.com/organicmaps/organicmaps/pull/3806
Signed-off-by: Andrew Shkrob <andrew.shkrob.social@yandex.by>
=> [android] Refactor `getLocalDate` and add `drawableToBitmap`. For AA support

android/res/values-de/strings.xml, data/categories.txt, data/strings/types_strings.txt, iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
=> [strings] some more de search enhancements

android/src/app/organicmaps/util/Graphics.java
Signed-off-by: Andrew Shkrob <andrew.shkrob.social@yandex.by>
=> [android] Fix comments from #4061

tools/unix/generate_localizations.sh
=> [tools] Fixed non-working localizations script

base/buffer_vector.hpp, base/deferred_task.cpp, generator/osm_o5m_source.hpp, generator/tag_admixer.hpp, indexer/validate_and_format_contacts.cpp, map/transit/transit_display.cpp, openlr/openlr_model.cpp, platform/http_client.cpp, search/search_tests_support/test_results_matching.cpp, storage/country_decl.cpp, transit/experimental/transit_data.cpp, transit/transit_graph_data.cpp
Extracted from https://github.com/organicmaps/organicmaps/pull/4022
There are some other issues that could be fixed, but I propose to do it iteratively.
=> Fix small issues found by clang-tidy

generator/generator_tests/osm_type_test.cpp, generator/osm2type.cpp, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/road_access.hpp, routing/road_access_serialization.hpp, routing/routing_helpers.hpp, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/guides_tests.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/turn_test.cpp, routing/segment.hpp, routing/transit_graph.cpp, routing_common/bicycle_model.cpp, routing_common/pedestrian_model.cpp, transit/world_feed/world_feed_tests/world_feed_tests.cpp
Closes https://github.com/organicmaps/organicmaps/issues/3881
Closes https://github.com/organicmaps/organicmaps/issues/3929
Route calculation speed should be better.
https://github.com/organicmaps/organicmaps/issues/3625
https://github.com/organicmaps/organicmaps/issues/2998
https://github.com/organicmaps/organicmaps/issues/3001
https://github.com/organicmaps/organicmaps/issues/4007
=> [routing] Fixed model's speeds. Speedup cross-MWM algo.

android/flavors/gms-enabled/app/organicmaps/location/GoogleFusedLocationProvider.java
=> Show Google Location Services dialog only once

drape_frontend/drape_engine.cpp, generator/camera_info_collector.cpp, generator/osm_source.cpp, generator/world_roads_builder/world_roads_builder.cpp
Signed-off-by: Siarhei Fedartsou <siarhei.fedartsou@gmail.com>
=> Fix bugprone-use-after-move clang-tidy warnings

data/countries.txt
Closes https://github.com/organicmaps/organicmaps/issues/4051
Closes https://github.com/organicmaps/organicmaps/issues/3834
Closes https://github.com/organicmaps/organicmaps/issues/3313
Closes https://github.com/organicmaps/organicmaps/issues/3017
https://github.com/organicmaps/organicmaps/issues/2310
Closes https://github.com/organicmaps/organicmaps/issues/1290
=> [planet] New data from 221216.

packaging/app.organicmaps.desktop.metainfo.xml
=> [packaging] Add 2022.12.18-12 release notes to .metainfo.xml

generator/routing_index_generator.cpp, platform/measurement_utils.hpp, routing/edge_estimator.cpp, routing/geometry.cpp, routing/index_graph_starter.hpp, routing/index_graph_starter_joints.hpp, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_integration_tests/guides_tests.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/transit_route_test.cpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/world_graph.cpp, routing/world_graph.hpp, routing_common/bicycle_model.cpp
Closes https://github.com/organicmaps/organicmaps/issues/4110
Closes https://github.com/organicmaps/organicmaps/issues/4145
https://github.com/organicmaps/organicmaps/issues/4143
=> [routing] Fixed Cross-MWM borders penalty assign.

android/src/app/organicmaps/bookmarks/BookmarksListFragment.java, android/src/app/organicmaps/util/log/Logger.java, drape_frontend/animation/interpolators.cpp, geometry/angles.cpp, geometry/screenbase.cpp, geometry/screenbase.hpp, iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h, iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm, map/bookmark_manager.cpp, map/bookmark_manager.hpp
Trying to fix:
https://github.com/organicmaps/organicmaps/issues/3775
https://github.com/organicmaps/organicmaps/issues/3774
=> [android] Try to fix monkey crashes.

iphone/Maps/Classes/Components/MWMTableViewController.m
Fixes #4009
CC @SiarheiFedartsou
=> [ios] Fix font color for tableview footers

data/strings/sound.txt
Fixed just a couple of strings, after reviewing new TTS proposed by @zyphlar.
Signed-off-by: Matheus Gomes
=> Fixed PT and PT-BR sound.txt

indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, kml/kml_tests/serdes_tests.cpp, kml/serdes.cpp, kml/serdes.hpp, routing/mwm_hierarchy_handler.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_options.cpp, routing_common/vehicle_model.cpp, routing_common/vehicle_model.hpp
Closes https://github.com/organicmaps/organicmaps/issues/4182
=> [kml] Parse gx:Track.

data/editor.config
Make public bookcases addable and editable.
=> [editor] Add amenity=public_bookcase

data/categories.txt, data/strings/types_strings.txt
* Added leisure.track.area with same translations as leisure.track
* Added charging_station.motorcar with same translations charging_station
* Modified fr translation and synced categories with types_string
Should I also change categories.txt to enable search of leisure.track.area & charging_station.motorcar ?
Fixes #3959
=> [strings] added missing track.area & charging_station.motorcar

data/replaced_tags.txt
fixes https://github.com/organicmaps/organicmaps/issues/4044
(map regen needed)
=> [generator] support historic=fountain without amenity=fountain

platform/platform_linux.cpp
@pastk please check if it works on your system.
=> [linux] Approximate create time for older Linux versions

base/string_utils.hpp, data/categories.txt, search/region_info_getter.cpp, search/region_info_getter.hpp, search/reverse_geocoder.cpp, storage/country_tree.cpp, storage/country_tree.hpp, storage/country_tree_helpers.cpp, storage/storage.cpp, storage/storage.hpp
https://github.com/organicmaps/organicmaps/issues/857
=> [search] Avoid confusing city region in Australia addresses.

base/mem_trie.hpp, indexer/categories_holder.hpp, indexer/search_string_utils.cpp, indexer/search_string_utils.hpp, search/processor.cpp, search/search_integration_tests/processor_test.cpp, search/utils.hpp
https://github.com/organicmaps/organicmaps/issues/3655
=> [search] Avoid fancy categories matching.

android/res/values-cs/strings.xml, android/res/values-fr/strings.xml, data/strings/strings.txt, iphone/Maps/LocalizedStrings/cs.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/fr.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/fr.lproj/Localizable.stringsdict
Our user has contributed French translations. Please review.
=> Updated French translations

packaging/app.organicmaps.desktop.metainfo.xml
=> Add 2023.01.25-3 release notes to .metainfo.xml

data/strings/strings.txt
It fixes lots of typo problem in Persians translation like lots of missing Zero-width non-joiner etc.
=> fix Persian translation

android/res/values-fa/strings.xml, iphone/Maps/LocalizedStrings/fa.lproj/Localizable.strings
Interesting, how zero-width space will influence the UI. What about our search?
https://en.wikipedia.org/wiki/Zero-width_space
=> [strings] Regenerated Farsi

data/styles/clear/include/Roads.mapcss, data/styles/clear/include/Subways.mapcss
Doesn't need drules regeneration.
=> [styles] Minor validation fixes

CMakeLists.txt, indexer/CMakeLists.txt
=> [3party] Optionally allow building with packaged protobuf

tools/python/maps_generator/README.md
I tweaked some of the English wording in this doc. My intent is to make this a bit easier to understand to a newcomer that wants to generate some .mwm files themselves.
cc/ @endim8 @biodranik 
Inspired by:
https://github.com/organicmaps/organicmaps/issues/4392
Related issues:
https://github.com/organicmaps/organicmaps/issues/4405
https://github.com/organicmaps/organicmaps/issues/4406
=> Improve maps_generator README.

iphone/Maps/Classes/MapViewController.mm, iphone/Maps/Core/DeepLink/DeepLinkHandler.swift, map/framework.cpp
Fixes #4285
Fixes #3012
To test cold and non-cold start, use https://omaps.app/api
=> iOS API coldstart fix

data/config.xsd, data/editor.config, editor/editor_config.cpp, editor/editor_tests/config_loader_test.cpp, editor/editor_tests/osm_editor_test.cpp, editor/editor_tests/osm_editor_test.hpp, editor/osm_editor.cpp
This PR following works started here #4050
=> [editor] Migrate mapsme to omaps

data/editor.config, editor/editor_tests/editor_config_test.cpp
Signed-off-by: Jean-Baptiste CHARRON <jeanbaptiste.charron@outlook.fr>
This PR following work started in #4034 :
- First commit to replace mapsme by omaps (in editor.config, xsd file and all file in editor directory)
-  Second commit to add Internet field on more of POI (WIP)
=> [editor] Improvements in editor.config

drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/screen_animations.cpp, drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp
Android Auto before
https://user-images.githubusercontent.com/10351358/215907976-88d3f31e-2bc3-42d7-a487-9621db6f1b74.mov
Android Auto after
https://user-images.githubusercontent.com/10351358/215907991-88cf49b7-af39-48f9-b1b3-2941e37faa0b.mov
Android before
https://user-images.githubusercontent.com/10351358/215908077-7fead4f0-13e2-4407-b2df-2712d0fe3e52.mp4
Android after
https://user-images.githubusercontent.com/10351358/215908098-52cfbfdf-29f8-427a-be67-ff3b3eae1d39.mp4
=> [drape] SetCenterEvent animation fix

routing/routing_tests/turns_sound_test.cpp, routing/routing_tests/turns_tts_text_tests.cpp, routing/turns_notification_manager.cpp, routing/turns_sound_settings.cpp, routing/turns_tts_text.cpp
Thanks @Shura0 for the initial patch here https://github.com/organicmaps/organicmaps/pull/4354
=> [routing] 50m threshold to skip next turn distance notification.

packaging/app.organicmaps.desktop.metainfo.xml
Intended for fixing https://github.com/flathub/app.organicmaps.desktop/issues/26
=> [packaging] Clarify feature disparity

android/jni/app/organicmaps/Framework.cpp, android/jni/app/organicmaps/Framework.hpp, android/jni/app/organicmaps/Map.cpp, android/src/app/organicmaps/Map.java, android/src/app/organicmaps/MapFragment.java, android/src/app/organicmaps/car/NavigationSession.java, android/src/app/organicmaps/car/SurfaceRenderer.java, android/src/app/organicmaps/car/UiHelpers.java, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/drape_frontend_tests/user_event_stream_tests.cpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp, drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp, map/framework.cpp, map/framework.hpp
Расположение компаса временное.
Добавил TODO и таску в чеклист, чтобы настроить его корректное отображение. Возможно его стоит вообще убрать из AA.
Есть проблема:
* Маленький зум, position mode == NotFollow
* Меняю position mode на Follow
* Стрелка двигается в центр экрана
* Происходит зум
* Стрелка перемещается в нужное место
Подробности в конце видео
Есть идеи, как починить?
Здесь задается `VisibleRect`:
https://github.com/organicmaps/organicmaps/blob/cf0ebed1820a55380c7437e0b4a5e21f3d56275d/android/src/app/organicmaps/car/SurfaceRenderer.java#L60-L66
Вопрос:
Нормальная ли это реализация `onClick`? Используется для нажатия на компас.
https://github.com/organicmaps/organicmaps/blob/cf0ebed1820a55380c7437e0b4a5e21f3d56275d/android/src/app/organicmaps/Map.java#L290-L294
Видео: …
=> [android-auto] Add location button

data/strings/types_strings.txt
Closes #3996
I did not feel comfortable in using automatic translation, given this is a very specific term (and varies by countries with same language, such as Spanish). Therefore, I used mainly the terms displayed on Wikipedia.
PS.: could someone please regenerate the strings? :)
Signed-off-by: Matheus Gomes
=> Added type.highway.busway translations

android/src/app/organicmaps/maplayer/MapButtonsController.java
From https://github.com/organicmaps/organicmaps/pull/4174#issuecomment-1409046540
=> android: fix map buttons shown when going back from editor

drape_frontend/apply_feature_functors.cpp, drape_frontend/apply_feature_functors.hpp, drape_frontend/stylist.cpp, drape_frontend/stylist.hpp
=> Minor drape refactoring

editor/editor_tests/xml_feature_test.cpp, editor/xml_feature.cpp, editor/xml_feature.hpp, indexer/feature.cpp
Closes https://github.com/organicmaps/organicmaps/issues/1118
=> [editor] Correct diet:vegan, diet:vegetarian.

iphone/Maps/UI/Editor/MWMEditorViewController.mm
Fixes issue on the first screenshot here: #4516
=> [ios][editor] Removed duplicated floors and zip code cells

tools/unix/translate_categories.sh
=> [tools] Fixed wrong RTL translations generated by the trans tool

iphone/Maps/UI/Editor/Cells/MWMNoteCell.m, iphone/Maps/UI/Editor/Cells/MWMNoteCell.xib, iphone/Maps/UI/Editor/MWMEditorViewController.mm
=> [ios] Increased top margin for the Note header, decreased Note size

docs/INSTALL.md
Removed Windows 10: Manual Boost library initialization from INSTALL.md
=> Removed Windows 10 manual boost library initialization from INSTALL.md

android/src/app/organicmaps/editor/EditorFragment.java, android/src/app/organicmaps/util/UiUtils.java
Fix #4541
Before
After
I have tested, with others field it's work
=> [android] Fix type of error message for building levels field

android/src/app/organicmaps/dialog/EditTextDialogFragment.java
Done with updating the edit text error style
=>  Improve error message foreach all field in OM #4465

android/res/values-nb/strings.xml, data/categories.txt, data/strings/strings.txt, iphone/Maps/LocalizedStrings/nb.lproj/Localizable.strings
Tried running the `git submodule update --init --recursive`, but it failed.
Do you prefer these as a single commit, or as these three separate ones? I can easily squash them.
=> [strings] Updated Norwegian translations

README.md
#4609 I hereby certify that I am the author of the commit and that I have the right to submit it under the open source license indicated in the file; or, if not an author, I represent that my employer or client has authorized me to contribute it under the same license.
=> Added link to the code of conduct in README.MD

docs/INSTALL.md
Add instructions to [INSTALL.md](https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md) to avoid symlink problems while building Android app under Windows.
Related issues: [#3095](https://github.com/orgs/organicmaps/discussions/3095) & [#4494](https://github.com/organicmaps/organicmaps/discussions/4494)
=> [docs] Add instructions to avoid symlink problems under Windows

android/res/values/strings.xml, data/strings/types_strings.txt, iphone/Maps/LocalizedStrings/ar.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/be.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/bg.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/ca.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/cs.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/da.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/en-GB.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/en.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/fa.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/fr.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/he.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/hu.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/id.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/ko.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/pt-BR.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/ro.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/sk.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/sv.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/sw.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/th.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/vi.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/zh-Hant.lproj/Localizable.strings
triggered by https://github.com/organicmaps/organicmaps/pull/4592#discussion_r1117986837
fixing initial ones is especially useful as new contributors will see them when checking preferred style
maybe script checking all would be nice
note that Capital Letter For Every Word may be preferred for English but would be silly for some other languages, like Polish
=> Fix capitalization in English 

android/src/app/organicmaps/MwmActivity.java, android/src/app/organicmaps/base/BaseMwmFragmentActivity.java, android/src/app/organicmaps/util/Utils.java
=> [android] Fix a crash in Bundle.getParcelable()

android/res/values/integer.xml, android/src/app/organicmaps/widget/placepage/PlacePageController.java
This reverts commit 2912ca6a5d674ec6c919df333914991ec766f2e3.
=> Revert "android: allow up to 5 place page buttons"

iphone/Maps/Core/Theme/Components/IFonts.swift, iphone/Maps/Core/Theme/Fonts.swift, iphone/Maps/Core/Theme/GlobalStyleSheet.swift
* fixes: #3280
Signed-off-by: Angelina Perez <perezangelina.0907@gmail.com>
=> [ios] Making headers bold

CMakeLists.txt, generator/complex_generator/complex_generator.cpp, generator/feature_segments_checker/feature_segments_checker.cpp, generator/generator_tool/generator_tool.cpp, generator/srtm_coverage_checker/srtm_coverage_checker.cpp, generator/world_roads_builder/world_roads_builder_tool/world_roads_builder_tool.cpp, map/benchmark_tool/main.cpp, map/extrapolation_benchmark/extrapolation_benchmark.cpp, mapshot/mapshot.cpp, openlr/openlr_match_quality/openlr_assessment_tool/main.cpp, openlr/openlr_stat/openlr_stat.cpp, poly_borders/poly_borders_tool/poly_borders_tool.cpp, qt/main.cpp, routing/routes_builder/routes_builder_tool/routes_builder_tool.cpp, routing/routing_consistency_tests/routing_consistency_tests.cpp, routing/routing_quality/routing_quality_tool/routing_quality_tool.cpp, search/search_quality/assessment_tool/assessment_tool.cpp, search/search_quality/features_collector_tool/features_collector_tool.cpp, search/search_quality/samples_generation_tool/samples_generation_tool.cpp, search/search_quality/search_quality_tool/search_quality_tool.cpp, skin_generator/main.cpp, topography_generator/main.cpp, track_analyzing/track_analyzer/track_analyzer.cpp, track_generator/track_generator_tool.cpp, transit/world_feed/gtfs_converter/gtfs_converter.cpp
* For compiler diagnostics
* For dependency management
=> [3party] Treat gflags as a system header

.github/workflows/android-check.yaml, .github/workflows/ios-check.yaml, .github/workflows/linux-check.yaml, .github/workflows/macos-check.yaml
It will help to avoid waiting for available free runners.
=> [github] Cancel previous actions if PR or branch was updated

android/src/app/organicmaps/downloader/DownloaderAdapter.java
Following https://github.com/organicmaps/organicmaps/pull/4701#discussion_r1132958631
=> [android] update code style and fix some warnings

android/multidex-config.txt
Could fix the issue from #4658
=> [android] Fix ClassNotFoundException

android/res/layout/fragment_map_placeholder.xml
This PR update style on button to follow theming
|---|---|
|![Capture](https://user-images.githubusercontent.com/87148630/225096449-d27ea6ca-3e8b-42e8-ad6e-eb7ef5729b99.PNG) | ![Capture2](https://user-images.githubusercontent.com/87148630/225096608-ed890ea9-993a-4f95-865b-3c9a16b5360d.PNG) |
=> [android] Improve style on button

qt/about.cpp
=> [Desktop] Make version number selectable/copyable

data/categories.txt
I'm tired of getting a plethora of small stores while looking for a supermarket :)
=> [categories] Distinguish supermarkets and convenience stores

drape_frontend/stylist.cpp, drape_frontend/stylist.hpp, indexer/classificator.cpp, indexer/classificator.hpp, indexer/map_object.cpp, map/place_page_info.cpp, map/place_page_info.hpp
Fixes/improves cases from #4590, see screenshots there.
Its not a complete fix as some cases require priorities adjustment also (TBD in #4645).
=> Render main type overlay draw rules only

android/res/color/image_view.xml, android/res/layout/fragment_editor_host.xml, android/src/app/organicmaps/editor/AdvancedTimetableFragment.java, android/src/app/organicmaps/editor/EditorHostFragment.java
Before             |  After
:-------------------------:|:-------------------------:
=> Improved wrong syntax popup.

android/src/app/organicmaps/DownloadResourcesLegacyActivity.java, android/src/app/organicmaps/SplashActivity.java, android/src/app/organicmaps/util/UiUtils.java
=> [android] Fix broken PICK_POINT API

android/res/layout/fragment_color_grid.xml
=> [android] Fix Bookmark's color picker in RTL mode

qt/CMakeLists.txt, qt/about.cpp, qt/main.cpp, qt/mainwindow.cpp, qt/osm_auth_dialog.cpp, qt/res/OrganicMaps.desktop
Also improve desktop entry & OSM auth dialog a bit
=> [desktop] Add application name

README.md, docs/CONTRIBUTING.md
you do not need to read docs when you are donating
BTW, it may make sense to mention OSM mapping as one of ways to contribute.
=> [doc] Move doc reading request where it is needed

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.xib
=> Ipad turns fix in Navigation

data/countries.txt, routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_integration_tests/guides_tests.cpp, routing/routing_integration_tests/speed_camera_notifications_tests.cpp, routing/routing_integration_tests/turn_test.cpp
https://github.com/organicmaps/organicmaps/issues/4837
Known issues. Broken _a bit_ routing [here](https://www.openstreetmap.org/node/4501657797#map=13/54.8790/8.5738) due to the changed mapping scheme.
Should refactor type=route, route=ferry/shuttle_train/train Relations for cases where there are no dedicated Ways.
=> [planet] New data from 230329.

routing/car_directions.cpp, routing/route.hpp, routing/routing_tests/turns_generator_test.cpp, routing/turns.cpp, routing/turns.hpp
Follow up from here https://github.com/organicmaps/organicmaps/pull/4886
=> [routing] Fixed unrestricted turn lanes.

tools/python/stylesheet/cat_stat.py
Signed-off-by: Mateusz Konieczny <matkoniecz@gmail.com>
Small step toward #4895
=> [doc] fix comment - key are limited to set of known ones

docs/EXPERIMENTAL_PUBLIC_TRANSPORT_SUPPORT.md
Really debatable is it actually easy and it adds nothing to docs anyway
=> [doc] Do not describe using experimental GTFS as easy

android/jni/app/organicmaps/Framework.cpp, android/src/app/organicmaps/Framework.java, android/src/app/organicmaps/MwmActivity.java
=> [android] Log and handle Android low memory events

docs/CONTRIBUTING.md
=> Just make a PR - and it will be reviewed.

android/src/app/organicmaps/car/NavigationSession.java, android/src/app/organicmaps/car/SurfaceRenderer.java, android/src/app/organicmaps/car/screens/BookmarksScreen.java, android/src/app/organicmaps/car/screens/CategoriesScreen.java, android/src/app/organicmaps/car/screens/ErrorScreen.java, android/src/app/organicmaps/car/screens/MapPlaceholderScreen.java, android/src/app/organicmaps/car/screens/MapScreen.java, android/src/app/organicmaps/car/screens/NavigationScreen.java, android/src/app/organicmaps/car/screens/base/BaseMapScreen.java, android/src/app/organicmaps/car/screens/base/BaseScreen.java, android/src/app/organicmaps/car/screens/search/SearchScreen.java, android/src/app/organicmaps/car/screens/settings/DrivingOptionsScreen.java, android/src/app/organicmaps/car/screens/settings/HelpScreen.java, android/src/app/organicmaps/car/screens/settings/SettingsScreen.java, android/src/app/organicmaps/car/util/UiHelpers.java
Links to https://github.com/organicmaps/organicmaps/pull/4936
=> [android-auto] Refactoring

android/jni/app/organicmaps/SearchEngine.cpp, android/src/app/organicmaps/MwmActivity.java, android/src/app/organicmaps/bookmarks/data/MapObject.java, android/src/app/organicmaps/routing/RoutingController.java, android/src/app/organicmaps/search/NativeSearchListener.java, android/src/app/organicmaps/search/SearchAdapter.java, android/src/app/organicmaps/search/SearchEngine.java, android/src/app/organicmaps/search/SearchResult.java
Links to https://github.com/organicmaps/organicmaps/pull/4936
=> [android] Refactoring required for Android Auto

drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp
Fixes performance issues on some Android devices
Fixes #3526
=> [drape] do not enable antialiasing in subway layer

android/src/app/organicmaps/MwmActivity.java, android/src/app/organicmaps/routing/RoutingController.java
Fixes bug in https://github.com/organicmaps/organicmaps/pull/4987
=> [android] Disclaimer fix

android/src/app/organicmaps/car/screens/CategoriesScreen.java, android/src/app/organicmaps/car/screens/MapScreen.java, android/src/app/organicmaps/car/screens/search/SearchOnMapScreen.java, android/src/app/organicmaps/car/screens/search/SearchScreen.java, android/src/app/organicmaps/car/screens/search/SearchUiHelpers.java
Demo:
https://user-images.githubusercontent.com/10351358/233177820-8cd59c18-51cf-4fb0-a442-1b2ecd3f1642.mp4
There are a lot of bugs on DHU's or Car Library's side. Not mine 😄 
I hope it will work correctly on real devices. I also saw the same bugs in other apps, f.e. maps.me.
Search screen:
* 0:10 - distance and opening hours are shown for the suggestion. If you check the code, you'll find it's not possible.
* 0:14 - 0:18  - distance and opening hours are displayed two times and even have different values for one search result
* 0:38 - 0:44 - search text is not updated when I click on the suggestion
SearchOnMap screen:
* same problems for distance and opening hours.
I circled all places that were displayed incorrectly with the mouse.
Also, don't check the logic of SearchOnMap screen very …
=> [android-auto] Search Screen

android/res/values/strings-tts.xml, platform/languages.hpp
Fixes #5032
@matheusgomesms @Jean-BaptisteC can you please test these languages in TTS?
=> Enabled TTS for es-MX, eu, nb, pt-BR and mr

routing/car_directions.cpp, routing/directions_engine.cpp, routing/geometry.cpp, routing/index_router.cpp, routing/routing_integration_tests/absent_regions_finder_tests.cpp, routing/routing_integration_tests/route_test.cpp, routing/turns_generator.cpp
Closes https://github.com/organicmaps/organicmaps/issues/5069
Better to merge after new data https://github.com/organicmaps/organicmaps/pull/5003
=> [routing] Fixed cross-MWM loops.

data/countries.txt
Should fix:
https://github.com/organicmaps/organicmaps/issues/5050
https://github.com/organicmaps/organicmaps/issues/4924
https://github.com/organicmaps/organicmaps/issues/4974
https://github.com/organicmaps/organicmaps/pull/4943#pullrequestreview-1376937611
https://github.com/organicmaps/organicmaps/issues/4994
https://github.com/organicmaps/organicmaps/issues/4955
=> [planet] New data from 230503.

tools/python/stylesheet/cat_stat.py
added based on my understanding, code reading and testing - still, may be wrong
=> [doc] try to document tools/python/stylesheet/cat_stat.py

kml/serdes.cpp
Fixes #4257
When users copy-paste bad characters from the web into bookmark descriptions, their bookmark lists can not be parsed and loaded by Expat. This fix does not save non-XML1.0 ASCII range characters.
A robust solution requires #3837
=> [kml] Do not save ASCII control symbols that are invalid for XML1.0

android/res/values-eu/strings.xml, data/strings/strings.txt, iphone/Maps/LocalizedStrings/eu.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/eu.lproj/Localizable.stringsdict
Closes #5154
@alexgabi I've fixed line endings and a few minor issues with your pull request. Please review it carefully and comment if something is wrong.
=> [strings] Corrected Basque (eu) translations

docs/INSTALL.md
After #5164, I tried to improve a little bit that Command Line Tools should be installed.
Signed-off-by: Matheus Gomes
=> Making clearer that Command Line Tools must be installed

qt/bookmark_dialog.cpp
=> [desktop] Fixes blue bookmarks color invisible in the dark mode

android/jni/app/organicmaps/Framework.cpp, android/src/app/organicmaps/Framework.java, android/src/app/organicmaps/MwmActivity.java, android/src/app/organicmaps/car/NavigationSession.java, android/src/app/organicmaps/car/SurfaceRenderer.java, android/src/app/organicmaps/car/screens/BookmarksScreen.java, android/src/app/organicmaps/car/screens/CategoriesScreen.java, android/src/app/organicmaps/car/screens/MapScreen.java, android/src/app/organicmaps/car/screens/NavigationScreen.java, android/src/app/organicmaps/car/screens/PlaceScreen.java, android/src/app/organicmaps/car/screens/hacks/PopToRootHack.java, android/src/app/organicmaps/car/util/OnBackPressedCallback.java, android/src/app/organicmaps/car/util/UiHelpers.java
https://user-images.githubusercontent.com/10351358/234840824-f0f1c546-6fd5-41e0-beb5-dcefab7c7638.mp4
When PlacePage is activated, PopToRootHack is called. See in `PopToRootHack.java` how it works.
0:08 - 0:10 - example of the case described in `UiHelpers.createSettingsAction()`
TODO:
* Device locked
* Map used on Car
* Device unlocked (`MwmActivity.onStart()` + `MwmActivity.onResume()`)
* `MwmActivity.mapDisplayChanged(Car)` called
* `Framework.nativeRemovePlacePageActivationListener();` called
=> [android-auto] Place Screen

android/res/layout/layout_nav_top.xml, android/res/layout/menu.xml
=> [android] Prevent map interaction behind routing and navigation panels

qt/main.cpp, qt/qt_common/map_widget.cpp
Made suggested changes from [here](https://github.com/organicmaps/organicmaps/pull/4957)
@Ferenc- Could you test it, please?
=> [qt] Set OGL v3.2 on startup.

android/src/app/organicmaps/background/OsmUploadWork.java
The bug was introduced in #4691 and somehow slipped through the review and tests.
=> [android] Fixed delayed OSM edits upload only on charging

iphone/CoreApi/CoreApi/DeepLink/DeepLinkParser.mm, iphone/Maps/Classes/MapViewController.mm, iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
=> [ios] Fixed non-working and repeated import of KML/KMZ files

android/src/app/organicmaps/MwmActivity.java, android/src/app/organicmaps/car/NavigationSession.java, android/src/app/organicmaps/car/screens/NavigationScreen.java, android/src/app/organicmaps/car/screens/PlaceScreen.java, android/src/app/organicmaps/car/screens/settings/DrivingOptionsScreen.java
https://github.com/organicmaps/organicmaps/assets/10351358/9aa5bb45-11ef-42af-9f7c-5da36d520441
=> [android-auto] Route planning

data/strings/types_strings.txt
=> fix: Bad translation for French of Wind generator string

routing/routing_integration_tests/absent_regions_finder_tests.cpp, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/turn_test.cpp, routing_common/car_model_coefs.hpp
Added routing integration tests.
=> [routing] Updated car model factors.

android/src/fdroid/play/listings/tr-TR/release-notes.txt, android/src/fdroid/play/listings/tr-TR/title-google.txt, data/categories.txt, data/strings/strings.txt, data/strings/types_strings.txt
- Translated Android release notes to Turkish
- Changed Turkish app title for Google Play. This one is better.
- Translated missing strings to Turkish and updated some translations
- Translated missing types strings to Turkish and updated some translations
- Translated missing categories to Turkish and updated some translations
=> Updated Turkish Translations

android/res/values-sv/strings.xml, data/strings/strings.txt, iphone/Maps/LocalizedStrings/sv.lproj/Localizable.stringsdict
=> Fix plural "places" in Swedish

drape_frontend/area_shape.cpp, drape_frontend/backend_renderer.cpp
=> [drape] Do not draw 3D area with more than 10K vertexes.

indexer/caching_rank_table_loader.cpp, indexer/caching_rank_table_loader.hpp, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, indexer/indexer_tests/rank_table_test.cpp, indexer/rank_table.cpp, indexer/rank_table.hpp, indexer/search_string_utils.cpp, search/dummy_rank_table.cpp, search/geocoder.cpp, search/intersection_result.hpp, search/model.cpp, search/ranker.cpp, search/ranking_info.cpp, search/ranking_utils.cpp, search/search_integration_tests/processor_test.cpp, search/search_quality/search_quality_tests/real_mwm_tests.cpp
Closes https://github.com/organicmaps/organicmaps/issues/5296
Closes https://github.com/organicmaps/organicmaps/issues/5186
Closes https://github.com/organicmaps/organicmaps/issues/5150
Of course, all these magic factors, words, constants, etc should be taken out into config files someday.
=> [search] Some ranking fixes.
