- android/app/src/main/res/layout/color_row.xml
- android/app/src/main/res/layout/fragment_edit_bookmark.xml
- android/app/src/main/res/layout/fragment_editor_host.xml
- android/app/src/main/res/layout/fragment_osm_profile.xml
- android/app/src/main/res/layout/item_bookmark_group_list_header.xml
- android/app/src/main/res/layout/item_editor_input.xml
- android/app/src/main/res/layout/item_phone.xml
- android/app/src/main/res/layout/item_street.xml
Google recommends using ConstraintLayout instead RelativeLayout and LinearLayout.
More information [here](https://developer.android.com/topic/performance/rendering/optimizing-view-hierarchies?hl=en#managing) And ConstraintLayout needs less calculation to generate a view
I have tested on Pixel 6 - Android 14 with max size police and max size UI in portrait and landscape mode.
I don't add screenshots because there are no UI differences.
> [android] Improve performance of some layouts

- iphone/Maps/Classes/CarPlay/CarPlayService.swift
- iphone/Maps/Classes/Components/MWMNavigationController.m
- iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Core/Settings/MWMSettings.mm
- iphone/Maps/Core/Theme/Core/ThemeManager.swift
- iphone/Maps/Core/Theme/Renderers/UITextFieldRenderer.swift
- iphone/Maps/UI/CarPlay/CarPlayMapViewController.swift
- iphone/Maps/UI/PlacePage/Components/PlacePageHeader/PlacePageHeaderViewController.swift
- iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
- iphone/Maps/UI/PlacePage/Components/PlacePagePreviewViewController.swift
- iphone/Maps/UI/PlacePage/Components/WikiDescriptionViewController.swift
- iphone/Maps/UI/PlacePage/PlacePage.storyboard
- iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.m
- iphone/Maps/UI/PlacePage/PlacePageViewController.swift
- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
- iphone/Maps/UI/Storyboard/Settings.storyboard
See https://github.com/organicmaps/organicmaps/issues/749 , not closing it yet as Android part should also be implemented.
1. Synchronize the auto-switching between light/dark themes to the device when the user selects `Auto` in the OM Settings.
When the On/Off is selected in OM Settings synchronization is disabled.
2. When the user uses CarPlay and Carplay auto-updates content style then the map theme will be changed to it. There is no possibility to force the map theme whiole using the CarPlay (except Carplay's settings). 
3. A lot of bugs related to the auto theme changing were fixed, because with the current `ThemeManager` and `StyleManager` systems UI elements usually support the creation with the current theme, but do not auto-update when the theme is changing.
4. Move the NightMode …
> [ios] Synchronize the app light/dark appearance with the device

- iphone/Maps/UI/PlacePage/PlacePage.storyboard
Currently, in iOS long attributes in the Place Page get cropped to a single line. In Android they span multiple lines if needed. This PR allows multiline attributes in the Place Page in iOS. This can be specially useful for languages other than English that have longer texts.
Before/After:
--
How it currently looks in Android:
> [ios][placepage] Allow multiline attributes in Place Page

- android/app/src/main/java/app/organicmaps/settings/SettingsPrefsFragment.java
- android/app/src/main/res/xml/prefs_main.xml
PR #7230 introduces a new fragment to manage TTS settings but the property specified in `prefs_main.xml` https://github.com/organicmaps/organicmaps/blob/8297a92c52ec4f720d1f78d3cc3f33b67e268ac7/android/app/src/main/res/xml/prefs_main.xml#L129 to start the TTS fragment doesn't work.
On latest beta, open TTS settings do nothing and hide a crash because we catch the exception -> https://github.com/organicmaps/organicmaps/blob/8297a92c52ec4f720d1f78d3cc3f33b67e268ac7/android/app/src/main/java/app/organicmaps/settings/SettingsActivity.java#L39
This PR:
- Remove property in preference xml file
- Add a new else if in onPreferenceTreeClick method in SettingsPrefsFragment.java to create TTS fragment. I have followed the same logic as how StoragePathFragment is created.
Tested on Pixel 6 - Android …
> [android] Fix TTS settings not working

- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.xib
Related PR https://github.com/organicmaps/organicmaps/pull/7196
This PR reduces the top bar height when navigation is enabled.
Before/After:
> [ios] Reduce the navigation screen top bar height

- iphone/Maps/Categories/UIView+AddSeparator.swift
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/Downloader/DownloadAllView/DownloadAllView.xib
- iphone/Maps/UI/Downloader/DownloadMapsViewController.swift
- iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
- iphone/Maps/UI/Storyboard/Main.storyboard
PR https://github.com/organicmaps/organicmaps/pull/7236 partly fixes the DownloadMapsVC layout but there are still some problems.
This PR fixes the Download/Update view on the DownloadMapsVC.
Before PR7236:
After PR7236(for screenshots I forced visibility of the view to show the layout and there is no content because the maps were up-to-date):
After this PR:
> [ios] Fix the bottom 'download all' view layout

- android/app/src/main/cpp/app/organicmaps/bookmarks/data/BookmarkManager.cpp
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarksSharingHelper.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkManager.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkSharingResult.java
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- qt/bookmark_dialog.cpp
Refactoring required for #995 - still only one bookmark is exported, but code from ui to c++ works with list of categories now - as suggested in https://github.com/organicmaps/organicmaps/issues/995#issuecomment-1897763732.
I fixed iOS code to make it compile, but need help with test - I don't have an opportunity to run it.
> [bookmarks] Use list of categories ids in java/cpp

- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardEntity.h
- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/BaseRoutePreviewStatus.swift
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/TransportRoutePreviewStatus.swift
Fix https://github.com/organicmaps/organicmaps/pull/7292
When the app appearance is changed and the route preview screen is active the estimates colors are not changed properly:
This happens because `estimates` is a stored property (of `MWMNavigationDashboardEntity` class) of the `NSAttributedString` type that is built during initialization and cannot be changed dynamically to react to the theme changes.
`@property(copy, nonatomic, readonly) NSAttributedString *estimate;`
```objc
entity.estimate =
estimate(info.m_totalTimeInSec, @(info.m_totalPedestrianDistanceStr.c_str()),
@(info.m_totalPedestrianUnitsSuffix.c_str()), self.etaAttributes, self.etaSecondaryAttributes, YES, YES);
NSAttributedString *estimate(NSTimeInterval time, NSString *distance, NSString *distanceUnits,
NSDictionary …
```
> [ios] Fix the route estimates colors when the app appearance was changed

- base/base_tests/string_utils_test.cpp
As recommended [here](https://github.com/organicmaps/organicmaps/pull/7316#issuecomment-1929015217).
Needed for https://github.com/organicmaps/organicmaps/pull/7299
> [base][test]: Use `u16string_view` instead of `char16_t[]`

- indexer/feature_utils.hpp
- indexer/map_object.cpp
- indexer/map_object.hpp
- iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.xib
- map/framework.cpp
- map/place_page_info.cpp
- search/intermediate_result.cpp
- search/ranker.cpp
- search/result.cpp
- search/result.hpp
- search/search_tests/results_tests.cpp
In this PR:
* Add the main type (Restaurant, petrol station, bank...) of a search result when searching for a minor type (Toilets, compressed air, ATM...).
* Remove the duplicated type from the description when it is already shown in the title.
--
* Fixes https://github.com/organicmaps/organicmaps/issues/1648
-- 
Before/After:
> Add main type to search description and remove duplicate type

- iphone/DatePicker/DatePicker/Cells/RangeFirstCell.swift
- iphone/DatePicker/DatePicker/Cells/RangeLastCell.swift
- iphone/DatePicker/DatePicker/Cells/RangeSingleCell.swift
- iphone/DatePicker/DatePicker/Cells/SelectedSingleCell.swift
- iphone/Maps/Categories/CALayer+SetCorner.swift
- iphone/Maps/Categories/UIView+Snapshot.swift
- iphone/Maps/Classes/Components/Modal/AlertPresentationController.swift
- iphone/Maps/Classes/Components/Modal/IPadModalPresentationController.swift
- iphone/Maps/Classes/Components/Modal/PromoBookingPresentationController.swift
- iphone/Maps/Classes/CustomAlert/Toast/Toast.swift
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/TransportTransitSteps/TransportRuler.swift
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/TransportTransitSteps/TransportTransitPedestrian.swift
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/TransportTransitSteps/TransportTransitTrain.swift
- iphone/Maps/Core/Theme/Renderers/UISearchBarRenderer.swift
- iphone/Maps/Core/Theme/Renderers/UITextFieldRenderer.swift
- iphone/Maps/Core/Theme/Renderers/UIViewRenderer.swift
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/BottomMenu/Menu/BottomMenuViewController.swift
- iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuLayerButton.swift
- iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarButton.swift
- iphone/Maps/UI/PlacePage/PlacePageViewController.swift
- iphone/Maps/UI/PlacePage/Views/DifficultyView.swift
If you look closely, you’ll not find a sharp corner in any Apple product. Al UI in Apple’s apps and products are smoothly-rounded. This is because Apple always uses `superellipses` for the rectangle's corners rounding (`squircle`) .
To read more about superellipses:
https://blog.minimal.app/rounded-corners-in-the-apple-ecosystem/
https://habr.com/ru/companies/droider/articles/517298/
This PR implements this small fix for UI elements to slightly improve the app's visual smoothness.
Since ios13 UIKit introduced the continuous corner curve style:
`public static let continuous: CALayerCornerCurve`
This property should be always set manually so I move it into the extension.
It would be better to increase a little bit some corner radiuses to make the app not so edgy.
For example:
> [ios] Change the views rounded corners to the superellipses

- iphone/Maps/Core/Theme/Colors.swift
This PR updates the primary OM color in the iOS to match with the Android.
> [ios] Match the iOS primary OM color with the Android

- iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarInteractor.swift
Sometimes the app crashes during the tap on the Menu button.
1. tap on the map to hide the bottom bar and side buttons
2. while the hiding animation is in progress tap on the Menu button (you should do it immidietely)
3. app should fail
Touching the map on the free area to update the visibility of the controls is handled in the core c++ code.
If you quickly tap on the map to hide the menu and then on the disappearing menu button, there are 2 cases:
1. If you tap super quickly, UIKit processes the second tap faster than the c++ code processes the first one and you can see the menu opening and closing immediately. But this case is rarer because you have to tap extremely fast.
2. If you tap slightly slower on the menu, but still while the hiding button is progress - then the core will first …
> [ios] Fix crash when user taps the Menu button during the TabBar hiding animation

- 3party/CMakeLists.txt
- CMakeLists.txt
- cmake/OmimHelpers.cmake
- platform/CMakeLists.txt
- storage/CMakeLists.txt
Now build should fail on an unsupported platform until a new platform is explicitly added.
> [cmake] Simplified platform variables

- iphone/Maps/UI/Search/MWMSearchManager.mm
When the user taps on the Search screen's `close` button:
1. search screen disappears
2. keyboard scrolls down
The overall animation is serial and looks a little bit slow.
This small PR fix that.
Before (real speed/slowmo):
After:
> [ios] Improve the search screen closing animation

- android/app/src/main/java/app/organicmaps/routing/RoutingController.java
- android/app/src/main/java/app/organicmaps/routing/RoutingPlanController.java
- iphone/Maps/Core/Routing/MWMRouter.mm
Do not show "Routing options enabled"  when using ruler.
Based on https://github.com/organicmaps/organicmaps/pull/3601.
Closes #6579.
> Do not show "Routing options enabled"  when using ruler

- android/app/src/main/res/layout/fragment_editor_host.xml
This PR fixes search bar overlapping, this bug was introduced by PR #7267
- I have removed useless attributes used before with relative layout
- Added constraint layout between search bar and button to validate
- Added margin end at the search bar to take to do not overlapping button
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/96a7ccb3-15e7-4af9-9857-e9a6720f2f32" height=500 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/7f7dd520-573f-494c-bdd7-8dadc469761f" height=500 />|
Todo:
> [android] Fix search bar in cuisine editor

- iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarButton.swift
- iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarView.swift
- iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarViewController.xib
Sometimes when the user taps on the tab button he misses because the tappable area is defined by the button's bounds.
This PR extends the bottom tab buttons tappable area by 15pt to avoid tap miss.
> [ios] Extend bottom tab buttons tappable area by 15pt

- android/app/src/main/cpp/app/organicmaps/editor/Editor.cpp
- indexer/editable_map_object.cpp
- indexer/editable_map_object.hpp
- indexer/feature_utils.cpp
- indexer/feature_utils.hpp
- indexer/ftraits.hpp
- indexer/indexer_tests/editable_map_object_test.cpp
- indexer/map_object.cpp
- indexer/map_object.hpp
- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm
- iphone/Maps/UI/Editor/MWMEditorViewController.mm
- map/place_page_info.cpp
- map/place_page_info.hpp
- qt/editor_dialog.cpp
- search/intermediate_result.cpp
- search/search_integration_tests/search_edited_features_test.cpp
This PR adds recycling, WiFi, operator, wheelchair, ATM, elevation information to search result description. 
Also changed the WiFi indicator from string to 🛜 symbol.
> Add recycling, elevation to search result description

- base/base_tests/string_utils_test.cpp
- base/internal/message.cpp
- base/internal/message.hpp
- base/string_utils.hpp
- drape/glyph_manager.cpp
- indexer/indexer_tests/trie_test.cpp
- indexer/succinct_trie_builder.hpp
- indexer/trie.hpp
That allows to use std::u32string_view in the code, adding useful std::basic_string_view methods
> Use char32_t instead of uint32_t for UniChar

- iphone/Maps/Core/Theme/Renderers/UISearchBarRenderer.swift
- iphone/Maps/UI/Search/SearchBar.swift
This PF continues https://github.com/organicmaps/organicmaps/pull/7236 and fixes some issues for iOS12.
Usually UIKit exends UIImage to the TextField's edges and 1.0 size is enough to render proper image. But it works properly only scince iOS13 and doesn't work on iOS12 (which doesn't extend height).
`control.setSearchFieldBackgroundImage(UIImage(), for: .normal) `is not working on iOS 12 and breaks layout and colors.
But this call is needed to remove defalut tinted image from TextField's background when UISearchController is used.
How this bug looks on iOS12:
Tested on iOS 12.5 (iPhone 6).
> [ios] fix search bars for iOS12

- android/app/src/main/java/app/organicmaps/settings/SettingsPrefsFragment.java
- android/app/src/main/res/values/donottranslate.xml
- android/app/src/main/res/xml/prefs_main.xml
This PR:
- Add a new preference key `prefs_routing`
- Implement `updateRoutingSettingsPrefsSummary` method to update summary of routing preference when one of routing options was enabled as Andrew has done for TTS preference
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/2de4ef09-9366-48f0-94e9-9ba369eaba98" height=500 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/c46347b4-5fee-4d58-802b-36bfc9d4c61e" height=500 />|
> [android] Add summary to know when routing options is enabled

- indexer/feature.cpp
This reverts commit 3919b98c32c28da59e25638aa181e4a890f9bc4c.
Closes https://github.com/organicmaps/organicmaps/issues/7162
This CHECK should be present in the generator branch only.
Relation https://www.openstreetmap.org/relation/14474492 was ill-formed.
> Revert "[generator] Use release CHECK to verify FeatureType geometry."

- iphone/Maps/Classes/CustomAlert/CreateBookmarkCategory/MWMBCCreateCategoryAlert.xib
- iphone/Maps/Classes/CustomAlert/MWMPlaceDoesntExistAlert.xib
- iphone/Maps/Core/Settings/MWMSettings.mm
- iphone/Maps/Core/Theme/Core/ThemeManager.swift
- iphone/Maps/Core/Theme/GlobalStyleSheet.swift
Closes  https://github.com/organicmaps/organicmaps/issues/7448
This PR fixes:
Bug was caused by doubling style name attributes in the textfield:
How to reproduce:
1. Set in the application settings appearance to the light (dark)
2. Terminate the application
3. Change the device's theme to the dark (light)
4. Open the OM
5. Goes to the Bookmarks edit or Settings and change the device's theme again (multiple times)
6. You will see that some elements can change their colors
This bug is caused by the issue in the system theme changing implementation: when the user change the theme in the settings we override the native `window.traitCollection.userInterfaceStyle` in the `MWMSettings setTheme`, but this property is not overridden on the app launch. So there is no mechanism to restore the state …
> [ios] Fix themes switching issues

- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListInterfaces.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListPresenter.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListRouter.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListViewController.swift
- iphone/Maps/Bookmarks/BookmarksList/Cells/BookmarkCell.swift
- iphone/Maps/Bookmarks/BookmarksList/Cells/BookmarkCell.xib
- iphone/Maps/Bookmarks/BookmarksList/Cells/TrackCell.swift
- iphone/Maps/Bookmarks/BookmarksList/Cells/TrackCell.xib
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/ColorPicker/ColorPicker.swift
- iphone/Maps/UI/EditBookmark/BookmarkColorViewController.swift
- iphone/Maps/UI/EditBookmark/EditBookmarkViewController.swift
- iphone/Maps/UI/EditBookmark/EditTrackViewController.swift
- iphone/Maps/UI/EditBookmark/SelectBookmarkGroupViewController.swift
This PR implements:
1. Modal presentation for the color selection
When a user want to quickly change a single option there is better solution to make the screen modal. Why modal? Apple's hig says:
> Help people perform a distinct, narrowly scoped task without **losing track of their previous context**
https://developer.apple.com/design/human-interface-guidelines/modality
2. Modal presentation for the category selection (to match with the color selection)
3. Possibility to change color by tapping on the `circle color icon` without opening the `Edit bookmark` screen (it's really faster to change color now!)
4. New reusable ColorPicker class that:
- use native color picking for tracks if > iOS14.0
- use old color picking for all other cases and `iPad designed for Mac` (because on mac this …
> [ios] Change the bookmarks/tracks color from the color icon modally

- iphone/Maps/UI/ColorPicker/ColorPicker.swift
- iphone/Maps/UI/EditBookmark/EditTrackViewController.swift
Fix crash caused by the https://github.com/organicmaps/organicmaps/pull/7499 whe non srgb color passed from the ColorPicker.
> [ios] Fix srgb color crash

- android/app/build.gradle
After updating Android Studio to version Iguana (2023.2.1), I get many `error: cannot find symbol xxxxx` java build errors.
This PR adds to the `android/app/build.gradle` file a couple of needed `androidx.*` dependencies.
> [android] Add 'androidx' dependencies to build.gradle

- tools/python/clean_strings_txt.py
In commit [[strings][android] Google Play only translation for OSM login](https://github.com/organicmaps/organicmaps/commit/9e7a63ed63e1bc8dfabf5a870a5bc80d824d2765) @biodranik added new string `"username"` which is used in a single file `android/app/src/google/res/layout/osm_login_text_input.xml`
But strings generation script fails with `ERROR: there are unused strings` because it doesn't search in `android/app/src/google` resources.
Fix: Added Google subfolder to string usage search
> [String] Fix string usage script

- iphone/Maps/Bookmarks/BookmarksList/Cells/SubgroupCell.xib
- iphone/Maps/Bookmarks/Categories/Categories/BMCCategoryCell.xib
- iphone/Maps/Images.xcassets/ic_eye_off.imageset/Contents.json
- iphone/Maps/Images.xcassets/ic_eye_off.imageset/ic_eye_off.svg
- iphone/Maps/Images.xcassets/ic_eye_on.imageset/Contents.json
- iphone/Maps/Images.xcassets/ic_eye_on.imageset/ic_eye_on.svg
Closes https://github.com/organicmaps/organicmaps/issues/7566
This PR fixes the issue caused by the previous PR https://github.com/organicmaps/organicmaps/pull/7508 when `eye icon` is used by mistake not only for the BMCViewController (categories list) but for the Opening hours too.
Tested on: 
iPhone 6 iOS12.5 (device)
iPhone 11pro iOS17.2 (device)
iPhone 15pro iOS17.2 (sim)
Result: eye icons are implemented only for the bookmarks lit cells and for the opening hours icon is reverted.
> [ios] Fix opening hours icons

- base/internal/message.hpp
- drape/drape_tests/bidi_tests.cpp
- drape/utils/glyph_usage_tracker.cpp
Commit f05be9bf713a6ad7e686695de89296b728a26176,
changed `UniChar` from  `uint32_t` to `char32_t`.
Unlike `uint32_t` the `char32_t` has explicitly
deleted `<<` operator in C++20, and this operator
has been in use on `UniChar`.
> [base][drape] Fix `deleted operator <<` of char32_t on C++20

- data/categories.txt
- data/editor.config
Note they're different from `amenity-parcel_locker` (unmanned).
And they're not necessarily a "postal" feature (hence I didn't add to `@post` category) as they might just serve some big outlet store nearby. But also could be a manned / walk-in version of `amenity-parcel_locker`.
> Make [parcel] pickup points (shop-outpost) searchable and addable

- iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.m
Closes https://github.com/organicmaps/organicmaps/issues/7567
This bug is caused by https://github.com/organicmaps/organicmaps/pull/7292
Sometimes when the `traitCollectionDidChange` was called by the system during the view's initialization from nib on a device this icon was redrawn in a wrong way: the icon changed its state from selected to deselected by mistake.
This PF fixes this bug. 
Before:
https://github.com/organicmaps/organicmaps/assets/79797627/cb3668af-e53c-4cbf-9417-be3e689c47d2
After:
https://github.com/organicmaps/organicmaps/assets/79797627/4c6409f3-018c-4205-b733-242ebd1c6a0b
> [ios] Fix bug when the user's 'saved bookmark' tab icon has wrong selected color and icon

- android/app/src/main/cpp/app/organicmaps/bookmarks/data/BookmarkManager.cpp
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkCategoriesDataProvider.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkManager.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/CacheBookmarkCategoriesDataProvider.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/CoreBookmarkCategoriesDataProvider.java
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListInteractor.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
- iphone/Maps/Bookmarks/Categories/Category settings/CategorySettingsViewController.swift
- iphone/Maps/Classes/CarPlay/Template Builders/ListTemplateBuilder.swift
- iphone/Maps/UI/EditBookmark/SelectBookmarkGroupViewController.swift
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/map_tests/bookmarks_test.cpp
- qt/bookmark_dialog.cpp
- qt/screenshoter.cpp
Closes https://github.com/organicmaps/organicmaps/issues/3475
This issue contains two bugs:
1. To display the categories list in the ios we use MWMBookmarksManager's :
` (NSArray<MWMBookmarkGroup *> *)userCategories;`
which calls c++ BoormarkManager's
`auto const & list = self.bm.GetBmGroupsIdList(); `
which returns
`kml::GroupIdCollection const & GetBmGroupsIdList() const { return m_bmGroupsIdList; }`
`m_bmGroupsIdList` is a sorted list of categories ids
and sorting happens in the method:
```cpp
void BookmarkManager::UpdateBmGroupIdList()
{
CHECK_THREAD_CHECKER(m_threadChecker, ());
size_t const count = m_categories.size();
// All this routine to get sorted list by last modified time.
using PairT = std::pair<kml::MarkGroupId, BookmarkCategory const *>;
std::vector<PairT> vec; …
```
> [bookmarks] [ios] Fix bookmarks categories sorting bug

- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/map_tests/bookmarks_test.cpp
- platform/platform.hpp
- platform/platform_android.cpp
- platform/platform_ios.mm
- platform/platform_linux.cpp
- platform/platform_mac.mm
- platform/platform_tests/platform_test.cpp
Fixes #7564
@cyber-toad The fix was easy, there is no need to use the last modified file time because files are often copied anyway just before importing them, due to system restrictions.
@kirylkaveryn can you please test it and confirm that the fix works?
> Set last modified time for imported KML or GPX before saving them

- android/app/src/main/java/app/organicmaps/editor/data/HoursMinutes.java
The fix for another crash caused by ede7eda0c00df40a6cb23330ee888cbc64eca50e
CC @Isira-Seneviratne @rtsisyk 
```
03-19 16:26:26.539 E/AndroidRuntime( 2828): FATAL EXCEPTION: main
03-19 16:26:26.539 E/AndroidRuntime( 2828): Process: app.organicmaps, PID: 2828
03-19 16:26:26.539 E/AndroidRuntime( 2828): j$.time.DateTimeException: Invalid value for HourOfDay (valid values 0 - 23): 24
03-19 16:26:26.539 E/AndroidRuntime( 2828):  at j$.time.temporal.ValueRange.checkValidValue(Unknown Source:13)
03-19 16:26:26.539 E/AndroidRuntime( 2828):  at j$.time.temporal.ChronoField.checkValidValue(Unknown Source:4)
03-19 16:26:26.539 E/AndroidRuntime( 2828):  at j$.time.LocalTime.of(Unknown Source:3)
03-19 16:26:26.539 E/AndroidRuntime( 2828):  at …
```
> [android] Fixed crash when opening PP displaying 24h opening hours with 12h system time format

- android/app/src/main/res/layout/map_buttons_layout_planning.xml
Fixes #7680 
Resolved the overlap issue
> [android] fix the overlapping of map buttons in RTL map planning

- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm
Closes https://github.com/organicmaps/organicmaps/issues/7509
This bug was caused by the https://github.com/organicmaps/organicmaps/pull/7331 when after selecting the `Transport` routing type some properties (timeToTarget, targetDistance, targetUnits) weren't properly updated estimates.
Tested on:
- iPhone 11Pro 17.2 (device)
- iPhone 6 12.5 (device)
Result:
https://github.com/organicmaps/organicmaps/assets/79797627/0395c109-c4ce-4b21-a9fc-a4a028af1ba3
> [ios] Fix estimates when the following type is changing

- iphone/Maps/Classes/CarPlay/CarPlayRouter.swift
- iphone/Maps/Classes/CarPlay/CarPlayService.swift
- iphone/Maps/Classes/CarPlay/Templates Data/RouteInfo.swift
- iphone/Maps/Core/Framework/ProxyObjects/Routing/MWMRoutingManager.mm
Use NumberFormatter to parse distance instead of Double.
Fixes #6209
Fixes #6478
> [ios] Fix distance freeze for locales with comma as decimal seperator

- android/app/src/main/res/color/text_color_primary.xml
- android/app/src/main/res/color/text_color_primary_dark.xml
- android/app/src/main/res/color/text_color_secondary.xml
- android/app/src/main/res/color/text_color_secondary_dark.xml
- android/app/src/main/res/values/themes-base.xml
This PR enables the change of colors (dimming) when the Preferences are disabled (currently, in the Settings Page for the "Voice Instructions"), for better location of enabled/disabled controls:
> [android] Change color for disabled texts

- map/bookmark.cpp
- map/bookmark.hpp
- map/bookmark_manager.cpp
- map/user_mark_layer.cpp
- map/user_mark_layer.hpp
Fixes #7645 by disabling update of the modification time when list visibility is changed.
Below is an initial text for this PR.
---
As we started to honestly sort lists by their modification time, any visibility change that modifies a list, now also changes its order.
There is a benefit in moving hidden lists at the bottom.
Moving enabled lists at the top also makes sense.
But it does not look very intuitive and convenient. Should we avoid any automatic sorting at all and allow only manual sorting? Should we add sort by name instead / in addition?
Another option is to not modify the list "last modified" field when its visibility is changed. Here we have two options:
1. Sort and show checked/visible lists first, at the top.
2. Don't sort and show a mix of checked/unchecked lists.
Any …
> [bookmarks] Do not update bookmark list modification time when list visibility is changed

- platform/CMakeLists.txt
ld: warning: ignoring duplicate libraries: 'libbase.a' Undefined symbols for architecture arm64:
"_SecPKCS12Import", referenced from:
-[MultipartUploadTask extractIdentityWithCertData:certPassword:] in libplatform.a[2](unity_0_mm.mm.o)
"_kSecImportExportPassphrase", referenced from:
-[MultipartUploadTask extractIdentityWithCertData:certPassword:] in libplatform.a[2](unity_0_mm.mm.o)
"_kSecImportItemCertChain", referenced from:
-[MultipartUploadTask extractIdentityWithCertData:certPassword:] in libplatform.a[2](unity_0_mm.mm.o)
"_kSecImportItemIdentity", referenced from:
-[MultipartUploadTask extractIdentityWithCertData:certPassword:] in libplatform.a[2](unity_0_mm.mm.o)
ld: symbol(s) not found for architecture arm64
> [mac] Fixes linker error for bsdiff_tests

- data/countries_names.txt
The translation of Republika Srpska in some languages (az, ca, et) appears to be confused with Republika Serbia.
I changed it to the current translation from Wikipedia.
> [strings] Update translation for Republika Srpska

- coding/internal/file_data.cpp
C standard does not guarantee that file opened in append mode is seeked to the end. In particular, MSVC CRT does not do that, so ftell64 always returns 0. Fixes some tests on Windows.
> Always seek to end of file when opening in append mode

- data/replaced_tags.txt
closes #3156
Removed `shop=vacant` by replacing it with `disused:shop=yes` in `data/replace_tats.txt`
before
now
OSM: https://www.openstreetmap.org/node/4338842100
> [styles] Removed shop=vacant

- iphone/Maps/Classes/CustomViews/CircularProgress/MWMCircularProgressView.m
Closes https://github.com/organicmaps/organicmaps/issues/7782
I cannot reproduce such a huge mismatch, but I found that the device rotation will trigger the progress bar layout reloading, but the bar's `backgroundLayer` will not update its path.
This PR fixes this issue by refreshing the backgroundLayer's path too.
How to reproduce: 
- Start downloading some maps
- Tap on the some PP in this region
- Rotate the device
- You will see a small gap between bars
- It will be more visible if you open PP in the horizontal orientation and rotate to the vertical.
Tested on:
Before:
(it's hard to see it on the gif)
After:
> [ios] Fix the circular downloading progress bar layout on the PP screen

- data/mapcss-mapping.csv
natural=stone has 55k uses, by description hardly has any difference to natural=rock
- related to #6312
> [classif] Merge natural=stone into natural=rock

- iphone/Maps/Classes/CustomAlert/Toast/Toast.swift
- iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm
Fixing issue #7555 by adding capability to hide toast when view disappears.  Also addressed potential other cases.
https://github.com/organicmaps/organicmaps/assets/156805389/b8c4d10a-56ca-4544-9417-61b4eab98f79
Tested on iPhone 15 simulator
> [ios] Fix isolines reminder being displayed on top of other dialogs

- README.md
Outdoor Style wasn't a GSOC project.
(The project was about internal refactoring of the styles system, so not really user-facing, hence little point mentioning it).
> [docs] Remove Outdoor style from GSOC projects

- android/app/src/main/res/values-bg/strings.xml
- android/app/src/main/res/values/strings.xml
- data/categories.txt
- data/editor.config
- data/strings/types_strings.txt
- editor/editor_tests/editor_config_test.cpp
- iphone/Maps/LocalizedStrings/bg.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/ca.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/en-GB.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/en.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/hi.lproj/Localizable.strings
Many of the following types are better mapped as areas (as a building usually), however:
- its much better to have a node than nothing
- if there is a node, then its more obvious/actionable that it could be further improved
- most renderers (OM included) render them the same (icon & label) regardless whether its an area or node
- people are confused why can't they add a specific POI when they see same POI type present on the map
- https://github.com/organicmaps/organicmaps/issues/6733
I've also checked that:
- OSM wiki allows mapping a particular feature as a node
- at least 20% of mapped features are nodes, so its not uncommon way
Enabled adding which was previously disabled:
(initially when editor config was added many more types had "adding" disabled e.g. hospitals, colleges, …
> [editor] Add/allow more types commonly mapped as nodes

- indexer/editable_map_object.cpp
Don't mistakenly update wheelchair values in OSM database
* Fixes https://github.com/organicmaps/organicmaps/issues/7642
> [editor] Don't mistakenly update wheelchair values in OSM database

- iphone/Maps/Maps.xcodeproj/project.pbxproj
- xcode/common.xcconfig
- xcode/kml/kml.xcodeproj/project.pbxproj
- xcode/platform/platform.xcodeproj/project.pbxproj
- xcode/search/search.xcodeproj/project.pbxproj
- Increased MACOSX_DEPLOYMENT_TARGET to 10.15 (Catalina)
- Automatically generate info.plist file for test binaries
- Fixed paths to Qt6
Our desktop test targets can be run from XCode (some of them may need to fix dependencies first).
> [xcode] Fixed running test binaries on Mac

- packaging/app.organicmaps.desktop.metainfo.xml
Fixes the following two flathub linter warnings:
I: app.organicmaps.desktop:6: developer-name-tag-deprecated
The toplevel `developer_name` element is deprecated. Please use the `name` element in a
`developer` block instead.
I: app.organicmaps.desktop:~: developer-info-missing
This component contains no `developer` element with information about its author.
> [packaging] Fix deprecated `developer_name` & missing `developer`

- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/PrivacyInfo.xcprivacy
Closes https://github.com/organicmaps/organicmaps/issues/7754
This PR adds PrivacyInfo file with missing API declarations as described in [Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api).
> [ios] Add PrivacyInfo with missing API declarations

- base/base_tests/buffer_vector_test.cpp
- base/internal/message.cpp
- base/internal/message.hpp
- drape/CMakeLists.txt
- drape/drape_tests/font_texture_tests.cpp
- drape/drape_tests/glyph_mng_tests.cpp
- drape/font_constants.hpp
- drape/font_texture.cpp
- drape/glyph_manager.cpp
- drape/glyph_manager.hpp
- drape/texture_manager.cpp
- drape_frontend/gui/gui_text.cpp
- drape_frontend/text_layout.cpp
- drape_frontend/text_layout.hpp
- qt/CMakeLists.txt
> Minor drape fixes

- data/mapcss-mapping.csv
- `drinking_water:refill=yes` (>500 uses), closes https://github.com/organicmaps/organicmaps/issues/7613
- `drinking_water=treated` (>200 uses)
> Support drinking_water:refill=yes

- data/categories.txt
- drape_frontend/selection_shape_generator.cpp
- search/search_integration_tests/processor_test.cpp
Closes https://github.com/organicmaps/organicmaps/issues/7867
Closes https://github.com/organicmaps/organicmaps/issues/3269
> [search] Do not emit private swimming pools.

- tools/python/translate.py
```
[tools] Updated translate.py script
- Correct/filter out pt-PT and zh translations
- Use ar in DeepL
- Remove es-MX as it is not supported by Google
```
> [tools] Filter out pt-PT and zh translation generated by Google

- iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuItemCell.swift
- iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuItemCell.xib
Sorry, i'm creating a new PR to close out issue 7605. I inadvertently closed it as it was on the main branch. I created a new branch and am pushed the same commit as before. 
Here is a link to the previous PR:
https://github.com/organicmaps/organicmaps/pull/7689
Text from previous PR:
Update the xib and swift files related to BottomMenuItemCell to address the issue seen in fixed https://github.com/organicmaps/organicmaps/issues/7605 issue.
Fixes #6213 as seen here:
Tested on Simulator iPhone SE 1st gen iOS 15
> [ios] fix: Text trimming on the Menu screen on small screen #7605

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkManager.java
Google Files app uses incorrect binary mime type when opening gpx files, this change allows to import gpx from Google Files app into Organic Maps.
Samsung browser adds .xml extension to downloaded files, this change also allows to import such files.
> [android] Import .gpx and .gpx.xml files from Google Files app

- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Classes/MapsAppDelegate.h
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/Maps.xcodeproj/xcshareddata/xcschemes/OMaps.xcscheme
- iphone/Maps/Tests/CarPlayServiceTests.swift
- iphone/Maps/UI/CarPlay/CarPlayMapViewController.swift
This PR adds the `Unit test target` to iOS.
---
The easiest way to add some tests:
1. select in the XCode `File -> New -> File...`
2. find and select `Unit Test Case Class`
3. pay attention that `OMapsTest` target is selected
4. Save into `Tests` directory
5. Add the line  `@testable import Organic_Maps__Debug_` below `import XCTest` to get access to all OM public and internal classes.
6. Write your tests
7. Select a simulator as a run destination to run test cases. 
--- 
As an example the test case for the `CarPlayService` method `createEstimates` (thanks to @fabwu for fix) was added:
Before the fix we can see that test case the with coma-separator used for the distace initialization fails and with dot passes:
After fix (using the double instead of the string):
---
At least one issue …
> [ios] add unit test target

- 3party/open-location-code/openlocationcode.cc
Without this change the code can not be compiled with the latest GCC 13 because an error reported on `openlocationcode.cc:139:3`.
```
error: 'int64_t' was not declared in this scope
note: 'int64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
```
The porting guide of GCC 13 explains,
that `cstdint` might need to be explicitly included: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
> Fix missing cstdint on GCC 13

- editor/changeset_wrapper.cpp
- editor/changeset_wrapper.hpp
- editor/osm_editor.cpp
fixes #2298
This PR solves the problem that, when adding a node at a location where a different node is located already, the tags of the new feature are added to the existing node. This often leads to nonsense combinations (see #2298) and can also make address nodes unusable.
Test:
- Bug in current Play Store version: https://www.openstreetmap.org/changeset/149696066
- This PR doesn't overwrite the old node, but creates a new node: https://www.openstreetmap.org/changeset/149697572
The existing node remains untouched: https://www.openstreetmap.org/node/11257500263
> [editor] Fixed bug overwriting existing features

- iphone/Maps/Maps.xcodeproj/xcshareddata/xcschemes/OMaps.xcscheme
When you run the tests by default Xcode uses the tests parallelizing. When tests are run in parallel, Xcode spins up multiple clones of the simulator. These simulator windows are named “Clone 1” and so on. This makes sense for slow-running UI tests but not for the fast-running unit tests. It takes longer for Xcode to set up the simulator clones.
This PR disables the tests parallelizing.
> [xcode] Disable the tests parallelizing

- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksObserver.h
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListInteractor.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListInterfaces.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListPresenter.swift
- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
For now to handle the` file sharing` OM uses the observing pattern tightened to the MWMBookmarksManagers, that is too complex for this straightforward task:
1. subscribe for the observarion
2. register observer
3. send sharing message
4. wait for sharing result
5. handle sharing result
6. notify observers
7. unsubscribe from observing
This is too complex because the c++ method that we interact with uses the completion handlers to return sharing results and there is no sense in wrapping the completion handle into observation:
```cpp
void BookmarkManager::PrepareFileForSharing(kml::GroupIdCollection && categoriesIds, SharingHandler && handler)
```
This PR converts c++ completion handler into the objc and returns to the caller so we can share files easily with the MWMBookmarksManagers and …
> [ios] [bookmarks] Remove observer pattern during the category files exporting

- iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuItemCell.xib
to fix issue #7863 relating to rtl languages.
Tested on iPad pro 11 simulator:
here in arabic:
in hebrew:
in english:
> [ios] fix alignment of rtl languages in bottom menu

- iphone/Maps/Bookmarks/BookmarksList/BookmarksListInterfaces.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListPresenter.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListViewController.swift
Resolution of issue #7894
Tested on iPad Pro 11 simulator
https://github.com/organicmaps/organicmaps/assets/156805389/c4644cdd-1481-49d9-98a1-13a2e5ae3eb6
> [ios] Correct location of more menu in bookmark lists

- iphone/Maps/UI/Editor/MWMEditorViewController.mm
A break was missing in the switch-case and was causing a fallthrough and a crash in debug. This fixes it.
* Related to https://github.com/organicmaps/organicmaps/pull/7835
> [ios][editor] Fix unintended fallthrough in switch-case

- android/app/src/main/java/app/organicmaps/routing/RoutingController.java
The public transportation router was forcibly overriding the previously selected mode whenever the planning activity was resumed, with the subway layer active. For instance, if you started a route planning (which automatically uses PT when that layer is on), switched to car mode and then changed some driving options, when you got back to the planning screen, the router would have changed back to PT, instead of keeping it on car.
This occurred because of `RoutingController#rebuildLastRoute`, called whenever an activity (such as the driving options) concluded, which would, indirectly, call `RoutingController#initLastRouteType`. This method is responsible for defaulting the router to the most adequate type for the start+finish point combo, or, if the subway layer is selected, to set it to …
> [android] Fix PT router overriding previous mode if subway layer active

- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
- iphone/Maps/Categories/UIApplication+LoadingOverlay.swift
- iphone/Maps/Classes/LoadingOverlay/LoadingOverlayViewController.swift
- iphone/Maps/Maps.xcodeproj/project.pbxproj
The sharing process may take some time when there are many files and the screen isn't blocked during this process.
Current behavior:
https://github.com/organicmaps/organicmaps/assets/79797627/671f7229-52c2-4d1d-8713-f22e77a0f304
___
This PR adds a loading overlay screen with an activity indicator that disables user interaction while files are being prepared.
The Dimming effect isn't very strong (0,3 alpha) but it can be increased.
Result:
https://github.com/organicmaps/organicmaps/assets/79797627/735279e3-d87e-4faa-92e7-e3e433a65662
Tested on:
iPhone 11pro (17.2)
iPhone 6 (12.5)
MasOS designed for iPad
> [ios] Add a loading overlay screen with an activity indicator for the bookmarks sharing

- iphone/Maps/UI/Help/AboutController/AboutController.swift
These changes are to add default email client support in the about menu. Issue #7758.
I tested it on my ipad 11 running 17.0.3
I would post a video but opening the email app does share some personal info
> [ios] Add default email client support to about menu

- android/app/src/main/res/values-eu/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/eu.lproj/Localizable.strings
Some translation corrections in the "eu" version
> [strings] Update strings.txt EU

- .github/workflows/linux-check.yaml
- drape/drape_tests/font_texture_tests.cpp
- drape/drape_tests/glyph_mng_tests.cpp
Allows to test how fonts are rendered on Linux.
Related to #4281
> [linux] Run GlyphLoadingTest on Linux with GUI

- base/base.cpp
- base/internal/message.hpp
- base/logging.cpp
- base/logging.hpp
- qt/main.cpp
Example:
```
I(1) 0.72366 search/processor.cpp:210 SetPreferredLocale(): New preferred locale: en
D(1) 0.72374 search/processor.cpp:229 SetInputLocale(): New input locale: en locale code:
W(2) 0.72979 search/geocoder.cpp:736 CacheWorldLocalities(): Can't find World map file.
```
Before change:
```
LOG TID(1) DEBUG  7.1459e-05 platform/platform_mac.mm:135 Platform: Resources Directory: /
LOG TID(1) DEBUG 0.000118709 platform/platform_mac.mm:136 Platform: Writable Directory: /
LOG TID(1) DEBUG    0.000133 platform/platform_mac.mm:137 Platform: Tmp Directory: /
LOG TID(1) DEBUG 0.000136417 platform/platform_mac.mm:138 Platform: Settings Directory: /
LOG TID(1) INFO  0.000162875 qt/main.cpp:121 main(): Organic Maps 2024.04.22-3-c91add3a-Darwin started, detected CPU cores: 1024
```
> [core] Simplified logs output

- map/routing_manager.cpp
- search/search_quality/helpers.cpp
- search/search_quality/sample.cpp
- storage/diff_scheme/diff_scheme_loader.cpp
- tools/python/maps_generator/generator/stages_declaration.py
- tools/python/post_generation/__main__.py
This change will reduce the size of generated countries.txt from 405K to 355K, which is beneficial for app size and for future transfers over the wire.
> Save produced json in a more compact UTF-8 format

- data/mapcss-mapping.csv
- data/styles/clear/include/Roads.mapcss
- data/styles/outdoors/include/Roads.mapcss
- generator/generator_tests/osm_type_test.cpp
- generator/osm2type.cpp
Follow-up to https://github.com/organicmaps/organicmaps/pull/7878
Treating all `bicycle=yes` ways as shared paths was a mistake, see
- https://github.com/organicmaps/organicmaps/pull/8018
This patch makes only `bicycle=designated` ways treated as shared (with a special rendering). E.g. for footways it means ~8-9 times less will be "shared".
It doesn't affect routing which should be fixed also IMO.
> [classif] Don't treat bicycle=yes as a shared path

- CMakeLists.txt
The message is too noisy to be printed on every configure run.
`FATAL_ERROR` part is covered by `REQUIRED` argument in `find_package` call.
Since this happens after `add_subdirectory(3party)`, I removed its mention from comment.
> Don't use custom error handling when searching for python

- map/place_page_info.cpp
This PR adds back the missing local language name to the place page. 
I think this may have been lost in the SetFromFeatureType refactoring in https://github.com/organicmaps/organicmaps/pull/7334. @vng PTAL
* Fixes https://github.com/organicmaps/organicmaps/issues/7795
---
> [placepage] Add missing local language name

- generator/osm_element.cpp
- generator/osm_element.hpp
- generator/relation_tags.cpp
- generator/relation_tags.hpp
https://github.com/organicmaps/organicmaps/issues/8028
> [generator] Fixed foot/bicycle tag from Relation.

- iphone/Maps/UI/Editor/Cells/MWMEditorAdditionalNameTableViewCell.m
- iphone/Maps/UI/Editor/Cells/MWMEditorAdditionalNameTableViewCell.xib
This PR fixes the cell layout and increases the tappable zone so that when you tap on any cell area the text field activates.
Before:
After:
> [ios]  Fix the AdditionalNameTableViewCell tappable area

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarkCollectionAdapter.java
- android/app/src/main/java/app/organicmaps/bookmarks/ChooseBookmarkCategoryFragment.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkManager.java
- android/app/src/main/java/app/organicmaps/editor/EditorFragment.java
- android/app/src/main/java/app/organicmaps/editor/FeatureCategoryFragment.java
- android/app/src/main/java/app/organicmaps/editor/OsmLoginFragment.java
- android/app/src/main/java/app/organicmaps/editor/PhoneListAdapter.java
- android/app/src/main/java/app/organicmaps/editor/SimpleTimetableAdapter.java
- android/app/src/main/java/app/organicmaps/location/AndroidNativeProvider.java
- android/app/src/main/java/app/organicmaps/location/LocationHelper.java
- android/app/src/main/java/app/organicmaps/location/RouteSimulationProvider.java
- android/app/src/main/java/app/organicmaps/maplayer/SearchWheel.java
- android/app/src/main/java/app/organicmaps/routing/BaseRoutingErrorDialogFragment.java
- android/app/src/main/java/app/organicmaps/search/CategoriesAdapter.java
- android/app/src/main/java/app/organicmaps/search/TabAdapter.java
- android/app/src/main/java/app/organicmaps/settings/StorageItem.java
- android/app/src/main/java/app/organicmaps/util/Utils.java
- android/app/src/main/java/app/organicmaps/util/bottomsheet/MenuBottomSheetFragment.java
- android/app/src/main/java/app/organicmaps/widget/placepage/BookmarkColorDialogFragment.java
- android/app/src/main/java/app/organicmaps/widget/placepage/DirectionFragment.java
- android/app/src/main/java/app/organicmaps/widget/placepage/sections/PlacePhoneAdapter.java
This PR fixes some Android Studio warnings:
- Remove unused imports
- Replace StringBuilder with String
- Use lambda
- Replace `.size == 0` by `isEmpty()`
- Remove useless semicolons
- Remove redundant type
- Use final on variables when possible
> [android] Remove Android Studio warnings

- indexer/editable_map_object.cpp
- indexer/editable_map_object.hpp
- indexer/indexer_tests/editable_map_object_test.cpp
- map/framework.cpp
closes #1481
- Removed code that prevents users from adding a multilingual name in case it is the same as `name=*`. In uni lingual countries the OSM convention is that e.g. `name:de` should be the same as `name`. (see: #1481)
- ~~Allowed users to remove names / submit an empty name. This is e.g. helpful when the name of a POI (e.g. restaurant) changes. OM users can then update the multilingual names in languages they know and remove the wrong names in languages they don't know (no multilingual name is better than a wrong one) (see: #6292)~~
> [editor] Removed superfluous name=* restrictions

- iphone/Maps/UI/Editor/MWMEditorViewController.mm
This PR fixes the bug when the same language can be added multiple times to the additional languages list.
Tested on:
https://github.com/organicmaps/organicmaps/assets/79797627/6e23d3bd-f087-45ab-9ceb-20235c7bbdf6
Edit:
Add:
> [ios]  Fix the bug when the same language can be added multiple times to the additional languages list

- qt/mainwindow.cpp
This small PR adds the option to quit the OrganicMaps application with a Ctrl-Q keyboard shortcut or using the "Exit" entry on the menu.
I have tested it in Linux and seems to be working fine. This is my first contribution to OrganicMaps, so forgive me if it does not follow all the guidelines.
> [desktop] Add "Exit" menu option and Ctrl-Q shortcut to quit the desktop application

- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarkGroup.m
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
This method is needed to implement the following features:
- hide the `export all` button (https://github.com/organicmaps/organicmaps/issues/8055)
- disable the `backup` button into the icloud sync enabling alert
Also, I've made a small refactoring of the `isCategoryNotEmpty` method to use the already `IsCategoryEmpty` which checks the `empty` (rather than the `cont`).
> [Bookmarks] Add `areAllCategoriesEmpty` method to the bookmarks manager

- editor/changeset_wrapper.cpp
- editor/changeset_wrapper.hpp
- editor/osm_editor.cpp
This doesn't work well in many cases:
https://github.com/organicmaps/organicmaps/issues/8125
This reverts commit 3c9c54eda61d84609bdcf5f298d0abb26e3f4281.
Reopens #2298, closes #8125, reverts #7853
> Revert "[editor] Fixed bug overwriting existing features"

- map/bookmark_manager.cpp
Log printing uses charPtr as char const *, assuming that it's a null-terminated string. But it's a vector.
> Fixed memory access past the end of the vector data

- drape_frontend/gui/gui_text.cpp
- drape_frontend/gui/gui_text.hpp
Should fix https://github.com/organicmaps/organicmaps/issues/8128 and linked issues.
Fixes #8127
Fixes #8108
> [drape] Fixed MutableLabelHandle mutation buffer's size.

- iphone/Maps/Classes/CustomViews/Login/MWMAuthorizationLoginViewController.mm
- iphone/Maps/Classes/CustomViews/Login/MWMAuthorizationOSMLoginViewController.mm
This PR fixes https://github.com/organicmaps/organicmaps/issues/8136 only for iOS:
- Remove capitalizedString for “OSM account” title;
- Remove capitalizedString for “OpenStreetMap Profile” title.
> [ios] Remove OSM login titles capitalization

- editor/opening_hours_ui.cpp
Fixes #3036
Changed verifications to allow the non-business hours button to work after midnight.
> [iOS] Non-Business Hours button works after midnight

- editor/changeset_wrapper.cpp
- editor/changeset_wrapper.hpp
- editor/osm_editor.cpp
Re-added flagging, like in #7853, but for "info:features_merged=yes" instead of "feature_cloes_by". 
The "info:features_merged=yes" tag is added to changesets when the feature merging code is executed. This makes evaluating / making statistics for #2298 possible (see: https://github.com/organicmaps/organicmaps/pull/7853#discussion_r1558308223).
:heavy_check_mark: Tested in https://www.openstreetmap.org/changeset/151378253
> [editor] Add flag to changeset when features are merged

- drape/font_constants.hpp
- drape/font_texture.cpp
- drape/glyph.hpp
- drape/glyph_manager.cpp
- drape/glyph_manager.hpp
- drape/texture_manager.cpp
- drape_frontend/backend_renderer.cpp
- drape_frontend/gui/gui_text.cpp
- drape_frontend/text_layout.cpp
- drape_frontend/visual_params.cpp
- drape_frontend/visual_params.hpp
All glyphs are rendered to the texture in SDF mode, with the same base size.
They are scaled to the necessary size when the text is rendered to another texture.
> [drape] Use global constant for the base font size and removed unused vars

- platform/measurement_utils.cpp
- platform/platform_tests/measurement_tests.cpp
from: `https://osm.org/go/0EEFEVaz-?m=`
to: `https://osm.org/go/0EEFEVaz-?m`
tiny fix, looks a bit strange to have an empty query string
> [platform] remove redundant `=` from osm.org/go link

- data/strings/types_strings.txt
Quick fix: fixed Portuguese exit (entrance/door) strings.
Although PT and PT-BR translations are the same, since it seems OM is moving translations to Weblate, I preferred to have it duplicated. Let's see how it works in the future.
> [strings] Fixed Portuguese exit strings

- editor/editor_tests/ui2oh_test.cpp
- editor/ui2oh.cpp
This PR fixes the parsing of the "opening hours" strings that start with an "off" statement.
One example of opening hours not being processed correctly is the opening_hours tag `Mo off; Tu-Su 12:00-16:30, 19:00-24:00` of [this restaurant in OSM](https://www.openstreetmap.org/node/9592619990).
Current opening hours parsing implementation does not like "off" statements if they are located in the first place, so this PR reorders the statements by placing the "off" ones at the end of the list.
This PR closes [PR 1612](https://github.com/organicmaps/organicmaps/issues/1612)
> [editor] Fix parsing of 'off' opening hours

- iphone/Maps/Core/Location/MWMLocationManager.mm
> [CLActivityTypeOtherNavigation](https://developer.apple.com/documentation/corelocation/clactivitytype/clactivitytypeothernavigation?language=objc)
The value that indicates positioning for activities that don’t or may not adhere to roads such as cycling, scooters, trains, boats and off-road vehicles.
> [CLActivityTypeFitness](https://developer.apple.com/documentation/corelocation/clactivitytype/clactivitytypefitness?language=objc)
The value that indicates positioning during dedicated fitness sessions, such as walking workouts, running workouts, cycling workouts, and so on.
Note that in the current car navigation mode position will be closer to Apple's road network data:
> [CLActivityTypeAutomotiveNavigation](https://developer.apple.com/documentation/corelocation/clactivitytype/clactivityt …
> [ios] Set correct location service activity type for cycling

- iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm
Use AVAudioSessionCategoryOptionInterruptSpokenAudioAndMixWithOthers to interrupt spoken content during TTS.
Apple recommends using this option for navigation apps:
> Set this option if your app’s audio is occasional and spoken, such as in a **turn-by-turn navigation app** or an exercise app. This avoids intelligibility problems when two spoken audio apps mix. If you set this option, also set the [AVAudioSessionCategoryOptionDuckOthers](doc://com.apple.documentation/documentation/avfaudio/avaudiosessioncategoryoptions/avaudiosessioncategoryoptionduckothers?language=objc) option unless you have a specific reason not to. Ducking other audio, rather than interrupting it, is appropriate when the other audio isn’t spoken audio.
[Source](https://developer.apple.com/documentation/avfaudio/avaudio …
> [ios] Interrupt podcasts instead of duck them during TTS

- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/map_tests/bookmarks_test.cpp
Key points:
1. `CreateCategories` is called to create the category from the parsed data. Now this method re-write the collection without duplication to the MarkGroupId if the fileName is the same. Generation the unique fileNames is responsibility of the `GenerateValidAndUniqueFilePathForKML`
2. `GetCategoryByFileName` returns the MarkGroupId associated with the categotry fileName (filename is actually the file path).
3. `ReloadBookmarkCategory` cleans up the old data from memory and reloads the collection.
4. The parameter `saveBookmarksIfNeeded` was added to the `NotifyChanges` because the reloaded file shouldn't be resaved to prevent the race condition (get new version from cloud -> parse -> re-save -> update cloud -> get from sync -> parse -> re-save...). All new files that were added …
> [bookmarks] Reuse the MarkGroupId during the category reloading

- android/app/src/main/java/app/organicmaps/editor/EditorFragment.java
- data/editor.config
All is in the title ^^.
Related to https://github.com/organicmaps/organicmaps/pull/8052#issuecomment-2118874974
> [editor] Limit more fields (website, menu, social medias, etc...) for some POI types

- android/app/src/main/java/app/organicmaps/routing/RoutingBottomMenuController.java
- android/app/src/main/java/app/organicmaps/widget/recycler/DotDividerItemDecoration.java
- android/app/src/main/java/app/organicmaps/widget/recycler/MultilineLayoutManager.java
Closes #7084
Changes made:
- In MultilineLayoutManager.java: if called with LAYOUT_DIRECTION_RTL tag, the layout is now properly written.
- In RoutinBottomMenuController.java: MultilineLayoutManager class is now called with the new parameter, the mTransitFrame's layout direction.
- In DotDividerItemDecoration.java: to properly place the dots between the elements in the list, these elements are iterated from right to left when the layout direction is RTL.
**Screenshots of changes**
| Before             |  After |
:-------------------------:|:-------------------------:
| Ruler mode             |  Transit mode |
:-------------------------:|:-------------------------:
> [android] Display list of stop points in ruler and transit mode properly in RTL

- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
> [ios] Hide the `Export all bookmarks and tracks` button when there are no bookmarks

- qt/place_page_dialog_user.cpp
1. Adds short description to place page dialog.
2. Adds word-wrap for all long fields.
3. Bug fix: removes duplicate Instagram.
4. Adds some layout stretching.
Points 2 and 4 are in preparation to move the page dialog to a panel to the left of the map :slightly_smiling_face: (which I'll do in a separate PR). This will hopefully make the place page less of a nuisance when one specific place is selected but you still want to explore the surroundings, giving a more intuitive experience that is also consistent with the mobile version (where you can select a place, and then drag the map around to  see the surroundings).
|-|-|
| ![image](https://github.com/organicmaps/organicmaps/assets/43684166/24f696d4-8ed5-420b-9afa-ec1ba4f597ce) | …
> Improve page dialog (user)

- iphone/Maps/Tests/Core/TextToSpeech/MWMTextToSpeechTests.mm
This pr fixes the error in some xcodes:
```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk/usr/include/c++/v1/__algorithm/find.h:25:18 
Invalid operands to binary expression ('std::pair<std::string, std::string>' and 'const std::pair<const char *, const char *>')
```
> [ios] fix compile error in the MWMTextToSpeechTest

- drape_frontend/gui/choose_position_mark.cpp
- drape_frontend/gui/compass.cpp
- drape_frontend/gui/compass.hpp
- drape_frontend/gui/copyright_label.cpp
- drape_frontend/gui/copyright_label.hpp
- drape_frontend/gui/gui_text.cpp
- drape_frontend/gui/gui_text.hpp
- drape_frontend/gui/layer_render.cpp
- drape_frontend/gui/layer_render.hpp
- drape_frontend/gui/ruler.cpp
- drape_frontend/gui/ruler.hpp
- drape_frontend/gui/shape.cpp
- drape_frontend/gui/shape.hpp
The removed size is not used in the code. The only case for a tappable GUI element is covered explicitly.
A small speed-up of the renderer never hurts.
> [drape][gui] Removed unused size

- drape/CMakeLists.txt
- drape/drape_tests/glyph_mng_tests.cpp
- drape/fonts_tool/CMakeLists.txt
- drape/fonts_tool/fonts_tool.cpp
- drape/glyph_manager.cpp
- drape/glyph_manager.hpp
- drape/harfbuzz_shaping.cpp
- drape/harfbuzz_shaping.hpp
- iphone/Maps/Maps.xcodeproj/xcshareddata/xcschemes/OMaps.xcscheme
- xcode/drape/drape.xcodeproj/project.pbxproj
A part of #4281 
- Added a font_tool to experiment and test runs algorithm
- Updated existing test to show/compare different lang strings rendered in different ways
Harfbuzz shaping requires splitting each string into segments (runs). Each run should have the same:
- font
- direction
- script
- language
The base idea of getting runs is based on the Chromium source code, with some changes and improvements.
There are many TODOs that can be handled later.
> [drape] Split text into segments needed for proper text shaping with Harfbuzz

- android/app/src/main/cpp/app/organicmaps/vulkan/android_vulkan_context_factory.cpp
- drape/vulkan/vulkan_base_context.cpp
- drape/vulkan/vulkan_gpu_buffer_impl.cpp
- drape/vulkan/vulkan_layers.cpp
- drape/vulkan/vulkan_layers.hpp
- drape/vulkan/vulkan_mesh_object_impl.cpp
- drape/vulkan/vulkan_texture.cpp
- drape/vulkan/vulkan_texture.hpp
- shaders/vulkan_program_params.cpp
Added extended validation (`VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT`) - https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkValidationFeatureEnableEXT.html
The following validation errors are fixed:
1.
```
OMcore                  app.organicmaps.debug                E  vulkan/vulkan_layers.cpp:162 DebugReportCallbackImpl(): Vulkan Diagnostics [ Validation ] [ COMMAND_BUFFER ] [OBJ: 12970367442591508160 LOC: 1611758864 ]: Validation Error: [ VUID-vkCmdBindDescriptorSets-pDescriptorSets-06715 ] Object 0: handle = 0xb400007815f566c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x4a581c0000000195, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 2: handle = 0xa7baa9000000011c, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x60117d10 | …
```
> Fix Vulkan Validation issues on Android

- iphone/Maps/Common/Common.swift
This PR adds logging using the default OSLogger for ios>14.0 during the release.
This PR does not affect the core logging.
> [ios] add default OSLog Logger for ios>14.0 to release

- android/app/src/main/res/values-de/strings.xml
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
- Added German translations for the new Cycle & Foot Paths category as well as for the new Hiking categories. 
- Changed translation for unmade paths to "Pfad"
- Kept the old "Weg" for `area:highway=path`
> [translations] German translation for hiking and cycle paths

- docs/INSTALL.md
Compiling on Nixos (Linux) and got
```
CMake Error at CMakeLists.txt:309 (message):
Could not find python3 to use in qt/, shaders/ and 3party/.
```
Worth specifying all dependencies -- if this isn't required for Windows or something we can say so of course.
> Python3 dependency

- .github/workflows/coverage-check.yaml
fix coverage check by switching to system-wide gcovr
was broken by https://github.com/organicmaps/organicmaps/pull/8193
due to [PEP 668 – Marking Python base environments as “externally managed”](https://peps.python.org/pep-0668/).
also install libfreetype-dev and libharfbuzz-dev, as it won't run without them
> Fix coverage check

- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
- iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
- iphone/Maps/UI/PlacePage/PlacePageInteractor.swift
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
Closes https://github.com/organicmaps/organicmaps/issues/8189
This PR fixes the issue when the bookmark/track data on the opened PP isn't updated during the editing from the `Bookmarks - select bm - Edit bookmark` - see #8189.
> [ios] Fix crash during the bookmark editing on ipad when the PP is open

- data/mapcss-mapping.csv
- data/types.txt
- routing_common/routing_common_tests/vehicle_model_test.cpp
- routing_common/vehicle_model.hpp
Following #8168
Also fixes wrong hardcoded ID for highway=busway.
> [classif] Move low use highway=road to a higher ID 

- CONTRIBUTORS
- android/app/src/main/cpp/app/organicmaps/editor/OsmOAuth.cpp
- android/app/src/main/java/app/organicmaps/editor/OsmOAuth.java
- android/app/src/main/java/app/organicmaps/editor/ProfileFragment.java
- android/app/src/main/res/drawable/profile_generic.xml
- android/app/src/main/res/layout/fragment_osm_profile.xml
Some work towards a better user profile page. 
Sadly i'm gonna be really busy for the next couple of months, so loading the profile image will have to wait (although it's somewhat working at [redauburn/organicmaps/android-user-profile](https://github.com/RedAuburn/organicmaps/tree/android-user-profile), albeit in the wrong place...)
i thought i may as well submit this stripped down version though, which has a new user info layout, displays the username, and formats the changeset count according to locale.
before/after:
generic profile image from https://svgsilh.com/image/378368.html (CC0)
> [android] better user profile (initial layout)

- docs/INSTALL.md
I often clone things first and read docs second rather than use Github's interface. This causes problems with submodules, especially shallow submodules. I finally found a workflow that's pretty ok and figured I'd share it here for other contributors.
> Elaborate on shallow submodule options

- data/countries_names.txt
I found these errors with Notepad++ search query `en = .*[^A-Za-z -—,\n]`
> [strings] Update regions translations

- .clang-format
- CMakeLists.txt
- cmake/OmimHelpers.cmake
- docs/CPP_STYLE.md
Seems to be all that's needed to upgrade. 
Using g++13 because it's the first version with support for std::format (and close to full support for c++20 generally afaik) https://stackoverflow.com/a/69156536
building android & desktop works
https://developer.apple.com/xcode/cpp/
> [core] update to c++20

- drape/vulkan/vulkan_layers.hpp
- drape/vulkan/vulkan_object_manager.cpp
- drape/vulkan/vulkan_object_manager.hpp
- drape/vulkan/vulkan_param_descriptor.hpp
- shaders/program_manager.cpp
- shaders/vulkan_program_params.cpp
- shaders/vulkan_program_params.hpp
- shaders/vulkan_program_pool.cpp
- shaders/vulkan_program_pool.hpp
Current implementation call `vkAllocateDescriptorSets` multiple times until it finishes successfully. It's not efficient and may cause validation issues.
Example:
```
OMcore                  app.organicmaps.debug                E  vulkan/vulkan_layers.cpp:162 DebugReportCallbackImpl(): Vulkan Diagnostics [ Validation ] [ DESCRIPTOR_POOL ] [OBJ: 18065711617638662146 LOC: 1434762579 ]: Validation Error: [ VUID-VkDescriptorSetAllocateInfo-apiVersion-07896 ] Object 0: handle = 0xfab64d0000000002, type = VK_OBJECT_TYPE_DESCRIPTOR_POOL; | MessageID = 0x5584bd53 | vkAllocateDescriptorSets():  Unable to allocate 1 descriptors of type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC from VkDescriptorPool 0xfab64d0000000002[]. This pool only has 0 descriptors of this type remaining. The Vulkan spec …
```
> [drape][Vulkan] Improve descriptor sets allocation

- drape/vulkan/vulkan_layers.cpp
- drape/vulkan/vulkan_layers.hpp
```
omim/drape/vulkan/vulkan_layers.hpp:43:47: error: cannot initialize a member subobject of type 'VkDebugReportCallbackEXT' (aka 'unsigned long long') with an rvalue of type 'std::nullptr_t'
VkDebugReportCallbackEXT m_reportCallback = nullptr;
^~~~~~~
```
CC @renderexpert
> [android] Fix Vulkan build error

- .github/workflows/android-check.yaml
Do not build many archs on one runner for faster feedback from Github.
> [github] Check arm32 Android builds too

- android/app/src/main/res/values-es/strings.xml
- android/app/src/main/res/values-it/strings.xml
- android/app/src/main/res/values-ru/strings.xml
- android/app/src/main/res/values/donottranslate.xml
- android/app/src/main/res/values/strings.xml
- data/strings/strings.txt
Fixes #2383
Any help with testing en, ru, es, it and some other language (with a fallback to en) is appreciated.
@organicmaps/translations-fr @organicmaps/translations-de is it possible to ask for help and translate the TTS FAQ also to German and French? You may also add localized screenshots if necessary, an example of other translations is here: https://github.com/organicmaps/organicmaps.github.io/tree/master/content/faq/text-to-speech-android-tts
It will appear here: https://organicmaps.app/faq/text-to-speech-android-tts/
> [android] Fix TTS FAQ link

- iphone/Maps/UI/Editor/MWMEditorViewController.mm
- iphone/Maps/UI/Editor/OpeningHours/MWMOpeningHoursEditorViewController.mm
- iphone/Maps/UI/Editor/Street/MWMStreetEditorViewController.mm
After #8147 I realized at least 2 pages where there in unnecessary capitalization in titles:
Probably not necessary to English strings, but to Romance languages it is a bit weird.
Anyway, I think this PR fixes these two cases, if you agree.
Also, if you search for `.capitalizedString` in the whole repository there's another case: [iphone/Maps/UI/Editor/MWMEditorViewController.mm](https://github.com/organicmaps/organicmaps/blob/bed3b121462036d946056d059fc1c4065e3dd91a/iphone/Maps/UI/Editor/MWMEditorViewController.mm#L202)
I didn't edit this case because I couldn't find where, but if you wish I can also remove there (or feel free to edit this PR).
> [iOS] Fixed titles capitalization

- generator/osm2type.cpp
- indexer/drawing_rule_def.hpp
```
warning: arithmetic between enumeration type 'feature::Layer' and floating-point type 'const double' is deprecated [-Wdeprecated-enum-float-conversion]
```
> [C++20] Fixed warning

- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/UI/PlacePage/Components/PlacePagePreviewViewController.swift
- iphone/Maps/UI/PlacePage/PlacePageBuilder.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
- iphone/Maps/UI/PlacePage/PlacePagePresenter.swift
- iphone/Maps/UI/PlacePage/PlacePageViewController.swift
The current PlacePage behavior when a user select/changes the poi is:
1. close the current opened PP screen with animation
2. open a new PP screen with animation
On every tap.
This may be quite distractive and jumpy:
___
This PR implements a small refactoring to `Reload` the PlacePage screen content rather than recreate it.
Benefits:
1. faster
2. less jumping animations
This behavior doesn't affect the iPad (and mac) because the PP on the iPad appears without animation.
Tested on:
Because the PlacePage legacy code is quite sensitive for the changes it would be great to make additional manual tests for this implementation for the different devices and ios versions.
___
https://github.com/organicmaps/organicmaps/assets/79797627/4596ca71-7897-4cbe-99cc-d164223ab412 …
> [ios] Reload the PP content instead of Recreate the entire screen

- iphone/Maps/UI/DocumentPicker/DocumentPicker.swift
This PR Fixes the #8410
The file should be imported as a copy because the files app will block access after dismissing.
> [ios] fix file import using the uidocumentpicker

- android/app/src/main/res/values-uk/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/uk.lproj/Localizable.strings
Found that Ukrainian string contains "КМЗ" instead of "KMZ". Probably machine translation artifact.
Fixed. Regenerated strings.
> [Strings] Ukrainan KMZ transliteration fix

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/java/app/organicmaps/Framework.java
- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/car/CarAppSession.java
- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.h
- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
- iphone/Maps/Bookmarks/BookmarksCoordinator.swift
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Core/Routing/MWMRouter.mm
- iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm
- iphone/Maps/UI/Search/MWMSearchManager.mm
- map/framework.cpp
- map/framework.hpp
- map/mwm_url.cpp
- qt/draw_widget.cpp
- search/search_quality/assessment_tool/main_view.cpp
Closes https://github.com/organicmaps/organicmaps/issues/8442
The old logic when the dismissing method should control not only the PP dismissing but also the fullscreen mode toggling contains too many responsibilities, and produces unexpected behavior (if the PP is opened and the user long taps on the map the PP will be dismissed but the side buttons not - ios, or deeplink handling hides the side buttons - ios), and hard to read and debug.
This PR continues https://github.com/organicmaps/organicmaps/pull/7876 and splits the `DeactivateMapSelection(bool notifyUI)` into the `DeactivateMapSelection()` and `SwitchFullScreen()`.
The additional callback `m_onSwitchFullScreen = std::move(onSwitchFullScreen);` was added.
Fullscreen mode switching is blocked when:
- navigation mode is active
- …
> [android] [ios] Split the deactivate PP and switch fullscreen mode logic

- generator/osm2type.cpp
> Recognise more surface types, treat fine_gravel as "formed" by default

- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/UI/PlacePage/PlacePageBuilder.swift
- iphone/Maps/UI/PlacePage/PlacePagePresenter.swift
- iphone/Maps/UI/PlacePage/PlacePageViewController.swift
- Long tap activates the Fullscreen mode and hides both the PP and the controls
- The second long tap deactivates the fullscreen mode and puts back the controls
- Controls are always visible on navigation, planning the route, searching modes
- If the fullscreen is enabled and the user opens the PP, the controls will be hidden
- If the fullscreen is enabled and the PP is opened, the longtap will exit the fullscreen without hiding the PP
https://github.com/organicmaps/organicmaps/assets/79797627/bf2fcf2f-698e-467b-8853-3e0ac9b6e08f
https://github.com/organicmaps/organicmaps/assets/79797627/75e99a24-5400-4726-bcd5-693e23b91afc
> [ios] Fix the fullscreen mode enter/exit behaviour

- iphone/Maps/Categories/UIColor+MapsMeColor.h
- iphone/Maps/Categories/UIColor+MapsMeColor.m
Usage of local `day` and `night` dictionaries were replaced with `StyleManager.shared.theme.colors` in
e85ac9d4dae886f24a5377467cef28444b4c80f1.
I don't see any other code that can use them, after removing them, project builds and works just fine.
> [ios] Remove unused code in UIColor+MapsMeColor

- indexer/map_object.cpp
- indexer/map_object.hpp
- map/place_page_info.cpp
Retrying to add all types to Place Page. Now it should be better than https://github.com/organicmaps/organicmaps/pull/8238, as it will only show types matched by existing checker `IsPoiChecker`. This should filter out useless stuff and internal things like psurface-*.
https://github.com/organicmaps/organicmaps/blob/32fa5823167212791b94a35bbfe0c682d99f2d64/indexer/ftypes_matcher.cpp#L461-L482
* Related to https://github.com/organicmaps/organicmaps/issues/3744
* Related to https://github.com/organicmaps/organicmaps/issues/4025#issuecomment-1807217279
* Related to https://github.com/organicmaps/organicmaps/issues/6882
* Fixes https://github.com/organicmaps/organicmaps/issues/8355
> [placepage] Show all types (filtering only POIs)

- android/app/src/main/res/values-pl/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/pl.lproj/Localizable.stringsdict
Fixes issue discovered in this comment: https://github.com/organicmaps/organicmaps/commit/0c3eb4f900957e615068c0d43bc2e46f451bc9a8#r143440343
A good example of how translations should work is here: https://localizely.com/language-plural-rules/
The main rule: `other` key should always be present to work. Our twine implementation doesn't handle it properly when `other` is missing. See 37a92fac952cc7f090ab708847a66598a2406b93 for details.
> [strings] Fix Polish translations

- docs/INSTALL.md
Update instructions for macOS. Git-lfs is required, which is not part of a standard git install
Also point to map generator readme files
> Update INSTALL.md for macOS

- indexer/ftypes_matcher.cpp
- indexer/ftypes_matcher.hpp
- indexer/indexer_tests/editable_map_object_test.cpp
- indexer/map_object.cpp
- indexer/map_object.hpp
- map/place_page_info.cpp
- map/place_page_info.hpp
Additional fixes after https://github.com/organicmaps/organicmaps/pull/8481. 
* Show level=1 types, allowing to show generic `shop`, but keep discarding generic `amenity`. Related to https://github.com/organicmaps/organicmaps/issues/8590. 
* Show secondary types in subtitle when the POI has no name and the main type is shown in the title. Fixes https://github.com/organicmaps/organicmaps/issues/8591
---
https://www.openstreetmap.org/way/63848074#map=19/43.18253/-0.60851
https://omaps.app/_n_dpiSdC0/Total
om://_n_dpiSdC0/Total
---
https://www.openstreetmap.org/way/809647468#map=18/42.81471/-1.59428
https://omaps.app/0n_T5cW_HC/Football
om://0n_T5cW_HC/Football
---
https://www.openstreetmap.org/node/9219269542#map=19/56.63970/47.92440
https://omaps.app/05gSBsr7Ks/Bus_Stop …
> Additional fixes for showing all POI types

- qt/CMakeLists.txt
We can see that the file is name 00_ and not 08_
https://github.com/organicmaps/organicmaps/blob/master/data/00_NotoSansMalayalam-Regular.ttf
> Update path to NotoSansMalayalam-Regular

- iphone/Maps/Tests/Core/iCloudTests/iCloudDirectoryMonitorTests/iCloudDirectoryMonitorTests.swift
This test case is totally useless and should be removed.
> [ios] Remove unnecessary icloud test case

- qt/mainwindow.cpp
Since Qt6 this specialization in QMenu is deprecated. We should use the function from QWidget.
Parameters are in a different order (text, shortcut, receiver, member).
https://doc.qt.io/qt-6/qmenu-obsolete.html
> QMenu::addAction is deprecated

- android/app/src/main/res/layout/dialog_edit_text.xml
- android/app/src/main/res/layout/edit_bookmark_common.xml
- android/app/src/main/res/layout/fragment_bookmark_category_settings.xml
- android/app/src/main/res/layout/fragment_edit_description.xml
- android/app/src/main/res/values/styles.xml
A user on Telegram has reported cursor in the bookmarks fields is different from the cursor on fields in the editor.
This PR uses editor styles in bookmarks to use the same cursor everywhere.
No visual difference except cursor in blue
It seems the size of the text is a little more big
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/36781370-31e8-4ee3-a40b-59c499def90e" height=500 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/eebbd8ae-6d33-416b-a2f7-861fc66a43cc" height=500 />|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/a762ad92-8f3e-41b3-9b01-904406152afb" height=500 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/27f9afb9-7341-4441-a4fd-16d9864478c7" height=500 />|
> [android] Use same cursor styles in bookmarks fields

- search/search_quality/assessment_tool/search_request_runner.cpp
Fixes the following warning:
````
search_request_runner.cpp:141:24: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
141 |   params.m_onResults = [=](search::Results const & results)
|                        ^
search_request_runner.cpp:141:24: note: add explicit ‘this’ or ‘*this’ capture
````
> [search] Fix warning about deprecated implicit capture of ‘this’

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/util/UiUtils.java
As @pastk asked in [comment](https://github.com/organicmaps/organicmaps/pull/8443#issuecomment-2185319015)
Changed android behaviour: in fullscreen mode opening a placepage doesn't exit fullscreen mode.
https://github.com/organicmaps/organicmaps/assets/720808/9ad2d727-ff52-42c8-89e2-0a04010a6b7c
Now OM exits fullscreen mode before starting navigation.
Also in route planning mode you can enter/exit fullscreen mode with a long tap.
> [Android] Placepage doesn't exit fullscreen mode

- packaging/app.organicmaps.desktop.metainfo.xml
Error emitted by the validation command (on the already compiled and built repo):
````
flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions repo repo'
````
in the `Validate build` step of the `flathub` builds.
> [packaging] Fix `metainfo-launchable-tag-wrong-value`

- packaging/app.organicmaps.desktop.metainfo.xml
Fixes the following warning:
````
"warnings": [
"appstream-screenshot-missing-caption"
],
"info": [
"appstream-screenshot-missing-caption: One or more screenshots are missing captions in the Metainfo file"
],
````
emitted by the validation command (on the already compiled and built repo).
See the occurence in:
https://buildbot.flathub.org/#/builders/26/builds/16574/steps/11/logs/stdio
Also the `Run appstreamcli in pedantic mode` step of the `validate-appstream` GH Action job reports the detailed line numbers:
````
P: app.organicmaps.desktop:99: screenshot-no-caption
P: app.organicmaps.desktop:102: screenshot-no-caption
P: app.organicmaps.desktop:105: screenshot-no-caption
P: app.organicmaps.desktop:108: screenshot-no-caption
````
> [packaging] Add screenshot captions to appstream metadata

- android/app/src/main/res/layout-land/map_buttons_bottom.xml
aligns lower buttons with the zoom & position buttons
New/old
(red blocks are same size)
> [android] align main screen buttons in landscape

- android/app/src/main/res/layout/edit_bookmark_common.xml
- android/app/src/main/res/layout/fragment_edit_bookmark.xml
Fixes #7720
This PR fixes:
- Scroll in InputEditText
- Increase height InputEditText to edit more easily
I have use same structure as fragment_bookmark_category_settings ->NestedScrollView + Linear Layout
- NestedScrollView take all space of screen to improve scroll in InputEditText (I have add margin at the bottom to improve access at the bottom of the InputEditText with keyboard)
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/ea0f5e8c-ec69-4d94-832b-9fef38477dd5" height=500 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/540b6681-c21f-40c7-bf3b-aa6a59f82a8c" height=500 />|
Before
https://github.com/organicmaps/organicmaps/assets/87148630/b40f3ba1-38e3-41ed-9881-808be49be07f
After …
> [android] Fix scroll in edit bookmark

- android/app/src/main/res/layout/fragment_osm_profile.xml
This PR:
- On osm_history item, I have removed textSize property and and applied MwmTextAppearance.Body2 (Style and size don't change, always 16 sp)
- On about_osm item, I have removed textSize property and applied MwmTextAppearance.Body3 (size of text has changed 12 to 14sp)
|Before|After|
|-|-|
|<img src="https://github.com/user-attachments/assets/59b0757d-8aab-48d4-a38b-daed507b68d4" height=300 />|<img src="https://github.com/user-attachments/assets/c861f8a4-5193-49fc-9043-fb5d9a48d464" height=300 />|
> [android] Increase size of OSM link on OSM profile

- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/Help/AboutController/AboutController.swift
- iphone/Maps/UI/Help/AboutController/Models/SocialMedia.swift
- iphone/Maps/UI/MailComposer/MailComposer.swift
- iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm
This PR refactors the mail composing:
- logic is moved to the MailComposer class
- MailComposer can: 
1. send the regular empty email to the provided recipient
2. send the bug report with the attached log file (it is encapsulated in the MailComposer because it is a single-purpose method and doesn't used anywhere else)
> [ios] Move the mail composing logic to the `MailComposer` class

- drape/glyph_manager.cpp
- drape/glyph_manager.hpp
- drape_frontend/text_layout.cpp
Fixes https://github.com/organicmaps/organicmaps/issues/8771 by disabling text splitting, as it was before Harfbuzz integration.
A better fix is implementing a proper splitting for RTL texts by mirroring the current algo.
> Disable incorrect text splitting into two lines for RTL

- generator/address_parser/CMakeLists.txt
- generator/address_parser/address_parser_tests/CMakeLists.txt
- generator/address_parser/address_parser_tests/parser_tests.cpp
target_link_libraries was executed even if the project was not created
> Move address_parser_tests to a subdirectory to fix building with SKIP_TESTS=ON

- search/query_saver.cpp
- search/query_saver.hpp
10 is too few. On modern phones, there's plenty of free space in the list. And there's also Clear search button (and enable/disable search history setting on Android).
> [search] Store 50 recent searches instead of 10

- map/framework.cpp
- map/framework.hpp
Closes #4141
When user taps on the map we do next steps:
1. Search for a bookmark at the tap position
2. Search for a POI at the tap position
3. Search for a building at the tap position.
4. Search for any feature at the tap position
I added additional bookmark search after POI is selected.
> Fixed selection of a POI with bookmark when bookmark is not selected

- drape_frontend/user_event_stream.cpp
- drape_frontend/user_event_stream.hpp
Removes the rotation snapping when nearing north-up
resolves https://github.com/organicmaps/organicmaps/issues/3065, resolves https://github.com/organicmaps/organicmaps/issues/2219
(also was mentioned in telegram a few times)
> [Core] Remove snap rotation

- iphone/CoreApi/CoreApi/Logger/Logger.mm
If the app crashes, the log message is missed because the file writing was dispatched to a separate utility queue.
The logs will be synchronously written to the log file (if enabled in the settings) in the current thread in these cases:
1. the app fails with the `CHECK` or `ASSERT` (on debug) which use the `Critical` level
2. the `Error` level log is triggered
It will help debug the crashes/error reasons between app reloadings.
This is how the log file will look after the crashed app relaunch:
```
D(1) 45.62401 drape_frontend/drape_engine.cpp:382 SetRenderingEnabled(): Rendering enabled
D(1) 47.00417 drape_frontend/drape_engine.cpp:390 SetRenderingDisabled(): Rendering disabled
C(1) 58.12411 map/bookmark_manager.cpp:2495 DeleteBmCategory(): CHECK(false) Test failure // <--- failure reason …
```
> [ios] Write the Error and Critical messages to the log file synchronously in the current thread

- iphone/Maps/Core/Location/MWMLocationManager.mm
Now the log messages will look like this:
```
I(1) 0.00000 Local time: 2024-08-05 08:16:17 +0000 , Time Zone: GMT+4
I(1) 2.76888 search/processor.cpp:210 SetPreferredLocale(): New preferred locale: en
D(1) 2.76919 search/processor.cpp:229 SetInputLocale(): New input locale: en locale code: \^A
W(2) 2.78217 search/geocoder.cpp:734 CacheWorldLocalities(): Can't find World map file.
I(1) 2.89736 storage/storage.cpp:956 RegisterLocalFile(): Found file: Georgia in directory: /var/mobile/Containers/Data/Application/1AAA36CA-4E01-4AF6-9306-B90D2F42A831/Documents/240528 with size: 82878068
I(1) 2.89743 storage/storage.cpp:956 RegisterLocalFile(): Found file: World in directory:  with size: 47893857
I(1) 2.89747 storage/storage.cpp:956 RegisterLocalFile(): Found file: WorldCoasts in directory: …
```
> [ios] Add more logs to the `Location manager`

- CMakeLists.txt
Declared the variable in them main CMakeLists.txt, which makes it not "manually-specified". It also documents it, which is a plus.
Follow up to @biodranik's [comment](https://github.com/organicmaps/organicmaps/pull/8710#issuecomment-2269600683) in #8710.
> [tools] Fix CMake warning regarding BUILD_STANDALONE

- tools/python/translate.py
Most of our translations are formal, let's keep it in sync.
> [tools] Use formal translations instead of informal for DeepL languages

- map/gps_track_storage.cpp
Without this fix, when the gps storage file size is 0, 1, 2 or 3 bytes, points are never stored in the storage after failing to initialize it.
To test: set the size of the gps_track.dat file to zero.
Fixes https://github.com/organicmaps/organicmaps/issues/8064
> Properly recreate the recent track storage file if it is corrupted/empty

- map/routing_mark.cpp
- platform/distance.cpp
- platform/localization.cpp
- platform/localization.hpp
- platform/measurement_utils.cpp
- platform/measurement_utils.hpp
- platform/platform_tests/distance_tests.cpp
Clean up and minor speed up of the locale-formatting code.
> Avoid unnecessary Locale copying in ToStringPrecisionLocale

- routing/route.cpp
- routing/routing_helpers.cpp
- routing/turns_notification_manager.cpp
Fixes #8822 
See below sample output. We have the GPS coordinate of each point in the route, the turn detail, and the road name info, which is most/all of the info needed to reconstruct direction/announcement decisions.
We also have the preexisting TTS/TTSn logging for what's actually spoken, and a new "TTS Distance" log entry that helps diagnose early/late announcements (it's a simple calculation based on a fixed number of seconds to begin the announcement and the current speed, with min/max bounds. See turns_notification_manager.cpp line 41, it's currently hardcoded to 8 seconds in both a vehicle and as a pedestrian, though obviously there's more to it than that, and more than one announcement per turn.)
<pre>
routing/index_router.cpp:714 CalculateSubroute(): Routing in mode: Joints …
> Increase logging for direction calculation and TTS

- iphone/Maps/Core/Location/MWMLocationManager.mm
The app is configured to update the GPS location in the background but this information is not passed to the framework. 
With this commit the GPS location is passed to the framework even when the app is in background. This results in a higher battery usage if there is an active route but the battery usage will remain the same if no route is active because the GPS location is not updated.
Close #6940
> [ios] Allow location update when app is in background

- android/app/src/main/cpp/app/organicmaps/editor/Editor.cpp
- android/app/src/main/java/app/organicmaps/editor/Editor.java
- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.h
- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageButtonsData.h
- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageButtonsData.mm
- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
- iphone/Maps/UI/BottomMenu/Menu/BottomMenuPresenter.swift
- iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuItemCell.swift
- iphone/Maps/UI/PlacePage/Components/PlacePageButtonsViewController.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
- map/framework.cpp
- map/framework.hpp
- map/place_page_info.cpp
- map/place_page_info.hpp
- platform/mwm_version.cpp
- platform/mwm_version.hpp
- storage/storage.cpp
- storage/storage.hpp
The `Add Place to OSM` can be selected even in disabled (text is gray) mode in ios.
1. The `Add/Edit place` on the PP should be disabled when the map is not downloaded OR outdated (>3mo)
2. The `Add place` on the Menu should be disabled when the map is not downloaded OR outdated (>3mo)
3. If the user open the `Add place` from the `Menu` and moves the map an additional check should happens to prevent editing of the outdated map
4. The `Add/Edit place` on the PP should be visible even if disabled (as a next step it will be possible to change the title to the "Update/Download [name of the region]" and navigate the user to the downloading page from this button).
1. The logic to check if the map/poi is editable is moved from the `mwm_info` to the `storage` and based on the file's `state` and …
> [ios] [android] Refactor the visibility and enabling states of the Add/Edit Place buttons on the PP and Menu

- platform/platform_unix_impl.cpp
There are several bug reports that iOS wrongly says that there is no free space available (e.g. https://github.com/organicmaps/organicmaps/issues/2969 ). As we can get iOS logs now, we can try to debug such cases.
> Enabled logs for free disk space checks when downloading/updating countries

- android/app/src/main/res/values-be/strings.xml
- android/app/src/main/res/values-cs/strings.xml
- android/app/src/main/res/values-pl/strings.xml
- android/app/src/main/res/values-ru/strings.xml
- android/app/src/main/res/values-sk/strings.xml
- android/app/src/main/res/values-uk/strings.xml
- iphone/Maps/LocalizedStrings/be.lproj/Localizable.stringsdict
- iphone/Maps/LocalizedStrings/cs.lproj/Localizable.stringsdict
- iphone/Maps/LocalizedStrings/pl.lproj/Localizable.stringsdict
- iphone/Maps/LocalizedStrings/ru.lproj/Localizable.stringsdict
- iphone/Maps/LocalizedStrings/sk.lproj/Localizable.stringsdict
- iphone/Maps/LocalizedStrings/uk.lproj/Localizable.stringsdict
This depends on https://github.com/organicmaps/twine/pull/9
This reorders plural forms from alphabetic order into CLDR order
> [strings] Sort plural forms in CLDR order

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/java/app/organicmaps/routing/RoutingInfo.java
- android/app/src/main/java/app/organicmaps/widget/menu/NavMenu.java
Changed navigation UI to show speed and speed limit with `'/'` separator (as in iOS).
How to check it on emulator?
**Expected result:** speed limit should be displayed in navigation mode:
I used GPX track [Florida. Busch Gardens - Pollo Tropical.gpx](https://gist.github.com/strump/d4b8cadde7324e4cba5dc802b9d9cb99) to emulate city ride.
> [Android] Speed limit in navigation mode

- android/app/src/main/java/app/organicmaps/SplashActivity.java
- android/app/src/main/java/app/organicmaps/intent/Factory.java
Fixes #8984
See c90c6bb "Fix SecurityException ..." (#7287)
See b2a6dd2 "Fix the crosshair (PICK_POINT) API" (#8910)
> [android] Fix "FORWARD_RESULT_FLAG used while also requesting a result"

- ge0/ge0_tests/geo_url_tests.cpp
- ge0/geo_url_parser.cpp
If we fail trying to parse the coordinates of geo-URI, URL decode the coordinates and try again. Strictly speaking this is against the RFC but seems pretty safe given how limited the valid set is for coordinates in the RFC.
fixes: #8816
> Try decoding geo URL coordinates before giving up on parsing

- android/app/src/main/java/app/organicmaps/settings/VoiceInstructionsSettingsFragment.java
PR that hides the Preferences in Voice Settings panel when the TTS is disabled/not available.
Previous possible implementations are:
* https://github.com/organicmaps/organicmaps/pull/7759: Disables (greys) preferences using general XML styles. It does not behave correctly when switching to Night mode, as the color of the tiles remain incorrectly dark.
* https://github.com/organicmaps/organicmaps/pull/9007: Disables (greys) preferences using custom Preference classes to get access to internal TextView control of the preferences.
> [android] Hide preferences in voice settings when disabled

- iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm
The audio session is once configured during initialization and then each time a audio session is set active. This commit configures the audio session only once when the app is started. In addition, it sets AVAudioSessionModeVoicePrompt, which is recommended for apps that use text-to-speech.
Close #8988
> [ios] Configure audio session once with AVAudioSessionModeVoicePrompt

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/cpp/app/organicmaps/editor/OsmOAuth.cpp
- android/app/src/main/java/app/organicmaps/Framework.java
- android/app/src/main/java/app/organicmaps/api/RequestType.java
- android/app/src/main/java/app/organicmaps/editor/OsmLoginActivity.java
- android/app/src/main/java/app/organicmaps/editor/OsmLoginFragment.java
- android/app/src/main/java/app/organicmaps/editor/OsmOAuth.java
- android/app/src/main/java/app/organicmaps/editor/ProfileActivity.java
- android/app/src/main/java/app/organicmaps/editor/ProfileFragment.java
- android/app/src/main/java/app/organicmaps/intent/Factory.java
- android/app/src/main/res/layout/fragment_osm_login.xml
- editor/osm_auth.cpp
- editor/osm_auth.hpp
- iphone/CoreApi/CoreApi/DeepLink/DeepLinkParser.h
- iphone/CoreApi/CoreApi/DeepLink/DeepLinkParser.mm
- iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
- map/framework.cpp
- map/framework.hpp
- map/map_tests/mwm_url_tests.cpp
- map/mwm_url.cpp
- map/mwm_url.hpp
**N.B.** New login flow is enabled only for "google" builds! F-Droid and Web builds should work as previously.
How OAuth2 flow should work (happy path):
* `OsmLoginFragment` - User pushes "Login to OpenStreetMap" button
* `OsmLoginFragment` - triggers browser
* `Browser` - OSM.org login flow
* `Browser` - redirects to `om://oauth2/osm/callback?code=XXX`
* `MwmActivity` - handles `om://` URI and extracts code value
* `MwmActivity` - calls OsmLoginActivity with code in extras
* `OsmLoginFragment` - calls native code to get OAuth2 token using code
* `OsmLoginFragment` - calls native code to get username using OAuth2 token
* `OsmLoginFragment` - redirects to `ProfileActivity`
https://github.com/user-attachments/assets/94f51fca-4fac-45b8-94ae-7495731ed93e
This PR does the same as #8825 but …
> [Android] OAuth2 flow with browser V2

- iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm
- iphone/Maps/UI/Help/AboutController/AboutController.swift
- iphone/Maps/UI/MailComposer/MailComposer.swift
This change should help to understand which logs came from iCloud code.
> [ios] Distinguish bug reports from iCloud by their email subject

- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
Fix the commit 90ee2af3f6eb83e433e494fe24f412603aeec987 that breaks the cell localized string
before/after:
> [ios] fix Recent Path cell title localized string

- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
All is in the title ^^.
Close #9100
https://github.com/user-attachments/assets/bb28efbf-dff9-4972-95b0-d572ec67cb88
> [android] Fix "If you select a node that has outdoor seating and then select something else it will incorrectly say it also has outdoor seating"

- android/app/src/main/cpp/app/organicmaps/LocationState.cpp
- drape_frontend/my_position_controller.cpp
- iphone/Maps/Core/Location/location_util.h
- map/bookmark_manager.cpp
- map/extrapolation/extrapolator.cpp
- map/framework.cpp
- map/framework.hpp
- map/gps_track.cpp
- map/gps_track.hpp
- map/gps_track_collection.hpp
- map/gps_track_filter.cpp
- map/gps_track_filter.hpp
- map/gps_track_storage.cpp
- map/gps_tracker.hpp
- map/map_tests/extrapolator_tests.cpp
- map/map_tests/gps_track_collection_test.cpp
- map/map_tests/gps_track_storage_test.cpp
- map/map_tests/gps_track_test.cpp
- platform/apple_location_service.mm
- platform/location.hpp
- platform/qt_location_service.cpp
- routing/routing_integration_tests/speed_camera_notifications_tests.cpp
- routing/routing_session.cpp
- routing/routing_tests/routing_session_test.cpp
- routing/speed_camera_manager.cpp
This struct was introduced to save a bit of memory compared to GpsInfo. Now, when we are recording and saving tracks, there is no need in the incomplete struct, or in duplicating the same fields that are already present in GpsInfo.
Related to https://github.com/organicmaps/organicmaps/pull/9107
CC @rtsisyk
> Get rid of GpsTrackInfo

- kml/serdes.cpp
To store tracks with timestamps and other data, we need to support `gx:Track` tag.
Details are here: https://developers.google.com/kml/documentation/kmlreference#kml-extension-namespace-and-the-gx-prefix
> Declare kml 2.2 gx extension support to serialize recorded tracks

- android/app/src/main/java/app/organicmaps/util/log/ZipLogsTask.java
Problem: Currently, the exported file has the following structure:
* logs.zip/logs/app.log
* logs.zip/logs/logcat.log
The logs/ folder is unnecessary. This issue is tracked here: https://github.com/organicmaps/organicmaps/issues/6219
Solution: Now, the zip archive will contain only the files and folders inside the /logs/ directory, but not the directory itself.
> Android: Exclude parent logs/ directory from exported zip archive

- android/app/src/main/java/app/organicmaps/bookmarks/BookmarkListAdapter.java
Now, whenever the UI state changes, the number of lines in the description is checked, and the visibility of the "More" button is determined based on that.
Fixes https://github.com/organicmaps/organicmaps/issues/5502
> The "More" button no longer appears when the category description is short

- android/app/src/main/java/app/organicmaps/bookmarks/Holders.java
The problem was due to excessive optimization when calculating the value for description, even though the entire page display logic relies on a complete, unconditional redraw.
Fixes https://github.com/organicmaps/organicmaps/issues/4826
> Apply new category description immediately after editing

- android/app/src/main/res/layout/fragment_bookmark_category_settings.xml
To fix this, I simply disabled the animation, which lags on low-end devices. I felt this was the best solution because such animation in the bottom sheet looks "messy", with noticeable jumps even on flagship phones.
https://github.com/user-attachments/assets/ebf865ec-b199-4dc7-9dcf-929c95f81494
> Fixed overlapping text when opening the category editing page

- android/app/src/main/java/app/organicmaps/bookmarks/BookmarkListAdapter.java
- android/app/src/main/java/app/organicmaps/bookmarks/Holders.java
My fix ensures that the category's metadata (including the title) is always displayed, regardless of the presence of a description. Additionally, if the description is empty, the view is not shown at all to avoid taking up space.
https://github.com/user-attachments/assets/8a5a9292-3dcc-4ff0-9154-1ae3ca0b0d2a
> The absence of a category description no longer results in a blank description page

- routing/router.cpp
Removed support of "helicopter" route type. Backward compatibility is not needed anymore.
> Helicopter leftovers cleanup

- drape_frontend/frontend_renderer.cpp
- geometry/bounding_box.hpp
`-ffast-math` does not support infinity values, and recent gcc properly warns about it:
```
/home/runner/work/organicmaps/organicmaps/geometry/bounding_box.hpp:53:47: warning: use of infinity is undefined behavior due to the currently enabled floating-point options [-Wnan-infinity-disabled]
53 |   static double constexpr kPositiveInfinity = std::numeric_limits<double>::infinity();
|                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
> Fix the use of infinity

- ge0/ge0_tests/geo_url_tests.cpp
- ge0/geo_url_parser.cpp
This issue was reported by one of our users, the software producing such wrong URIs is called `Wiki Camps Australia Version 5.8.5a`:
```
08-24 14:17:08.462 W/OMcore  (18806): ge0/geo_url_parser.cpp:208 Parse(): Missing coordinates in geo:-32.899583,139.043969&z=12
08-24 14:17:08.462 W/BookmarkManager(18806): Importing bookmarks from geo:-32.899583,139.043969&z=12
08-24 14:17:08.462 W/BookmarkManager(18806): Could not find a supported file type in geo:-32.899583,139.043969&z=12
```
> [api] Fixed wrong geo url parsing with &z= in the host name instead of ?z=

- qt/qt_common/helpers.hpp
- qt/qt_common/map_widget.cpp
- qt/qt_common/map_widget.hpp
I have created this PR that simply adds key bindings to the keyboard arrows. That way it is easy to navigate the map using only the keyboard.
Following the existing bindings for zoom +/- there are also bindings with the <Alt> modifier that produce a smaller change. For instance <Alt>+Left shifts the image by half of what Left arrow would do.
> Support navigation with the keyboard arrows

- tools/unix/build_omim.sh
This PR simply fixes a problem with option `-p`  of tools/unix/build_omim.sh.
If one uses the following command:
```
./tools/unix/build_omim.sh -p build -r desktop
```
an errors is shown. This PR fixes that.
> Add missing getopts option

- iphone/Maps/Core/Location/MWMLocationManager.mm
As [documentation says](https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate/locationmanagerdidresumelocationupdates(_:)?language=objc):
> Core Location does not resume updates automatically after it pauses them.
We can [disable the pausing](https://developer.apple.com/documentation/corelocation/cllocationmanager/pauseslocationupdatesautomatically?language=objc) when the track recording or the navigation mode is enabled.
> After a pause occurs, it’s your responsibility to restart location services again when you determine that they’re needed.
> [ios] Prevent location updates from pausing in the background during navigation or track recording.

- base/base_tests/timer_test.cpp
- base/timer.cpp
Fixes https://github.com/organicmaps/organicmaps/issues/9127
Note that fractional seconds are ignored/dropped, because POSIX time_t works only with integer seconds.
> Fixed parsing fractional seconds from ISO 8601 string timestamps

- data/gpx_test_data/track_with_timestamps.gpx
- data/gpx_test_data/track_with_timestamps_broken.gpx
- data/gpx_test_data/track_without_timestamps.gpx
- data/kml_test_data/generated.kml
- data/kml_test_data/generated_mixed_tracks.kml
- data/kml_test_data/track_with_timestamps_mismatch.kml
- data/kml_test_data/track_with_timestams_different_orders.kml
- kml/kml_tests/gpx_tests.cpp
- kml/kml_tests/serdes_tests.cpp
- kml/serdes.cpp
- kml/serdes_common.cpp
- kml/serdes_common.hpp
- kml/serdes_gpx.cpp
- kml/serdes_gpx.hpp
- kml/types.cpp
- kml/types.hpp
- map/bookmark_helpers.cpp
- map/map_tests/bookmarks_test.cpp
This PR:
1. Adds timestamps to the `MultiGeometry`
2. Implement the KML deserealization for the tracks with the timestamps that uses [`gx:Track`/`gx:MultiTrack` format ](https://developers.google.com/kml/documentation/kmlreference#gx:track)
3. Implement the KML serealization for the tracks with the timestamps to the `gx:Track` format:  
- The tracks **without** timestamps will be saved using the `<LineString>` tag (and grouped with the `<MultilineGeometry>` if there are several tracks).
- The tracks **with** the timestamps will be saved using the `gx:Track` (and grouped with the `<gx:MultiTrack>` if there are several tracks)
@cyber-toad can you please review the changes?
> [kml] Implement support for KML tracks with timestamps

- map/bookmark_manager.cpp
- map/gps_track.cpp
- map/gps_track.hpp
- map/gps_tracker.cpp
- map/gps_tracker.hpp
This PR implements writing the `timestamps` and `altitudes` during the track recording.
It continues the https://github.com/organicmaps/organicmaps/pull/9140
> Save `TrackRecording`'s timestamps and altitudes

- map/bookmark_helpers.cpp
Makes logs clearer, with correct paths instead of temporary ones.
> Print original path to the saved file instead of a path to the temporary kml

- iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarViewController.xib
Without this fix, tapping on a red dot does nothing instead of opening the menu
Fixes https://github.com/organicmaps/organicmaps/issues/9229
> [ios] Red dots on menu and help button now properly pass taps to the underlying buttons

- android/app/src/main/res/values-fr/strings.xml
- android/app/src/main/res/values-nl/strings.xml
- android/app/src/main/res/values-zh-rTW/strings.xml
- android/app/src/main/res/values-zh/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/fr.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/zh-Hans.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/zh-Hant.lproj/Localizable.strings
URL encoding with % doesn't work and links were not clickable. I removed the encoding from the strings to fix the issue.
(See: https://github.com/organicmaps/organicmaps/pull/6173#issuecomment-2351060721)
> Removed % URL encoding from inline links

- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
Originally was hard-coded to use only the light accent colour, now queries the theme.
before above, after below:
> [Android] fix colour of disable-able buttons

- iphone/Maps/OMaps.plist
- iphone/Maps/UI/PlacePage/Components/OpenInAppActionSheet/OpenInApplication.swift
This PR adds the [Go Map!!](https://github.com/bryceco/GoMap) editor to the Open in Another App button.
This is working fine using the web link scheme. However, then the button appears even if Go Map!! is not installed.
`https://gomaposm.com/edit?center=47.679056,-122.212559&zoom=21`
I have tried using the app scheme, but it doesn't seem to detect that the app is installed and the button doesn't show up. 
`gomaposm://edit?center=47.679056,-122.212559&zoom=21`
@bryceco Any idea why the `gomaposm://` scheme doesn't work?
* Fixes https://github.com/organicmaps/organicmaps/issues/9104
> [ios][placepage] Add Go Map!! to Open in Another App

- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
Closes #9352 
The bug was caused by the 747b3553fb06bf4ff46165e8804a9eb119910080
The VieweControllers should be pushed from the `MapViewController`'s navigation controller.
The `topViewController` property shouldn't be used to push/pop on the main screens stack.
https://github.com/user-attachments/assets/3d38f22b-dae7-4b30-89f5-a86c566d50be
> [ios] Fix Recently Deleted screen opening bug

- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
* Fixes #9205 
Description:
- New row was being inserted at the end of the section, Should be on the top
- `getCategories()` function sorts the categories to update the table data source
| https://github.com/user-attachments/assets/5454116e-ffbe-47dc-a808-7dd009fc7375 | https://github.com/user-attachments/assets/9a01b65d-22a9-4e64-930a-60d7795692a9 |
> [ios] Fix: New bookmark list placement

- android/app/src/main/AndroidManifest.xml
After @RedAuburn  PR https://github.com/organicmaps/organicmaps/pull/9332 was merged new issue appeared on Android 10+.
When user tries to login using OAuth2 (only for Google flavored builds) he sees error "Web browser is not available".
**Fix:** allow browser intent explicitly for Android 10+ in AndroidManifest. See details https://stackoverflow.com/a/70988018
This issue is simmilar to https://github.com/organicmaps/organicmaps/pull/9263. We should test PRs on a wider range of Android versions.
> [Android] Fix browser triggering in Android 14

- map/framework.cpp
fixes #2835 
Update POI info in the place page after editing an object. This PR first deselects the object and then re selects it in the same way it is done for created features.
> Update POI info in place page after editing

- android/app/src/main/java/app/organicmaps/editor/EditorHostFragment.java
fixes #5727
When showing the login page after an edit users now get send back to the map after pressing back or logging in. Previously users were send back to the category list (see #5727).
> return to map after edit->login

- data/categories.txt
- indexer/ftypes_matcher.cpp
`amenity-arts_centre` was missing from `categories.txt`. Added translations from `types_strings.txt`
> [categories] Add missing amenity-arts_centre

- routing/ruler_router.cpp
Fix index pointing out of array bound. For some reason it worked for Android but reading some garbage. On iOS simulator it crashes ruller router.
> Ruler router fix

- indexer/ftypes_matcher.cpp
Same as `amenity=parking` and `amenity=fuel`, we should also show operator for `amenity=motorcycle_parking`, `amenity=bicycle_parking`, and `amenity=charging_station`
> [core] Add "motorcycle_parking", "bicycle_parking", "charging_station", to IsOperatorOthersPoiChecker

- android/app/src/main/java/app/organicmaps/downloader/BottomPanel.java
- android/app/src/main/java/app/organicmaps/downloader/DownloaderFragment.java
- android/app/src/main/java/app/organicmaps/downloader/DownloaderInsetsListener.java
- android/app/src/main/java/app/organicmaps/help/CopyrightFragment.java
- android/app/src/main/java/app/organicmaps/help/FaqFragment.java
- android/app/src/main/java/app/organicmaps/help/HelpFragment.java
Aims to fix #9423 by requesting insets when the state of buttons changes.
Found another issue with RecyclerView: since basic insets handling is spread across multiple classes, the RecyclerView handles incoming insets as well. This results in additional spacing when scrolled to the end.  
Decided to move all insets-related logic for the Downloader screen into a separate class, which consumes all insets.
> [Android] Rewrite insets handling logic for Downloader screen

- data/test_data/osm/cycle_barrier.osm
- generator/generator_tests/road_access_test.cpp
- generator/road_access_generator.cpp
fixes #3920, fixes #9233
Block barrier=cycle_barrier only for bicycle=no case
I added unit tests, could anyone help me with testing please - as I understand it is required to build maps with new generator code?
> [routing] Allow to pass cycle-barrier if bicycle=no is not specified

- iphone/Maps/main.mm
- platform/platform_ios.mm
before:
`I(1) 0.03557 Maps/main.mm:10 main: Organic Maps 2022.11.17-0-ios started, detected CPU cores: 10`
after
`I(1) 0.02030 Maps/main.mm:10 main: Organic Maps (Debug) app.organicmaps.debug 2022.11.17-0-ios started, detected CPU cores: 10`
> [ios] Log app name and bundle id on the app start

- drape_frontend/gps_track_renderer.cpp
- geometry/spline.cpp
- geometry/spline.hpp
Closes https://github.com/organicmaps/organicmaps/issues/9488
This PR contains 3 small fixes to increase the track drawing performance:
1. during the iteration the track length for the current point is calculated and stored in the property
2. `GetFullLength` is moved out of iteration scope because it is not changed
3. skip drawing iteration when there is nothing changed during the `UpdatePoints` call
Profiling results:
[track_recording_rendering.trace.zip](https://github.com/user-attachments/files/17330000/track_recording_rendering.trace.zip)
> [drape] Fix track rendering performance issues

- iphone/Maps/Categories/UIButton+ImagePadding.swift
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMRoutePreview.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMiPadRoutePreview.xib
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMiPhoneRoutePreview.xib
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/BaseRoutePreviewStatus.swift
- iphone/Maps/Images.xcassets/Search/Cells/ic_search_mode_list.imageset/Contents.json
- iphone/Maps/Images.xcassets/ic_24px_manager.imageset/Contents.json
- iphone/Maps/Maps.xcodeproj/project.pbxproj
Fixes #7976 for buttons when an RTL script is used
Before | After
------ | -----
> [ios] Fix image padding for buttons in right-to-left layout

- android/app/src/main/java/app/organicmaps/editor/EditorHostFragment.java
- android/app/src/main/java/app/organicmaps/editor/FeatureCategoryActivity.java
fixes  #9444
Now users are correctly prompted to login after editing. The problem was that navigateToParent() closed the login Activity directly after starting it.
Tested on Android 14 and 10.
> Prompt users for OSM login fix

- map/gps_track.cpp
- map/gps_track.hpp
- map/gps_track_collection.cpp
- map/gps_track_collection.hpp
- map/gps_track_storage.cpp
- map/gps_track_storage.hpp
- map/gps_tracker.cpp
- map/gps_tracker.hpp
- map/map_tests/gps_track_collection_test.cpp
- map/map_tests/gps_track_storage_test.cpp
- map/map_tests/gps_track_test.cpp
Related to the https://github.com/organicmaps/organicmaps/issues/8927
Because of the `RecentPath` feature (when the user can limit the recording duration) was fully replaced with the `TrackRecording` the file's tail shouldn't be truncated. As a user can record a track for more than 24h we shouldn't limit the file size and lose the user-generated data.
This is why the `Duration`, `TruncFile`, and `m_maxItemCount`- related code were removed.
The better idea is to notify the user using the blinking button + alert every 24h (as an example) that the track is still recorded.
> [map] Remove Duration and File Rotation from the track recording

- indexer/feature_meta.cpp
link goes from: https://commons.wikimedia.org/wiki/File:Cute_dog_(4985400144).jpg
to: https://commons.m.wikimedia.org/wiki/File:Cute_dog_(4985400144).jpg#/media/File:Cute_dog_(4985400144).jpg
the viewer is a bit nicer UX-wise
> [Core] link to the Commons media viewer for single files

- android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkManager.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/Icon.java
The annotation was half-deleted in https://github.com/organicmaps/organicmaps/pull/9523#discussion_r1802660683. Cleanup redundant leftovers.
> [android] Cleanup unused annotation

- android/app/src/main/java/app/organicmaps/bookmarks/BookmarkListAdapter.java
- android/app/src/main/java/app/organicmaps/bookmarks/data/CategoryDataSource.java
- android/app/src/main/java/app/organicmaps/content/DataSource.java
The issue was caused by calling RecyclerView.AdapterDataObserver.onChanged() at an unexpected time.
I decided not to modify the onChanged() method because it works with a cached version of the native object. To prevent the developer from having to think about when to invalidate the DataSource, I integrated it into the already existing onDelete.
This PR is an alternative to: https://github.com/organicmaps/organicmaps/pull/9189.
> After deleting the last track in a category, the category itself is now deleted

- indexer/ftypes_matcher.cpp
- indexer/ftypes_matcher.hpp
- search/intermediate_result.cpp
- search/intermediate_result.hpp
- search/ranker.cpp
This PR modifies how the search results are shown:
* Use brand as name if name is empty
* Don't use address as name if name is empty, unless the POI is simply an address
Related issues:
* Fixes https://github.com/organicmaps/organicmaps/issues/8875
* Fixes https://github.com/organicmaps/organicmaps/issues/6882
---
> [search] Use brand as name and don't use address as name

- search/query_params.cpp
- search/ranking_info.cpp
- search/search_quality/search_quality_tests/real_mwm_tests.cpp
- "ntra, sra, sta" synonyms
- "Parque Ciudad" ranking. Fancy ranking because separate "parque" and "ciudad" tokens match suburbs and cities.
> [search] Fixed ranking, added some ES synonyms.

- data/editor.config
editor.config fine tuning:
- `place=farm` not addable because it's ambiguous with `landuse=farmyard`
- `shop=auction` not addable because it's an undocumented category with only 135 usages
- `shop=pastry` addable, I don't see any conflict with bakery
> editor.config fine tuning

- data/test_data/gpx/color.gpx
- data/test_data/gpx/export_test.gpx
- kml/kml_tests/gpx_tests.cpp
- kml/serdes_gpx.cpp
@cyber-toad 
From user's gpx:
```
<trk>
<name>Tag 5 (2)</name>
<trkseg>
<trkpt lat="50.6967272" lon="-2.7154925">
<ele>80.81</ele>
<time>2015-08-19T11:13:31Z</time>
<name>Start: 12:13:31</name>
<extensions><gpxtpx:TrackPointExtension><gpxtpx:speed>14.74</gpxtpx:speed></gpxtpx:TrackPointExtension></extensions>
</trkpt>
</trkseg>
<trkseg>
<trkpt lat="50.7008367" lon="-2.7273928">
<ele>38.11</ele>
<time>2015-08-19T11:14:37Z</time>
<name>Start: 12:14:37</name>
<extensions><gpxtpx:TrackPointExtension><gpxtpx:speed>11.24</gpxtpx:speed></gpxtpx:TrackPointExtension></extensions>
</trkpt>
<trkpt lat="50.7009689" lon="-2.7274845">
<ele>29.10</ele>
<time>2015-08-19T11:14:38Z</time>
<extensions><gpxtpx:TrackPointExtension><gpxtpx:speed>9.83</gpxtpx:speed></gpxtpx:TrackPointExtension></extensions> …
```
> [gpx] Skip incomplete segments.

- iphone/Maps/Core/iCloud/CloudDirectoryMonitor.swift
- iphone/Maps/Core/iCloud/LocalDirectoryMonitor.swift
- iphone/Maps/Core/iCloud/MetadataItem.swift
- iphone/Maps/Core/iCloud/SynchronizaionManager.swift
- iphone/Maps/Core/iCloud/SynchronizationStateResolver.swift
Content logging is moved closer to the source - to the monitor's didFinishGathering/didUpdate methods instead of state resolver.
> [ios] improve icloud sync logging

- base/base_tests/bits_test.cpp
- base/bits.hpp
- coding/compressed_bit_vector.cpp
Also removed buggy PopCount for arrays (it fails starting from n = 32 bits)
It's a polished/fixed version of @meenbeese 's #9088 , thanks for the inspiration!
Closes #9607
Closes #9088
> Use faster std::popcount

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/cpp/app/organicmaps/Framework.hpp
- android/app/src/main/cpp/app/organicmaps/Map.cpp
- android/app/src/main/cpp/app/organicmaps/vulkan/android_vulkan_context_factory.cpp
- android/app/src/main/cpp/app/organicmaps/vulkan/android_vulkan_context_factory.hpp
- android/app/src/main/java/app/organicmaps/Map.java
- android/app/src/main/java/app/organicmaps/util/ROMUtils.java
- android/app/src/main/java/app/organicmaps/util/log/LogsManager.java
- drape/graphics_context_factory.hpp
- drape/support_manager.cpp
- drape/support_manager.hpp
Follow up https://github.com/organicmaps/organicmaps/pull/9309
- Keep Vulkan renderer for SM-G930F (S7) with the stock Android.
- Ban Vulkan for old Androids (Mali-T*) like S7, S6 and lower with custom Androids (Lineage, Cyanogen).
"Custom ROM" means something not in stock for the device (was rooted and installed something else). ROMUtils.isCustomROM code is heuristic and was inspired by ChatGPT.
> [android] Ban Vulkan for Mali-T* devices with a custom ROM.

- .gitmodules
- qt/CMakeLists.txt
This fix was only intended to be deployed until Qt 5.10.
> [tools] Delete redundant macdeployqtfix submodule

- qt/preferences_dialog.cpp
Removes:
* Alternative name
* Old/Previous name
As pointed out in https://github.com/organicmaps/organicmaps/pull/9618#issuecomment-2469252648
> [qt] Exclude service languages from map language menu

- android/app/build.gradle
- android/app/src/main/java/app/organicmaps/util/SharedPropertiesUtils.java
@rtsisyk Take a look. I don't understand why we need gradle java toolchain entry, but it doesn't work now on MacOS.
```
vng@Viktars-MacBook-Pro android % gradle --version
Welcome to Gradle 8.11!
Here are the highlights of this release:
- Parallel load and store for Configuration Cache
- Java compilation errors at the end of the build output
- Consolidated report for warnings and deprecations
For more details see https://docs.gradle.org/8.11/release-notes.html
------------------------------------------------------------
Gradle 8.11
------------------------------------------------------------
Build time:    2024-11-11 13:58:01 UTC
Revision:      b2ef976169a05b3c76d04f0fa76a940859f96fa4
Kotlin:        2.0.20
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on …
```
> [android] Minor fixes.

- drape/drape_tests/glyph_mng_tests.cpp
> [tests] Visual test for two missing Latin Extended-A characters

- data/categories.txt
This temporarily fixes #9674.
I still believe that this search should be done on the `operator=` tag. Until this is done, this works good enough to find police emergency services locations, even if they don't exactly match the query.
This might also match queries by users searching for "Guardia di Finanza", which is a dedicated branch of the Italian authorities for finance, but they are still a military organ of the government which interacts with the citizens like "Carabinieri". 
This **could** be removed, but it would also exclude "Guardia Costiera" which is the branch dedicated to sea emergencies.
> Add aliases for Police (#9674)

- defines.hpp
- iphone/Maps/Core/Settings/MWMSettings.mm
- map/framework.cpp
- map/framework.hpp
- platform/CMakeLists.txt
- platform/platform_tests/CMakeLists.txt
- platform/platform_tests/meta_config_tests.cpp
- platform/platform_tests/products_tests.cpp
- platform/products.cpp
- platform/products.hpp
- platform/servers_list.cpp
- platform/servers_list.hpp
- platform/settings.cpp
- platform/settings.hpp
- storage/map_files_downloader.cpp
- xcode/platform/platform.xcodeproj/project.pbxproj
This PR adds support for the product's config to the core.
1. fetch and parse ProductsConfig json
2. save it to the separate file "products_settings.json" (when the new incoming setting config during the map update doesn't contain the `productsConfig` the file will be deleted)
3. add unit tests for servers config and products config
4. add conditions for showing/not showing the products section to the framework:
- Whether the connection is enabled.
- Whether donations are enabled at all.
- Whether the map for the selected Point of Interest (POI) is downloaded.
- Timeout since the first launch.
- Timeout since the app was closed + timeout since the last tap on the donation button.
Timeout are different for the debug and release schemes.
> [core] Implement products configuration

- iphone/Maps/UI/EditBookmark/EditBookmarkViewController.swift
Closes #9722
The bug was caused by the `tableveiew` scrolling with animation to the section's bottom on every `textview` update.
Before:
https://github.com/user-attachments/assets/95d51088-08f4-45a5-bfc2-80d224d0c52c
After:
https://github.com/user-attachments/assets/cc7bbd21-763d-466a-a6e6-fd3d3abcfeb6
> [ios] fix the bookmark description jumping bug during editing

- docs/DEBUG_COMMANDS.md
adds `?olight` and `?odark` to docs.
> [Docs] document outdoor style commands

- platform/measurement_utils.cpp
The current speed is not very precise as it depends on the GPS location. Showing 3,4km/h is not very useful, as it can't be that precise.
This implementation rounds the current speed to the nearest full number, preventing these issues.
Closes #6570
Before:
After:
> Always show rounded current speed

- CMakeLists.txt
- android/app/build.gradle
- docs/INSTALL.md
Following #9377
Actually a new 3.30.3 cmake is not a hard requirement, the project builds just fine with older 3.22.1 (and prob even 3.18.1).
Maybe its better to stick with min 3.22.1 in the docs and `build.gradle`?
> [docs] Update INSTALL.md and revert cmake version

- indexer/validate_and_format_contacts.cpp
Fix the link validation for X(Twitter), closes #9788
> fix X link validation

- qt/qt_common/map_widget.cpp
Closes #7838 
**Symptoms:** after call `glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)` in [map_widget.cpp](https://github.com/organicmaps/organicmaps/blob/master/qt/qt_common/map_widget.cpp#L429) we get error: `glGetError()` returns code 1282.
I searched for possible solutions and on Stackoverflow someone supposed this could be vertex buffer issue ([Stackoverflow answer 1](https://stackoverflow.com/a/49304885) and [Stackoverflow answer 2](https://stackoverflow.com/a/32527554)). Shaders in `gl_150.vsh.glsl`, `gles_200.vsh.glsl`, and `gles_300.vsh.glsl` read QVector4D from `"a_position"` input attribute.
I changed `a_position` assignment for OpenGL vertex shader using `glVertexAttribPointer(...)` which I saw in official Qt example https://doc.qt.io/qt-6/qtopengl-hellogles3-example.html
It works on …
> Qt 6.7 fix

- android/app/src/main/cpp/app/organicmaps/editor/Editor.cpp
- iphone/Maps/UI/Editor/MWMObjectsCategorySelectorDataSource.mm
Added EN as an additional search language in the editor. So users can use englisch, as well as native words in the search. This makes the editor search more consistent with the search on the map (supports en + locale as well) and increases the changes of finding the category users are looking for.
--- 
Tested on Android, but **not** on iOS
The case when lang / locale() == "en" is not a problem as `NewFeatureCategories::AddLanguage` takes care of this case and adds each language only once.
> EN as additional search language in the editor

- indexer/postcodes_matcher.cpp
Added the `annnn` format for Argentinian post codes (a := letter, n := number). This way e.g. V9418 is recognized as a valid post code.
Most addresses in Argentina use `nnnn` which is the old address format. The official address format is `annnnaaa`, but the format `annnn` is also used in several places. So it's better to support it as well.
Examples:
https://www.openstreetmap.org/way/829421469
https://www.openstreetmap.org/node/10560533672
https://www.openstreetmap.org/way/849380896
Wikipedia: https://en.wikipedia.org/wiki/Postal_codes_in_Argentina
related to #5116
> Add alternative Argentinian post code format

- data/strings/sound.txt
Refined the Italian translation for navigation directions. The previous version incorrectly used "sulla" when directing users to turn onto streets or boulevards, leading to grammatically incorrect phrases such as “sulla viale.”
The phrase has been updated to use "in" instead, resulting in more natural and grammatically correct instructions.
This enhancement not only improves the overall fluency of the translation but also addresses grammatical inconsistencies that previously caused errors in the navigation guidance.
> Fix: Improved Italian navigation prompts for street types

- data/countries_names.txt
Chita, Krasnokamensk, Borzya are located in Zabaykalsky Krai (Russia), not in San Marino.
> [strings] Fixed Estonian description of San Marino

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/cpp/app/organicmaps/UserMarkHelper.cpp
- android/app/src/main/cpp/app/organicmaps/bookmarks/data/BookmarkManager.cpp
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm
- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData+Core.h
- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.mm
- iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData.mm
- iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/elevation_info.cpp
- map/elevation_info.hpp
- map/framework.cpp
- map/map_tests/CMakeLists.txt
- map/map_tests/bookmarks_test.cpp
- map/map_tests/elevation_info_tests.cpp
- map/place_page_info.cpp
- map/place_page_info.hpp
- map/track.cpp
- map/track.hpp
- xcode/map/map.xcodeproj/project.pbxproj
This PR:
1. Refactors the `Track`  
1.1. Add the `ElevationProfile` to the `Track`.
1.2. Remove the `interactive` property from the `Track` constructor and `IsInteractive` method because all the tracks should be interactive regardless of whether they have altitudes or not. 
The _old implementation_ doesn't allow to make track interactive during the initialization by passing false to the `IsInteractive` when there is no elevation data in the mwm data file (always)
https://github.com/organicmaps/organicmaps/blob/bbb32ef24f94357691ef7e6347f1e77e95ca9685/map/bookmark_manager.cpp#L2830-L2832
that prevents the interaction data caching:
https://github.com/organicmaps/organicmaps/blob/bbb32ef24f94357691ef7e6347f1e77e95ca9685/map/track.cpp#L65-L73
and because of the `m_interactionData` has never …
> [core] [ios] [android] Raw track selection

- iphone/Maps/Categories/UIView+AddSeparator.swift
- iphone/Maps/UI/BottomMenu/Menu/BottomMenuPresenter.swift
- iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuLayersCell.xib
- iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
- iphone/Maps/UI/PlacePage/PlacePage.storyboard
- iphone/Maps/UI/PlacePage/PlacePageViewController.swift
This PR:
- Refactors the UIView+AddSeparator to be more flexible.
- Fixes the separator color reloading bug when the user interface style was changed.
- Removes all the separators from the PlacePge xibs and storyboards.
- Fix `Layers menu` issue: a separator should be visible only for the Layers + Menu and hidden for the Layers only.
Before/After
> [ios] fix UIView+AddSeparator to support the top and bottom positions and fix separator issues

- android/app/src/main/res/values/styles.xml
Fixed multiline button style for DialogStackedButton. Closes #9727
Dialog is defined in `StackedButtonsDialog`. Layout is defined in `dialog_stacked_buttons.xml`. Each button has style `MwmWidget.Button.StackedButtonsDialog`. Modified the style to allow 2 lines for the buttons:
I also tried to add horizontal separators (**not in this PR yet**):
What do you think?
> [android] Track saving dialog buttons fix

- map/framework.cpp
- map/search_api.cpp
- map/search_api.hpp
Fix for https://github.com/organicmaps/organicmaps/issues/9822.
We now change Search API`s language on map language changing.
For English lang:
After changint to russian:
> Issue 9822. Change the search language when the map language changes.

- iphone/CoreApi/CoreApi.xcodeproj/project.pbxproj
- iphone/CoreApi/CoreApi/CoreApi.h
- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.h
- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
- iphone/CoreApi/CoreApi/TrackRecorder/TrackRecordingInfo+Core.h
- iphone/CoreApi/CoreApi/TrackRecorder/TrackRecordingInfo.h
- iphone/CoreApi/CoreApi/TrackRecorder/TrackRecordingInfo.mm
- map/framework.cpp
- map/framework.hpp
- map/gps_track.cpp
- map/gps_track.hpp
- map/gps_track_collection.cpp
- map/gps_track_collection.hpp
- map/gps_tracker.hpp
- map/map_tests/gps_track_collection_test.cpp
- platform/location.hpp
This PR:
1. Adds `GpsTrackInfo` entity that accumulates the track recording state info during the recording process. The calculation is almost the same as for the `ElevationInfo`, but the main difference is that that ElevationInfo stores all the points for drawing the elevation profile from the selected `multigeometry`. `GpsTrackInfo` is lightweight and only stores the current state to update the observers. The elevation profile drawing of the _recorded track_ seems to be an overhead and may impact the battery life. We can implement it later.
2. Add`SetTrackRecordingUpdateHandler(TrackRecordingUpdateHandler && trackRecordingDidUpdate);` to subscribe on the track recording updates
3. Removes unused code from the `GpsTrackCollection`
> [core] [ios] Observe track recording updates

- data/categories.txt
- data/countries-strings/et.json/localize.json
Mast and Flagpole are the only POIs not searchable in the Editor search. Fix it.
Follow-up to
- https://github.com/organicmaps/organicmaps/pull/9551
- https://github.com/organicmaps/organicmaps/issues/8290
@vng they could be removed when the editor search is refactored
> [strings] Make mast & flagpole searchable in the Editor

- android/app/src/main/res/layout/place_page_description_layout.xml
It looks better with some space between "...more" and the horizontal divider
| Before | Now |
| ![Screenshot_2024-12-16-18-53-43-576_app organicmaps](https://github.com/user-attachments/assets/9cec8c93-f141-48c8-95e3-c19953ac4e2c) | ![Screenshot_2024-12-16-18-53-23-430_app organicmaps debug](https://github.com/user-attachments/assets/6fafbb25-aca1-4401-a6ed-a86a50cc9d59) |
> Add spacing between Wikipedia field and horizontal divider

- map/framework.cpp
Fixes the following warning:
````
map/framework.cpp:2252:12: warning: variable ‘rect’ set but not used [-Wunused-but-set-variable]
````
> [map] Fix unused variable warning

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/util/Config.java
A temporary improvement until a better solution is implemented for
- https://github.com/organicmaps/organicmaps/issues/9344
> Today a friend of mine complained that the "buttons sometimes disappear when using OM for too long without closing the app". They did not know how to leave the full-screen mode so they used to close the app every time this happened.
> [android] Show a toast every time FS mode is entered

- android/app/src/main/java/app/organicmaps/bookmarks/BookmarkListAdapter.java
- android/app/src/main/res/layout/item_category_description.xml
There is uneven Gaping below Title in bookmark List Screen
BEFORE :
AFTER:
Problem Solved - There are two elements in the xml file who's visibility was on even when there was no text which was causing uneven gap so i have set the default visibility off those elements as gone since in the adopter no data is inserted in those two
> [android] Fixes Bookmark List Title UI Uneven Spacing 

- android/app/src/main/java/app/organicmaps/editor/EditorFragment.java
- android/app/src/main/java/app/organicmaps/editor/EditorHostFragment.java
- android/app/src/main/res/layout/fragment_editor.xml
Changed the category panel in the editor to be not clickable. This solves the problem that users unexpectedly lose input data when they click on the panel.
_An alternative would be to use a confirmation dialog to confirm the deletion of data, but making the panel not clickable at all is the cleaner solution IMO. We can re-activate the button once we have a proper implementation for category changes (#3491)_
**Previous behavior:**
- when creating a new POI, clicking on the panel would delete user input and go back to the category selection list.
- when editing a POI the panel had a click animation, but nothing happened on click.
**New behavior:**
- panel not clickable
> Category in editor not clickable

- drape_frontend/circles_pack_shape.cpp
Fixes the following GCC warning:
````
drape_frontend/circles_pack_shape.cpp:133:9: warning: ‘void* memset(void*, int, size_t)’
clearing an object of non-trivial type ‘struct df::CirclesPackDynamicVertex’;
use assignment or value-initialization instead [-Wclass-memaccess]
133 |   memset(m_buffer.data(), 0, m_buffer.size() * sizeof(CirclesPackDynamicVertex));
|   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````
> [drape_frontend] Fix `memset` of non-trivial `CirclesPackDynamicVertex` type

- indexer/drules_include.hpp
Fixes the ~40, GCC 14 warnings in the CI job:
````
generated_message_table_driven.h:159:20: warning: 'is_pod<google::protobuf::internal::AuxillaryParseTableField>'
is deprecated: use 'is_standard_layout && is_trivial' instead [-Wdeprecated-declarations]
159 | static_assert(std::is_pod<AuxillaryParseTableField>::value, "");
````
> [indexer] Fix the suppression of `deprecated-declarations`

- drape_frontend/arrow3d.cpp
Fixes the following GCC warning:
````
drape_frontend/arrow3d.cpp:503:11: warning: ‘void* memcpy(void*, const void*, size_t)’
copying an object of non-trivial type ‘glm::mat4’ {aka ‘struct glm::mat<4, 4, float, glm::packed_highp>’}
from an array of ‘const struct math::Matrix<float, 4, 4>’ [-Wclass-memaccess]
503 |     memcpy(&pTo3dView, &m, sizeof(pTo3dView));
|     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````
> [drape_frontend] Fix `memcpy` of non-trivial GLM type

- iphone/Maps/UI/Editor/MWMObjectsCategorySelectorController.mm
Closes https://github.com/organicmaps/organicmaps/issues/9812#issuecomment-2558623053
NSUTF8StringEncoding works incorrectly with html data type in the UITextView.
Results:
> [ios] fix encoding for the `empty category selection` text view

- generator/maxspeeds_builder.cpp
The following gcc warning is only emitted when `cmake` has been invoked with `-DCMAKE_CXX_FLAGS='-Og'` for debug purposes.
````
generator/maxspeeds_builder.cpp: In lambda function:
generator/maxspeeds_builder.cpp:249:9: warning: ‘status’ may be used uninitialized [-Wmaybe-uninitialized]
249 |         if (status == 0)
|         ^~
generator/maxspeeds_builder.cpp:181:13: note: ‘status’ was declared here
181 |         int status;
|             ^~~~~~
````
> [generator] Suppress false positive `may be used uninitialized`

- platform/platform_tests/downloader_utils_tests.cpp
- platform/platform_tests/meta_config_tests.cpp
- platform/servers_list.cpp
- platform/settings.cpp
- platform/settings.hpp
At the moment user-set settings could be potentially overridden by settings externally configured at the metaserver.
Its not nice. 
Limit them only to DonateUrl and NY which could originate **only** from the server.
> [core] Limit server-set set settings to DonateUrl and NY

- android/app/src/main/res/layout/item_track.xml
Fix #9726 
The text in the Track box gets cut off when displayed in a larger font.
> [Android] Fix the layout height

- data/mapcss-mapping.csv
- indexer/ftypes_matcher.cpp
- search/search_integration_tests/smoke_test.cpp
- search/types_skipper.cpp
Follow-up to https://github.com/organicmaps/organicmaps/pull/9885
Rationale for towers:
E.g. a user had been told about an observation tower or a bell tower in the area. How to find it?
There are many other [tower types](https://wiki.openstreetmap.org/wiki/Key:tower:type) a user might want to search for (and many are unnamed, check taginfo).
Before https://github.com/organicmaps/organicmaps/pull/9854 only cell towers were searchable (as they have their own subtype).
Peaks, saddles, passes, hot springs are important outdoor POIs.
This change makes even unnamed features searchable (just like e.g. nameless benches, cave entrances, etc.)
And improves search ranking for them a bit (after this PR the search engine will treat them as `TYPE_SUBPOI`, not a lower rank `TYPE_UNCLASSIFIED`).
E.g. go …
> [search] Make peaks, saddles, hot springs and towers more searchable

- android/app/src/main/AndroidManifest.xml
AA loses location info when the device is locked and OM is not launched.
We already had this issue and this is the only way I know to resolve it.
AA will find the location again during the navigation because it starts NavigationService which has location type.
But during the free drive AA can't fetch location.
The reason why we removed it is that we can't ensure the user has granted location permission before starting the AA app.
And if the service doesn't have specific permissions for its type it will crash within a time limit (5-15s I guess).
It's been almost a year since I reported this issue to Google and still no response. https://issuetracker.google.com/issues/322622698
https://github.com/organicmaps/organicmaps/pull/8860
I think it's better to have some low-chance fails (when the …
> [android-auto] Put back location type for AA service

- generator/osm2meta.cpp
fixes #9308
Allow more than one number for level. So e.g. "1;2" is allowed as well.
| Now | Before |
| ![Screenshot_2025-01-03-20-31-12-630_app organicmaps debug](https://github.com/user-attachments/assets/44c91a8e-32f8-4e3e-9360-be82533a07ed) | ![Screenshot_2025-01-03-20-41-33-026_app organicmaps](https://github.com/user-attachments/assets/cf515906-9f0d-4520-b5e2-683565aa6068) | 
https://www.openstreetmap.org/node/1237345504
_Android editing tested on the dev server: https://master.apis.dev.openstreetmap.org/changeset/397864_
> Allow more than one number for level

- android/app/src/main/AndroidManifest.xml
Reverts organicmaps/organicmaps#9965
It's not a good fix. On Android 14+ devices when location mode "Ask every time" is selected the app will fail every time :)
We need another solution here.
F.e. let's start NavigationService for AA even without navigation. With this approach, we will start the navigation service only after location permissions have been granted and there will be no issues with non-working location service in AA in free drive mode
> Revert "[android-auto] Put back location type for AA service"

- android/app/src/main/java/app/organicmaps/editor/ProfileFragment.java
- android/app/src/main/res/layout/fragment_osm_profile.xml
- Add insets handling to `ProfileFragment`
- Had to use margins on buttons instead of padding on container, so common `PaddingInsetsListener` can be used
- Fix layout for buttons: use correct constraint for `about_osm` button (regression from #9794)
Fixes #10019
> [Android] Add insets handling in ProfileFragment

- android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java
CategoryDataSource is connected to that one.
Resolves #10005
> [android] Fix the title after editing the name of a boomark.

- packaging/app.organicmaps.desktop.metainfo.xml
fixes https://github.com/flathub/app.organicmaps.desktop/issues/26#issuecomment-2571709466
And adds screenshot environment info, so store apps can show light/dark screenshots based on desktop theme.
> [Packaging] add environment info to desktop screenshots, fix typo

- android/app/src/main/java/app/organicmaps/location/LocationHelper.java
- android/app/src/main/java/org/chromium/base/ObserverList.java
- android/app/src/test/java/org/chromium/base/ObserverListTest.java
It's a legit case when a listener is removed from the list as a result of call to that listener. That causes the list of listeners to be modified during an iteration, which is not supported by standart collections.
The most efficient option to support that is to use ObserverList from Chromium project and this is done here.
Another options are a) to use CopyOnWriteArrayList b) to use Listeners class from the codebase. Both of them are less efficient and do more allocations.
Resolves #546
> Allow to modify list of listeners in LocationHelper from callbacks

- tools/python/descriptions/requirements.txt
- tools/python/descriptions/requirements_dev.txt
I updated to Fedora 41 with python 3.13.1 the other day. The `htmlmin` module doesn't work on this python version any more as `cgi` was removed (1). As the development of `htmlmin` is stale and the module wasn't updated since 2017 (2) I switched to the fork `htmlmin2`. That fixed the problem for me.
(1) https://docs.python.org/3/library/cgi.html
(2) https://github.com/mankyd/htmlmin/issues/66
> Use htmlmin2 to work on newer python versions

- search/latlon_match.cpp
- search/search_tests/latlon_match_test.cpp
Found that when coordinates had both a comma separator and a negative the parsing would skip the input. 
Resolves: #7999
> [search] Add handling for negative case when using comma separators

- CONTRIBUTORS
- closes #9898 
Based on the above PR by @zloidemon 
Compared to it this new PR
- preserves the original structure in the Maps.me section
- removes the coders/translators division in the OM section
> [docs] Update CONTRIBUTORS list

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/app/organicmaps/SplashActivity.java
This is a nice feature to reduce amount of uninstalls and full cleans.
Consider the case:
1. You don't have enough free space on your phone.
2. You go to the Settings -> Storage -> Apps to see which apps eats the space.
3. You see Organic Maps, click on it and click on Clean storage.
4. But instead of performing a full clean you see a screen to manage maps you have on the device.
Third-party storage managment apps could support this as well.
Resolves #1079
> Define manageSpaceActivity

- android/app/src/main/java/app/organicmaps/editor/EditorHostFragment.java
Show login to offline users to educate / inform them that logging in is necessary to finish the editing process. This avoids confusion for people who use the app offline and wonder why their edits are not uploaded.
**Before**
Login is shown after editing when the user is not logged in **and** internet is available.
**Now**
Login is shown after editing when the user is not logged in.
> Show OSM login to offline users

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/app/organicmaps/car/CarAppService.java
- android/app/src/main/res/values/donottranslate.xml
Related to: https://github.com/organicmaps/organicmaps/issues/7263
The issue was fixed by google: https://issuetracker.google.com/issues/322622698
They provided the correct example of how to deal with AA service
The solution is to make AA service a background service instead of a foreground service. Now we don't need to show a notification that our app is launched on AA and we don't need a `specialUse` foreground service type for it.
However, we still need to run foreground NavigationService to be able to constantly fetch location.
This is still not implemented.
There is an unused string left `aa_connected_to_car_notification_title`. It could be used as a notification text for NavigationService.
> [android-auto] Make AA background service

- android/app/src/main/res/layout/place_page_details.xml
- android/app/src/main/res/layout/place_page_links_fragment.xml
Reordered place page details to make the ordering more structured
- Moved phone down and grouped it with website and email (_websites are more important nowadays than phone numbers_)
- Moved wifi and outdoor_seating down to the other less important details
- Grouped level, capacity and wheelchair together
| Now | Before |
| ![Screenshot_20250106_153017_Debug Organic Maps](https://github.com/user-attachments/assets/3c613a4a-0e22-43a9-b911-6b969c186bd8) | ![Screenshot_20250106_153025_Organic Maps](https://github.com/user-attachments/assets/0006b92e-467c-4849-b07f-f260060b1002) | 
| ![Bildschirmfoto vom 2025-01-06 15-33-22](https://github.com/user-attachments/assets/764c2a33-ac19-4389-9808-02d5026cf814) | ![Bildschirmfoto vom 2025-01-06 …
> Reordered place page details

- data/strings/strings.txt
In Japanese, we use the word "録音" when we record sound. (sound is "音".)
"track" is not sound, so "記録" should be used here.
> [strings] fix typo in Japanese

- .github/CODEOWNERS
To make it as before:
anyone could review, mergers would approve and merge
> [github] Remove explicit CODEOWNERS for translations

- android/app/src/main/java/app/organicmaps/bookmarks/BookmarkCategoriesAdapter.java
- android/app/src/main/res/drawable/ic_add_list.xml
- android/app/src/main/res/drawable/ic_import.xml
This implementation is a solution to **#9951**. It replaces the existing **"+"** icon for importing bookmarks and tracks with a **downward arrow** icon, which is more intuitive and clearly represents the action of importing existing content. The **"+"** icon was not immediately clear, as it is typically associated with adding new items rather than importing.
---
- Fixes **#9951** by updating the icon for importing bookmarks and tracks.
---
- Replaced the **"+"** icon with a **downward arrow** icon.
- The new icon now clearly reflects the action of importing bookmarks and tracks.
- Improved user clarity by aligning the icon with standard expectations for import actions.
Below are two screenshots showcasing the difference:
**Current Icon:**
[Current Icon]
**Suggested Icon:**
> [bookmarks] Updated import bookmarks and tracks icon for consistency

- iphone/Maps/Classes/CustomViews/MapViewControls/TrackRecordingViewController.swift
On the first appearance, the corner styles are not set properly and the TR button is a square:
This PR fixes this issue.
> [ios] Fix track recording bug first appearnce bug

- iphone/Maps/UI/BottomMenu/Menu/BottomMenuViewController.swift
- iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuLayersCell.swift
- iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuLayersCell.xib
Closes https://github.com/organicmaps/organicmaps/issues/10143
On some ios versions the `tableView.layoutIfNeeded()` is called but the view isn't marked as it should be re-layouted. This bug is found on the iPhone Xs Max 18.2.
Also, this PR contains a small `BottomMenuLayerButton` refactoring.
> [ios] fix layers menu bug

- android/app/src/main/cpp/app/organicmaps/editor/Editor.cpp
- coding/string_utf8_multilang.cpp
- coding/string_utf8_multilang.hpp
- editor/osm_editor.cpp
- editor/osm_editor.hpp
- editor/xml_feature.cpp
- editor/xml_feature.hpp
- indexer/CMakeLists.txt
- indexer/edit_journal.cpp
- indexer/edit_journal.hpp
- indexer/editable_map_object.cpp
- indexer/editable_map_object.hpp
- indexer/feature_data.hpp
- indexer/feature_decl.cpp
- indexer/feature_decl.hpp
- map/framework.cpp
- xcode/indexer/indexer.xcodeproj/project.pbxproj
fixes  #9129, fixes #8102, fixes #2298, fixes #6260, fixes #6292, fixes #9126, fixes #6939, fixes #9508, fixes #9311
This PR supersedes #9138 and adds a Journal to explicitly store which changes were submitted by the user. See #9129 for why his information is needed when uploading to OSM.
Edits are logged in the Journal. A log contains info like e.g. `Tag "website" changed from "www.organicmaps.app" to "organicmaps.app"` or `ObjectCreated, Type amenity-bench, Location ...`. When uploading, only the Journal entries are used do update the OSM object. After a successful upload, the Journal is cleared.
Saving and restoring the Journal after an app restart is implemented now.
For the transition phase to the new editing logic the old uploading code is still functional. The old code is used when …
> Editor refactoring

- drape_frontend/navigator.cpp
- geometry/geometry_tests/screen_test.cpp
- geometry/screenbase.cpp
- geometry/screenbase.hpp
Found that when zoomed all the way in the `CheckMaxScale` if condition would discard the `tmp` screen so that then we will no rotate the screen at all. 
Added a new matrix transformation to keep the rotation but discard the scale in this case.
> [core] Allow for rotation when scale is max. 

- android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java
Fixes: #9288 
- Makes the whole GPS Error message text visible 
|---------|---------|
| ![before](https://github.com/user-attachments/assets/a818f50e-41ac-47af-8a9f-e0f8558598e3) | ![After](https://github.com/user-attachments/assets/f2cd87ae-89b4-430a-8c29-77931ddb52b2)
|
> [android]  Displays whole GPS error message in notification 

- android/app/src/main/AndroidManifest.xml
- Tested with simulated notch/cutout; functions well
- Compass already has support for reverse portrait
- Solves #9960 
Reasoning: I use my cup holder as a phone stand. If my phone is plugged in, I need to turn my phone upside down.
> [Android] Allow reverse portrait orientation

- xcode/fastlane.sh
The new Fastlane feature enables incremental synchronization of screenshots without fully removing them during each upload.
> [ios] Use FASTLANE_ENABLE_BETA_DELIVER_SYNC_SCREENSHOTS

- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
I followed a conservative approach here and didn't include updates that don't have any patch releases yet (like the newest AGP 8.8.0).
> [android] Update AGP, Gradle, NDK and deps

- android/app/src/main/res/layout/place_page_preview.xml
Fixes : #8913
| Before | After  |
|---------|---------|
| ![before](https://github.com/user-attachments/assets/9f9c416c-c03e-4025-b561-7a02d06535d1) |![after](https://github.com/user-attachments/assets/b9afe3ec-f2a3-465d-9e42-86bdacf40cb4)|
|![After](https://github.com/user-attachments/assets/8fff810d-1579-4f9d-a0b1-f268d9f9d0e3) |   ![Before](https://github.com/user-attachments/assets/0d2b5222-cc1b-4c61-9c5e-1feacca19c52)|
> [android] Fixes word wrapping around hyphens 

- routing/routing_integration_tests/bicycle_route_test.cpp
- routing/routing_integration_tests/routing_test_tools.hpp
- routing_common/bicycle_model.cpp
- routing_common/routing_common_tests/vehicle_model_test.cpp
A big review of weights and ETAs.
I've reviewed all the current integration tests - seems like some of them lost their value over time due to map changes or too similar to other tests. @vng I want to proceed and delete such tests, but first please review my comments in case I've missed something.
Then I've added a bunch of new tests.
Out of scope: some cases are not fixable by weights alone
- https://github.com/organicmaps/organicmaps/issues/9748
Cases solved:
- closes https://github.com/organicmaps/organicmaps/issues/7934
- closes https://github.com/organicmaps/organicmaps/issues/7954
- closes https://github.com/organicmaps/organicmaps/issues/1772
- closes https://github.com/organicmaps/organicmaps/issues/4059
- closes https://github.com/organicmaps/organicmaps/issues/6027
Improves:
- …
> Adjust bicycle routing weights and ETAs

- iphone/Maps/Core/Theme/Renderers/UITableViewRenderer.swift
- iphone/Maps/UI/Editor/OpeningHours/Cells/MWMOpeningHoursTimeSelectorTableViewCell.xib
The bug was caused by my recent style refactoring #10050 
Fixed.
Old style / Stylwe with bug / FIxed ( I removed the grayish bg)
> [ios] Fix UIDatePicker style in the Editor

- android/app/src/main/res/values-de/strings.xml
- android/app/src/main/res/values-es/strings.xml
- android/app/src/main/res/values-eu/strings.xml
- android/app/src/main/res/values-fr/strings.xml
- android/app/src/main/res/values-lv/strings.xml
- android/app/src/main/res/values-pt-rBR/strings.xml
- android/app/src/main/res/values-pt/strings.xml
- android/app/src/main/res/values-ru/strings.xml
- android/app/src/main/res/values/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/lv.lproj/Localizable.strings
Fixes #9334 
Strings changed : 
1.  Before : `Download the world map`
After: `Download the world overview`
2. Before : `Before you start using the app, please download the general world map to your device.`
After: `Before you start using the app, please download the general world overview to your device.`
"world overview" seems to be more adequate avoiding confusion, feel free to share better alternatives 
- Updated corresponding translations using DeepL API as mentioned in [Translations.md](https://github.com/organicmaps/organicmaps/blob/master/docs/TRANSLATIONS.md) 
- The Updated translated string seems to cause error when running `tools/unix/generate_localizations.sh` , for the languages `fa` &  `zh-Hant` , so i reverted these strings to original version
- Regenerated localizations …
> [Strings] Renamed "world map" to  "world overview map" for better user clarity

- iphone/Chart/Chart/ChartData/ChartData.swift
- iphone/Chart/Chart/ChartData/ChartPresentationLine.swift
- iphone/Chart/Chart/Views/ChartInfo/ChartInfoView.swift
- iphone/Chart/Chart/Views/ChartView.swift
- iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfileBuilder.swift
- iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfileDescriptionCell.swift
- iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfilePresenter.swift
- iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfileViewController.swift
- iphone/Maps/UI/PlacePage/PlacePage.storyboard
This PR slightly changes the Track Place Page UI and refactors a related to the elevation profile code.
These changes are important to continue work on #9942 because the TrackRecording PP UI should be readable but fully match with the Track PP UI.
1. Move the description collection view over the chart (see [design](https://www.figma.com/design/5R5LmdM6L4GyfWjSrtlFqZ/OM-Track-Recoding-by-KK?node-id=0-1&t=4uYyqlATrBRgHlZ6-1) with related discussions)
2. Remove the `ElevationProfileViewController` stroryboard and implement  programmatically (same for the  ElevationProfileDescriptionCell)
3. Remove some unused code from the `Chart` target
4. Add `isChartViewInfoHidden` to show/hide the info view and enable/disable user interaction (will be used for the track recording later)
| Before | After …
> [ios] Refactor ElevationProfileVC: update statistics collection UI and move it over the chart

- map/bookmark_helpers.cpp
Fixes #10117 
The title for bookmarks without a custom name was being set based on the system's preferred language, rather than the configured map language. This behavior differed from non-bookmarked places, where the map language was used.
https://github.com/user-attachments/assets/71246dd6-cdd9-49b2-b0d4-b30a8370c774
https://github.com/user-attachments/assets/301770ad-1320-4f32-9efa-c5e5dd8ff27e
> [bookmarks] Make bookmark's title depend on map language

- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/BaseRoutePreviewStatus.swift
Closes #9456
Before the Manage route option in dark mode on iPad was showing as white on white and was impossible to see.
Before,
After,
https://github.com/user-attachments/assets/d7a0aea0-53b4-49af-89cd-2ab66609948e
Author: Mandalorian7773, Committer: Mandalorian7773;
> [ios] Fix the Manage Route button visibility in dark mode on iPad

- android/app/src/main/java/app/organicmaps/car/screens/download/DownloaderScreen.java
- android/app/src/main/java/app/organicmaps/downloader/CountryItem.java
- android/app/src/main/java/app/organicmaps/downloader/CountrySuggestFragment.java
- android/app/src/main/java/app/organicmaps/downloader/OnmapDownloader.java
- android/app/src/main/java/app/organicmaps/util/StringUtils.java
I wasn't able to compile the app, but I improved showing localized percentages in Android. Probably it would be nice to have this on other OS as well.
> [android][l18n] fix localization of percentages in text

- android/app/src/main/res/layout/place_page_preview.xml
- docs/DEBUG_COMMANDS.md
- indexer/map_object.cpp
- indexer/map_object.hpp
- map/framework.cpp
- map/framework.hpp
- map/place_page_info.cpp
- map/place_page_info.hpp
New debug command which has been helpful while working on PR https://github.com/organicmaps/organicmaps/pull/8481. 
- `?all-types`: Shows all internal types in place page
- `?no-all-types`: Disables showing all internal types in place page
> [debug] Add ?all-types debug command to show all internal types

- data/strings/strings.txt
Fixed a strange Japanese sentence because the positions of “date” and “site” are reversed. / "日付"と"サイト"の位置が逆になっていて奇妙な日本語になっていたのを修正しました。
> [strings] fix Login TEXT in Japanese

- android/app/src/main/cpp/app/organicmaps/UserMarkHelper.cpp
- iphone/CoreApi/CoreApi/Bookmarks/TrackInfo+Core.h
- iphone/CoreApi/CoreApi/Bookmarks/TrackInfo.mm
- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageTrackData.mm
- map/CMakeLists.txt
- map/elevation_info.cpp
- map/elevation_info.hpp
- map/framework.cpp
- map/framework.hpp
- map/gps_track.cpp
- map/gps_track.hpp
- map/gps_track_collection.cpp
- map/gps_track_collection.hpp
- map/gps_tracker.cpp
- map/gps_tracker.hpp
- map/map_tests/CMakeLists.txt
- map/map_tests/elevation_info_tests.cpp
- map/map_tests/track_statistics_tests.cpp
- map/track.cpp
- map/track.hpp
- map/track_statistics.cpp
- map/track_statistics.hpp
- xcode/map/map.xcodeproj/project.pbxproj
Every `track`, `track recording`, and `route` should have the basic **statistic** to display (len, dur, max min elevation, ascend, descend, avg speed etc.). This statistic should be lightweight and have almost the same calculation logic for each entity.
Also there can be an _optional_ `ElevationInfo` data - the array of points to draw the chart (some tracks may not have one).
The statistics may be used frequently (during the recording udates or in the Bookmarks and Tracks to display in the list) but ElevationInfo data not.
In the current core implementation (master), the track statistic calculation is scattered in different places: 
- `Track` entity has its own `GetDistanceInMeters` and `GetDuration` method implementations and have the `ElevationInfo`. …
> [core] [map] Implement TrackStatistics and refactor ElevationInfo

- data/test_data/gpx/export_test.gpx
- kml/serdes_gpx.cpp
Issue that is fixed: 
1) Import some gpx file that contains tracks with special symbols in name
2) This file is handled properly because gpx code handles track names with cdata
3) Export single track from this list
4) Exported gpx file has special symbols inside metadata/name (not handled with cdata) and is broken
> [gpx] Use cdata for name field in gpx export

- android/app/src/main/res/values-pl/strings.xml
- android/app/src/main/res/values-uk/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/pl.lproj/Localizable.stringsdict
- iphone/Maps/LocalizedStrings/uk.lproj/Localizable.stringsdict
**pl**:
zero → %d zakładek ✅
"0 zakładek" is correct because zero follows "many" in Polish.
one → %d zakładka ✅
"1 zakładka" is correct (nominative singular).
few → %d zakładki ✅
"2, 3, 4 zakładki" is correct (nominative plural).
many → %d zakładek ✅
"5-9, 0, 11-14, 100 zakładek" follows genitive plural.
other → %d zakładek ✅
Required by ICU/Android, and in Polish, "other" behaves like "many".
**ru**:
zero → %d меток ✅
"0 меток" is correct because zero follows "many" in Russian.
one → %d метка ✅
"1 метка" is correct (nominative singular).
few → %d метки ✅
"2, 3, 4 метки" is correct (genitive singular).
many → %d меток ✅
"5-9, 0, 11-14, 100 меток" follows genitive plural.
other → %d меток ✅
Required by ICU/Android, and in Russian, "other" behaves like "many".
**uk**:
zero → %d міток ✅
"0 …
> [strings] Fix plurals for pl, ru, uk

- .github/CODEOWNERS
Otherwise too much time spend to chase reviewers from different teams on a typical "add a new poi" PR.
If help is needed with map icons then its better to mention the design team explicitly.
> [github] Don't require Design team to review each map icon change

- android/app/src/main/res/values-ja/strings.xml
- data/strings/strings.txt
- iphone/Maps/LocalizedStrings/ja.lproj/Localizable.strings
This is a retry of #10309.
translations of "sort" into more natural Japanese / sortの訳をより自然な日本語に
"並び替え中…" means ”we are in the process of sorting at this very moment". But it seems to indicate here "you can change the order from this menu".
It is that "ソート" make sense too (the same meaning), but adapted it to the surroundings.
/ 「並び替え中…」とすると「今まさに並び替えの動作の最中である」という意味になります。ですが、ここは並べ替えができるメニューが選べる、という意味だと思います。 また、"ソート"でも通じますが、周りが「並べ替え」とあるのでそちらに合わせます。
（Sorry. Only in Japanese from here on.）
「並び替え」と「並べ替え」では主語が違います。
- **リストが**並ぶ
- **私が**リストを並べる
ここでは「私がメニューを選んでリストを並べる」とした方が自然と思いましたので、「並び替え」から「並べ替え」に変更しています。
> [strings] fix 'sort' in Japanese

- map/framework.cpp
- map/gps_tracker.cpp
- map/gps_tracker.hpp
Clears the gps tracker after Saving to free up the memory until the next recording is started. 
In the previous implementation the data will stay in the memory `forever` until the next recording is started(it may be even months of unnecessary memory consumption).
> [core] [map] Clear the gps tracker on save

- android/app/src/main/java/app/organicmaps/search/SearchFragment.java
- android/app/src/main/java/app/organicmaps/search/TabAdapter.java
- android/app/src/main/java/app/organicmaps/util/Config.java
Fix to address #8773:
Calculate search recents list size correctly to set the correct tab in the SearchFragment's layout depending on whether or not, a search history exists.
On app restart, if a search history exists, the search history tab is shown instead of the categories tab, to achieve expected behavior.
Thanks!
> #8773 - On restart, show the search history tab, if search history exists

- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/BaseRoutePreviewStatus.swift
The bottom route status view sometimes jumps from the top to the bottom during the 1st rendering. It happens because the view's frame is not calculated on the `isVisible` and the view is `init/deinit` multiple times during the route building state changing. The bottom view now only changes its visibility and constraints, not the init/deinit on every update
The screenrecs with bug:
https://github.com/user-attachments/assets/6966a9d8-3200-4a87-8cb6-a63559a8c3aa
https://github.com/user-attachments/assets/00bf1260-a389-41d3-ac66-32870a010201
> [ios] Fix route planning UI reloading bug

- tools/unix/version.sh
This reverts commit ee36eb8d125c9a4535964e2b50642a66b74aca9b. That patch was a bit controversial from the start, and I had my doubts. @vng and @pastk aren’t buying it at all.
> Revert "[ios] Use today's commits count and two numbers from commit hash in the build number"

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarkCategoriesFragment.java
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarkCategorySettingsActivity.java
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarkListActivity.java
- android/app/src/main/java/app/organicmaps/bookmarks/BookmarksListFragment.java
- android/app/src/main/java/app/organicmaps/downloader/DownloaderFragment.java
- android/app/src/main/java/app/organicmaps/downloader/DownloaderToolbarController.java
- android/app/src/main/java/app/organicmaps/routing/RoutingPlanController.java
- android/app/src/main/java/app/organicmaps/routing/RoutingPlanFragment.java
- android/app/src/main/java/app/organicmaps/routing/RoutingPlanInplaceController.java
- android/app/src/main/java/app/organicmaps/search/SearchFragment.java
- android/app/src/main/java/app/organicmaps/settings/DrivingOptionsActivity.java
- android/app/src/main/java/app/organicmaps/settings/VoiceInstructionsSettingsFragment.java
- android/app/src/main/java/app/organicmaps/util/UiUtils.java
- android/app/src/main/java/app/organicmaps/widget/SearchToolbarController.java
Fixes: #3630
There's only one file [ProgressDialogFragment](https://github.com/organicmaps/organicmaps/blob/5c18ca362d9090def7206466357a511f324e9fac/android/app/src/main/java/app/organicmaps/dialog/ProgressDialogFragment.java#L32) where the use of `onActivityResult()` is still present. I couldn't find from where this Dialog was getting launched so was not able to register for result.
This dialog fragment is not being used, so should it be removed?
> [android] Use new result APIs

- drape/overlay_handle.cpp
- drape_frontend/text_handle.cpp
- fixes #8264 
A peculiar bug.
It seems that the intention was to render icons & captions on the top of 3D buildings when in perspective mode (see 2996e48cee3838dc1c1451251e03b4cfa2ef4af6).
The building height offset was taken with a wrong scale which made POI's rect miscalculated to be outside of screen rect, hence the POI was clipped and never displayed.
I'm not 100% sure that the fixed height scale is right now, but it fixes the bug and its the same fix as 09f40ceeb006843c405923afb05c5522f7d9f921 which fixed house numbers, but POI icons were just forgotten it seems.
ATM it doesn't always look like building captions or icons are on the top. Maybe it doesn't work for complex buildings with parts only...
> [drape] Fix disappearing building POIs when in perspective

- map/framework.cpp
- map/framework.hpp
- map/gps_track.cpp
- map/gps_track.hpp
- map/gps_track_collection.cpp
- map/gps_track_collection.hpp
- map/gps_tracker.cpp
- map/gps_tracker.hpp
This PR implements the calculation of the `ElevationInfo` drawing data for the track recording.
The `ElevationInfo` will be calculated by adding the missed points from the `GpsTrackCollection` only by request. It means that when the data isn't needed ( the track recording place page is not displayed: the place page is closed, not implemented or the phone is locked) it will not be calculated.
___
This PR is needed for the #9942.
> [core] [map] Calculate ElevationInfo data for the Track Recording live updates

- android/app/src/main/cpp/app/organicmaps/util/StringUtils.cpp
- android/app/src/main/java/app/organicmaps/routing/NavigationController.java
- android/app/src/main/java/app/organicmaps/util/StringUtils.java
- android/app/src/main/java/app/organicmaps/widget/LanesView.java
- android/app/src/main/java/app/organicmaps/widget/SpeedLimitView.java
- android/app/src/main/res/layout-land/layout_nav_top.xml
- android/app/src/main/res/layout/layout_nav_top.xml
- android/app/src/main/res/values/attrs.xml
- android/app/src/main/res/values/styles.xml
- platform/measurement_utils.cpp
- platform/measurement_utils.hpp
Closes: #10092
Added `measurement_utils::FormatSpeed` function which converts speed from double mps to int local units
Created `MwmWidget.SpeedLimit` style with config for the app
Added prefixes for style attributes for SpeedLimitView and LanesView
SpeedLimitView class is a standalone Android view which is not depended on OM's code
Handle motion events on the view - do nothing.
> [android] Fix SpeedLimitView

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/intent/Factory.java
- android/app/src/main/java/app/organicmaps/routing/RoutingController.java
Companion to https://github.com/organicmaps/organicmaps/pull/8431
Removes setting the routing mode to subway when the subway layer is active. Many people have been confused by this, and others would like to keep the subway layer on permanently, but still use the app as normal (https://github.com/organicmaps/organicmaps/issues/9565).
(the old behaviour also set the mLastRouterType to subway, so even if you disabled the layer, the next route you started would still be in subway routing mode)
> [android] Don't set subway routing mode when layer active

- android/app/src/main/java/app/organicmaps/MwmActivity.java
- android/app/src/main/java/app/organicmaps/maplayer/MapButtonsController.java
- android/app/src/main/java/app/organicmaps/maplayer/MapButtonsViewModel.java
- android/app/src/main/java/app/organicmaps/routing/NavigationController.java
- android/app/src/main/java/app/organicmaps/util/UiUtils.java
- android/app/src/main/res/drawable/ic_track_recording_status.xml
- android/app/src/main/res/layout-h400dp-land/map_buttons_layout_navigation.xml
- android/app/src/main/res/layout-h400dp-land/map_buttons_layout_planning.xml
- android/app/src/main/res/layout-h400dp-land/map_buttons_layout_regular.xml
- android/app/src/main/res/layout-h400dp/map_buttons_layout_navigation.xml
- android/app/src/main/res/layout-h400dp/map_buttons_layout_regular.xml
- android/app/src/main/res/layout-land/map_buttons_layout_navigation.xml
- android/app/src/main/res/layout-land/map_buttons_layout_regular.xml
- android/app/src/main/res/layout/map_buttons_layout_navigation.xml
- android/app/src/main/res/layout/map_buttons_layout_planning.xml
- android/app/src/main/res/layout/map_buttons_layout_regular.xml
- android/app/src/main/res/layout/map_status_track_recording.xml
- android/app/src/main/res/values-land/dimens.xml
- android/app/src/main/res/values/dimens.xml
This implementation is mirror of #9847 for android devices
Partially Fixes #9173 
It implements track recording widget on Map screen, Route plan screen and Navigation screen.
Redesigns the landscape layout (similar to iOS) to avoid overlaps.
- If the user taps the button the "Save" dialog will be shown.
- The button has a small blinking effect to attract the user slightly.
- The compass view will be moved under this button when it is active.
- The button is always visible when TR is active and cannot be hidden.
<p align="center">
</p>
<p align="center">
</p>
<p align="center">
</p>
<p align="center">
</p>
> [android] Add track recording widget to the map screen

- map/framework.cpp
Fixes #10211 
Made it so that `Framework::ShouldShowProducts()` doesn't attempt to invoke `Framework::GetCurrentPlacePageInfo()` without first ensuring the `HasPlacePageInfo()` check passes, which would otherwise lead to a crash.
> [android] Fix crash upon deleting a POI via the Editor

- drape/vulkan/vulkan_context_factory.cpp
Fix initialization of `VkPhysicalDeviceFeatures` struct, after compilation warning removal in [PR #10388](https://github.com/organicmaps/organicmaps/pull/10388).
> [drape] Fix initialization of struct

- android/app/src/main/java/app/organicmaps/settings/SettingsPrefsFragment.java
- android/app/src/main/res/xml/prefs_main.xml
- android/app/src/main/res/xml/prefs_voice_instructions.xml
- Fixes issue #10366
- I have made the items listed below invisible by default.
- ## Items:
1. `setting_emulate_bad_storage` in the file [prefs_main.xml](https://github.com/organicmaps/organicmaps/compare/master...DevarshVasani:organicmaps:visibility-change?expand=1#diff-e1683e1c09d15615e187204188064268330afaa421379f717aff1268780ec57d)
2. `pref_tts_street_names`, `pref_tts_language`, `pref_tts_test_voice`, and `pref_tts_volume` in the file [prefs_voice_instructions.xml](https://github.com/organicmaps/organicmaps/compare/master...DevarshVasani:organicmaps:visibility-change?expand=1#diff-07cc0fdbc609740bad8ce1ce30b0f2871fad71aef2eac631d4671f5f335a6d9a)
> [android] Made the "Emulate bad storage" setting invisible by default.

- iphone/Maps/Classes/CustomAlert/Toast/Toast.swift
- iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtons.mm
- iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm
- iphone/Maps/Core/Theme/GlobalStyleSheet.swift
- iphone/Maps/Core/TrackRecorder/TrackRecordingManager.swift
- iphone/Maps/UI/Editor/MWMEditorViewController.mm
- iphone/Maps/UI/Help/AboutController/AboutController.swift
- iphone/Maps/UI/Help/AboutController/Views/DonationView.swift
- iphone/Maps/UI/PlacePage/PlacePageInteractor.swift
- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
1. Update style: bigger fonts and insets to make toast more readable
2. Update background blur
3. Get rid of MWM prefix
4. Replace the `timer` with the `dispatch async after`. In this case, there is no need to create a whole timer for each toast message just to add a timeout.
5. Reorder Toast class methods for more readibility
6. Replace the instance  method `show` with a class `static show`. Because there is no need to call `show` every time: we do not have stored toast that will be shown in different places than created.
___
Before/Aftter
> [ios] Refactor Toast class and improve toast message style

- iphone/Maps/UI/Search/SearchOnMap/PlaceholderView.swift
The placeholder view animation on the search screen jumps on the modal presentation step changes.
This PR fix it.
> [ios] fix Placeholder view animation

- android/app/src/main/java/app/organicmaps/MwmActivity.java
Fixes #8915
When on fullscreen mode, after selecting "Route to", the app leaves fullscreen mode when initiating the navigation window. The same was not happening when navigating in "Route from" mode, and it was only possible to leave fullscreen mode after leaving the navigation window.
This commit fixes that bug, ensuring that the app leaves fullscreen mode when entering "Route from" navigation. Fullscreen mode can then be set again after exiting navigation.
Demonstration:
https://github.com/user-attachments/assets/0bbb4e50-4fcf-41b6-8dd7-4ae0a2e1a239
> [android] fix fullscreen exit on Route From

- android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java
- android/app/src/main/java/app/organicmaps/widget/placepage/sections/PlacePageBookmarkFragment.java
Fixes #2418
The callback listener supposed to be invoked after bookmark edits (`mListener` in `EditBookmarkFragment`) was made null on configuration changes. This change fixes the issue by leveraging the fact that the parent fragment (for cases when the issue occurs, i.e. `PlacePageBookmarkFragment`) itself implements the listener.
https://github.com/user-attachments/assets/74f786e1-fbed-4bab-9efe-fae4d45985fc
https://github.com/user-attachments/assets/77a27cd3-341c-4cbb-840d-7cec117c84a5
> [android] Fix bookmark edits not updating in place page on screen rotation

- .github/workflows/appstream-check.yaml
As the warning says in the [README](
https://github.com/hughsie/appstream-glib/blob/3bbf7e94243de5a2c4e0838c751dda1c4063d437/README.md?plain=1#L1) `appstream-glib` has been in maintenance mode for 2 years, apparently the flatpak runtimes are also not updated anymore. Their own recommendation is to use appstream cli,
that our CI already uses, so there is less and less benefit for keeping it in the CI.
> [github] Drop appstream-glib in favor of appstream cli

- iphone/Maps/Core/Search/MWMSearch.mm
Closes #10544
During the searching, the `searchCount` tracks the progress and notifies the observers (when 0 then completed). It crashes in debug when less than 0.
When the `?edits` command is typed into the search field the `searchInViewport`'s  `m_onStarted` callback is called, but `m_onStarted` **is not**  executed at all (in the core). It produces a data race in the `searchCount` and breaks the UI updates for this debug command.
https://github.com/organicmaps/organicmaps/blob/251c2022c855f11a33a0d7ed3e868566c0d1d9df/map/framework.cpp#L2793-L2822
The calling of the `m_onStarted` will not help because it is executed asynchronously as a separate UI task, is also produces a data race (when the count is <0).
Since the `searchEverywhere` and `searchInViewport` are called simultaneously …
> [ios] Fix search count calculation for `?edits` debug command

- android/app/src/main/java/app/organicmaps/sdk/routing/RoutePointInfo.java
- Build route
- Select start/intermediate/end point.
- Crash
> [android] Fixed crash when creating RoutePointInfo from JNI.

- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageTrackLayout.swift
The track PP will be fully expanded for now to allow user to see all of the info + elevation data
> [ios] Fully expand the track PP when opened

- iphone/Maps/UI/Search/SearchOnMap/Presentation/ModalPresentationStep.swift
Now the top inset is `8 + safe area`
Before / After
It doesn't affect landscape iPhone and the iPad
before
after
> [ios] Increase search screen top inset from the safe area

- iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
- iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm
- iphone/Maps/Classes/MapViewController.mm
The old implementation was rigidly tied to the place page top bound. It breaks the side buttons (zoom, location) hiding/showing animation when the PP is expanded. 
Now the side buttons follow the PP top edge with animation softly without rigidity and disappear animated when they are out of bounds.
Also, the `Layers` button now disappears when it does not fit in the available space.
> [ios] update side buttons animation

- iphone/Maps/Classes/CarPlay/MWMCarPlaySearchService.mm
- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.h
- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.mm
- iphone/Maps/Classes/MapViewController.h
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
- iphone/Maps/Core/Search/MWMSearch.h
- iphone/Maps/Core/Search/MWMSearch.mm
- iphone/Maps/Tests/UI/SearchOnMapTests/SearchOnMapTests.swift
- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapHeaderView.swift
- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapInteractor.swift
- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapManager.swift
- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapModels.swift
- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapPresenter.swift
- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapViewController.swift
- iphone/Maps/UI/Search/Tabs/SearchTabViewController.swift
When the user starts typing the query in the search field and selects the suggestion, the suggestion should replace the text + add spacing and allow to continue typing without breaking the search logic.
This logic was broken by the latest search UI redesign.
This broken behaviour is confirmed by the failing test (2 new checks was missed but added now):
1. Fix the broken logic
2. Refactor search - the `SearchQuery` class is used instead of `text + locale + isCategory` arguments passed through the bunch of methods.
Select suggestion (fixed)
Select category
Deeplink:
Paste coordinates
Routing + search
> [ios] Fix search suggestions

- android/app/src/main/cpp/app/organicmaps/UserMarkHelper.cpp
- android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp
- android/app/src/main/cpp/app/organicmaps/core/jni_helper.hpp
Fixes #9624 thanks to @batterydotac
Now it doesn't crash, but WiFi emoji is missing in the font, so it can be fixed separately. Note that other emoji (atm, toilet, accessibility) are displayed properly.
What I don't understand is: why the title without this conversion works, but only subtitle where types are displayed crashes? CC @hb0nd 
CC @hemanggs
> Fix crash on Android 5 and 6 when PP type field (subtitle) has unicode > 0xFFFF

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/java/app/organicmaps/Framework.java
- android/app/src/main/java/app/organicmaps/routing/RoutingBottomMenuController.java
- android/app/src/main/java/app/organicmaps/routing/RoutingPlanController.java
- android/app/src/main/res/layout-land/altitude_chart_panel.xml
- android/app/src/main/res/layout-w1020dp-land/altitude_chart_panel.xml
- android/app/src/main/res/layout/altitude_chart_panel.xml
- android/app/src/main/res/values/strings.xml
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/framework.cpp
- map/framework.hpp
- map/map_tests/bookmarks_test.cpp
- map/routing_manager.cpp
- map/routing_manager.hpp
- qt/routing_turns_visualizer.cpp
Save button is added to Manage Route dialog and stores track with pre-generated name (the same as used for track recorder's tracks).
You can see saved track under the route line from router.
UI suggestions are welcome.
> [routing] Add possibility to save routes as tracks

- android/app/src/main/java/app/organicmaps/settings/SettingsPrefsFragment.java
Issue:
The "3D buildings" and "Perspective view" settings are coupled per Settings page session so that if one is changed, it overwrites any changes made on the other compared to what the values were when the Settings page was entered.
Fix:
made changes to preference change listener to get the current 3D mode state at the time of the change
This was done by creating a fresh Params3dMode object inside the listener to hold the current state, rather than relying on a previously fetched final object.
> Fix unintended coupling of 3D settings in Settings page session (#10581)

- android/app/src/main/java/app/organicmaps/downloader/BottomPanel.java
Fixes #10617
This is regression of https://github.com/organicmaps/organicmaps/commit/91c5d8e95cfc5b3dee57102518145568f6bb312d#diff-149273e9111534aff084630c7cf7e8aabea1b962960d0e410fb17e5190ad62ccR42
Adding back `MapManager.nativeCancel(mFragment.getCurrentRoot());` fixes the issue.
I am not sure if this change gonna cause any regression. Was that change intended? Can you please confirm @hemanggs
> [android] fixes unable to cancel download bug

- iphone/Maps/Categories/UIViewController+alternative.swift
- iphone/Maps/Common/Common.swift
- iphone/Maps/Core/Theme/GlobalStyleSheet.swift
- iphone/Maps/Core/Theme/PlacePageStyleSheet.swift
- iphone/Maps/Tests/UI/SearchOnMapTests/SearchOnMapTests.swift
- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapInteractor.swift
Im not sure that this PR should close the https://github.com/organicmaps/organicmaps/issues/8404 because it is related only to the last comment: https://github.com/organicmaps/organicmaps/issues/8404#issuecomment-2913883463.
The logic of the decision of whether the device is iPad or not was not correct in the `alternativeSizeClass` methods - it should not rely on hor and vert size classes. Because iPad in `SplitView` mode can have compact horizontal size class (in 1/2 or 1/3- depends on device), this breaks the layout logic. Only in the fullscreen mode iPad will have [both regular](https://developer.apple.com/design/human-interface-guidelines/layout#iOS-iPadOS-device-size-classes).
(Sorry for the vertical GIF)
> [ios] Fix PlacePage layout for the iPad in SplitView mode

- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.h
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.mm
- iphone/Maps/Core/Search/MWMSearch.h
- iphone/Maps/Core/Search/MWMSearch.mm
- iphone/Maps/Tests/UI/SearchOnMapTests/SearchOnMapTests.swift
- iphone/Maps/UI/Search/SearchOnMap/Presentation/ModalPresentationStepsController.swift
- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapInteractor.swift
Closes https://github.com/organicmaps/organicmaps/issues/10561 and https://github.com/organicmaps/organicmaps/issues/10609
This PR:
1. Fixes the search modes switching by using the typed `SearchMode` that is tied to the presentation mode:
- When the screen is **fullscreen** on an iPhone, only the `search everywhere` will be triggered
- When the search is in the **"halfscreen" or compact** modes, both the search `everywhere` and `viewport` will be triggered.
- When the search is **hidden** only the `viewport` will be triggered.
- On the iPad, there are only 2 modes: **opened** ( `everywhere` + `viewport`) and **hidden** (`viewport`)
2. During the viewport updates, the new search will be triggered only when the previous search is finished to decrease the search payload and execute searches …
> [ios] Fix search infinity loading

- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.h
- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMiPhoneRoutePreview.xib
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewStatus/BaseRoutePreviewStatus.swift
Parity match with an Android https://github.com/organicmaps/organicmaps/pull/10528
> [ios] Add `save route as track` button to the route building screen

- drape/glyph_manager.cpp
A warning with the missing Unicode character code is displayed before this line, so there's no need to print the original string in full.
Fixes #10685
Grapes emoji are also popular in OpenStreetMap.org:
https://www.openstreetmap.org/node/427043258
https://www.openstreetmap.org/node/508567791
https://www.openstreetmap.org/node/807055352
https://www.openstreetmap.org/node/2721676230
https://www.openstreetmap.org/node/4785410399
https://www.openstreetmap.org/node/7775622442
https://www.openstreetmap.org/node/8525518430
https://www.openstreetmap.org/node/9967572810
https://www.openstreetmap.org/node/10900386710
https://www.openstreetmap.org/node/10935098949
https://www.openstreetmap.org/node/11134771875
https://www.openstreetmap.org/node/11220327798 …
> [android] Fix crash when print log with emoji on Android 5 and 6

- android/app/src/main/java/app/organicmaps/location/LocationHelper.java
- android/app/src/main/java/app/organicmaps/util/LocationUtils.java
partially fixes #10128
fixes #9054 #6270 
The current logic filters out all the location updates from all the providers except the fused location provider. Which results in a jumps in location arrow. Better solution is pass all the location updates (including fused location) through filter and the choose the precise one. 
We cannot solely rely on fused as well since some OS have issues with it. Check out this [comment](https://github.com/organicmaps/organicmaps/blob/master/android/app/src/main/java/app/organicmaps/location/AndroidNativeProvider.java#L92)
Note - Since multiple providers are there so flickering can still be seen but it is minimized due to checks. For total removal either we have to rely on single provider of we need to improve the filter.
> [android] Fix jump of current location point

- iphone/Maps/UI/BottomMenu/Menu/BottomMenuInteractor.swift
Hotfix for the issue caused by the #9942 - the stop track recording button doesnt stop the TR.
Now it shows the TR place page screen.
> [ios] Fix `stop track recording` button action

- iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfilePresenter.swift
- iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfileViewController.swift
When the track recording elevation info data is empty (less than 3 point) and the user start interacting with the chart it fail.
This PR fixed it.
> [ios] Disable elevation chart interaction when the chart data is empty

- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/IPlacePageLayout.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageTrackRecordingLayout.swift
- iphone/Maps/UI/PlacePage/PlacePageViewController.swift
This PR removes the **spacing** and **separator** between the header and track's data info body for Track Recording Place page to decrease its space and slightly improve visual style to not split the data visually.
Before/After:
> [ios] remove spacing and separator from the Track recording Place page

- android/app/src/main/java/app/organicmaps/downloader/DownloaderService.java
- android/app/src/main/java/app/organicmaps/location/TrackRecordingService.java
- android/app/src/main/java/app/organicmaps/routing/NavigationService.java
Fixes #9395
Its not sure it fixes the crash or not but this could be the cause of crash since in android api 34 and above we need to specify the foreground service type while calling the startForegound method for track recording and navigation.
Reference android documentation - https://developer.android.com/develop/background-work/services/foreground-services#start
Please test and provide feedback if its solves the crash or not
> Modified startForeground() method call to adapt for android 14+

- android/app/src/main/java/app/organicmaps/MapFragment.java
- android/app/src/main/java/app/organicmaps/MwmActivity.java
- Fixes #9819 
- Changed `requireActivity()` method to `getActivity()`.
- Added a check to ensure it's not null.
> [android] Fix IllegalStateException in destroySurface method.

- android/app/src/main/java/app/organicmaps/maplayer/MapButtonsController.java
Fixes : #10739
- Thanks to @pastk  for pointing out.
- The issue seems to be with race condition between application of inset and closing animation of keyboard screen , adding a slight delay fixes it ( 1000ms is enough , it went to 1200 ms on some outliers though) 
- Weirdly the i only found this issue on android 10  and not on android 5 , to be safe i have applied delay to android 10 and below.
- #10600 works as expected
CC @biodranik
> [android] Adds delay to inset application on API 29 and lower

- android/app/src/main/java/app/organicmaps/SplashActivity.java
- android/app/src/main/res/layout/activity_splash.xml
Fixes #10721
Used WindowInsetsCompat to apply bottom padding based on system navigation bar height. This prevents content overlap.
Tested on Android 14 Android 15 Android 16
android 14
android 15
https://github.com/user-attachments/assets/c87d7f05-e180-4246-bde6-066018a1d5f7
android 16
> Fixes #10721 |  prevent splash screen content from being overlapped | 

- android/app/src/main/cpp/app/organicmaps/Framework.cpp
- android/app/src/main/cpp/app/organicmaps/sdk/routing/JunctionInfo.hpp
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/map_tests/bookmarks_test.cpp
- map/routing_manager.cpp
- routing/routing_session.cpp
- routing/routing_session.hpp
Continues https://github.com/organicmaps/organicmaps/pull/10528
@biodranik @vng @cyber-toad I didn't find the possible situation when the `poins.count` and `altitudes.count` are not equal. Should we fail in this situation or it's better to make all altitudes = 0 (prev solution)?
The statistics differ because for the elevation chart, the road altitudes and distances are simplified (there are Simplify() method). IMO it's acceptable.
> [map] Save points altitudes when saving route as a track

- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageTrackData+Core.h
- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageTrackData.h
- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageTrackData.mm
- iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData+Core.h
- iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData.h
- iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData.mm
- iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
- iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfileBuilder.swift
- iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfilePresenter.swift
- iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfileViewController.swift
- iphone/Maps/UI/PlacePage/PlacePageBuilder.swift
- iphone/Maps/UI/PlacePage/PlacePageInteractor.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageTrackLayout.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageTrackRecordingLayout.swift
When a user selects a point on a track, the coordinates are stored in the PP (Place Page) data. However, these coordinates are not updated upon subsequent selections. As a result, the “Route to/from” buttons always use the coordinates of the initially selected point, breaking their expected behavior.
The coordinates of the selected track point are now updated on every new tap on the Track or while dragging in the Elevation chart. This ensures the “Route to/from” buttons always use the most recent selection. Key changes include:
1.	`Active point` and `My position` have been moved from the `Elevation profile` to `PlacePageTrackData`, as they represent track-wide state, not just data relevant to the chart.
2.	Subscription to active point updates has been moved from the `Elevation profile` to …
> [ios] Fix track selection point updates on every new tap

- .github/workflows/build-cmake.yaml
- .github/workflows/ios-beta.yaml
- .github/workflows/ios-check.yaml
- .github/workflows/ios-release.yaml
Maybe it also fixes failing iOS simulator in tests: https://github.com/organicmaps/organicmaps/actions/runs/15712497453/job/44273930870?pr=10707
```
2025-06-17 17:01:21.368 xcodebuild[17534:68865] [MT] IDETestOperationsObserverDebug: 772.225 elapsed -- Testing started completed.
2025-06-17 17:01:21.369 xcodebuild[17534:68865] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2025-06-17 17:01:21.369 xcodebuild[17534:68865] [MT] IDETestOperationsObserverDebug: 772.225 sec, +772.225 sec -- end
Testing failed:
Organic Maps (Debug) (62880) encountered an error (Test runner never began executing tests after launching)
** TEST FAILED **
```
> [github] Use the latest Xcode 16.4 for checks and releases

- android/app/src/main/java/app/organicmaps/editor/OsmLoginFragment.java
- android/app/src/main/java/app/organicmaps/util/Utils.java
Fixes #10741
Fixes #10689
I couldn't reproduce the issue. So I don't know why OM can't open browser. Maybe some permissions problem. Changed behaviour: if browser coulnd't be found then we fallback to login + password UI (no browser required).
Unified `Utils.openUri` and `Utils.openUrl` functions.
Rebased on `master`.
Replaced try-catch with if-else block for browser availability check.
> [Android] Check browser availability before showing OAuth login UI.

- android/app/src/main/java/app/organicmaps/background/OsmUploadWork.java
May resolve duplicate notes uploading for Android mentioned in #2071
Keeps only one unit of work active by dropping the next one.
> enqueueUniqueWork
Added in [1.0.0](https://developer.android.com/jetpack/androidx/releases/work#1.0.0)
> public @[NonNull](https://developer.android.com/reference/androidx/annotation/NonNull) [Operation](https://developer.android.com/reference/androidx/work/Operation) [enqueueUniqueWork](https://developer.android.com/reference/androidx/work/WorkManager#enqueueUniqueWork(kotlin.String,androidx.work.ExistingWorkPolicy,androidx.work.OneTimeWorkRequest))(
@[NonNull](https://developer.android.com/reference/androidx/annotation/NonNull) [String](https://developer.android.com/reference/java/lang/String.html) uniqueWorkName, …
> [android][editor] Keep the last background unique osm upload work to avoid duplicates

- map/framework.cpp
Closes https://github.com/organicmaps/organicmaps/issues/10757
This is the 1st attempt to fix the track selection zoom level. The `SetModelViewCenter` appears not to be suitable for the tracks.
There are some questions:
1. Should we bring back the viewport on deselecting the track? It seems logical and the bookmarks has the same behaviour.
2. Should we update the viewport when the PP is fully opened (2nd iteration) and update the zoom level accordingly (see how the bookmarks are zoomed)? Because the PP takes a lot of space (almost half of the screen). So maybe a little track cropping is ok?
> [map] Fix zoom on selected/saved track

- android/app/src/main/java/app/organicmaps/util/Utils.java
Reverted changes from PR #10779.
Replaced `intent.resolveActivity()` with try-catch block. `resolveActivity()` method depends on security system which changes from one Android version to another. try-catch block is more reliable way to trigger a browser.
> [Android] Browser availability check fix

- android/app/src/main/java/app/organicmaps/sdk/util/Config.java
- platform/settings.cpp
- platform/settings.hpp
- qt/preferences_dialog.cpp
@AndrewShkrob Is it ok with AA? Because R.string.theme_nav_auto is absent there.
When the user downloads the app in the evening, they should see the light theme by default (like on iOS).
> [android] Set default theme as NavAuto.

- README.md
The old one was full, limited by max of 1K signups.
> [readme] Updated link to beta testing for Android

- iphone/CoreApi/CoreApi/Logger/Logger.mm
Fixes:
1. The log.txt file is saved root documents directory so the user can find it manually in the OM container
2. The log.txt is **not** immediately deleted while creating the zip
3. Zip archive for sharing is created in the tmp directory as before (to be cleaned up automatically)
> [ios] Save log.txt file to the root documents directory

- base/base_tests/math_test.cpp
- base/math.hpp
- drape/stipple_pen_resource.cpp
- drape/stipple_pen_resource.hpp
- drape_frontend/gui/ruler_helper.cpp
- drape_frontend/traffic_renderer.cpp
- drape_frontend/visual_params.cpp
- ge0/url_generator.cpp
- generator/cells_merger.cpp
- generator/maxspeeds_builder.cpp
- generator/srtm_parser.cpp
- geometry/geometry_tests/screen_test.cpp
- geometry/screenbase.cpp
- indexer/feature_impl.cpp
- indexer/ftypes_matcher.cpp
- indexer/scales.cpp
- map/map_tests/bookmarks_test.cpp
- platform/distance.cpp
- platform/measurement_utils.cpp
- platform/utm_mgrs_utils.cpp
- qt/qt_common/scale_slider.cpp
- routing/cross_border_graph.hpp
- topography_generator/generator.cpp
See https://clang.llvm.org/extra/clang-tidy/checks/bugprone/incorrect-roundings.html
> Removed SignedRound and replaced std::round with std::lround where needed

- iphone/Maps/Bookmarks/Categories/Categories/BMCCategoryCell.xib
Some bookmark list titles can be long and one line is not enough to show them in full, specially in smaller devices. This PR allows bookmark list titles to span multiple lines.
> [ios] Show multiline titles in bookmark lists

- tools/unix/generate_symbols.sh
Like
`OUT_PATH=../build-Qt_6_9_0_for_macOS-Debug ./tools/unix/generate_symbols.sh`
to avoid a useless build into hardcoded `out/release`.
> [tools] Ability to run generate_symbols with specified OUT_PATH.

- tools/unix/generate_symbols.sh
This reverts commit b456d46057d9ea7564e107f1a4e5ed95ebba3d76.
Alternative fix: https://github.com/organicmaps/organicmaps/pull/10932/files#diff-5309a243e8ca5ad68505ee25d57b037c330d745ec7d943a8564118f888164cf8
> Revert "[tools] Ability to run generate_symbols with specified OUT_PATH."

- .github/workflows/build-cmake.yaml
- .gitmodules
- 3party/CMakeLists.txt
- docs/INSTALL.md
- libs/platform/chunks_download_strategy.cpp
- libs/platform/country_file.cpp
- libs/platform/get_text_by_id.cpp
- libs/platform/http_client.cpp
- libs/platform/http_request.cpp
- libs/platform/http_thread_qt.cpp
- libs/platform/local_country_file.cpp
- libs/platform/local_country_file_utils.cpp
- libs/platform/platform_android.cpp
- libs/platform/platform_tests/CMakeLists.txt
- libs/platform/platform_tests/country_file_tests.cpp
- libs/platform/platform_tests/downloader_tests/downloader_test.cpp
- libs/platform/platform_tests/get_text_by_id_tests.cpp
- libs/platform/platform_tests/glaze_test.cpp
- libs/platform/platform_tests/local_country_file_tests.cpp
- libs/platform/platform_tests_support/test_socket.cpp
- libs/platform/platform_unix_impl.cpp
- libs/platform/platform_win.cpp
- libs/platform/settings.cpp
- It's fast
- Supports JSON with comments
- Compile time reflection (easy to use, see unit test)
- Also supports [CSV](https://stephenberry.github.io/glaze/csv/) and [BEVE](https://stephenberry.github.io/glaze/binary/)
- It even has a [thread pool](https://stephenberry.github.io/glaze/thread-pool/) and [optional HTTP client/server support](https://stephenberry.github.io/glaze/networking/http-rest-support/) 😱
More info: https://stephenberry.github.io/glaze/
We can replace jansson with glaze in our code, and use it in any new code requiring JSON.
Basic usage example: https://github.com/organicmaps/organicmaps/pull/10986/commits/d26da69bc0e3c41bbdb849bdb0e95bbbdd887802#diff-950b68aa006f985d763c9f3e4274df1bb9226211394ad4925f45a8e6467e2fc3R48-R89
Advanced usage example: …
> Add Glaze JSON parser

- libs/base/random.hpp
`std::uniform_int_distribution<T>` requires `sizeof(T) >= sizeof(short)`
> Make UniformRandom standard-conforming

- libs/coding/files_container.cpp
- libs/coding/mmap_reader.cpp
The POSIX standard says, that `fcntl.h` is to be included as `#include <fcntl.h>`.
This change fixes the compiler warnings that happen with `musl` libc :
```
/usr/include/sys/fcntl.h:1:2: warning: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Wcpp]
1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
|  ^~~~~~~
In file included from /home/ferenc/github.com/organicmaps/organicmaps/libs/coding/mmap_reader.cpp:18,
from /home/ferenc/github.com/organicmaps/organicmaps/build-alpine-3.21/build-alpine-3.21/libs/coding/CMakeFiles/coding.dir/Unity/unity_0_cxx.cxx:40:
/usr/include/sys/fcntl.h:1:2: warning: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Wcpp]
1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
| …
```
> [libs][linux] Fix incorrect include of `fcntl.h`

- iphone/Maps/Core/TrackRecorder/TrackRecordingManager.swift
There are a bunch of crashes of the track recording live activity widget running for macOS.
This PR disables it.
> [ios] Disable track recording live activity widget for apps running on macos

- iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
Every time before the PP screen is created the pp data existance should be checked like done in the
https://github.com/organicmaps/organicmaps/blob/53718e1bce241716bcd0018a47ab8036fbb72d09/iphone/Maps/Classes/MapViewController.mm#L275-L279
This PR adds the same check to the track recording PP update callback to fix the crash when the user interacts with the chart:
> [ios] Check that pp data exists before update the TR PP screen

- iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm
> [ios] Fixed ATM translation in the PlacePage

- android/app/src/main/java/app/organicmaps/editor/FeatureCategoryAdapter.java
Fixes #11038
- Problem caused due to `item_feature_category_footer.xml` being wrapped with `FeatureViewHolder` instead of `FooterViewHolder`
- Introduced as part of [refactoring](https://github.com/organicmaps/organicmaps/commit/548aa1ad9d6066daa3c3df152fb6d474e0aa2ed1#diff-a974a0a4515c7e4e18628d519635b018341de06bcf1c2c666db4577c6b5ef108:~:text=56-,%40Override,%7D,-78) 
CC @biodranik
> [android] Refactoring regression fix

- libs/map/map_tests/bookmarks_test.cpp
- libs/platform/platform_android.cpp
- libs/platform/platform_linux.cpp
- libs/platform/platform_mac.mm
- libs/platform/platform_win.cpp
Observed in Ubuntu 24 via Orb on arm-based Mac. Fixes failing `GetFileCreationTime_GetFileModificationTime` test.
> [linux] Fix zero file creation (birth) time

- iphone/Maps/Categories/UIKitCategories.m
Reported by user, fixes opening of websites like this one: https://www.openstreetmap.org/way/1245855481#map=17/49.448456/0.816851&layers=V
> [ios] Fix opening websites with percent encoding characters

- android/app/src/main/java/app/organicmaps/MapFragment.java
- android/app/src/main/java/app/organicmaps/car/SurfaceRenderer.java
- android/app/src/main/java/app/organicmaps/sdk/Map.java
There was a call `MwmApplication.from(mCarContext).getLocationHelper()` in `SurfaceRenderer` which resulted in NullPointerException
Probably the call happens too early when car context is not yet bind to app context.
Another NullPointerException was in MapFragment. The call to `mMap` object happened before the fragment is attached (and `mMap` object is created)
> [android-auto] Fix null pointer exception

- iphone/Maps/UI/PlacePage/PlacePageViewController.swift
Closes https://github.com/organicmaps/organicmaps/issues/10567 
Sometimes, during the fast taps on one of the action button, the action can be triggered multiple times when the current place page data object is deinitialized. The app should not crash in such situations. The fix prevents the double-tap action handling.
The issue can be easily reproduced by the double-tapping on the `remove stop` button during the _route building_.
> [ios] Skip addBoorkmark/routeRemoveStop when there is no place page data

- libs/base/string_utils.cpp
- libs/indexer/categories_holder.cpp
This reverts commit f3bae5ca8543c9f7c8bad78e1a5fef760db6352b.
Revert the wrong merge. Actually, strings::Trim is called from many places (including kml), so should make a valid UTF8 fix with updating comments.
> Revert "Fix some incorrect usage of std::isspace and std::isdigit"

- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
Hides category bar for map objects other than track and bookmarks
CC @AndrewShkrob
> [android] Fix hide PP category for other map objects other than track and bookmark

- libs/map/routing_manager.cpp
This should simplify route planning and avoid unnecessary zoom in back and back again.
Based on discussion in https://github.com/orgs/organicmaps/discussions/4178#discussioncomment-14109633
Fixes the issue from this video:
https://github.com/user-attachments/assets/4cc9b362-ae2b-4af5-894b-99d1265248ea
> Do not autozoom to show the full route when adding stops

- android/app/src/main/java/app/organicmaps/car/screens/NavigationScreen.java
- android/app/src/main/java/app/organicmaps/car/util/Colors.java
From now on we will use green background for navigation templates in night mode. We already used green background in day mode.
Before
After
Rationale:
* Morons from google
> [android-auto] Fix theme issues

- android/app/src/main/java/app/organicmaps/bookmarks/BookmarksToolbarController.java
- android/app/src/main/java/app/organicmaps/search/FloatingSearchToolbarController.java
- android/app/src/main/java/app/organicmaps/widget/SearchToolbarController.java
- android/app/src/main/res/layout/fragment_editor_host.xml
- android/app/src/main/res/layout/toolbar_search_controls.xml
Hi
this PR is for a UI fix in the search bar "X" button. The issue was that on the Google Pixel 6 model, the Cancel and Save buttons overlapped when using German language. I have resolved this issue and tested it on an emulator with the same device model. The screenshot is attached. I also applied some padding and shifted the button to the left. The issue is now completely fixed.
Now I have update in my last commit to modern Textfeild with inbuild clear button :-
Before
After 
Now it will not overlap 
Issuse #11219
> Updated Button Issue

- .github/workflows/ios-check.yaml
Fixes https://github.com/organicmaps/organicmaps/actions/runs/17251668423/job/48955136056?pr=11188
There should be no specific destinations when _building_. This PR uses the old approach that was used before commit 8637965a3a.
> [ios] Fix xcodebuild destination

- iphone/Maps/UI/EditBookmark/SelectBookmarkGroupViewController.swift
[ios] Show multi-line titles in bookmark list selector
* Related to https://github.com/organicmaps/organicmaps/pull/10923
Before/After:
> [ios] Show multi-line titles in bookmark list selector

- libs/drape_frontend/user_event_stream.cpp
Closes [#10549 ](https://github.com/organicmaps/organicmaps/issues/9122)
While debugging, I found that the crosshair point (screen center) is calculated incorrectly and depends on how much the PP is opened during the add point tap.
Here is what happens when the `add place` is tapped (and the PP is still opened because the animation is not started):
1. `void DrapeEngine::EnableChoosePositionMode` is called
https://github.com/organicmaps/organicmaps/blob/fbb0100c83abf00566e8f0c44884c09322be31b0/libs/drape_frontend/drape_engine.cpp#L653-L673
2. `FrontendRenderer::AcceptMessage` jumps to the `case Message::Type::SetAddNewPlaceMode:`
https://github.com/organicmaps/organicmaps/blob/fbb0100c83abf00566e8f0c44884c09322be31b0/libs/drape_frontend/frontend_renderer.cpp#L797-L820
3. New event …
> [ios]  Fix crosshair jumping when adding osm place from the place page

- data/test_data/gpx/export_test.gpx
- data/test_data/gpx/point_with_predefined_color_1.gpx
- data/test_data/gpx/point_with_predefined_color_2.gpx
- libs/kml/color_parser.cpp
- libs/kml/color_parser.hpp
- libs/kml/kml_tests/gpx_tests.cpp
- libs/kml/serdes_gpx.cpp
- libs/kml/serdes_gpx.hpp
- libs/map/bookmark.cpp
Fixes #11190
@biodranik, @vng  here is a draft version and I need some advice about implementation.
During the testing I noticed that Bookmarks in OM require PredefinedColor to be set up - looks like there is a difference with tracks and only several colors are supported. 
So some kind on mapping is required, I tried to implement it in kml::gpx::MapPredefinedColor, trying to re-use existing backward mapping (from PredefinedColor to rgb), but I'm not sure it is a good solution.
Also we have quite similar logic to map rgb to GarminColor, but it operates on different type of color.
From your point of view, what implementation we should have here?
> [gpx] Save bookmark color to gpx export

- libs/kml/kml_tests/gpx_tests.cpp
- libs/map/bookmark.cpp
- libs/map/bookmark.hpp
- libs/map/bookmark_manager.cpp
- libs/map/map_tests/bookmarks_test.cpp
Follow-up for #11238 
SetColor was not called actually, so reset of internal state was not done properly.
Fixed it and added the test.
> Fix bookmark color change

- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
- libs/map/place_page_info.cpp
- libs/map/place_page_info.hpp
Fixes #11210
Need to test, also need to filter out duplicate subtitle == title for bookmarks.
> [android] Show again missed bookmark subtitle with underlying types

- android/app/src/main/java/app/organicmaps/widget/placepage/DirectionFragment.java
- android/app/src/main/java/app/organicmaps/widget/placepage/PlacePageView.java
- android/app/src/main/res/layout/place_page_preview.xml
- Users complained that PP preview takes too much empty space (100% agree)
- Azimuth to North is very specific and needed only to a few users, so no need to show it in the PP preview
- It is now only shown if user presses on the arrow/distance to the selected place.
Before | After
-------|------
> [android] Reduce the height of the Place Plage preview by removing azimuth to north

- iphone/Maps/Classes/CarPlay/CarplayPlaceholderView.swift
- iphone/Maps/Classes/EAGLView.mm
- iphone/Maps/UI/CarPlay/CarPlayMapViewController.swift
Fixes https://github.com/organicmaps/organicmaps/issues/10900
Incorrect viewport and map scale while switching from the CarPlay to the iPhone.
1. Terminate the app
2. Connect to the car
3. Run the app in CarPlay
4. Switch to the Phone by tapping `Continue on the Phone`
5. The viewport will be incorrect (the location arrow will be in the top-left corner), and the zoom scale may be incorrect.
https://github.com/user-attachments/assets/a38fb34e-aac3-4ae1-88cb-ab7068856f42
1. The `updateVisibleViewPortToDefaultState` was called from the `viewDidLayoutSubviews` when the VC is removed from the stack, updates the viewport unexpectedly and overwrites the correct viewport with CP screen size when it shouldn't. It may break the viewport when switching to the phone.
2. When the app was not running …
> [ios] Fix CarPlay initial viewport and scale

- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/NavigationDashboardViewController.swift
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/EstimatesView.swift
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/TransportOptions/TransportOptionsSegmentedControl.swift
This PR fixes issues:
1. The accessibility setting `Button shapes` breaks the transport options segment control style.
2. Automatically tightens/reduces the estimates label font if needed
3. Slightly reduces spacing between transport options and the close button and increases buttons size
> [ios] Fix new route building `transport options segment control` and `estimates labels` issues

- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/NavigationDashboardInteractor.swift
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/NavigationDashboardRequest.swift
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePoints/RoutePointCollectionViewCell.swift
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePoints/RoutePoints.swift
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePoints/RoutePointsView.swift
- iphone/Maps/Core/Routing/MWMRouter.h
- iphone/Maps/Core/Routing/MWMRouter.mm
This PR fixes the crash when the user attempts to reorder route point cells when there is only one `Route from` point that exists.
Now:
1. The `from/to` point can be reordered
2. The  `add stop` is hidden when there is only 1 point (route from) because it is redundant in this state
https://github.com/user-attachments/assets/7bc6206b-bef0-4641-acfa-a1e5ced08a32
> [ios] Fix route points reordering when there is only 1 point

- android/app/src/main/java/app/organicmaps/routing/NavigationController.java
We are hiding speed limit view when no location (-> no current speed) is available. That doesn't sound right...
The change is to not hide speed limit view in this case.
> [android] Fix speed limit view

- iphone/Maps/Bookmarks/BookmarksList/BookmarksListInterfaces.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListPresenter.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListViewController.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListViewController.xib
- iphone/Maps/Categories/UIViewController+Navigation.h
- iphone/Maps/Categories/UIViewController+Navigation.m
- iphone/Maps/Core/Theme/CornerRadius.swift
- iphone/Maps/Core/Theme/GlobalStyleSheet.swift
- iphone/Maps/Core/Theme/Renderers/UISearchBarRenderer.swift
- iphone/Maps/UI/Downloader/Cells/MWMMapDownloaderButtonTableViewCell.xib
- iphone/Maps/UI/Downloader/DownloadMapsViewController.swift
- iphone/Maps/UI/Editor/MWMObjectsCategorySelectorController.mm
- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapHeaderView.swift
- iphone/Maps/UI/Storyboard/Main.storyboard
This PR fixes some issues but not all described in the https://github.com/organicmaps/organicmaps/issues/11403
Before / After
> [ios] Fix iOS26 UI issues

- iphone/Maps/Bookmarks/BookmarksList/BookmarksListViewController.swift
- iphone/Maps/Bookmarks/BookmarksList/BookmarksListViewController.xib
- iphone/Maps/Core/Theme/CornerRadius.swift
- iphone/Maps/Core/Theme/GlobalStyleSheet.swift
- iphone/Maps/Core/Theme/Renderers/UISearchBarRenderer.swift
- iphone/Maps/UI/Downloader/DownloadMapsViewController.swift
- iphone/Maps/UI/Editor/MWMObjectsCategorySelectorController.mm
- iphone/Maps/UI/Search/SearchOnMap/SearchOnMapHeaderView.swift
- iphone/Maps/UI/Storyboard/Main.storyboard
This PR reverts #11411 because the iOS Liquid Glass rollout should coincide with the CI migration to Xcode 26.
Since the app is currently built with Xcode 16, it should preserve the previous appearance.
iOS26 will look like:
> Revert "[ios] Fix iOS26 search bars appearance and layout"

- android/app/src/main/AndroidManifest.xml
- android/sdk/src/main/cpp/app/organicmaps/sdk/Framework.cpp
- android/sdk/src/main/java/app/organicmaps/sdk/bookmarks/data/BookmarkManager.java
- iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
- iphone/CoreApi/CoreApi/Common/MWMTypes.h
- iphone/Maps/OMaps.plist
- iphone/Maps/UI/DocumentPicker/DocumentPicker.swift
- iphone/Maps/UI/DocumentPicker/FileType.swift
- libs/kml/CMakeLists.txt
- libs/kml/color_parser.cpp
- libs/kml/color_parser.hpp
- libs/kml/kml_tests/CMakeLists.txt
- libs/kml/kml_tests/geojson_tests.cpp
- libs/kml/serdes_geojson.cpp
- libs/kml/serdes_geojson.hpp
- libs/kml/types.cpp
- libs/kml/types.hpp
- libs/map/bookmark_helpers.cpp
- libs/map/bookmark_helpers.hpp
- libs/map/bookmark_manager.cpp
- libs/platform/platform_tests/glaze_test.cpp
- xcode/kml/kml.xcodeproj/project.pbxproj
Added base support for GeoJson format
Here are 2 test files: [GeoJson-test-files.zip](https://github.com/user-attachments/files/21982502/GeoJson-test-files.zip).
Pick a KML file. Open https://geojson.io and drop KML file on the Globe. Website will generate GeoJson file for you. Import generated GeoJson into OM. Styling information usually is lost during such convertion.
GeoJson [specification](https://datatracker.ietf.org/doc/html/rfc7946) doesn't specify all aspects of bookmarks and tracks. No mention of colors or labels or multilanguage. It defines how geometry should be parsed and how to attach properties to it. Different tools generate different GeoJson properties.
| GeoJson.io | [UMap](https://umap.openstreetmap.fr) |
| --- | --- |
| <pre>{<br/>  "type": "Feature",<br/>  "geometry": …
> GeoJson import support
